kubernetes-sigs/kubebuilder

- cmd/kubebuilder-gen/codegen/run/util.go
- cmd/kubebuilder/create/util/util.go
- cmd/kubebuilder/initproject/init.go
- cmd/kubebuilder/util/util.go
- samples/controller/controller.go
- Always look for boilerplate in hack/boilerplate.go.txt
- Set the iargs variable in the sample controller
> Fix minor issues in finding boilerplate and sample

- pkg/controller/types/types.go
For better display in log statements e.g.
```
glog.Infof("Implement reconcile for '%s'.\n", k)
-> Implement reconcile for namespace/object
```
> Add string method for ReconcileKey

- README.md
This PR updates `README.md` to clarify that the user needs to download only one `tar.gz` file before running `kubebuilder init`.
> Clarify need to download only one tar.gz file

- cmd/kubebuilder/create/config/config.go
- cmd/kubebuilder/create/config/gen.go
- cmd/kubebuilder/create/example/example.go
Better error messaging for creating examples
Support only creating crds with create config
> Minor improvements to example creation and config creation commands

- README.md
This PR elaborates about controller code generation tags.
/assign @pwittrock
> Elaborate about controller code generation tags

- pkg/controller/types/types.go
While trying to determine what key to emit for an element without a
namespace, I looked at types.ReconcileKey which would emit "/name" which
doesn't appear to agree with the rest of the logic in kubebuilder. This
fixes types.ReconcileKey to emit the correct string value if namespace
is empty as well as adds a method to construct the object from a string.
> Fix an issue in types.ReconcileKey.String()

- cmd/internal/codegen/parse/apis.go
- cmd/internal/codegen/parse/controllers.go
- cmd/internal/codegen/parse/index.go
- cmd/internal/codegen/parse/rbac.go
- cmd/internal/codegen/parse/util.go
- cmd/kubebuilder/create/resource/controller.go
- cmd/kubebuilder/create/resource/resource.go
- cmd/kubebuilder/initproject/init.go
- docs/adding_non_namespaced_resources.md
- docs/declaring_rbac_rules_for_controllers.md
- pkg/gen/apis/doc.go
- pkg/gen/apis/example_test.go
- pkg/gen/controller/doc.go
- pkg/gen/controller/example_test.go
> standardize kubebuilder codegeneration labels to have +kubebuilder: prefix

- cmd/kubebuilder/initproject/dockerfile.go
Fixes #55 
- Set executable binary for ENTRYPOINT
- Set default value of --install-crds=false as CMD, which can be override.
> Set ENTRYPOINT and CMD for Dockerfile.controller

- cmd/kubebuilder/create/resource/controller.go
- Modified resourceControllerTemplate by adding
1) "k8s.io/client-go/tools/record"
2) event recorder field in Conroller struct
3) initializing event recorder in ProvideController
- Todo : Need some more tests.
Issue #53
> Add creating event recorder for controller in creating resource

- pkg/controller/eventhandlers/eventhandlers.go
This changes fixes a bug where generic controller
can get stuck in inifite loop while resolving parent object
for a generated object. It can happen where we encounter
an object with no owner reference while walking up the ancestor tree
and lookup paths are not yet done.
> fixed infinite loop in watchControllerOf API

- cmd/internal/codegen/parse/validation.go
with this change, something like following won't be treated as recursion
```
type MyKindSpec struct {
Replica int `json:"replica,omitempty"`
}
type MyKindStatus struct {
Stat MyKindSpec `json:"stat,omitempty"`
}
```
> fix the bug of recursion

- cmd/internal/codegen/parse/validation.go
This is the test I did. With type defined as
```
type MyKindSpec struct {
Replica int `json:"replica,omitempty"`
Pod v1.PodTemplate `json:"pod,omitempty"`
}
// MyKindStatus defines the observed state of MyKind
type MyKindStatus struct {
}
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// MyKind
// +k8s:openapi-gen=true
// +resource:path=mykinds
type MyKind struct {
metav1.TypeMeta   `json:",inline"`
metav1.ObjectMeta `json:"metadata,omitempty"`
Spec   MyKindSpec   `json:"spec,omitempty"`
Status MyKindStatus `json:"status,omitempty"`
}
```
Then create example yaml as
```
apiVersion: jingfang.example.com/v1beta1
kind: MyKind
metadata:
name: mykind-example
spec:
foo: bar
replica: 2
pod:
name: "something"
metadata:
name: "something"
```
This object passed …
> update validation for core types

- CONTRIBUTING.md
> Update link for local container builder

- README.md
- build/.goreleaser.yml
- build/build_kubebuilder.sh
- build/cloudbuild.yaml
- build/cloudbuild_snapshot.yaml
Highlights:
- Uses GoReleaser for building and publishing releases to Github
- Remove testing during the build process (will do done through Travis
as presubmit)
> added release automation

- build/.goreleaser.yml
Updated the GoReleaser configuration to package
all the binaries under bin/ directory.
> build: wrap binaries in bin/ directories

- build/build_kubebuilder.sh
GoReleaser debug output is flooding GCB console.
> disable debugging in GoReleaser command

- README.md
Reverting an accidental commit to README.
We want README to point to old releases until new release automation is in place.
> revert README changes

- cmd/internal/codegen/parse/controllers.go
- cmd/internal/codegen/parse/index.go
- cmd/internal/codegen/parse/rbac.go
- cmd/internal/codegen/parse/util.go
- cmd/internal/codegen/parse/validation.go
Adds some comments I found helpful while trying to understand the CRD generation flow so that I can add support for kubectl categories.
Interestingly, it looks like there are a bunch of whitespace changes because the tabstop seems inconsistent in the existing code.
> Comment fixes for code generation

- README.md
...and add a link, since this confused me on the first go-around.
> Clarify notion of 'version' in README

- build/.goreleaser.yml
kubebuilder version command was not returning correct version because
release process wasn't setting the version field correctly during
compilation of kubebuilder binary.
> set version field correctly during KB compilation

- test.sh
Makes it a little easier to follow what's going on :)
> Add basic output to test script

- test.sh
I'm using the test.sh script as part of my development flow, and it's very useful to be able to skip fetching and untarring the tools tarball when I already have the binaries on my local machine. This PR makes it possible to do this by setting `SKIP_FETCH_TOOLS=1`.
> Make it possible to skip fetch and untar of tools in test script

- .travis.yml
- test.sh
Makes the `set -x` behavior of test.sh dependent on `TRACE` environment variable; keeps current behavior in CI.
> Control -x in test.sh with TRACE

- cmd/internal/codegen/parse/crd.go
- cmd/internal/codegen/parse/util.go
- pkg/gen/apis/doc.go
- pkg/gen/apis/example_test.go
- test.sh
Support for kubectl categories using `+kubebuilder:categories=foo,bar,zab` tag
Closes #102 
Depends on #103
> Category support

- cmd/kubebuilder/main.go
From version 1.8 onwards a default GOPATH is assumed, so use that if one
isn't explicitly set.
> Don't terminate if GOPATH env var is unset

- .travis.yml
- Gopkg.lock
- Gopkg.toml
- build/build_vendor.sh
- cmd/kubebuilder/initproject/vendor.go
- test.sh
Highlights:
- Removed self dependency in Gopkg.toml for Kubebuilder project
- Update the Gopkg.toml file correctly for generated project
- Added `dep ensure` test in test.sh
- Update Travis config to add 'dep install'
Note: This also brings us one step closer to the goal of "not shipping vendors dir" in KB build. I will make a separate PR for that.
> fixed gopkg.toml for Kubebuilder and generated project

- cmd/kubebuilder/create/config/gen.go
- test.sh
... to facilitate adding test cases for validations etc in different CRDs.
> Make order of generated yaml from kubebuilder create config --crds deterministic

- build/test.sh
- cmd/internal/codegen/parse/parser.go
- cmd/kubebuilder-gen/internal/controllergen/inject.go
- cmd/kubebuilder/create/controller/controller.go
- cmd/kubebuilder/create/controller/controllertest.go
- cmd/kubebuilder/create/controller/run.go
- cmd/kubebuilder/create/create.go
- cmd/kubebuilder/create/resource/run.go
- cmd/kubebuilder/initproject/init.go
- cmd/kubebuilder/initproject/inject.go
- test.sh
- Add flag `controller-only` to init
- Add command `create controller` with flag `--core-type`
- Update controller template and inject template
- Add test with `create controller --core-type` in test.sh
This is to fix #41
> Add support for creating core type controllers

- cmd/internal/codegen/parse/apis.go
- cmd/internal/codegen/parse/util.go
- cmd/internal/codegen/types.go
- cmd/kubebuilder/docs/gen.go
- test.sh
- test/docs/expected/config-annotated.yaml
- parse doc annotations with +kubebuilder:doc:note and +kubebuilder:doc:warning
- support description_warning and description_note in config.yaml
#130
> Add annotation support for generating doc config.

- cmd/internal/codegen/parse/crd.go
- cmd/internal/codegen/parse/util.go
- cmd/kubebuilder-gen/codegen/run/generator.go
- cmd/kubebuilder/create/config/config.go
- cmd/kubebuilder/create/config/gen.go
- cmd/kubebuilder/docs/gen.go
- test.sh
- test/docs/expected/includes/_generated_bee_v1beta1_insect_concept.md
#137 
For `types.go` with content
```
package v1beta1
import (
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
type MyKindSpec struct {
Replica int `json:"replica,omitempty"`
Request map[string]string `json:"request,omitempty"`
}
type MyKindStatus struct {
value int `json:"value,omitempty"`
}
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// MyKind
// +k8s:openapi-gen=true
// +resource:path=mykinds
type MyKind struct {
metav1.TypeMeta   `json:",inline"`
metav1.ObjectMeta `json:"metadata,omitempty"`
Spec   MyKindSpec   `json:"spec,omitempty"`
Status MyKindStatus `json:"status,omitempty"`
}
```
The `install.yaml` file is
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
creationTimestamp: null
labels:
api: "" …
```
> Add skipmap flag to skip validation for AdditionlPropperties

- test.sh
- It doesn't work on MacOS, mainly because BSD sed is different from
GNU sed. However, Multi-line addition should use `i`/`a` instead of
`s` anyway. New sed command makes it clearer.
- Double quote path to avoid possible damage caused by space in path
- Consistent indent of 2 spaces
- Others that increase readability
> Several enhancements on test.sh

- .travis.yml
This currently allows OSX builds to fail, a follow-up PR can enable it as voting once it's proved itself for a while.
Fixes #185.
> Add OSX build job to travis config

- cmd/kubebuilder/initproject/dockerfile.go
- samples/memcached-api-server/Dockerfile.controller
To ensure the controller works well, rollback base image to ubuntu for now.
Consider to revisit the part when we have sufficient e2e tests
Fix: https://github.com/kubernetes-sigs/kubebuilder/issues/191
/assign @pwittrock @droot
> Rollback base image to ubuntu

- cmd/kubebuilder/util/util.go
Currently option `os.O_TRUNC` is only specified in func `create(path string)`, i.e for newly created files, but not for existing files.
Add the option in `OpenFile` func, to ensure old content in existing files get overwritten
Fix: https://github.com/kubernetes-sigs/kubebuilder/issues/190
> Add truncate options when opening files to overwrite contents in existing files

- .travis.yml
- samples/internal/test/e2e/kubebuildertest.go
- samples/memcached-api-server/test/hack/install.yaml
- test_existing_projects.sh
https://github.com/kubernetes-sigs/kubebuilder/issues/165
> Enable test for existing projects in travis

- CONTRIBUTING.md
There are no template variables for `GOOS` and `GOARCH` in `cloudbuild_local.yaml` so this prevents the error:
```
2018/05/24 10:39:32 Error validating build: key "_GOOS" in the substitution data is not matched in the template;key "_GOARCH" in the substitution data is not matched in the template
```
> Update contributing guide to build successfully

- pkg/webhook/doc.go
- pkg/webhook/internal/certprovisioner/certprovisioner.go
- pkg/webhook/internal/certprovisioner/doc.go
- pkg/webhook/internal/certprovisioner/example_test.go
- pkg/webhook/internal/certprovisioner/selfsignedcertprovisioner.go
The certprovider interface.
This PR supersedes https://github.com/kubernetes-sigs/kubebuilder/pull/217. 
This PR is split out from #205 w/ minor change.
> certprovider interface

- e2e.md
This PR creates a tutorial file about running e2e tests on remote clusters.
Partially addressing #124 
/assign @droot @pwittrock
> Running End-to-end Tests on Remote Clusters

- test/projects/validations/pkg/apis/apps/v1/testkind_types.go
- test/projects/validations/test/hack/install.yaml
- test_existing_projects.sh
- Move annotation tests into test projects.
- Modified `test_existing_projects.sh`. Run all projects tests in loop, so that no need to maintain this scripts.
> Add annotation tests into test projects

- cmd/kubebuilder/docs/gen.go
It doesn't seem that there are any files in pkg/controller that would
be necessary for documentation generation.
Fixes #249.
> Remove ./pkg/controller from docs/gen search paths

- cmd/kubebuilder/create/resource/run.go
Noticed that this output says to run a deprecated command.
> Update deprecated output from kubebuilder create

- cmd/internal/codegen/parse/crd.go
- cmd/internal/codegen/parse/util.go
- cmd/internal/codegen/types.go
- cmd/kubebuilder-gen/internal/resourcegen/versioned_generator.go
- cmd/kubebuilder/create/resource/resource.go
- cmd/kubebuilder/create/resource/run.go
- pkg/gen/apis/doc.go
- test.sh
Adds support for generating a CRD definition that includes a declaration of the status resource, triggered by the presence of the `+kubebuilder:subresource:status` tag.
This is needed to leverage CRD status subresources in projects created by kubebuilder
> Support for status subresource

- OWNERS_ALIASES
> change github handle

- test.sh
- test_existing_projects.sh
I think otherwise a failure in test_existing_projects.sh would not
have failed CI.
> Add standard error handling options to test.sh / test_existing_projects.sh

- docs/book/basics/what_is_the_controller_manager.md
With blockquotes the `newlines` in multiline commands were rendered as spaces, making it seem like you should try to run whole line.
(Reopening after signing CLA)
> Change blockquotes to code blocks

- pkg/controller/eventhandlers/eventhandlers.go
- pkg/controller/listeningqueue.go
Calling 'AddRateLimited' appears to indicate that an error has occurred
for the rate limiting queue.  This triggers exponential backoff
behavior, so if a large number of elements (20+) are owned by a resource
and the controller happens to encounter an error, this will cause
exponential backoff to reach the 1000 second limit.
> Change enqueuing items to use Add instead of AddRateLimited.

- cmd/Gopkg.lock
- cmd/vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go
- cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/controller/controller.go
- cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/controller/controllertest.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/apis/addtoscheme_policy_v1beta1.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/apis/creatures/v2alpha1/doc.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/apis/crew/v1/register.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/apis/policy/group.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/apis/policy/v1beta1/doc.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/apis/policy/v1beta1/healthcheckpolicy_types.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/apis/policy/v1beta1/register.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/apis/ship/v1beta1/doc.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/apis/ship/v1beta1/register.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/controller/add_healthcheckpolicy.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/controller/firstmate/firstmate_controller.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/controller/healthcheckpolicy/healthcheckpolicy_controller.go
- cmd/vendor/sigs.k8s.io/controller-tools/test/pkg/controller/kraken/kraken_controller.go
- bind resource for controller based on whether resource is created.
1) If resource is created in project, bind with created resource.
2) If resource not created, gkv matches core types, bind with core-types.
3) Else, using specified resourcePath by flag `--resource-pkg-path` (TODO)
#342 
#335 
#338
> Fix domain resource issues in controller

- CONTRIBUTING.md
Improve https://github.com/kubernetes-sigs/kubebuilder/issues/350
1. use `cloud-build-local` instead of `container-builder-local` (deprecated).
1. clarify setup tools step.
1. refine some words/sections
Thanks for reivew.
> improve contributing guide

- docs/book/README.md
> Fix URL for the Gitbook

- cmd/Gopkg.lock
- cmd/Gopkg.toml
- cmd/kubebuilder/initproject/init.go
- cmd/vendor/github.com/Masterminds/semver/.travis.yml
- cmd/vendor/github.com/Masterminds/semver/CHANGELOG.md
- cmd/vendor/github.com/Masterminds/semver/LICENSE.txt
- cmd/vendor/github.com/Masterminds/semver/Makefile
- cmd/vendor/github.com/Masterminds/semver/README.md
- cmd/vendor/github.com/Masterminds/semver/appveyor.yml
- cmd/vendor/github.com/Masterminds/semver/benchmark_test.go
- cmd/vendor/github.com/Masterminds/semver/collection.go
- cmd/vendor/github.com/Masterminds/semver/collection_test.go
- cmd/vendor/github.com/Masterminds/semver/constraints.go
- cmd/vendor/github.com/Masterminds/semver/constraints_test.go
- cmd/vendor/github.com/Masterminds/semver/doc.go
- cmd/vendor/github.com/Masterminds/semver/version.go
- cmd/vendor/github.com/Masterminds/semver/version_test.go
This does not allow one to use go from tip which has a version of "devel". Wasn't sure if we want to support this.
When I do a dep ensure, a bunch of changes occur in the root Gopkg.toml and vendor directory. Wasn't sure how it was being managed, but I tried to keep it to a minimal change.
> Check go version

- docs/book/SUMMARY.md
- docs/book/beyond_basics/dependencies.md
- docs/book/beyond_basics/upgrading_kubebuilder.md
This adds a section on dependency management, with an explanation of how
and why kubebuilder handles dependencies, and updates the upgrading
section to have the latest reccomendations on how to update.
> [book] section on dependencies, update upgrading

- docs/book/beyond_basics/dependencies.md
Running `dep ensure -update` without specifying any target is broken and is also not recommended by the `dep`. Instead, we can achieve the same effect by updating the sigs.k8s.io/controller-*. 
fixes #374
> updated docs for updating the vendor deps

- docs/book/quick_start.md
version 1.0.0 is no longer usable
Related: #382
> Update Quick Start Guide

- cmd/kubebuilder/alpha.go
- cmd/kubebuilder/main.go
- cmd/kubebuilder/webhook.go
Supersede #409
This CL blocks the move of `scaffold` pkg and `test` project from `container-tools` to `kubebuilder`, because `generated_golden.sh` in `container-tools` expects the webhook command to exist in kubebuilder.
> add alpha webhook cmd

- cmd/init_project.go
Whenever dep ensure is executed, during `init` or `update vendor`, run in verbose mode.
Fixes #384
> Execute dep ensure with verbose enabled

- cmd/go_version_test.go
- cmd/init_project.go
Highlights:
- Go version doesn't follow semver style from syntax perspective, so
use semver pkg wasn't helpful
- re-implemented go version check without using the semver pkg.
fixes #412 #439
> improved Go version check

- cmd/init_project.go
- pkg/scaffold/project/kustomize.go
- pkg/scaffold/project/kustomize_metrics_patch.go
- pkg/scaffold/project/project_test.go
- test/project/config/default/kustomization.yaml
- test/project/config/default/manager_prometheus_metrics_patch.yaml
Quick highlights:
- Scaffolds a patch which enables prometheus scraping on the manager pods.  Using the most common annotations used by Stackdriver, [weaveworks](https://www.weave.works/docs/cloud/latest/tasks/monitor/configuration-k8s/)
- Enables the patch in `kustomization.yaml` file.
> enable prometheus metrics integration

- CONTRIBUTING.md
[cloudbuild_local.yaml](https://github.com/kubernetes-sigs/kubebuilder/blob/master/build/cloudbuild_local.yaml) seems to be useless ATM.
I can delete it in this PR.
fixes #486
> update how to build kubebuilder locally

- scripts/install.sh
- Add bash installation script for macos or linux users.
- Download latest version of kuberbuilder or specify the version, untar it and move project under /usr/local/bin/kubebuilder if it is empty. Otherwise exit
- Fix #482
> Add bash installation script for macos or linux users

- pkg/scaffold/controller/controller.go
- test/project/config/rbac/rbac_role.yaml
- test/project/pkg/controller/firstmate/firstmate_controller.go
- test/project/pkg/controller/frigate/frigate_controller.go
- test/project/pkg/controller/healthcheckpolicy/healthcheckpolicy_controller.go
- test/project/pkg/controller/kraken/kraken_controller.go
- test/project/pkg/controller/namespace/namespace_controller.go
While testing status subresources, I discovered that we are not generating RBAC permissions for status sub resource. This PR addresses that.
> add RBAC annotation for status subresource

- pkg/scaffold/manager/config.go
- pkg/scaffold/manager/dockerfile.go
- test/project/Dockerfile
- test/project/config/manager/manager.yaml
/root/ encourages use of the root user, and / is more the pattern I've
seen for thin containers.
> Put the manager binary into /, instead of /root/

- build/cloudbuild_tools.yaml
- build/thirdparty/darwin/Dockerfile
- build/thirdparty/linux/Dockerfile
KB now only need 3 tools for integration testing:
- kube-apiserver
- etcd
- kubectl
For linux, these 3 are fetched from official releases.
For darwin (MacOS), kube-apiserver is built from source, because k8s doesn't release a darwin kube-apiserver; while etcd and kubectl are fetched from official releases.
> update how to build tools for kubebuilder

- cmd/webhook.go
This PR fixes the issue described in https://github.com/kubernetes-sigs/kubebuilder/issues/505#issuecomment-447173482.
`pkg/webhook.go` is only generated by `kubebuilder init` with version v1.0.5+. If the project was generated by an older kubebuilder, missing `pkg/webhook.go` will cause it failed to compile.
This PR ensure it always exist each time running `kubebuilder alpha webhook` command. If not exist, generate it.
> make webhook scaffolding work with old project

- pkg/scaffold/project/makefile.go
- test/project/Makefile
The root-cause of the issues we are seeing is deepcopy-gen doesn't support building/generating outside GOPATH. So for now, failing fast when we detect missing GOPATH in `generate` target can save users in this case.
fixes #531 #359
> :bug: report error if GOPATH env is missing

- docs/book/getting_started/installation_and_setup.md
- docs/book/quick_start.md
`ZSH` automatically escapes links and breaks copy + paste:
```bash
curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${version}/kubebuilder_${version}_darwin_${arch}.tar.gz
curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v$\{version\}/kubebuilder_$\{version\}_darwin_$\{arch\}.tar.gz
```
Also bumped version to `v1.0.7`
> Fix download links on ZSH

- pkg/scaffold/project/project_test.go
While working on PR #572 I noticed there were some hard-coded years in the tests in `pkg/scaffold/project/project_test.go`.
This PR removes those hard-coded years and dynamically sets the year.
> Remove hardcoded years in scaffold tests

- DESIGN.md
- README.md
This elaborates on the design principals of KubeBuilder,
controller-runtime, and controller-tools.
It's been pointed out that we don't have much documentation on the guiding principals of the KubeBuilder project, beyond the vision that sits in the heads of the maintainers and a brief section in the readme.  This attempts to rectify that situation.
> :book: Elaborate on the design pricipals of KB

- pkg/scaffold/manager/dockerfile.go
- test/project/Dockerfile
The vendor directory is rarely changed during development and is big.
So, moving its copy to lower layer in docker build can make docker builds faster.
> Improve Dockerfile template such that copying vendor dir is cached.

- cmd/init_project.go
- pkg/scaffold/project/kustomize.go
- pkg/scaffold/project/kustomize_manager_base.go
- pkg/scaffold/project/kustomize_rbac_base.go
- pkg/scaffold/project/project_test.go
- test/project/config/default/kustomization.yaml
- test/project/config/manager/kustomization.yaml
- test/project/config/rbac/kustomization.yaml
> update kustomize scaffolding to work with kustomize 2.0

- designs/simplified-scaffolding.md
This introduces a design for a simplified scaffolding that addresses
both persistent pedagogical issues and dependency injection issues with
our current scaffolding.
> :running: Design for Simplified Scaffolding

- test/internal/e2e/kubebuildertest.go
Hi, we updated some exported function comments based on best practices from Effective Go. It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- docs/book/beyond_basics/using_client_go_informers.md
- `manager.RunnableFunc` should block or it'll trigger shutdown.
- `source.Informer`'s `InformerProvider` field was renamed to `Informer`
> Update documentation for client-go informers

- docs/book/beyond_basics/controller_watches.md
otherwise we got
```
2019/03/20 16:12:57 // +kubebuilder:rbac: tags must be key value pairs.  Expected keys [groups=<group1;group2>,resources=<resource1;resource2>,verbs=<verb1;verb2>] Got string: [groups="",resources=pods,verbs=get;watch;list,create,update,delete]
```
> typo correction

- Makefile
This repo is slightly annoying to install from source since `main.go` is in `cmd/` instead of a `kubebuilder` directory, so I added a make target roughly equivilant to typical `go install`. Alternate options to make this easier include:
- have `main.go` be in the repo root
- have a `cmd/kubebuilder/main.go`
for either of those, `go get -u sigs.k8s.io/kubebuilder/...` would be a viable install route.
This route was the least invasive, so I started there, but I'd be up for PRing other routes if there's interest.
> add an install target to makefile

- cmd/main.go
`go/build.Default.GOPATH` already has identical defaulting behavior (using `$GOPATH` if set)
https://golang.org/pkg/go/build/#Context
> Default is the default Context for builds. It uses the GOARCH, GOOS, GOROOT, and GOPATH environment variables if set, or else the compiled code's GOARCH, GOOS, and GOROOT.
> simplify GOPATH

- .gitignore
since `make build` writes binaries here we should gitignore it
> gitignore bin/

- docs/book/_redirects
This adds https://go.kubebuilder.io/releases/* as a vanity url for the
github releases page.
DNS may take a bit to propagate
> :running: Add shortlinks to releases via go.kubebuilder.io

- pkg/scaffold/v2/dockerfile.go
- testdata/project_v2/Dockerfile
Main changes:
- use Go 1.12.5 with Go modules to build the manager binary
- use distroless (stripped down image)
> :bugfix: fixed docker image file for v2 scaffolding

- netlify.toml
This fixes the redirects for the book-v1 branch so that they properly
evaluate the alias v1.book --> book-v1.book.
> :running: Fix netlify redirects for v1 book

- .travis.yml
brew install git-lfs takes forever (5m), so we download directly with curl instead (0.8s).
> :running: Download git-lfs directly on OSX

- docs/book/src/introduction.md
The domain alias isn't working quite right, so just point directly to
the canonical subdomain.
> :book: Fix legacy book link

- cmd/main.go
- cmd/webhook.go
- generated_golden.sh
- pkg/scaffold/project.go
- pkg/scaffold/v2/certmanager/kustomize.go
- pkg/scaffold/v2/crd/enablewebhook_patch.go
- pkg/scaffold/v2/dockerfile.go
- pkg/scaffold/v2/kustomize.go
- pkg/scaffold/v2/manager/config.go
- pkg/scaffold/v2/webhook/enablecainection_patch.go
- pkg/scaffold/v2/webhook/kustomization.go
- pkg/scaffold/v2/webhook/service.go
- pkg/scaffold/v2/webhook_manager_patch.go
- testdata/project-v2/Dockerfile
- testdata/project-v2/config/certmanager/kustomization.yaml
- testdata/project-v2/config/crd/bases/crew.testproject.org_captains.yaml
- testdata/project-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
- testdata/project-v2/config/crd/patches/webhook_in_captain.yaml
- testdata/project-v2/config/crd/patches/webhook_in_firstmate.yaml
- testdata/project-v2/config/default/kustomization.yaml
- testdata/project-v2/config/default/manager_webhook_patch.yaml
- testdata/project-v2/config/default/webhookcainjection_patch.yaml
- testdata/project-v2/config/manager/kustomization.yaml
- testdata/project-v2/config/manager/manager.yaml
- testdata/project-v2/config/rbac/role.yaml
- testdata/project-v2/config/webhook/kustomization.yaml
- remove dead code in `generated_golden.sh`
- fix broken webhook related scaffolding due to name or path change.
- split `NAMESPACE` into 2 different kustomize config, so `webhook` base can be used w/o `certmanager`.
- use `distroless/static`
> :sparkles: fix webhook related scaffolding

- build/.goreleaser.yml
- build/cloudbuild.yaml
- build/cloudbuild_local.yaml
- build/cloudbuild_snapshot.yaml
Highlights:
- use Goreleaser with Go 1.12.5
- Enable Go modules
> :running: switch to using Go modules in build tooling

- build/cloudbuild.yaml
- build/cloudbuild_local.yaml
- build/cloudbuild_snapshot.yaml
This PR updates the cloudbuild manifests to use k8s 1.14.1 for packaging k8s binaries (kube-apiserver, etcd, kubectl) in future kb releases.
Note: I haven't tested if kb projects works with 1.14.1 release.
> :running: package k8s 1.14.1 in kubebuilder builds

- build/cloudbuild.yaml
- build/cloudbuild_local.yaml
- build/cloudbuild_snapshot.yaml
- common.sh
This change ensures our test scripts are using k8s 1.14.1 binaries.
> :running: use k8s 1.14.1 in test scripts

- build/test.sh
- cmd/init_project.go
- test.sh
This switches the default scaffolding to v2, since we want people to use
this version.
> :warning: Switch default project version to v2

- docs/book/src/quick-start.md
- netlify.toml
This adds go links for kustomize and the snapshot builds, and updates the docs to mention Kustomize installation and the snapshot builds.
> Kustomize and Snapshot Go Links

- docs/book/src/quick-start.md
This fixes the kustomize go link to point at the actual kustomize go link, and not the latest go link.
> Fix kustomize go link in quickstart

- cmd/api.go
This should fix #717 There were also some more spelling mistakes for controller vs. controllers
> Fix path prefixes in cmd help

- docs/book/src/cronjob-tutorial/running.md
- docs/book/src/cronjob-tutorial/testdata/project/config/samples/batch_v1_cronjob.yaml
For users familiar with CronJobs, this is self-explanatory, but I thought it would be nice to have a real example. 
Also, the yaml isn't in a code block so it looks whack right now.
>  📖 use real example, fix yaml in markdown

- cmd/api.go
As a follow up to #728 here is a simple approach to version specific questions. Although I am not sure if this is the right way to approach this, it really seems more complex to add a helper for this. @abursavich what do you think about the `Examples`? I haven't found a proper way to make those version specific.
> Add version dependent questions for generating APIs

- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
The comments in the cronjob controller were indented too much, causing
them to be interpretted as code blocks and not as normal text blocks.
This should fix that.
> :book: Fix controller chapter indentation

- pkg/scaffold/api.go
- pkg/scaffold/input/input.go
- pkg/scaffold/scaffold.go
- testdata/project-v2/PROJECT
This change does the following:
- introduces book-keeping of scaffolded resources in PROJECT file
- Validates if new resource belong to existing scaffolded groups
fixes #739
> :bug: added multigroup check while creating resource

- pkg/scaffold/api.go
- pkg/scaffold/v2/controller.go
- pkg/scaffold/v2/controller_suitetest.go
- pkg/scaffold/v2/crd/kustomization.go
- pkg/scaffold/v2/internal/string_utils.go
- pkg/scaffold/v2/internal/string_utils_test.go
- pkg/scaffold/v2/main.go
- testdata/project-v2/controllers/suite_test.go
The change improves the logic for updating the main.go when
new API/Controller is added to the project.
fixes #740
> :bug: fix missing add-to-scheme calls on new API version

- .travis.yml
- common.sh
- generate_vendor.sh
- go.mod
- go.sum
- pkg/scaffold/v1/manager/config.go
- pkg/scaffold/v2/manager/config.go
- scripts/install_and_setup.sh
- test/e2e/config.go
- test/e2e/e2e_test.go
- test/e2e/e2ev1.go
- test/e2e/kubebuildertest.go
- test/e2e/util.go
- test/kind-config.yaml
- test_e2e.sh
- testdata/gopath/src/project/config/manager/manager.yaml
- testdata/project-v2/config/manager/manager.yaml
This PR enables e2e test for v1 project.
Some code under `/test/e2e` was accidentally deleted in an earlier refactoring. I introduce it back with necessary changes.
> :running: enable e2e tests on travis

- docs/book/src/cronjob-tutorial/testdata/emptyapi.go
`Cronjobs` is not a source, `Cronjob` is.
> Wrong terminology format

- pkg/scaffold/v2/dockerfile.go
- testdata/project-v2/Dockerfile
Before: every time you change your source file, the downloaded go module cache are invalidated.
After: the downloaded go module cache are always reused.
fixes: #755
> :sparkles: cache go module cache in docker

- pkg/scaffold/v2/main.go
- pkg/scaffold/v2/manager/config.go
- testdata/project-v2/config/manager/manager.yaml
- testdata/project-v2/main.go
The leader election feature is disabled when running locally using `make
run`, while it is enabled by default when running in a k8s cluster.
> :sparkles: add a flag for the leader election feature

- pkg/scaffold/v2/makefile.go
- testdata/project-v2/Makefile
This fixes #746 
I've removed the GOPATH entirely, since it was a redundant call anyways.
> :running: support GOBIN for installed binaries.

- docs/book/src/cronjob-tutorial.md
- docs/book/src/cronjob-tutorial/basic-project.md
I'm going through the book and found a couple of typos to fix. The links in basic-project are quite broken and I took a guess at their correct relative urls. Let me know if those match your expectations.
I was unable to find a match for `Kustomize base`, it is unresolved.
> Update kubebuilder book for typos and repaired links

- test.sh
Due to git-lfs quota issues, we are hosting vendor tarball on GCS.
This change enables using the GCS hosted vendor tarball instead of using the one from Github LFS.
> :running: use vendor tarball from GCS bucket

- .gitattributes
- .travis.yml
- CONTRIBUTING.md
- common.sh
- generated_golden.sh
- test.sh
- test/e2e/e2e_v1.go
- testdata/vendor.v1.tgz
We no longer use git-lfs due to bandwidth quota issues. This removes remaining git-lfs usage from test scripts.
> :running: remove git-lfs usage

- docs/book/src/cronjob-tutorial/basic-project.md
- docs/book/src/cronjob-tutorial/main-revisited.md
Directory trees like `testdata/project/config/default` aren't listed by mdbook, breaking links in the book. Workaround this by using the github URLs for the paths. There's going to be a better way, but at least the links will work.
I introduced it in #779 when replacing `TODO.md` with the directory
> Fix broken dir listing by using github URLs

- pkg/scaffold/v2/main.go
- testdata/project-v2/main.go
This new scheme should make users life easier.
fixes https://github.com/kubernetes-sigs/kubebuilder/issues/797
xref: https://github.com/kubernetes-sigs/controller-runtime/issues/492
> :sparkles: scheme should have all builtin types registered by default

- pkg/scaffold/v2/main.go
- testdata/project-v2/main.go
It's generally not good practice to modify someone else's scheme, so we
add k8s types to our new scheme instead.
(re) fixes #797
> Add existing k8s types to new scheme

- scripts/install_and_setup.sh
Now that this https://github.com/kubernetes-sigs/kustomize/commit/f9c631e9eec7a2d6e46eb9e1bf5122f68b97d12d is part of a release switch to the release build
> :running: use a released version of kustomize

- docs/book/src/SUMMARY.md
- docs/book/src/reference/generating-crd.md
This change copies the reference docs for CRD generation from v1
to v2 with minimal changes.
> :book: added CRD generation reference for v2 docs

- cmd/main.go
When packages.Load can't find a module path, it fabricates one out of
the current absolute path.  We should not use that when it happens.
Fixes #745
> :bug: Don't use packages.Load's underscore paths

- docs/book/src/quick-start.md
Suggestion: Add documentation to ensure that kustomize is executable when users install it. 
I ran into issues when trying to deploy an image that required kustomize. It installed correctly, but was not executable and I therefore encountered errors.
> Added information about how to make kustomize executable

- pkg/scaffold/v2/metricsauth/kustomize_auth_proxy_patch.go
- testdata/project-v2/config/default/manager_auth_proxy_patch.yaml
when `manager_auth_proxy_patch` is enabled, the
`--enable-leader-election` arg inside `manager/manager.yaml` will be
overriden.
> fix enable-leader-election overriden by patch.

- docs/book/src/quick-start.md
Added Missing link for controller reference on the [quick start page ](https://book.kubebuilder.io/quick-start.html)
Partially fixes issue #773
> Added the missing link for controller reference

- docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_types.go
> fix the example validation for minimum length of string type

- cmd/init_project.go
- pkg/scaffold/v2/gomod.go
Since the default project version is v2 and it relies on go modules, it makes sense to adapt the help usage accordingly.
> Rename Gopkg.toml to go.mod in help usage

- docs/book/src/cronjob-tutorial/testdata/project/main.go
Adding the scheme to the reconciler initialization accidentally got dropped during a refresh.  This restores it.
Fixes #870
> :book: add the missing scheme back

- scripts/install_and_setup.sh
Added  `export GO111MODULE=on` to the install_and_setup.sh 
Without this environment variable, running this script will produce the following error: 
```
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
ignoring ../go.mod;
see 'go help modules'
go: cannot use path@version syntax in GOPATH mode
```
> Adding the GO111MODULE environment variable

- pkg/scaffold/v2/makefile.go
- testdata/project-v2/Makefile
The `manifests` makefile target isn't called as expected during the build process. This section from [the kubebuilder book](https://kubebuilder.io/reference/generating-crd.html) (specifically "If you examine the Makefile ... manifests target is also listed as prerequisite for other targets like run ...) implies a `make run` should create manifests. 
This issue was found because the yaml files in the cluster didn't match what the binary expected (with a make run).
> :sparkles: Makefile: Create manifests with 'run' target

- go.sum
- pkg/scaffold/project/kustomize.go
- pkg/scaffold/v2/crd/kustomization.go
- pkg/scaffold/v2/kustomize.go
- testdata/gopath/src/project/config/default/kustomization.yaml
- testdata/project-v2/config/crd/kustomization.yaml
- testdata/project-v2/config/default/kustomization.yaml
kustomize has deprecated `patches` fields for months.
It should be replaced by `patchesStrategicMerge`.
`patches` if in old format will be auto convert to the new format in v3.0.4+. So this PR is not considering a breaking change.
Ref: https://github.com/kubernetes-sigs/kustomize/pull/1355 and kubernetes-sigs/kustomize#1363
> :sparkles: replace patches with patchesStrategicMerge

- docs/book/book.toml
- docs/book/install-and-build.sh
- docs/book/litgo.sh
- docs/book/markerdocs.sh
- docs/book/src/SUMMARY.md
- docs/book/src/cronjob-tutorial/epilogue.md
- docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
- docs/book/src/cronjob-tutorial/testdata/emptymain.go
- docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
- docs/book/src/multiversion-tutorial/api-implementation.md
- docs/book/src/multiversion-tutorial/deployment.md
- docs/book/src/reference/generating-crd.md
- docs/book/src/reference/markers.md
- docs/book/src/reference/markers/crd-validation.md
- docs/book/src/reference/markers/crd.md
- docs/book/src/reference/markers/object.md
- docs/book/src/reference/markers/rbac.md
- docs/book/src/reference/markers/webhook.md
- docs/book/theme/css/general.css
- docs/book/utils/go.sum
- docs/book/utils/litgo/literate.go
- docs/book/utils/markerdocs/doctypes.go
- docs/book/utils/markerdocs/html.go
- docs/book/utils/markerdocs/main.go
- docs/book/utils/plugin/input.go
- docs/book/utils/plugin/plugin.go
- docs/book/utils/plugin/utils.go
This generates marker-docs using controller-gen, and then inserts them (in HTML form) into the book as part of the build process (via an mdbook plugin).
Closes #815
> :book: Marker Docs

- cmd/init_project.go
- cmd/main.go
- cmd/util/util.go
Key changes:
- kills global variables domain and repo under utils pkg.
- Moved code to find current repo to init-project command (thats the only place where it is needed). 
fixes #899
> :bug: help/version command fails when default repo is not initialized

- docs/book/src/cronjob-tutorial/basic-project.md
- The Makefile snippet in particular weren't very readable. :-)
> Basic Project docs: Add blank lines before code blocks to fix formatting

- docs/book/install-and-build.sh
- docs/book/src/cronjob-tutorial/running-webhook.md
- docs/book/theme/css/general.css
Put the note in an `<aside>` block.
fixes: #893
> :book: add a note for bootstrapping webhooks for pods

- docs/book/src/cronjob-tutorial/basic-project.md
- docs/book/src/cronjob-tutorial/cronjob-tutorial.md
- docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
- docs/book/src/multiversion-tutorial/deployment.md
- docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
- docs/book/src/multiversion-tutorial/tutorial.md
- docs/book/theme/css/general.css
- docs/book/utils/litgo/literate.go
This adds links to the source for the tutorials in both a note at the start of each, and on each literate Go file when mentioned.
It also fixes a couple of code formatting issues, and hides the copy buttons on code blocks to make them flow a bit better with normal text in literate go sections.
> :book: Links to source in tutorial & misc docs fixes

- docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
- docs/book/src/cronjob-tutorial/testdata/project/api/v1/zz_generated.deepcopy.go
- docs/book/src/cronjob-tutorial/testdata/project/go.mod
- docs/book/src/cronjob-tutorial/testdata/project/go.sum
- docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go
- docs/book/src/multiversion-tutorial/testdata/project/go.mod
- docs/book/src/multiversion-tutorial/testdata/project/go.sum
- pkg/scaffold/v2/gomod.go
- pkg/scaffold/v2/webhook/webhook.go
- testdata/project-v2/api/v1/captain_webhook.go
- testdata/project-v2/go.mod
- testdata/project-v2/go.sum
https://github.com/kubernetes-sigs/controller-runtime/pull/525 added support for validating deletion operation.
- scaffold `go.mod` with CR `v0.2.0-beta.5` and scaffold `ValidateDelete`.
- Update book to reflect the new scaffolding.
> :sparkles: scaffold ValidateDelete for validating webhook

- docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
- pkg/scaffold/v2/makefile.go
- testdata/project-v2/Makefile
kubebuilder used to do `kubectl apply -f config/crd/bases` to create CRDs.
Now it switches to use `kustomize build config/crd | kubectl apply -f -`
> :sparkles: use kustomize to apply CRDs

- docs/book/src/SUMMARY.md
- docs/book/src/reference/controller-gen.md
- docs/book/src/reference/markers.md
- docs/book/theme/css/general.css
- docs/book/utils/markerdocs/main.go
This documents the controller-gen CLI options in the book, with the help
of the markerdocs mdbook plugin.
Fixes kubernetes-sigs/controller-tools#292
> Add controller-gen CLI options to book

- docs/book/theme/css/general.css
- docs/book/utils/litgo/literate.go
This makes the literate go collapsed code sections a bit more pretty
looking.  They now look like comments that can be clicked to expand.
> :book: Make the code expandos a bit more pretty

- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
- Support default parameter field
- Fix wrong deletion on SuccessfulJobsHistoryLimit & FailedJobsHistoryLimit
- Fix wrong next schedule as returned lastMissed is a pointer
- Delete dependent Job in background when deleting CronJob
> :book: Fix cronjob tutorial to delete and get next schedule correctly

- docs/book/src/reference/generating-crd.md
Signed-off-by: Chuck Ha <chuckh@vmware.com>
Fixes #941
> 🐛 Fix subresource:status typo in gitbook

- pkg/scaffold/v2/gomod.go
- pkg/scaffold/v2/makefile.go
- testdata/project-v2/Makefile
- testdata/project-v2/go.mod
- testdata/project-v2/go.sum
This PR enables use of 0.2.0-rc.0 releases of controller-runtime/tools in kubebuilder projects.
> :running: bumped up controller-runtime/tools to 0.2.0-rc.0

- cmd/api.go
Fixed a minor issue in the directory structure shown in examples of kubebuilder create api --help command
Issue Addressed: [Issue 956](https://github.com/kubernetes-sigs/kubebuilder/issues/956)
> Correct the directory structure in the example provided.

- pkg/scaffold/input/input.go
* fix bug
* remove`_` because `range` that has 2 return values returns index first.
* `range` that has 1 return value returns value only.
> fix range value

- pkg/scaffold/v1/resource/resource.go
- pkg/scaffold/v1/resource/resource_test.go
- https://github.com/kubernetes-sigs/kubebuilder/issues/954
allow the usage of dash in the group names
Allow users to create API's with a group name like `mypapp-operator.example.com`. Note that the controller allows it.
> Allow group names with dash

- cmd/init_project.go
As best I can tell, `--repo` is used to set go module and package names. It doesn't need to be hosted on github.
> clarify usage text on init --repo flag

- docs/book/basics/status_subresource.md
The contributor repo got re-arranged to be per-sig, so we need to adjust accordingly.
> Fix the API conventions link

- docs/book/src/SUMMARY.md
- docs/book/src/reference/artifacts.md
- netlify.toml
Adding `go.kubebuilder` links and documentation for published test binaries and container images.
Fixes #914 
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> test binary and container image redirects and docs

- CONTRIBUTING.md
- Makefile
- https://github.com/kubernetes-sigs/kubebuilder/issues/978
Small changes in order to make clear the fixed path that the devs should use as add script to test the build and e2e in the makefile.
> getting started to contribute with. Add makefile commands and improve CONTRIBUTING.MD

- cmd/api.go
- cmd/vendor_update.go
- cmd/webhook_v1.go
- cmd/webhook_v2.go
- pkg/model/types.go
- pkg/scaffold/api.go
- pkg/scaffold/project.go
- pkg/scaffold/project/project_test.go
- pkg/scaffold/scaffold.go
- pkg/scaffold/util/util.go
- pkg/scaffold/v1/manager/manager_test.go
- pkg/scaffold/v1/resource/resource_test.go
- pkg/scaffold/v1/webhook/webhook_test.go
- pkg/scaffold/v2/controller.go
- pkg/scaffold/v2/controller_suitetest.go
- pkg/scaffold/v2/main.go
- pkg/scaffold/v2/webhook/webhook.go
- plugins/README.md
- plugins/addon/channel.go
- plugins/addon/controller.go
- plugins/addon/helpers.go
- plugins/addon/manifest.go
- plugins/addon/plugin.go
- plugins/addon/type.go
Plugin model; --pattern=addon flag that generates an addon operator
We implement the initial plugin model, starting with an in-process
implementation that can support out-of-process later.  As plugins do
not yet form part of the stable interface for kubebuilder, we only
enable them when the KUBEBUILDER_ENABLE_PLUGINS env var is set.
We implement an initial plugin for addons: `--pattern=addon` creates a
controller & resource that follow the style of
https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern
This style of declarative addon operators is being investigated in the
cluster-addons subject, with code at
https://github.com/kubernetes-sigs/addon-operators
> Initial addons via plugin model

- docs/book/basics/simple_resource.md
Update the replica field to use a pointer in the type definition and the controller reconciliation code.
Fixes #434 
/cc @mengqiy
> Use pointers for replicas field in the gitbook

- build/.goreleaser.yml
Fixes: https://github.com/kubernetes-sigs/kubebuilder/issues/966
> Ship arm64 and ppc64le binaries

- designs/integrating-kubebuilder-and-osdk.md
This adds a document that describes the high-level plan for integrating Kubebuilder and Operator SDK.
> Add KB/SDK integration design document

- pkg/scaffold/v2/dockerfile.go
- pkg/scaffold/v2/main.go
- pkg/scaffold/v2/webhook/service.go
- pkg/scaffold/v2/webhook_manager_patch.go
- testdata/project-v2/config/default/manager_webhook_patch.yaml
- testdata/project-v2/config/webhook/service.yaml
- testdata/project-v2/main.go
- Setup user on docker image to run it as rootless
- https://github.com/kubernetes-sigs/kubebuilder/issues/883
- https://jira.coreos.com/browse/OSDK-473
```
$ cd upimage/
$ kubebuilder init --domain up.image
$ kubebuilder create api --group kubeimage --version v1 --kind TestImg
$ make
$ oc login -u system:admin
$ make install
$ make docker-build docker-push IMG=cmacedo/upimage:test
$ make deploy IMG=cmacedo/upimage:test
```
Checked that it worked in Minishift/OCP as well.
> Setup user on docker image to run it as no root

- docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- docs/book/src/migration/testdata/gopath/project-v1/config/default/manager_auth_proxy_patch.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- pkg/scaffold/v1/metricsauth/kustomize_auth_proxy_patch.go
- pkg/scaffold/v2/metricsauth/kustomize_auth_proxy_patch.go
- test_e2e.sh
- testdata/gopath/src/project/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v2/config/default/manager_auth_proxy_patch.yaml
Upstream has released `quay.io/brancz/kube-rbac-proxy:v0.4.1`, we follows that.
fixes #1021
> :sparkles: bump kube-rbac-proxy to v0.4.1

- docs/book/src/reference/markers.md
**Description of the change:**
Add documentation for the map syntax added for marker arguments by https://github.com/kubernetes-sigs/controller-tools/pull/329
> Document marker syntax for maps

- docs/book/src/SUMMARY.md
- docs/book/src/reference/metrics.md
- docs/book/src/reference/reference.md
Hello there!
I am a user of kubebuilder and recently was trying to figure out how to publish additional metrics from my controllers.  I struggled to find documentation on how to achieve this, but did eventually figure it out from another PR (https://github.com/kubernetes-sigs/controller-runtime/pull/132)
This PR adds a simple example of how one might add collectors and register them with the global registry.
I also updated `reference.md` which seemed to have some stale content.
I'd be happy to adjust the example if someone has a better approach or more generic way of presenting the idea to users for documentation purposes.
I intentionally didn't add a lot of extra explanation to the doc, since the example is pretty straightforward.  Let me know if you want more context or examples.
> Add custom prometheus metrics documentation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support-question.md
- .github/PULL_REQUEST_TEMPLATE.md
The PR/issue templates that got merged didn't quite match what we
wanted, so this attempts to fix them up, moving things into comments
and making them match the KB guidelines a bit more
Related to #1050
> Fixup PR/issue templates

- README.md
- docs/README.md
Hi there, this is a small PR to update a couple references to GitBook, which no longer seems to be in use.  I replaced the `docs/book/README.md` instructions for GitBook with mdBook instructions, for other folks who want to come in and make documentation changes.  I searched the project and didn't see any other references to GitBook.
> Remove GitBook instructions/reference and add mdBook instructions

- test/e2e/test_context.go
Add warning prefix to the non-critical error logs, e.g. error during
cleanup. We always run cleanup code no matter if the test succeed or fail.
So cleanup may return errors, when early steps fail.
> :running: improve v2 e2e tests logging

- .travis.yml
- Replace get the latest version of dep by using the version 0.5.1 which we know that should work with go 1.12+. 
- Add GOPROXY=https://proxy.golang.org/ env in the Travis
- Fix indentation as well 
**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1085
**Root Cause**
It was getting the latest one which will require 1.13 now and the project is not supporting it yet.
> fix(ci): By using fix version of dep which is compatible with go 1.12

- designs/simplified-scaffolding.md
- docs/book/src/cronjob-tutorial/testdata/emptymain.go
- docs/book/src/cronjob-tutorial/testdata/project/main.go
- docs/book/src/multiversion-tutorial/testdata/project/main.go
- pkg/scaffold/v2/main.go
- testdata/project-v2/main.go
`zap.Logger` has been deprecated so it's necessary to use `zap.New`.
ref) https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/log/zap/zap.go#L44
> Use zap.New instead of zap.Logger in ctrl.SetLogger

- common.sh
Ensure that the common.sh script will be always able to download the file. 
**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1087 and https://github.com/kubernetes-sigs/kubebuilder/issues/1078
**Following the local tests**
> fix: remove tmp/vendor.v1.tgz to ensure that it will work always

- Makefile
- scripts/install_and_setup.sh
* Add targets for all scripts which need to be used
* Add comments over targets and doc the project by using help 
* Add go get module kind which is required to run the target
* Upgrade Kind from `sigs.k8s.io/kind@v0.4.0` to `sigs.k8s.io/kind@v0.5.1`
**Motivation**
* To make easier use and understand what is required
* Avoid doing manually the required workaround to update the test data currently
* Solve the issue `common.sh: line 160: kind: command not found` when `make test-project-generation` is used
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1089
> feat(makefile improvements) + feat(upgrade kind dep/module)

- docs/book/src/SUMMARY.md
- docs/book/src/reference/testing/envtest.md
- docs/book/src/reference/writing-tests.md
- docs/testing/integration.md
ref: https://github.com/kubernetes-sigs/kubebuilder/issues/1000
This commit adds documentation on available options (environment
variables and flags) to configure the control plane set up using
envtest.
For now, it also adds the pre-existing integration.md file to
/references and links it to the kubebuilder book; this _might_ turn out
being out of scope (more on this below).
Feedback on the following would be very useful (in addition to anything missing or not quite right):
* Level of detail on what each option affects. Is it too vague/too detailed/ about right at the moment?
* (as mentioned above) I've added this content to integration.md, because some documentation related to integration testing was there already, so it seemed like a fitting spot. I'm not sure what intentions the author …
> Document envtest options

- .travis.yml
- common.sh
- scripts/install.sh
- test_ci.sh
Update common.sh to fetch missing dependencies when SKIP_FETCH_TOOLS is false.
We could also build base images with the artifacts (dep, kubebuilder, etcd, api-server, v1 and v2 project tarballs) inside them. I'm not familiar with the (any?) process for publishing official images in Kubernetes projects, and we can always iterate, so I'm offering this up as an initial cut
> 🏃 task: enable running tests in prow

- CONTRIBUTING.md
- docs/CONTRIBUTING-ROLES.md
This adds documentation of formal code contributor roles (reviewer,
approver) and criteria for attaining those roles.  It also adds notes on
non-code roles.
Fixes #1086 
> Formal Contributor Roles

- build/cloudbuild_tools.yaml
- build/thirdparty/darwin/Dockerfile
- build/thirdparty/linux/Dockerfile
This PR has changes required to build k8s 1.15.5 binaries that needs to be shipped with kubebuilder releases.
> :sparkles: upgraded k8s binaries to 1.15.5

- docs/book/src/reference/generating-crd.md
Fixed printer column examples. 
Fixes issue: https://github.com/kubernetes-sigs/kubebuilder/issues/1114
> Fixed printer column examples in the generating-crd reference doc

- .travis.yml
- pkg/scaffold/v2/certmanager/certificate.go
- pkg/scaffold/v2/certmanager/kustomizeconfig.go
- pkg/scaffold/v2/crd/enablecainjection_patch.go
- pkg/scaffold/v2/kustomize.go
- pkg/scaffold/v2/types.go
- pkg/scaffold/v2/webhook/enablecainection_patch.go
- scripts/install_and_setup.sh
- test/e2e/utils/test_context.go
- test/e2e/v2/e2e_suite.go
- testdata/project-v2/api/v1/admiral_types.go
- testdata/project-v2/api/v1/captain_types.go
- testdata/project-v2/api/v1/firstmate_types.go
- testdata/project-v2/config/certmanager/certificate.yaml
- testdata/project-v2/config/certmanager/kustomizeconfig.yaml
- testdata/project-v2/config/crd/bases/crew.testproject.org_admirals.yaml
- testdata/project-v2/config/crd/bases/crew.testproject.org_captains.yaml
- testdata/project-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
- testdata/project-v2/config/crd/patches/cainjection_in_admirals.yaml
- testdata/project-v2/config/crd/patches/cainjection_in_captains.yaml
- testdata/project-v2/config/crd/patches/cainjection_in_firstmates.yaml
- testdata/project-v2/config/default/kustomization.yaml
- testdata/project-v2/config/default/webhookcainjection_patch.yaml
This PR updates the `group` and `version` references to `cert-manager` to function correctly with `v0.11`.
>The v0.11 release marks the removal of the v1alpha1 API that was used in previous versions of cert-manager, as well as our API group changing to be cert-manager.io instead of certmanager.k8s.io.
https://docs.cert-manager.io/en/latest/tasks/upgrading/upgrading-0.10-0.11.html
Fixes #1093 
Todo:
> :sparkles: Update cert-manager group and version to match 0.11 change

- build/cloudbuild.yaml
- build/cloudbuild_local.yaml
- build/cloudbuild_snapshot.yaml
- common.sh
Changes:
- Use Kubernetes 1.15.5 binaries in tests
- Use Kubernetes 1.15.5 in release bundle
> :running: bump up k8s tools to 1.15.5

- Makefile
- pkg/scaffold/v2/controller.go
- testdata/project-v2/controllers/namespace_controller.go
**Description** 
Add missing import.
**Motivation**
Closes: #1119
> Fix import

- pkg/scaffold/api.go
- plugins/addon/channel.go
- plugins/addon/controller.go
- plugins/addon/helpers.go
- plugins/addon/manifest.go
- plugins/addon/type.go
This change adds the plumbing for plugins to act on the controller and fixes the addon pattern to output a buildable controller.
changes:
- controller runs in a second phase and needs the Plugins configured on
the Scaffold
- fix path to the api/<version>/<resource>_type.go file for file
replacement
- make the addon plugin work with the 2 phase run (api then controller)
by not failing if the manifest/channel file has already been generated
- fixup import paths
> plugins/addon: perform replacements for type and controller

- docs/book/src/reference/testing/envtest.md
This fixes syntax highlighting and the `append` usage (to avoid mutating
the default flag slice) in the envtest reference in the book.
> :book: Fix syntax highlighting & append in envtest ref

- pkg/scaffold/v1/resource/resource.go
- pkg/scaffold/v1/resource/resource_test.go
kinds expected to be Pascal case
> minor typo fix in kind string format validation

- cmd/init_project.go
- cmd/main.go
This PR deprecates v1 projects. Fixes #1136
> Deprecate v1 projects

- pkg/scaffold/api.go
Delegate resource validation to itself
Fixes #1145
> Remove duplicated scaffold API validation code

- go.mod
- go.sum
- pkg/scaffold/input/input.go
- pkg/scaffold/project/project.go
- pkg/scaffold/scaffold.go
- testdata/gopath/src/project/PROJECT
- testdata/project-v2/PROJECT
This implements the `yaml` parsing using the `sigs.k8s.io/yaml` parser instead of the `gopkg.in/yaml.v2` libraries.
This was motivated by trying to keep all dependencies within sig/k8s owned projects.
closes #1166
> Use sigs.k8s.io/yaml for parsing.

- cmd/init_project.go
- pkg/scaffold/api.go
> Error string should not be capitalized or end with punctuation inspection
> Reports error strings format issues.
> Error strings should not be capitalized or end with punctuation mark.
> See [Code review comments: error strings](https://github.com/golang/go/wiki/CodeReviewComments#error-strings) for more details.
Closes: #1177
/kind cleanup
> Error string formatting

- cmd/main.go
- cmd/version/version.go
Change list:
- Avoid variable and package name collision
- Stop exporting get version function
- Document why version strings cannot be constants
/kind cleanup
> Solve name collision and document why version strings can not be const

- pkg/scaffold/output.go
Tiny PR that removes the filesystem creation if it is `nil` as that is already being done at the start of `WriteCloser` method that is called right away.
/kind cleanup
> Remove duplicate code

- pkg/scaffold/resource/resource.go
- pkg/scaffold/resource/resource_test.go
- solve the scaffolding issue with groups with `.` as example.com by doing the same fix that is done with `-`
**Motivation**
Closes: #1138
> solve issue with groups with '.' as example.com

- cmd/api.go
- pkg/scaffold/api.go
This changeset updates `create api` command logic, rejecting duplicate APIs by default, but allowing to continue with `--force` flag.
Note that it only affects v2 projects, since in v1 projects resources are not tracked by the PROJECT file.
Fixes #1110
> Handle creation of duplicate API resources

- docs/book/src/reference/testing/envtest.md
...and offer one example of how to cover owner relationship in integration
tests.
This is something that has tripped us up quite a bit, maybe there's others.
xref: https://github.com/kubernetes-sigs/controller-runtime/issues/626
cc @hoegaarden
> Document lack of controller manager in integration tests

- pkg/scaffold/api.go
- pkg/scaffold/v2/crd_editor_rbac.go
- pkg/scaffold/v2/crd_viewer_rbac.go
- test/e2e/v2/e2e_suite.go
- testdata/project-v2/config/rbac/admiral_editor_role.yaml
- testdata/project-v2/config/rbac/admiral_viewer_role.yaml
- testdata/project-v2/config/rbac/captain_editor_role.yaml
- testdata/project-v2/config/rbac/captain_viewer_role.yaml
- testdata/project-v2/config/rbac/firstmate_editor_role.yaml
- testdata/project-v2/config/rbac/firstmate_viewer_role.yaml
- Add editor and viewer roles for each CRD
**Motivation**
Closes: #886
> feat(rbac) : add editor and viewer role for crds

- docs/book/src/cronjob-tutorial/webhook-implementation.md
- docs/book/src/reference/markers/webhook.md
Adds the command to scaffold out webhooks to the docs. It was in the migration guide, but the main docs were incomplete. If you didn't run the scaffolding and just satisfy the validator/defaulter interfaces as mentioned, you would not actually be calling `SetupWebhookWithManager()` in your main and you might be confused why the thing that it says automatically happens does not in fact automatically happen.
> Add webhook scaffolding to docs

- netlify.toml
URL starting with `console.cloud.google.com` requires user to login before download anything. This defeat our purpose of making these public accessible.
This PR switch them to use `storage.googleapis.com` which doesn't require anything if the file to download is public.
> :running: fix kubebuilder go links

- .travis.yml
- common.sh
- scripts/setup.sh
- test_e2e.sh
Fixes prow e2e optional presubmit (maybe?)
> :running: 🛠 fix prow presubmits

- pkg/scaffold/v2/crd_editor_rbac.go
- pkg/scaffold/v2/crd_viewer_rbac.go
- testdata/project-v2/config/rbac/admiral_editor_role.yaml
- testdata/project-v2/config/rbac/admiral_viewer_role.yaml
- testdata/project-v2/config/rbac/captain_editor_role.yaml
- testdata/project-v2/config/rbac/captain_viewer_role.yaml
- testdata/project-v2/config/rbac/firstmate_editor_role.yaml
- testdata/project-v2/config/rbac/firstmate_viewer_role.yaml
As @erictune pointed out in https://github.com/kubernetes-sigs/kubebuilder/pull/1165#discussion_r347689204, editor role is intended for end users which should not have permissions to edit `*/status`.
fixes #886
> :bug: end users should not have permissions to edit */status

- docs/book/src/cronjob-tutorial/api-design.md
- docs/book/src/cronjob-tutorial/running-webhook.md
- docs/book/src/cronjob-tutorial/testdata/emptyapi.go
- docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
- docs/book/src/multiversion-tutorial/api-changes.md
First of all, thanks so much for kubebuilder, and especially for the book. I learned a lot of new things about building controllers from reading it, even after having built a few controllers (not using kubebuilder) in production. The book does a phenomenal job of explaining why certain things need to be done, and it is a really great idea to explain the code-level concepts in the actual code itself (via the literate Go snippets).
While reading through the book, I noticed a few small spelling mistakes and tweaks that I thought I'd send a PR to fix.
> docs/book: small grammar/spelling tweaks

- cmd/util/util.go
Evaluate and remove non-needed exported functions or at least make them non-exported to reduce the API surface.
> Unused exported function inspection
> Reports unused exported functions.
Closes: #1178
/kind cleanup
> Unused exported functions removal

- docs/book/src/quick-start.md
- docs/book/src/reference/writing-tests.md
The envtest link was incorrect -- it should point to /reference/testing/envtest
> fix typo/invalid link in the book

- docs/book/src/quick-start.md
This fixes a few issues with the guestbook types:
* Uses tabs instead of spaces
* Dedupes the `GuestbookStatus` struct
* Adds a `Guestbook` type
* Removes the `TLS` field from the `GuestbookSpec` since the
corresponding `TLSPolicy` type is neither defined nor imported
* Removes the `Nodes` field from the `GuestbookSpec` struct
[Closes #1238]
> Fix guestbook types in Quick Start

- cmd/webhook_v1.go
- pkg/scaffold/v1/crd/doc.go
- pkg/scaffold/v1/webhook/add_server.go
- pkg/scaffold/v1/webhook/admissionbuilder.go
- pkg/scaffold/v1/webhook/admissionhandler.go
- pkg/scaffold/v1/webhook/server.go
- pkg/scaffold/v1/webhook/webhook_test.go
- pkg/scaffold/v2/controller_suitetest.go
- pkg/scaffold/v2/webhook/webhook.go
Removes some fields that `File` structs had but are not being used.
/kind cleanup
> Remove scaffolding fields that were not used

- .travis.yml
- CONTRIBUTING.md
- Makefile
- cmd/init_project.go
- cmd/main.go
- cmd/util/validations.go
- common.sh
- pkg/scaffold/api.go
- pkg/scaffold/resource/resource.go
- pkg/scaffold/util/util.go
- pkg/scaffold/v1/webhook/admissionbuilder.go
- pkg/scaffold/v1/webhook/admissionhandler.go
- pkg/scaffold/v1/webhook/util.go
- pkg/scaffold/v1/webhook/webhook_test.go
- pkg/scaffold/v2/internal/string_utils_test.go
- scripts/verify.sh
- test/e2e/utils/kubectl.go
- test/e2e/v2/e2e_suite.go
- add golangci-lint as linter (same used in controller-runtime see [here](https://github.com/kubernetes-sigs/controller-runtime/blob/15b5243f9fde6794ee298dfa9d21d7072bec3a3f/hack/check-everything.sh#L69-L75)). 
- fix the basic tests which are enabled when we run only ` golangci-lint run` in order to add it
Following the fixes made.
```
$ golangci-lint run
pkg/scaffold/api.go:278:6: SA6005: should use !strings.EqualFold(a, b) instead of strings.ToLower(a) != strings.ToLower(b) (staticcheck)
if strings.ToLower(r.Group) != strings.ToLower(existingGroup) {
^
cmd/util/util.go:25:2: S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (gosimple)
if err != nil {
^
test/e2e/v2/e2e_suite.go:335:5: S1003: should use !strings.Contains(input, …
```
> Add lint check and fix min required issues

- docs/book/src/reference/writing-tests.md
- docs/testing/e2e.md
- docs/testing/integration.md
The link `Writing and Running Integration Tests` on the [documentation](https://book.kubebuilder.io/reference/writing-tests.html) is wrong.
This fix links the URL to `../../../testing/integration.md` that seems to be the correct link!
> Fix the wrong link

- test_e2e.sh
Fixes https://github.com/kubernetes-sigs/kubebuilder/issues/1223
Don't think we actually need to do anything more complicated here, just want to cleanup after ourselves.
> tests: delete kind cluster after e2e

- CONTRIBUTING.md
- RELEASE.md
There really isn't more to say about this.
> community: fix discussion group links

- cmd/webhook_v1.go
- cmd/webhook_v2.go
- pkg/scaffold/v1/crd/suite_test.go
- pkg/scaffold/v1/webhook/webhook_test.go
Webhooks and some tests were using resources without validation. This may end up in some unexpected bugs in the future
/kind cleanup
> Validate resources for webhooks and tests

- .travis.yml
- build/cloudbuild.yaml
- build/cloudbuild_local.yaml
- build/cloudbuild_snapshot.yaml
- common.sh
Changes:
Use Kubernetes 1.16.4 binaries in tests
Use Kubernetes 1.16.4 in release bundle
> 🏃 Bump k8s tools to 1.16.4

- docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
- docs/book/src/migration/testdata/gopath/project-v1/pkg/controller/cronjob/cronjob_controller.go
- docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
`sigs.k8s.io/controller-runtime/pkg/client` includes the code for ignoreNotFound for a few months, see
[IgnoreNotFound](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/interfaces.go#L130)
This PR proposes to remove the code from kubebuilder. That is because the client package has to be part of the dependencies, it simplifies the work and it remove another dependency.
> remove ignoreNotFound code and rely on controller-runtime

- pkg/scaffold/v2/makefile.go
init has a --path argument that specifies where the boilerplate file should be
written to. Unfortunately, the Makefile generation wasn't taking it into
account.
> scaffold: Don't hardcode the boilerplate path in the Makefile

- build/.goreleaser.yml
- cmd/util/validations.go
- docs/book/install-and-build.sh
- docs/book/litgo.sh
- docs/book/markerdocs.sh
- pkg/model/types.go
- pkg/scaffold/input/input_suite_test.go
- pkg/scaffold/input/input_test.go
- pkg/scaffold/project/project_suite_test.go
- pkg/scaffold/project/project_test.go
- pkg/scaffold/resource/resource_suite_test.go
- pkg/scaffold/resource/resource_test.go
- pkg/scaffold/scaffold_suite_test.go
- pkg/scaffold/scaffold_test.go
- pkg/scaffold/v1/crd/suite_test.go
- pkg/scaffold/v1/manager/manager_suite_test.go
- pkg/scaffold/v1/manager/manager_test.go
- pkg/scaffold/v1/webhook/webhook_suite_test.go
- pkg/scaffold/v1/webhook/webhook_test.go
- pkg/scaffold/v2/prometheus/monitor.go
- scripts/generate_dep_manifest.sh
- scripts/install.sh
- test/kind-config.yaml
Added copyrights to the following files: 
/build/.goreleaser.yml
/docs/book/install-and-build.sh
/docs/book/litgo.sh
/docs/book/markerdocs.sh
/cmd/util/validations.go
/pkg/model/types.go
/pkg/scaffold/scaffold_suite_test.go
/pkg/scaffold/scaffold_test.go
/pkg/scaffold/input/input_suite_test.go
/pkg/scaffold/input/input_test.go
/pkg/scaffold/project/project_suite_test.go
/pkg/scaffold/project/project_test.go
/pkg/scaffold/resource/resource_suite_test.go
/pkg/scaffold/resource/resource_test.go
/pkg/scaffold/v1/crd/suite_test.go
/pkg/scaffold/v1/manager/manager_suite_test.go
/pkg/scaffold/v1/manager/manager_test.go
/pkg/scaffold/v1/webhook/webhook_suite_test.go
/pkg/scaffold/v1/webhook/webhook_test.go
/pkg/scaffold/v2/prometheus/monitor.go
/scripts/generate_dep_manifest.sh …
> Added copyrights

- scripts/verify.sh
Enable the lint check goimports
Note that nothing needed to be fixed in this case.
> :running: Enable the lint check goimports 

- pkg/scaffold/api.go
`resource` is a package name, so using the same for the variable is a collision:
https://github.com/kubernetes-sigs/kubebuilder/blob/3ec07ea772fe1f392f37347b50c354d3b578f4bb/pkg/scaffold/api.go#L29
/kind bug
> Resolve package and variable name collision

- pkg/scaffold/input/input.go
- pkg/scaffold/scaffold.go
- pkg/scaffold/v2/controller/controller_suitetest.go
The method `setFieldsAndValidate` was doing two things, as the name suggests. The logic has been split into two separate methods: `setFields` and `validate`. The `Validate` interface has been modified so that it is only implemented by files, as other structs as resources or some scaffolders also use the `Validate() error` signature.
/kind cleanup
> Split injecting fields and validating files

- pkg/scaffold/v1/controller/controller.go
- pkg/scaffold/v1/controller/controllersuitetest.go
- pkg/scaffold/v1/controller/controllertest.go
- pkg/scaffold/v2/certmanager/certificate.go
- pkg/scaffold/v2/certmanager/kustomize.go
- pkg/scaffold/v2/certmanager/kustomizeconfig.go
- pkg/scaffold/v2/controller/controller.go
- pkg/scaffold/v2/crd/enablecainjection_patch.go
- pkg/scaffold/v2/crd/enablewebhook_patch.go
- pkg/scaffold/v2/prometheus/kustomize.go
- pkg/scaffold/v2/prometheus/monitor.go
- pkg/scaffold/v2/webhook/webhook.go
- pkg/scaffold/v2/webhook_manager_patch.go
Some structs that implemented `File` interface did not have the interface check that most of the structs had. This PR adds the missing ones.
/kind cleanup
> Add interface validation check for missing types

- .gitignore
- .travis.yml
- Makefile
- Add coveralls to check the % of code covered.
See: https://coveralls.io/github/kubernetes-sigs/kubebuilder
> feat add coverage tests

- pkg/scaffold/v2/controller/controller_suitetest.go
- pkg/scaffold/v2/internal/string_utils_test.go
- scripts/verify.sh
`go vet` and `go fmt` were being called before `golangci-lint`. The later is able to run those two checks and that will benefit from the speed enhancements golangci-lint does (concurrency, evaluating files only once, building shared caches, etc.)
> Delegate go vet and go fmt to golangci-lint

- pkg/scaffold/api.go
- pkg/scaffold/scaffold.go
- pkg/scaffold/v2/crd/kustomization.go
- pkg/scaffold/v2/crd/kustomizeconfig.go
Two files were being scaffolded with the `IfExistsAction` set to `Error` which will make the scaffolder return an error, and these kinds of errors were being skipped afterwards. `IfExistsAction` set to `Skip` (default value) is the official way of achieving this.
After doing so, the `isAlreadyExistsError` was unused, and therefore there was no reason to keep `alreadyExistsError` as a struct, `fmt.Errorf` was used instead to simplify the code.
/kind bug
> Fix unofficial way of handling already existing files

- cmd/util/util.go
- scripts/verify.sh
Ensure that all default ones will be enabled. See: https://github.com/golangci/golangci-lint#enabled-by-default-linters
> add missing lints to keep enabled all default ones

- .travis.yml
- We do not need to run the golint checks in all servers as the golden scripts. Just check them once would be enough.
> (travis improvements): Run checks scripts just once

- cmd/edit.go
- pkg/scaffold/api.go
- pkg/scaffold/project.go
- pkg/scaffold/scaffold.go
- pkg/scaffold/util/util.go
- pkg/scaffold/v1/crd/crd_sample.go
- pkg/scaffold/v2/controller/controller_suitetest.go
- pkg/scaffold/v2/main.go
- pkg/scaffold/v2/prometheus/monitor.go
- scripts/verify.sh
- test/e2e/utils/kubectl.go
- test/e2e/utils/test_context.go
- test/e2e/v1/e2e_suite.go
- test/e2e/v2/e2e_suite.go
- Enable golint check
- Fix issues /(Clean code)
Closes: #1181
> enable lint golint and fix notifications

- pkg/scaffold/v2/webhook/webhook.go
- testdata/project-v2-multigroup/apis/crew/v1/captain_webhook.go
- testdata/project-v2-multigroup/apis/ship/v1beta1/frigate_webhook.go
- testdata/project-v2/api/v1/captain_webhook.go
- testdata/project-v2/api/v1/firstmate_webhook.go
> :bug: replace pkg/runtime/log for pkg/log in just the v2 scaffolding.

- scripts/verify.sh
Suggested in https://github.com/kubernetes-sigs/kubebuilder/pull/1310#discussion_r367616222
Tacked in #1309
/kind cleanup
> Order linters

- .travis.yml
- test.sh
Order Travis script execution in order to avoid using resources if easier checks fail. If any stage fails, the rest are not executed, and thus easy to run stages should be placed first.
The order chosen has been:
1. Linting: fastest to run (`verify.sh`).
2. Golden test: only executed once (`golden_test.sh`).
3. Local test: only executed once (`test.sh`).
4. Test: executed for several OS, Go and K8s configurations (`test_e2e.sh`).
5. Coverage: trivial (`make test-coverage`).
Additional changes:
- `test.sh` was being run with `test_e2e.sh` so it was being executed 4 times when only 2 are needed (`linux` and `osx`).
- `golden_test.sh` was being run with `verify.sh` so if `verify.sh` failed, you needed to wait 5-10 minutes to finish that test.
- `test.sh` was not testing the multi-group …
> Order travis stages and clean non-needed tests

- cmd/vendor_update.go
- cmd/webhook_v1.go
- cmd/webhook_v2.go
- pkg/model/file.go
- pkg/model/resource.go
- pkg/model/universe.go
- pkg/scaffold/api.go
- pkg/scaffold/project.go
- pkg/scaffold/scaffold.go
- plugins/addon/type.go
Include the PROJECT file into `model.Universe`.
It also provides a constructor for `model.Universe` called `model.NewUniverse` that uses the functional options paradigm to provide optional configuration.
The main motivation is providing plugins access to the configuration file. Additionally, `scaffold.Execute` needs some information aside from the files it scaffolds. Right now this informnation is provided in three different ways. As fields to the `Scaffold` instance, the first parameter to `Scaffold.Execute` (`model.Universe`), and the second parameter to `Scaffold.Execute` (`input.Options`). This change is a first step into providing a single way to provide that information.
/kind feature
> Include PROJECT file information into model.Universe

- OWNERS
- OWNERS_ALIASES
The `OWNERS` and `OWNERS_ALIASES` files format were outdated, I followed the guide in https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md to update to the current format.
NOTE: no new reviewer nor approver was added with this change.
> Update OWNERS and OWNERS_ALIASES files to new format

- plugins/README.md
The Cluster Addons sub-project decided to use 'cluster-addons' consistently across Slack, Github and elsewhere, cf https://github.com/kubernetes/org/issues/1583
> repository and sub-project name is cluster-addons now

- OWNERS
- OWNERS_ALIASES
This cleans up old users from the OWNERS and OWNERS_ALIASES files.
This should mean that folks who get assigned for reviews are now active.
> Clean old users from the OWNERS file

- common.sh
The code `(go mod edit -json &>/dev/null)` fails if modules are not enabled because of `set -o errexit`. This commit fixes it so the script continues its execution.
> Fix "if modules enabled" check in common.sh

- pkg/scaffold/project/project_test.go
- scripts/verify.sh
Enabled linters: prealloc, scopelint, typecheck, unconvert
On my local run only "unconvert" linter had an issue in `pkg/scaffold/project/project_test.go` which is fixed.
Part of #1309
> Enable linters for golangci-lint

- docs/book/theme/css/general.css
This removes the margin before/after collapsible code blocks, so that
collapse-normal-collapse mostly appears as one continuous block.
> :book: Bikeshed styling on code blocks in books a bit

- pkg/model/resource/options.go
- pkg/model/resource/options_test.go
- pkg/model/resource/validation.go
This PR should address issues https://github.com/kubernetes-sigs/kubebuilder/issues/1019 and https://github.com/kubernetes-sigs/kubebuilder/issues/1091.
The implementation uses the validation logic that runs against `Kind` in
apimachinery; i.e. allows any `Kind` value that, when converted to
lowercase, is a valid DNS-1035 label.
Reusing that logic instead of reimplementing it helps with ensuring that
the two (i.e. `Kind` validation in core Kubernetes and `Kind` validation
in kubebuilder) are as similar as possible.
Would love feedback on:
* The choice to use [`k8s.io/apimachinery` logic](https://github.com/kubernetes/kubernetes/blob/b3b15a9e260ac65edfa14dd80add9046f3fa9b1f/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L549-L582) vs continuing …
> Support mixed case Kind

- designs/extensible-cli-and-scaffolding-plugins-phase-1.md
- designs/extensible-cli-and-scaffolding-plugins.md
**Description of the change**
This PR adds a design proposal for Kubebuilder CLI and scaffolding extensibility
**Motivation for the change**
To achieve agreement on a way forward for Kubebuilder CLI and scaffolding extensibility so that the Kubernetes controller/operator communities can align on Go project layouts and enable extension points for other customizations.
> designs: extensible CLI and scaffolding plugins

- common.sh
- docs/book/src/reference/kind.md
kind deprecated get kubeconfig-path, we should just directly export the kubeconfig for e2e.
found while debugging some flakey tests
> 🏃‍♂️ fix kind kubeconfig export and docs

- .travis.yml
Prow and Travis are overlapping. This PR removes the e2e tests from Travis but leaves the local tests, as the OSX version isn't run by prow.
#1344
> Remove overlapping tests with Prow

- .golangci.yml
- scripts/verify.sh
This change adds `.golangci.yml` file for better control over linting with `golangci-lint`. The list of linters moved from `scripts/verify.sh` to this file. No linters were added or removed.
This was suggested in https://github.com/kubernetes-sigs/kubebuilder/issues/1267#issuecomment-571814215
Also kind of related to https://github.com/kubernetes-sigs/kubebuilder/issues/1309
> Introduce .golangci.yml

- pkg/model/resource/resource.go
- pkg/scaffold/internal/templates/v1/crd/addtoscheme.go
- pkg/scaffold/internal/templates/v1/crd/crd_sample.go
- pkg/scaffold/internal/templates/v1/crd/doc.go
- pkg/scaffold/internal/templates/v1/crd/group.go
- pkg/scaffold/internal/templates/v1/crd/register.go
- pkg/scaffold/internal/templates/v1/crd/types.go
- pkg/scaffold/internal/templates/v1/crd/typestest.go
- pkg/scaffold/internal/templates/v1/crd/version_suitetest.go
- pkg/scaffold/internal/templates/v2/controller/controller_suitetest.go
- pkg/scaffold/internal/templates/v2/crd/enablecainjection_patch.go
- pkg/scaffold/internal/templates/v2/crd/enablewebhook_patch.go
- pkg/scaffold/internal/templates/v2/crd_editor_rbac.go
- pkg/scaffold/internal/templates/v2/crd_sample.go
- pkg/scaffold/internal/templates/v2/crd_viewer_rbac.go
- pkg/scaffold/internal/templates/v2/group.go
- pkg/scaffold/internal/templates/v2/types.go
- pkg/scaffold/internal/templates/v2/webhook/webhook.go
After resouce validation was moved to the `Options` struct (#1255), `Resource.Validate()` is a no-op.
This PR requests removes these `Validate` functions.
> Remove no-op validations

- docs/book/src/multiversion-tutorial/deployment.md
This PR fixes the documentation reference to the correct code snippet in the multiversion-tutorial/deployment.md.
Fix #1392
> Fix multiversion deployment example

- pkg/model/file/funcmap.go
- pkg/model/file/interfaces.go
- pkg/scaffold/internal/machinery/scaffold.go
- pkg/scaffold/internal/templates/v2/main.go
- testdata/project-v2-multigroup/main.go
- testdata/project-v2/main.go
https://github.com/kubernetes-sigs/controller-runtime/pull/446 removed the defaulting for LeaderElectionID.
It makes sense for controller-runtime. But kubebuilder should still be able to scaffold a project that work out-of-box.
So we will give users some instructions to update it in code comment.
> :sparkles: default a LeaderElectionID

- plugins/addon/type.go
We weren't processing the Namespaced field.
Equivalent of #864
> declarative pattern: Support cluster scoped types

- docs/book/src/multiversion-tutorial/api-changes.md
I'm pretty sure this is supposed to say `v1` instead of `v2`.
> Clarifying a sentence re: backwards compatability

- pkg/scaffold/internal/templates/v2/controller/controller_suitetest.go
Fixes #1416 
This change includes the addition of a missing import, `"sigs.k8s.io/controller-runtime/pkg/envtest"` in the scaffold file `controllers/suite_test.go`.
> Include the missing envtest import.

- plugins/addon/controller.go
- plugins/addon/type.go
The plugin addon template is out-of-date and breaks functionality when creating api using the `--pattern=addon` flag.
This PR fixes the plugin addon template.
> Fix broken plugin addon template

- docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- docs/book/src/migration/testdata/gopath/project-v1/config/default/manager_auth_proxy_patch.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- pkg/scaffold/internal/templates/v1/metricsauth/kustomize_auth_proxy_patch.go
- pkg/scaffold/internal/templates/v2/metricsauth/auth_proxy_patch.go
- test_e2e.sh
- testdata/gopath/src/project/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v2-multigroup/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v2/config/default/manager_auth_proxy_patch.yaml
The current kube-rbac-proxy image used by kubebuilder contains a version of `musl` that is vulnerable to [CVE-2019-14697](https://nvd.nist.gov/vuln/detail/CVE-2019-14697)
Based on #1041, I believe kubebuilder follows upstream for kube-rbac-proxy. Upstream has released v0.5.0 which includes the patched version of `musl`. 
This PR updates the image used in this project. However, I believe similar to #1021, it will first require an owner to hand-tag and release v0.5.0, please.
> bump kube-rbac-proxy to v0.5.0

- docs/book/src/multiversion-tutorial/deployment.md
This describes how kubectl handles preferred versions, with a link to
the official docs.  This should make it clearer how folks can expect
users to interact with multiversion APIs.  It also adds a reminder to
always use qualified GVRs in scripts.
> :book: note multiversion kubectl behavior

- internal/config/config.go
So `Config.Version` does not also need to be updated when `DefaultVersion` is changed in the future.
> internal/config/config.go: use `DefaultVersion` instead of `config.Version2`

- cmd/edit.go
- cmd/update.go
- designs/extensible-cli-and-scaffolding-plugins-phase-1.md
- internal/cmdutil/cmdutil.go
- pkg/cli/api.go
- pkg/cli/cli.go
- pkg/cli/cmd_helpers.go
- pkg/cli/init.go
- pkg/cli/webhook.go
- pkg/plugin/plugin.go
- pkg/plugin/v1/api.go
- pkg/plugin/v1/init.go
- pkg/plugin/v1/webhook.go
- pkg/plugin/v2/api.go
- pkg/plugin/v2/init.go
- pkg/plugin/v2/webhook.go
- pkg/scaffold/api.go
- pkg/scaffold/edit.go
- pkg/scaffold/init.go
A config object is initialized/loaded/saved by the CLI. Scaffolds or plugins shouldn't have to load/save a config object, nor should anything exported have internal parameters that cannot be populated if called outside of kubebuilder.
/cc @DirectXMan12 @mengqiy @Adirio @camilamacedo86
> cli: delegate management of a config to a `CLI`

- cmd/main.go
- designs/extensible-cli-and-scaffolding-plugins-phase-1.md
- pkg/cli/api.go
- pkg/cli/cli.go
- pkg/cli/init.go
- pkg/cli/webhook.go
- pkg/model/config/config.go
- pkg/plugin/plugin.go
- pkg/plugin/v1/init.go
- pkg/plugin/v1/plugin.go
- pkg/plugin/v2/init.go
- pkg/plugin/v2/plugin.go
- pkg/plugin/validation.go
- testdata/project-v2-addon/PROJECT
- testdata/project-v2-multigroup/PROJECT
- testdata/project-v2/PROJECT
**Description of Change:**
* pkg/cli: `--plugins` allows a binary invoker to select which plugins known to a `CLI` to run; this flag can be set with a shortened (non-fully-qualified) name. Either a plugin name passed to `--plugins` or the name set in an initialized project's config layout, in order of precedence, is resolved to a known plugin.
* pkg/model/config: add project file `layout` key, containing the `Init` plugin key that scaffolded a project
* pkg/{cli,plugin}: add plugin name validation
* pkg/plugin/v2: set `layout` key in config
**Motivation for Change:** finishes up phase 1 of plugin implementation. The `layout` key determines which plugin (name and version) initialized a project, useful for a plugin implementation to deduce which post-init plugins should be called. …
> feature/plugins: config `layout`, `--plugins` flag, and plugin name validation

- internal/config/config.go
- internal/config/config_test.go
- pkg/model/config/config.go
- pkg/model/config/config_test.go
Other plugins will need to configure their scaffolded projects, requiring the config format to support arbitrary fields in addition to well-defined keys kubebuilder uses. These keys will be housed under the `plugins` key/`Config.ExtraFields`; `EncodeExtraFields()` and `DecodeExtraFields()` handle adding and populating arbitrary objects to/from `ExtraFields`. This feature does not interfere with existing configs or how kubebuilder interacts with them.
Extra fields are only relevant to plugins so this should not go into master first.
/cc @DirectXMan12 @mengqiy @Adirio @camilamacedo86
> config: allow addition of arbitrary extra fields to `Config`

- docs/book/src/quick-start.md
Update quick-start.md to Kubebuilder version 2.3.1 as 2.3.0 has a bug related to api creation.
This could impact new users negatively.
> Update quickstart to 2.3.1

- docs/book/src/quick-start.md
Cherry-pick f6508e6 (update quick-start.md kubebuilder version to 2.3.1) as per request of PR #1450
> Cherry-pick f6508e6 (update quick-start.md kubebuilder version to 2.3.1)

- docs/book/src/cronjob-tutorial/cert-manager.md
- docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/certificate.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/kustomizeconfig.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
Update documentation for certmanager 0.11 group and version change.
Change from certmanager.k8s.io/v1alpha1 to cert-manager.io/v1alpha2.
Fixes #1434 
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>
> Update doc certmanager 0.11 group and version change

- docs/book/src/cronjob-tutorial/cert-manager.md
- docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/certificate.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/kustomizeconfig.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
Update doc certmanager 0.11 group and version change from certmanager.k8s.io/v1alpha1 to cert-manager.io/v1alpha2.
Cherry-pick by request https://github.com/kubernetes-sigs/kubebuilder/pull/1444#pullrequestreview-383924228.
Signed-off-by: JenTing Hsiao <jenting.hsiao@suse.com>
> Cherry-pick c6fea14

- cmd/completion.go
- cmd/main.go
- docs/book/src/SUMMARY.md
- docs/book/src/quick-start.md
- docs/book/src/reference/completion.md
- docs/book/src/reference/reference.md
Description: 
Add completion command to enable Auto bash/zsh completion.
Motivation:
To have kubebuilder cli auto completion enabled.
Closes: #1346
>  Add bash/zsh completion command

- cmd/internal/go_version.go
- cmd/internal/go_version_test.go
Upgrade the go check to ensure that the version used is according to the minimal requirements
> update the go check for the minimal required version

- pkg/cli/api.go
- pkg/cli/init.go
- pkg/cli/webhook.go
- pkg/plugin/v1/init.go
- pkg/plugin/v2/init.go
- pkg/plugin/v2/webhook.go
* pkg/plugin: inject command name from Context so help messages contain the correct command name
* pkg/cli: use layout or cliPluginKeys in error messages if no plugin for a command is found
/cc @camilamacedo86 @DirectXMan12 @Adirio
> plugin: improve error and help messages

- pkg/scaffold/internal/templates/v2/main.go
- testdata/project-v2-addon/main.go
- testdata/project-v2-multigroup/main.go
- testdata/project-v2/main.go
Add the use of `utilruntime.Must()` from apimachinery to catch errors with scheme configurations. 
Signed-off-by: Chris Hein <me@chrishein.com>
> Using utilruntime.Must() for adding schemes

- pkg/scaffold/init.go
- pkg/scaffold/internal/templates/v2/makefile.go
- testdata/project-v2-addon/Makefile
- testdata/project-v2-multigroup/Makefile
- testdata/project-v2/Makefile
Resolves #1426
As long as the kustomize binary is already present in the PATH, the makefile behavior will be identical to before this patch (See the [which statement](https://github.com/kubernetes-sigs/kubebuilder/compare/master...toonsevrin:master#diff-c29bfcc8d5d17695c61078bd7fd55ec4R139)). In my opinion this is perfect backwards compatibility and this patch should be included in v2.
Note that the test `continuous-integration/travis-ci/pr` will fail due to the Makefile being changed.
Notes:
* I have not yet tested this (or written automated tests for this)
* Neither controller-gen nor kustomize are currently checksummed (this is a small vulnerability, but was already present): See #1429. This should be patched in a separate PR.
> Install kustomize if not present

- generate_testdata.sh
- test.sh
* generate_testdata.sh: refactor common code for v2 projects
* test.sh: add missing addons test
> test scripts: add missing addons test, some refactoring

- pkg/cli/cli.go
- pkg/cli/cli_suite_test.go
- pkg/cli/cli_test.go
- pkg/cli/init.go
- testdata/project-v2-addon/go.mod
- testdata/project-v3-addon/go.mod
Per discussion in https://github.com/kubernetes-sigs/kubebuilder/pull/1403#discussion_r405014466:
>[H]aving a global --plugins flag is not in scope for phase 1 since the type of plugin used in init solely determines what plugin is used for subsequent commands (the layout config key). A global --plugins flag will be discussed in phase 2: #1378.
~There still may be a use case for phase 1 global `--plugins`: I scaffold a project with `--plugins=go-x` then want to create an API using plugin `go-y`, which "understands" a project initialized by `go-y`; without a global `--plugins` flag I would have to change my config's `layout` value.~
~Thoughts?~
/cc @DirectXMan12 @mengqiy @joelanford
> plugins: move `--plugins` from global to `init`-only

- testdata/project-v2-addon/go.mod
- testdata/project-v3-addon/go.mod
Just `make generate` to update the master branch and fix the CI. 
Reason: The mod kubebuilder-declarative-pattern is added when the testdata add-on project is gen, if it changes after the PR be pushed and the CI finished then, the boot will merge the PR in the master because it will just re-run the prow tests. However, the make check-testdata for the master branch will be executed after the merge and will fail.
Solution: Add `make check-generate` in the prow to avoid this scenario in the future. The need was tracked in: https://github.com/kubernetes-sigs/kubebuilder/issues/1503
> fix: master branch CI with mock testdata update

- pkg/plugin/v2/init.go
- test/e2e/v2/e2e_suite.go
- test/e2e/v3/e2e_suite.go
remove the deprecated flags: depArgs and dep. Use fetch-deps instead of them. See:
```go
if err := fs.MarkDeprecated("dep", "use the fetch-deps flag instead"); err != nil {
log.Printf("error to mark dep flag as deprecated: %v", err)
}
if err := fs.MarkDeprecated("depArgs", "will be removed with version 1 scaffolding"); err != nil {
log.Printf("error to mark dep flag as deprecated: %v", err)
}
```
**Motivation**
comments/suggestions made when we remove the V1 source code
> remove the deprecated flags: depArgs and dep. Use fetch-deps instead of them.

- testdata/project-v2-addon/go.mod
- testdata/project-v3-addon/go.mod
It is just to fix the the testdata. A new change in the module `sigs.k8s.io/kubebuilder-declarative-pattern` was merged and it is indirectly added when the projects with add-on are generated. 
PS.: It is not very common, however, the solution to avoid this scenario would be to add the testdada check to the prow which we already have an issue with this need tracked.
> update testdata to fix CI

- docs/book/src/reference/generating-crd.md
Added an "Age" print column as an example as well.
Its a pretty common use case, and it was not obvious to me how to make it work. In my head, I would have to do something like `now - .metadata.creationTimestamp` somehow.... found that I just need to set the `type` to `date` by digging the prometheus-operator codebase.
Hope this makes it easier for the next people :)
> docs: example of age print column

- test/e2e/utils/test_context.go
- test/e2e/utils/util.go
- test/e2e/v2/e2e_suite.go
- test/e2e/v3/e2e_suite.go
Allow the test utils to be used for other projects as well.
> allow test utils be extended

- pkg/scaffold/edit.go
- testdata/project-v2-multigroup/Dockerfile
- testdata/project-v3-multigroup/Dockerfile
closes: #1500
PS.: I do not consider this bug fix as a braking change because:
After having project scaffold and with the project layout update to multigroup support then, users are still able to use the command to re-run the edit --multigroup=true which would apply the fix. 
ps.: shows that we have not too many users using the multigroup since the issue was not reported so far.
> fix: unable to build multigroup projects

- docs/book/src/cronjob-tutorial/testdata/project/config/rbac/leader_election_role.yaml
- pkg/scaffold/internal/templates/leaderelectionrole.go
- testdata/project-v2-addon/config/rbac/leader_election_role.yaml
- testdata/project-v2-multigroup/config/rbac/leader_election_role.yaml
- testdata/project-v2/config/rbac/leader_election_role.yaml
- testdata/project-v3-addon/config/rbac/leader_election_role.yaml
- testdata/project-v3-multigroup/config/rbac/leader_election_role.yaml
- testdata/project-v3/config/rbac/leader_election_role.yaml
> add patch verb to events in the leader_election_role

- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
- docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
in controller-runtime@v0.6.0 the FieldIndexer interface is
```
type FieldIndexer interface {
// IndexFields adds an index with the given field name on the given object type
// by using the given function to extract the value for that field.  If you want
// compatibility with the Kubernetes API server, only return one key, and only use
// fields that the API server supports.  Otherwise, you can return multiple keys,
// and "equality" in the field selector means that at least one key matches the value.
// The FieldIndexer will automatically take care of indexing over namespace
// and supporting efficient all-namespace queries.
IndexField(ctx context.Context, obj runtime.Object, field string, extractValue IndexerFunc) error
}
```
fix to add a context to IndexField method
just a small fix
> FIX: fix for controller-runtime 0.6.0 GetFieldIndexer().IndexField ctx param

- CONTRIBUTING.md
> doc: add versions information to the contribution guidelines

- pkg/cli/api.go
- pkg/cli/cmd_helpers.go
- pkg/cli/init.go
- pkg/cli/webhook.go
Instead of only using plugin names in command errors, keys should be used for more informative error messages. An action should be suggested in the error message as well.
Additionally, the `init` command setup should use the `cmdErr` idiom used by other command setups for uniform error reporting.
/cc @camilamacedo86 @joelanford @mengqiy
> pkg/cli: use cmd error idiom for 'init' and plugin keys in cmd errors

- pkg/plugin/v2/api.go
- pkg/scaffold/api.go
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1525 
Closes: #1503 (no longer required after it as well)
> fix: fixed version of sigs.k8s.io/kubebuilder-declarative-pattern which should be used

- pkg/cli/cli.go
A `CLI`'s default plugins now contain only one plugin per project version, and the `Option` returned by `WithDefaultPlugins` will return an error if multiple are found. The one-to-one mapping identifies which plugin that should be run when no plugin key is passed via `layout` or `--plugins`.
* pkg/cli: change the type of cli.defaultPluginsFromOptions such that
it maps one project version to one plugin.
Relates to #1536.
/cc @joelanford @camilamacedo86 @DirectXMan12
> pkg/cli: only allow one default plugin per project version

- internal/config/config_test.go
- pkg/model/config/config.go
- pkg/model/config/config_test.go
This PR adds two new types, `PluginConfigs` and `pluginConfig`. `PluginConfigs` is a wrapper for `map[string]pluginConfig` for (de)serialization purposes and `pluginConfig` wraps `interface{}` so users do not have to see internals of plugin config storage.
* pkg/model/config: the `Plugin` field of a `Config` is now of type `PluginConfigs`
* internal,pkg: update test cases
Initial discussion: [#1443](https://github.com/kubernetes-sigs/kubebuilder/pull/1443/files#r398818145).
/cc @DirectXMan12 @mengqiy @camilamacedo86
> pkg/model/config: wrap plugin config in types

- pkg/plugin/plugin.go
- pkg/plugin/plugin_test.go
Plugin version comparisons were incorrect: stage cmp order should be: `stable > beta > alpha`.
/cc @camilamacedo86 @DirectXMan12 @joelanford 
/kind bug
> pkg/plugin/plugin.go: correct version stage comparison

- docs/book/src/reference/using-finalizers.md
> Docs: Fix invalid URL to Kubernetes reference docs in Using Finalizers 

- pkg/cli/init.go
Any flag help printed should be consistent between invocations so generated CLI docs (cobra has a nice API for this) don't break randomly. Also remove duplicate plugin keys from flag help.
/cc @camilamacedo86 @DirectXMan12
> pkg/cli/init.go: make flag help consistent

- DESIGN.md
... I think you meant 'principles' in this case.
> A small correction

- go.mod
- go.sum
Has no need to have in the go.mod `github.com/blang/semver v3.5.1+incompatible` and it has been removed with the go mod tidy.
> clean up via go mod tidy : remove module added github.com/blang/semver v3.5.1+incompatible

- CONTRIBUTING.md
- Makefile
- scripts/setup.sh
- test/e2e/utils/test_context.go
- test_e2e_local.sh
This change introduces a `test_e2e_local.sh` script for running e2e
tests locally. Addresses #1435.
Split out from #1546
> 🌱 local e2e script

- pkg/plugin/v3/scaffolds/internal/templates/main.go
- testdata/project-v3-multigroup/main.go
- Fix controller alias 
**Motivation**
Closes: #1382
> fix: controller alias for multigroups (v3)

- pkg/plugin/v3/scaffolds/internal/templates/leaderelectionrole.go
- testdata/project-v3-addon/config/rbac/leader_election_role.yaml
- testdata/project-v3-multigroup/config/rbac/leader_election_role.yaml
- testdata/project-v3/config/rbac/leader_election_role.yaml
Closes: #1473
Theoretically, any deletion would be a breaking change. However, in this case, we are scaffolding something that does not exist and has no value at all. So, because of this was done for V2,V3. 
blocked;
TODO: Apply to V3 plugin 2.X only.
Waiting for #1498
> fix: remove role for configmaps/status which do not exists from leader_election_role.yaml

- docs/book/src/quick-start.md
- docs/testing/integration.md
- docs/using_an_external_type.md
> doc: fix controller typo

- docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
I believe the intention was to explain idempotence, so this is just a small typo correction
> Fix typo in deleteExternalResources comment

- .travis.yml
- pkg/cli/plugins_test.go
- pkg/plugin/v2/scaffolds/edit.go
- pkg/plugin/v3/scaffolds/edit.go
- test/e2e/utils/util.go
- test/e2e/v2/e2e_suite.go
- test/e2e/v3/e2e_suite.go
- Upgrade lint for the latest version
- perform goftm fix and ignore check for gosec in a false positive raised by it.
> upgrade lint version and perform fixes

- pkg/plugin/v3/scaffolds/internal/templates/main.go
- testdata/project-v3-multigroup/main.go
> feat: add group in the controller logs for multi-group

- docs/book/src/quick-start.md
- pkg/plugin/v3/scaffolds/internal/templates/makefile.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
Add option to undeploy controller.
> feat: add undeploy IMG option (V3 only)

- internal/cmdutil/cmdutil.go
The interface should jump for the next step if a Scaffold was not returned. otherwise, it will fail.
> Check if has Scaffold before exec

- docs/book/src/cronjob-tutorial/testdata/project/.dockerignore
- docs/book/src/multiversion-tutorial/testdata/project/.dockerignore
- pkg/plugin/v3/scaffolds/init.go
- pkg/plugin/v3/scaffolds/internal/templates/dockerignorefile.go
- testdata/project-v3-addon/.dockerignore
- testdata/project-v3-multigroup/.dockerignore
- testdata/project-v3/.dockerignore
> feat: add dockerignore file to the scaffold (V3 only)

- designs/README.md
- designs/simplified-scaffolding.md
- docs/book/getting_started/hello_world.md
- docs/book/src/cronjob-tutorial/controller-overview.md
- docs/book/src/cronjob-tutorial/gvks.md
- docs/book/src/cronjob-tutorial/testdata/emptyapi.go
- docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
- docs/book/src/cronjob-tutorial/testdata/emptymain.go
- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
- docs/book/src/cronjob-tutorial/writing-tests.md
- docs/book/src/migration/v1vsv2.md
- docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_conversion.go
- docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go
- docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_conversion.go
- docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go
- docs/book/src/reference/envtest.md
- docs/book/src/reference/markers.md
- docs/book/src/reference/webhook-for-core-types.md
- docs/book/src/reference/webhook-overview.md
Signed-off-by: knight42 <anonymousknight96@gmail.com>
1. fix outdated links, like `https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/cache#MultiNamespacedCacheBuilder`, by changing them to something like `https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache?tab=doc#MultiNamespacedCacheBuilder`
2. replace links to godoc.org with links to pkg.go.dev
3. remove trailing spaces
> doc: replace links to godoc.org with links to pkg.go.dev

- docs/book/src/quick-start.md
I changed the documentation, so it will contain a working example
Previously, the example not generated the deep copy function required by the SchemeBuilder.Register
It fixes #1586 issue, that complains about the not out of box working example
> Add missing kubebuilder annotation to the getting started document

- pkg/plugin/v3/init.go
- pkg/plugin/v3/scaffolds/internal/templates/kustomize.go
- testdata/project-v3-addon/config/default/kustomization.yaml
- testdata/project-v3-multigroup/config/default/kustomization.yaml
- testdata/project-v3/config/default/kustomization.yaml
When I create a project, I want to be able to specify my project name. Furthermore I would like to create/work on my project in an arbitrary directory. Instead of adding a flag to support setting project name, use the basename of `--repo` which is more likely to be the desired project name than the directory name.
/cc @DirectXMan12 @hasbro17 @camilamacedo86
> pkg/plugin/v3: use repo instead of directory basename as project name

- docs/book/src/cronjob-tutorial/cronjob-tutorial.md
- pkg/model/config/config.go
- pkg/plugin/v3/init.go
- pkg/plugin/v3/scaffolds/init.go
- pkg/plugin/v3/scaffolds/internal/templates/kustomize.go
- testdata/project-v3-addon/PROJECT
- testdata/project-v3-multigroup/PROJECT
- testdata/project-v3/PROJECT
This PR adds a `project-name` config key and an optional `init --project-name` to the v3-alpha plugin. Plugin authors for non-Go plugins will find such a key useful, as `repo` doesn't make much sense for non-Go plugins. This reverts #1596 behavior.
Changes:
* pkg/model/config: add 'project-name' which configures a project's name
* pkg/plugin/v3/init.go: add --project-name which sets a config's 'project-name' key
/cc @pwittrock @camilamacedo86
> config: add `project-name` config key and optional `init --project-name`

- .gitignore
- scripts/setup_envtest_bins.sh
This pr is just for we add the script that will be used in the solution to set up the env test locally for we are able to close #1599. See:
```
camilamacedo@Camilas-MacBook-Pro ~/go/src/sigs.k8s.io/kubebuilder (only-script) $ rm -rf testbin/
camilamacedo@Camilas-MacBook-Pro ~/go/src/sigs.k8s.io/kubebuilder (only-script) $ ./scripts/setup_envtest_bins.sh v1.18.2 v3.4.3
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 26.6M  100 26.6M    0     0  6759k      0  0:00:04  0:00:04 --:--:-- 6760k
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 47.8M  100 47.8M    0     0  7932k      0  0:00:06  0:00:06 --:--:-- 8369k …
```
> feat: add script in the repo to setup envtest

- pkg/model/config/config.go
- pkg/model/file/interfaces.go
- pkg/model/file/mixins.go
- pkg/model/universe.go
- pkg/plugin/v3/init.go
- pkg/plugin/v3/scaffolds/init.go
- pkg/plugin/v3/scaffolds/internal/templates/kustomize.go
- testdata/project-v3-addon/PROJECT
- testdata/project-v3-multigroup/PROJECT
- testdata/project-v3/PROJECT
This PR adds `pkg/model/file.ProjectNameMixin`, which will inject the `Config.ProjectName` into any structs that embed this mixin.
/cc @joelanford @pwittrock
> plugins: change project name config tag, add `pkg/model/file.ProjectNameMixin`

- .travis.yml
- scripts/setup_envtest_bins.sh
- test.sh
**decription**
- small fix regards issue faced running the script in the Linux
- add a test  to check its execution in both platforms
Related to the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/1608
> fix: script call for linux

- pkg/plugin/v2/init.go
- pkg/plugin/v2/scaffolds/internal/templates/kustomize.go
- pkg/plugin/v3/init.go
- testdata/project-v2-addon/config/default/kustomization.yaml
- testdata/project-v2-multigroup/config/default/kustomization.yaml
- testdata/project-v2/config/default/kustomization.yaml
Follow up from #1609 for plugin v2. This is not a change to the plugin itself, just to how it handles project version 3-alpha's `projectName` field.
/cc @pwittrock @camilamacedo86 @joelanford
> pkg/plugin/v2: use config project name if project version is v3+

- docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
Using GetFinalizers and SetFinalizer methods as they seem more proper.
> using built in finalizer function and fix some syntax

- internal/config/config_test.go
- pkg/model/config/config.go
- pkg/model/config/config_test.go
The `plugins` field was introduced in the `3-alpha` project config version, and should not be able to be used with any project version less than that.
/cc @joelanford @camilamacedo86 @DirectXMan12 
/kind bug
> pkg/model/config: only project versions >= v3 can use plugins config options

- docs/book/src/SUMMARY.md
- docs/book/src/cronjob-tutorial/writing-tests.md
- docs/book/src/reference/envtest.md
This PR fixes #1621, which was caused by an old sidebar link that should have been deleted as part of moving the integration test example under the CronJob example section.
> Fix old link to envtest docs that should have been removed

- docs/book/src/SUMMARY.md
- docs/book/src/reference/makefile-helpers.md
- docs/book/src/reference/reference.md
- doc: add makefile helpers
**Motivation**
- https://github.com/operator-framework/operator-sdk/issues/3630
- and CRD's versions
> doc: add makefile helpers

- pkg/plugin/v2/init.go
- pkg/plugin/v3/init.go
Fixed path to the generated `main.go` file in `init` command description. I'm not sure about `v3`, because as I can see it will be possible to define the project's layout, so I can revert it.
> Fix path to generated main.go 

- docs/book/src/cronjob-tutorial/testdata/emptymain.go
* Added a "full stop" after "RoleBinding respectively" and before "For further information" to separate both paragraphs since even though they are perfectly written inside "emptymain.go" file but not appearing as desired in the Kubebuilder book (i.e. documentation) 
* For better readability and understanding
* Change done inside kubebuilder/docs/book/src/cronjob-tutorial/testdata/emptymain.go
> docs: added a full stop for better readbility

- docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
- Where: CronJob Tutorial,  webhook implementation
- What: adjusted page reference; added fullstop
Better readability
---
As this is a minor change, there is no associated issue (as far as I could see).
> doc: update reference with name of page

- DESIGN.md
- Where: `design.md`
- What: corrected minor grammar mistakes
Better readability
---
As this is a minor change, there is no associated issue (as far as I could see).
> doc: correct minor grammar mistakes

- .travis.yml
We do not need any more call the lint on Travis since it has been called via webhooks now.
> :seedling: removing lint check from travis

- CONTRIBUTING.md
We need to be started to adopt here the same controller-runtime standard.  Otherwise will be very hard to know what changed in the releases.  
**Motivation**
https://github.com/kubernetes-sigs/kubebuilder/issues/712
> :book: add PR Process in Contribution.MD guide

- pkg/plugin/v3/scaffolds/internal/templates/config/manager/config.go
- pkg/plugin/v3/scaffolds/internal/templates/dockerfile.go
- testdata/project-v3-addon/Dockerfile
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-multigroup/Dockerfile
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3/Dockerfile
- testdata/project-v3/config/manager/manager.yaml
PR #983 changes the manager's user to nonroot but it doesn't work out of the box. 
This change modifies the default behaviour of manager pod to use non-root uid for both kube-rbac-proxy container and the manager.
There are two issues when deploying the manager in non-root cluster if we try to use the config/default as-is  
1. kube-rbac-proxy uses root by default instead of a nonroot image - https://github.com/brancz/kube-rbac-proxy/blob/master/Dockerfile#L1 which causes pod to request for root and fail. 
2. Kubernetes cannot verify the `nonroot` user in manager because it is a string (https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/v2/scaffolds/internal/templates/dockerfile.go#L65) resulting in `container has runAsNonRoot and image has non-numeric user (nonroot), …
> :sparkles: specify nonroot uid for manager (v3+ only)

- pkg/plugin/v2/scaffolds/internal/templates/controller/controller_suitetest.go
- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
- testdata/project-v2-addon/controllers/suite_test.go
- testdata/project-v2-multigroup/controllers/crew/suite_test.go
- testdata/project-v2-multigroup/controllers/foo.policy/suite_test.go
- testdata/project-v2-multigroup/controllers/sea-creatures/suite_test.go
- testdata/project-v2-multigroup/controllers/ship/suite_test.go
- testdata/project-v2/controllers/suite_test.go
- testdata/project-v3-addon/controllers/suite_test.go
- testdata/project-v3-multigroup/controllers/crew/suite_test.go
- testdata/project-v3-multigroup/controllers/foo.policy/suite_test.go
- testdata/project-v3-multigroup/controllers/sea-creatures/suite_test.go
- testdata/project-v3-multigroup/controllers/ship/suite_test.go
- testdata/project-v3/controllers/suite_test.go
This pull request fixes a bug where the scaffold generates the incorrect filepath to the CRDs when using multigroup. The issue was raised here: Closes #1665
> :bug: Fix CRD Path for Multigroup

- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller_test.go
- docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
This PR closes #1680. The cause of the bug was usage of a namespace that did not exist yet; in the test, we now use the `default` namespace that is guaranteed to exist without extra boilerplate logic. We also use `printer.NewlineReporter{}` consistent with this change in other kubebuilder code.
> Fix 1680: Usage of nonexistent namespace in cronjob example tests

- pkg/plugin/v2/scaffolds/internal/templates/controller/controller_suitetest.go
- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
- testdata/project-v2-addon/controllers/suite_test.go
- testdata/project-v2/controllers/suite_test.go
- testdata/project-v3-addon/controllers/suite_test.go
- testdata/project-v3/controllers/suite_test.go
Follow up of https://github.com/kubernetes-sigs/kubebuilder/pull/1673
If is multigroup the path needs more one ../ otherwise not.
> :bug: fix: the CRD paths is only ../.. when is multigroup

- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller.go
- testdata/project-v3-multigroup/config/rbac/role.yaml
- testdata/project-v3-multigroup/controllers/crew/captain_controller.go
- testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
- testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
- testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
- testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
- testdata/project-v3/config/rbac/role.yaml
- testdata/project-v3/controllers/admiral_controller.go
- testdata/project-v3/controllers/captain_controller.go
- testdata/project-v3/controllers/firstmate_controller.go
**Description of the change**
Added a <resource>/finalizer kubebuilder marker as a default marker for the controller. This is to allow the update;patch;get operation on finalizer of the resource if the [ownerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) enabled on the cluster.
**Motivation of the change**
The kubebuilder operator doesn't work seamlessly on the vanilla kubernetes like openshift unless the finalizers permission marker is added on the Reconcile function. 
Fixes #1654
> :sparkles: Added the changes for include finalizer as a default controller markers

- go.mod
- go.sum
This module is used for pluralization of kinds here in
kubebuilder. There's a fix in v0.2.2 for the pluralization of a kind
name in an operator that I'm working with, where it's currently
getting the incorrect pluralization.
> Update flect from v0.2.1 to v0.2.2

- docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
- docs/book/src/multiversion-tutorial/testdata/project/controllers/suite_test.go
- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
- testdata/project-v3-addon/controllers/suite_test.go
- testdata/project-v3-multigroup/controllers/crew/suite_test.go
- testdata/project-v3-multigroup/controllers/foo.policy/suite_test.go
- testdata/project-v3-multigroup/controllers/sea-creatures/suite_test.go
- testdata/project-v3-multigroup/controllers/ship/suite_test.go
- testdata/project-v3/controllers/suite_test.go
* **Deprecated**: `func LoggerTo(destWriter io.Writer, development bool) logr.Logger`
* Will use the new function instead: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/log/zap/zap.go#L42
> :sparkles: replace deprecated function LoggerTo() from zap package (only v3+)

- .github/ISSUE_TEMPLATE/support-question.md
The label triage/support has been reclassified as kind/support. The
kind/* family of labels makes more logical sense, as they describe the
"kind" of thing an issue or PR is.
For more information, see the announcement email:
https://groups.google.com/g/kubernetes-dev/c/YcaJpsjjLKw/m/i15cLLx5CAAJ
> 🌱 Update triage/support label references to kind/support

- pkg/plugin/v2/scaffolds/init.go
- pkg/plugin/v3/scaffolds/init.go
- pkg/plugin/v3/scaffolds/internal/templates/makefile.go
- testdata/project-v2-addon/go.mod
- testdata/project-v2-multigroup/go.mod
- testdata/project-v2/go.mod
- testdata/project-v3-addon/Makefile
- testdata/project-v3-addon/go.mod
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3-multigroup/go.mod
- testdata/project-v3/Makefile
- testdata/project-v3/go.mod
- Upgrade controller-runtime from v0.6.2 to v0.6.3
- Upgrade the makefile target test to use the v0.6.3 tag instead master to get the script since now it is released in the tag.
> :sparkles: upgrade controller-runtime from v0.6.2 to v0.6.3

- pkg/plugin/v2/webhook.go
Description
Follow up/fix of the PR:  https://github.com/kubernetes-sigs/kubebuilder/pull/1679/files#diff-5dd6baa6201e0ce7342b1eafbbb472e0R87-R89
Webhooks scaffolded with v2+ should use the V2 resource validation
> :seedling: the v2 webooks should use the v2 resource validation (:ghost:)

- pkg/plugin/v2/webhook.go
- pkg/plugin/v3/webhook.go
Add check to ensure that the resource exists to allow create webhooks and avoid issues such as : 
```
apis/ship/v1/captain_webhook.go:29:10: undefined: Captain
apis/ship/v1/captain_webhook.go:39:28: undefined: Captain
apis/ship/v1/captain_webhook.go:42:10: undefined: Captain
apis/ship/v1/captain_webhook.go:51:28: undefined: Captain
apis/ship/v1/captain_webhook.go:54:10: undefined: Captain
apis/ship/v1/captain_webhook.go:62:10: undefined: Captain
apis/ship/v1/captain_webhook.go:70:10: undefined: Captain
```
**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1701
> :bug: check if resource exist to allow to create webhooks

- .travis.yml
- CONTRIBUTING.md
- docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
- docs/book/src/cronjob-tutorial/testdata/project/go.mod
- docs/book/src/multiversion-tutorial/testdata/project/Dockerfile
- docs/book/src/multiversion-tutorial/testdata/project/go.mod
- docs/book/src/quick-start.md
- docs/book/utils/go.mod
- go.mod
- pkg/plugin/internal/util/go_version.go
- pkg/plugin/v3/scaffolds/internal/templates/dockerfile.go
- pkg/plugin/v3/scaffolds/internal/templates/gomod.go
- testdata/project-v3-addon/Dockerfile
- testdata/project-v3-addon/go.mod
- testdata/project-v3-multigroup/Dockerfile
- testdata/project-v3-multigroup/go.mod
- testdata/project-v3/Dockerfile
- testdata/project-v3/go.mod
- Update go version from 1.13 to 1.15 
**Note**
Here's the link to update the infra to run the CI jobs as well: kubernetes/test-infra#19527
>  :warning: Update kubebuilder cli and plugin v3+ to use go version 1.15

- pkg/plugin/v3/api.go
Description of the Change:
Added validation to check if main.go is present in the root directory or not.
Added the change for v2 and v3 as this is a bug fix.
Motivation of the change:
If user moves the main.go file and then tries to create any resources like webhook, the operation is done half way, the webhook gets created but kb errors out when trying to write to main file. This should be early detected and the operation should not be allowed at all.
Fixes: #1719
> :bug: Add validation for the main.go file present in root directory

- docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
- pkg/plugin/v3/scaffolds/internal/templates/config/crd/enablewebhook_patch.go
- testdata/project-v3-addon/config/crd/patches/webhook_in_admirals.yaml
- testdata/project-v3-addon/config/crd/patches/webhook_in_captains.yaml
- testdata/project-v3-addon/config/crd/patches/webhook_in_firstmates.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_captains.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_cruisers.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_destroyers.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_frigates.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_healthcheckpolicies.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_krakens.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_lakers.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_leviathans.yaml
- testdata/project-v3/config/crd/patches/webhook_in_admirals.yaml
- testdata/project-v3/config/crd/patches/webhook_in_captains.yaml
- testdata/project-v3/config/crd/patches/webhook_in_firstmates.yaml
Instead of having a dummy value in `caBundle`, (`caBundle: Cg==`), instead just omit that field entirely as it is not required.
Doing this means that repeated `kubectl apply` operators on a CRD work better, in accordance with [the documented behavior of apply and how it considers last-applied-configuration](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merging-changes-to-map-fields), since they do not change the `resourceVersion` of the CRD.
This fixes #1684.
> 🐛 Remove unneeded caBundle value from webhook patches (V3 only)

- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller.go
- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
- testdata/project-v3-multigroup/controllers/crew/captain_controller.go
- testdata/project-v3-multigroup/controllers/crew/suite_test.go
- testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
- testdata/project-v3-multigroup/controllers/foo.policy/suite_test.go
- testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/suite_test.go
- testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
- testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
- testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
- testdata/project-v3-multigroup/controllers/ship/suite_test.go
Use GroupPackageName (the API Group cleaned to be used as
the package name) as the package name when generating
controllers and controller suite test files with
non-empty API groups in MultiGroup projects.
When generating controller with an empty group name in a
MultiGroup project, or when generating a controller in a non
MultiGroup project keep the current behavior, which is
using the `controllers` package name for both the
controllers and controllers suite test files.
This applies only to Go v3 plugin as I understand this is a breaking change and breaking changes cannot be applied in v2. Can breaking changes be applied to v3 plugin code without the need of creating a new Go v4 plugin version? Is v3 still not considered "released"? By reading the versioning doc …
> ⚠ Generate controllers with API Group name as package names in multi-group projects (only Go plugin v3)

- pkg/plugin/v2/scaffolds/internal/templates/metricsauth/clientclusterrole.go
- pkg/plugin/v3/scaffolds/internal/templates/config/rbac/client_cluster_role.go
- testdata/project-v2-addon/config/rbac/auth_proxy_client_clusterrole.yaml
- testdata/project-v2-multigroup/config/rbac/auth_proxy_client_clusterrole.yaml
- testdata/project-v2/config/rbac/auth_proxy_client_clusterrole.yaml
- testdata/project-v3-addon/config/rbac/auth_proxy_client_clusterrole.yaml
- testdata/project-v3-multigroup/config/rbac/auth_proxy_client_clusterrole.yaml
- testdata/project-v3/config/rbac/auth_proxy_client_clusterrole.yaml
This PR updates the `metrics-reader` ClusterRole scaffolded by the v3 Go plugin to use apiVersion `rbac.authorization.k8s.io/v1` instead of the deprecated (since k8s 1.17) `rbac.authorization.k8s.io/v1beta1`.
All other template scaffolds are using `rbac.authorization.k8s.io/v1`. It seems that it was an oversight that caused this file to continue using `rbac.authorization.k8s.io/v1beta1`.
> 🐛 use rbac.authorization.k8s.io/v1 for the auth proxy client

- pkg/plugin/v3/scaffolds/internal/templates/main.go
- testdata/project-v3-addon/main.go
- testdata/project-v3-multigroup/main.go
- testdata/project-v3/main.go
This PR makes the `kubebuilder init` initialize the default logging in a way that:
- by Default the log level is `debug`
- any flag passed to the operator will change that log level accordingly (see https://sdk.operatorframework.io/docs/building-operators/golang/references/logging/)
to reduce friction and allow an operator developer not have to meddle with the main.go if not required, this will be related to trying inside the Reconcile function to call `r.Log.V(2).Info("message")` and trying to enable it on demand
- #885 related to changing logging levels
> ✨  feat(logging): make logging work by default (only v3+)

- pkg/plugin/v3/init.go
Do not allow scaffold/init a project in a directory when it has other files already.
The only files that shows make sense be allowed are .gitignore and go.mod
**Motivation**
https://github.com/operator-framework/operator-sdk/issues/4067
> :sparkles: not allow to init the project in a directory that is not cleaned (v3+ only)

- docs/book/src/quick-start.md
Add a note to make clear the versions which are officially supported for the prerequisites and dependencies since are the versions used to test and whcih are scaffolded by default. 
**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1655
**Preview**
https://deploy-preview-1735--kubebuilder.netlify.app/quick-start.html
> :book: add note about officially versions supported

- pkg/plugin/v3/scaffolds/internal/templates/main.go
- testdata/project-v3-addon/main.go
- testdata/project-v3-multigroup/main.go
- testdata/project-v3/main.go
Description of Change:
Added import path for all the kubernetes auth plugins in main.go
Motivation of Change:
Currently, main.go file imports auth plugins for the gcp only, instead of import the auth plugins for all gcp, azure and OIDC.
Fixes: #1730
> :sparkles: Add all kubernetes auth plugins for Azure, OIDC and gcp (only v3+)

- pkg/plugin/v3/scaffolds/api.go
- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller.go
- testdata/project-v3-multigroup/controllers/crew/captain_controller.go
- testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
- testdata/project-v3-multigroup/controllers/lakers_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
- testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
- testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
- testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
- testdata/project-v3/controllers/admiral_controller.go
- testdata/project-v3/controllers/captain_controller.go
- testdata/project-v3/controllers/firstmate_controller.go
Add comments for exported methods in generated controllers in order to provide help for users. 
**Motivation**
Closes #1606.
> :sparkles: add comments for the exported methods in generated controllers (only v3+)

- pkg/plugin/v3/scaffolds/internal/templates/config/api/webhook_suitetest.go
- pkg/plugin/v3/scaffolds/webhook.go
- testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/go.mod
- testdata/project-v3/api/v1/webhook_suite_test.go
- testdata/project-v3/go.mod
Description
Added the webhook suite generation while creating the webhooks using the envtest. 
Motivation:
The webhook envtest suite setup requires setting up quite a things which would be useful for users to be programmatically generated as the envtest has supported webhook testing.
Fixes #1707
> :sparkles: Add scaffolding for the webhook test suite (go/v3-alpha)

- pkg/internal/validation/dns.go
- pkg/internal/validation/project.go
- pkg/model/resource/options.go
- pkg/model/resource/options_test.go
- pkg/plugin/internal/util/go_version.go
- pkg/plugin/plugin.go
- Used non-capturing groups when the info is not relevant
- Simplified some expressions
While non-capturing groups should be a bit more performant that capturing groups, the improvement will be negligible. The motivations is mainly improving the clarity and readability of the regex expressions by simplifying some patters and not having unused capture groups.
/kind cleanup
> 👻 Enhance regex patterns

- pkg/plugin/v2/scaffolds/internal/templates/boilerplate.go
- pkg/plugin/v3/scaffolds/internal/templates/config/hack/boilerplate.go
Ensure that the copyright will be set when the owner is empty with the year only.
**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1620
**Local Test**
```
$ cat main.go 
/*
Copyright 2020.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
```
> :bug: fix copyright info when has not a owner set

- pkg/plugin/v3/scaffolds/internal/templates/config/api/webhook_suitetest.go
- testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
- testdata/project-v3/api/v1/webhook_suite_test.go
Add copyright and license to scaffolded webhook suite test file that was previously lacking it.
The file had the `BoilerplateMixin` needed to add the copyright and license but was not being scaffolded with it. As it is just a comment, I think we can consider this not-breaking even if previously scaffolded test suites may not be updated.
> ✨ Add copyright and license to scaffolded webhook suite test file

- pkg/plugin/v2/scaffolds/internal/templates/controller/controller_suitetest.go
- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
Remove `RepositoryMixin` from controller suite tests.
Controller suite test do not use the repository field for anything, so there is no need to inject it into the template.
P.S.: I have checked for every template and these two are the only ones with an unnecessary mixin or field.
> 🌱 Remove unused mixin from controller suite test template

- pkg/plugin/v2/edit.go
- pkg/plugin/v3/edit.go
Removes a field that was not being used inside the `edit` command.
Excess code removal. In the rest of the commands (`init`, `create`, ...) this field is used for error string formating but in `edit` it is not needed.
/kind cleanup
> 🌱 Remove unused commnadName field

- pkg/plugin/v2/scaffolds/internal/templates/boilerplate.go
- pkg/plugin/v3/scaffolds/internal/templates/config/hack/boilerplate.go
Boilerplate code has one different template bodys for each accepted license. Modify it so that a single template body is used and the license is extracted from a map of licenses.
This PR has two main goals:
1. Reduce the duplicated code by not having multiple copyright sections of the boilerplate.
1. Stop templating parts of the file during the `SetTemplateDefault` call, as later modifications to the template struct will not be reflected in the scaffolded file. For example, lets supose we want to modify the license  to "none" after the defaults have been set. As the template body was already selected including the License already in it, our change to the license would not yield any error but would not be applied.
> 🌱 Unify bolierplate with a single template body

- generate_testdata.sh
- pkg/plugin/v2/scaffolds/api.go
- pkg/plugin/v2/scaffolds/internal/templates/controller/controller.go
- pkg/plugin/v2/scaffolds/internal/templates/controller/controller_suitetest.go
- pkg/plugin/v2/scaffolds/internal/templates/main.go
- pkg/plugin/v3/scaffolds/api.go
- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller.go
- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
- pkg/plugin/v3/scaffolds/internal/templates/main.go
- testdata/project-v2-multigroup/config/rbac/role.yaml
- testdata/project-v2-multigroup/controllers/apps/pod_controller.go
- testdata/project-v2-multigroup/controllers/apps/suite_test.go
- testdata/project-v2-multigroup/main.go
- testdata/project-v2/config/rbac/role.yaml
- testdata/project-v2/controllers/laker_controller.go
- testdata/project-v2/main.go
- testdata/project-v3-multigroup/config/rbac/role.yaml
- testdata/project-v3-multigroup/controllers/apps/pod_controller.go
- testdata/project-v3-multigroup/controllers/apps/suite_test.go
- testdata/project-v3-multigroup/main.go
- testdata/project-v3/config/rbac/role.yaml
- testdata/project-v3/controllers/laker_controller.go
- testdata/project-v3/main.go
Fix the `kb create api` command when the create resource is set to false.
Added tests in the generate_testdata.sh so that such issue doesn't occur again.
*Motivation**
Fixes: #1767
> :bug: Fix the kubebuilder api creation when resource creation is set to false

- internal/config/config.go
- pkg/cli/cli.go
- pkg/cli/init.go
- pkg/model/config/config.go
- pkg/model/config/config_test.go
- remove v1 version 
- shows plugins --flag only if Project Version is != V2
**Motivation**
https://github.com/kubernetes-sigs/kubebuilder/pull/1636
Co-author @estroz
> :sparkles: remove v1 version and only shows --plugins flag when the project version is != V2

- docs/book/src/SUMMARY.md
- docs/book/src/reference/cli-plugins.md
- docs/book/src/reference/reference.md
This PR adds a plugin documentation on general development and versioning.
See #1539 and #1769 for details.
> :book: add CLI plugin doc

- pkg/plugin/v3/scaffolds/internal/templates/config/api/webhook_suitetest.go
- pkg/plugin/v3/scaffolds/internal/templates/config/controller/controller_suitetest.go
- testdata/project-v3-addon/controllers/suite_test.go
- testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/controllers/crew/suite_test.go
- testdata/project-v3-multigroup/controllers/foo.policy/suite_test.go
- testdata/project-v3-multigroup/controllers/sea-creatures/suite_test.go
- testdata/project-v3-multigroup/controllers/ship/suite_test.go
- testdata/project-v3-multigroup/controllers/suite_test.go
- testdata/project-v3/api/v1/webhook_suite_test.go
- testdata/project-v3/controllers/suite_test.go
**Description of the change**
Improved the scaffolding for the webhook and controller suites. 
Removed the Done as we are not running the asynchronous test suites.
**Motivation of the change**
Fixes: #1733
> :sparkles: Cleanup in the controller and webhook suites scaffolding (go/v3-alpha)

- testdata/project-v3-multigroup/controllers/apps/suite_test.go
The testdata generated is checked only in the Travis and not in prow. In this way, a pr was merged without sync/updated the testdata. Doing it now.
> :seedling: sync testdata

- pkg/cli/api.go
- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/cmd_helpers.go
- pkg/cli/edit.go
- pkg/cli/init.go
- pkg/cli/plugins.go
- pkg/cli/plugins_test.go
- pkg/cli/webhook.go
- pkg/plugin/helpers.go
- pkg/plugin/interfaces.go
- pkg/plugin/v2/api.go
- pkg/plugin/v2/edit.go
- pkg/plugin/v2/init.go
- pkg/plugin/v2/plugin.go
- pkg/plugin/v2/webhook.go
- pkg/plugin/v3/api.go
- pkg/plugin/v3/edit.go
- pkg/plugin/v3/init.go
- pkg/plugin/v3/plugin.go
- pkg/plugin/v3/webhook.go
Rename plugin getters return objects to `Subcommand`.
Currently, both the structs with the getters and those returned by them are called "plugin" (`Plugin -> Plugin`), leading to missunderstandings. In order to clarify which is which, one of them should be renamed. There are two possibilities:
1. Rename the struct with the getters to something like `PluginFactory`: `PluginFactory -> Plugin`
2. Rename the returned type to something like `Subcommand`: `Plugin -> Subcommand`
The word "plugin" is already extensively used in the code (comments, variable names, ...) to refer to the left term, so I figured that it would be easier to go for the second option.
When deciding which name to use, I saw how the base class for the right term structs was already `GenericSubcommand` and it basically …
> ⚠️ [Rename] Disambiguate plugin by calling subcommand what the plugin getters returns instead of plugin

- pkg/cli/cli.go
rename dummy
**Motivation**
Closes; https://github.com/kubernetes-sigs/kubebuilder/issues/1581
> :seedling: wg/naming : rename dummy

- pkg/model/config/config.go
Remove the comment over v1, since no longer exists v1 code in the project
**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1781
> :seedling: cleanup: remove v1 comment

- test_e2e_local.sh
Description:
Update the local tests e2e scripts to use the kubernetes version v1.18.0
Motivation:
We are adding the kubebuilder e2e tests pre submit jobs on the kubernetes v1.18.0 in [#19690](https://github.com/kubernetes/test-infra/pull/19690)
> :sparkles: Upgrade the version of kubernetes to v1.18.0 for local e2e tests

- pkg/plugin/v3/scaffolds/init.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
- upgrade controller-tool dep from 0.3.0 to 0.4.0 (go/v3-alpha only)
NOTE: The controller-tool no generates  CRD version to v1 by default (#468) and add admissionregisteration/v1 support for webhook (#469) which means that are breaking changes for v2+. Then, because of this, the fix can only be addressed to v3+ plugin. 
**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1634
> :warning: upgrade controller-tool dep from 0.3.0 to 0.4.0 (go/v3-alpha only)

- pkg/cli/alpha.go
- pkg/cli/create.go
Added suggestions for some commands so that when the CLI user writes a similar term it gets useful help information telling him the correct subcommand name
- `create`: `new`
- `alpha`: `experimental`
> ✨Suggestions for create and alpha commands

- pkg/plugin/v2/scaffolds/edit.go
- pkg/plugin/v3/scaffolds/edit.go
**Description of the change**
Add validation of kb edit command if the scaffolding is already on same side either `multigroup: true` or `multigroup: false`. kb edit command fails when it tries to change the Dockerfile that it doesn't find the apis or api directory respectively.
**Motivation of the change**
Fixes: #1747
> :bug: kubebuilder edit ignore the errors if the project layout is already on same type

- Makefile
- test.sh
With the introduction of the plugin design, the directory plugins were added to the project. However, the target and scripts which runs the go unit tests and the coveralls were not updated to cover the new directories.
> :seedling: add plugins directory to be checked in the tests and coveralls

- pkg/plugin/v3/scaffolds/internal/templates/config/manager/config.go
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3/config/manager/manager.yaml
Add the liveness and readiness probe for the manager deployment.
**Motivation**
Fixes: #1761
> :sparkles: Add the liveness and readiness probe in the manager deployment

- pkg/plugin/v3/scaffolds/internal/templates/config/manager/config.go
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3/config/manager/manager.yaml
Reverts kubernetes-sigs/kubebuilder#1795, which breaks go/v3-alpha.
It appears that the `/healthz` and/or `/readyz` handlers are not set up as #1795 assumes they have been. For now #1795 should be reverted so #1756 can add tests, then these endpoints can be re-added.
> :seedling: Revert ":sparkles: Add the liveness and readiness probe in the manager deployment"

- pkg/plugin/v3/scaffolds/init.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
Reverts kubernetes-sigs/kubebuilder#1787, which breaks go/v3-alpha:
>This PR broke go/v3-alpha silently because testdata generation can only use one tool version per script invocation, i.e. all testdata is generated with controller-gen v0.3.0 right now. This blocks #1756, so we'll have to go ahead and merge its parent PR #1644 to fix go/v3-alpha.
> :seedling: Revert ":warning: upgrade controller-tool dep from 0.3.0 to 0.4.0 (go/v3-alpha only)"

- pkg/plugin/v3/scaffolds/internal/templates/config/rbac/leader_election_role.go
- testdata/project-v3-addon/config/rbac/leader_election_role.yaml
- testdata/project-v3-multigroup/config/rbac/leader_election_role.yaml
- testdata/project-v3/config/rbac/leader_election_role.yaml
This PR adds `leases.coordination.k8s.io` to the leader-election-role Role under the same rule as `configmaps`. These permissions are required by default by controller-runtime's leader election, which uses "configmapsleases" as the default election type.
- go/v3-alpha: add leases.coordination.k8s.io to leader election RBAC
> :bug: (go/v3-alpha) add leases.coordination.k8s.io to leader-election-role

- build/.goreleaser.yml
- cmd/version.go
- common.sh
- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/version.go
Provide a `WithVersion` CLI `Option` that allows to provide a version string instead of having to create a `version` command and provide it as an extra command. When a version is provided this way, the CLI will create a version command automatically that prints this version string.
- ✨ New argument type for `cli.New`: `WithVersion`. Creating a command and providing it with `WithExtraCommands` should still work with the previous behavior, so this is not a breaking change, but frameworks using `kubebuilder` should migrate to the new approach.
- ⚠️ Removed `Version` and `NewCmd` from package `cmd/version`. This package is not part of the library itself, but as it is exported, it may be used by third parties.
> ⚠Provide version information as a CLI option

- Makefile
- generate_testdata.sh
- pkg/plugin/v3/scaffolds/internal/templates/makefile.go
- test.sh
- testdata/project-v3-addon/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
This PR modifies the Makefile so that it installs kustomize and controller-gen to `<project root>/bin` if they do not exist. Targets will always use these binaries instead of installing global binaries, which pollutes userspace. Users can still use their preferred binary by running
```sh
mkdir -p bin
ln -sf $(which $binary) bin/$binary
```
This PR also cleans up the top-level Makefile and scripts.
> :warning: (go/v3-alpha) Makefile: install kustomize and controller-gen locally

- pkg/model/file/funcmap.go
- pkg/plugin/v2/scaffolds/internal/templates/main.go
- pkg/plugin/v3/scaffolds/internal/templates/main.go
This change was sparked from the conversation on #722 see https://github.com/kubernetes-sigs/kubebuilder/pull/1790/files#r518340728 for the suggestion.
This moves a reused func to the global funcmap to reduced the need to copy it a third time for 
Signed-off-by: Chris Hein <me@chrishein.com>
> 🌱  refactoring hash function to global template funcs

- Makefile
Several variables are set when releasing a kubebuilder version in order to output the correct information when calling `kubebuilder version`. But when building from the source with `make build`, this variables were not being set, and thus the `kubebuilder version` output was providing no information:
```
Version: version.Version{KubeBuilderVersion:"unknown", KubernetesVendor:"unknown", GitCommit:"$Format:%H$", BuildDate:"1970-01-01T00:00:00Z", GoOs:"unknown", GoArch:"unknown"}
```
This PR updates those variables to reflect the current working environment.
Fixes #1401
P.S.: it also cleans a bit the `Makefile`
> 🌱 Set build variables during `make build`

- Makefile
The PR fixes a small typo in `git describe` invocation resulting in `kubeBuilderVersion` variable not being properly set
during the final binary linking phase.
> :seedling: Makefile: fix typo in 'git describe' invocation

- pkg/plugin/v3/scaffolds/internal/templates/makefile.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
Because folks may have `docker` aliased to `podman`, and Podman prefers options before positional arguments (containers/podman#2811):
```console
$ podman build --help | grep CONTEXT-DIRECTORY
podman build [command options] CONTEXT-DIRECTORY | URL
```
Generated with:
```console
$ sed -i 's/ . -t \([^ ]*\)/build -t \1 ./' $(git grep -l 'docker.*build.* \. ')
```
> :sparkles: (go/v3-alpha) *: Replace 'docker build . -t ${IMG}' with '-t ${IMG} .'

- test_e2e.sh
- test_e2e_local.sh
e2e tests seem to be timing out often across several PRs. This PR bumps the timeout from 15 to 20 minutes.
/kind flake
> :seedling: test_e2e.sh,test_e2e_local.sh: bump timeout to 20m

- pkg/plugins/golang/v3/scaffolds/init.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
This PR bumps `kustomize` version installed by the go/v3-alpha plugin to v3.8.7.
Closes #1657
/cc @camilamacedo86
> :sparkles: go/v3-alpha: bump KustomizeVersion to v3.8.7

- Makefile
- build/.goreleaser.yml
This PR fixes `-ldflags -X ...` settings in `build` and `install` make targets and in goreleaser's config, which should point to the `main` package.
/cc @Adirio
> :seedling: Makefile,build/.goreleaser.yml: fix ldflag variable setting

- pkg/plugins/golang/v3/scaffolds/internal/templates/config/certmanager/certificate.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/config/kdefault/kustomization.go
- test/e2e/utils/kubectl.go
- test/e2e/utils/test_context.go
- test/e2e/v2/plugin_cluster_test.go
- test/e2e/v3/generate_test.go
- test/e2e/v3/plugin_cluster_test.go
- testdata/project-v3-addon/config/certmanager/certificate.yaml
- testdata/project-v3-addon/config/default/kustomization.yaml
- testdata/project-v3-multigroup/config/certmanager/certificate.yaml
- testdata/project-v3-multigroup/config/default/kustomization.yaml
- testdata/project-v3/config/certmanager/certificate.yaml
- testdata/project-v3/config/default/kustomization.yaml
This PR bumps cert-manager CR apiVersion to v1 from v1beta2 for go/v3-alpha. TestContext has been updated to be cluster version-aware such that the correct cert-manager bundle URL is applied.
- pkg/plugin/v3/scaffolds/internal/templates/config: cert-manager CRs have apiVersion v1
- test/e2e/utils: KubectlVersion -> KubernetesVersion, which now gets created in NewTestContext. cert-manager install funcs use this version to get the correct bundle for a particular cluster version
- test/e2e/{v2,v3}: update {Install,Uninstall}CertManager() to include new 'hasv1beta2CRs' boolean arg, which depends on plugin being tested
Closes #1666 
Closes #1667
> :warning: (go/v3-alpha) bump cert-manager CRs to v1

- pkg/plugins/golang/v3/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/config/manager/config.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
- testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-addon/main.go
- testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3-multigroup/main.go
- testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3/config/manager/manager.yaml
- testdata/project-v3/main.go
This aligns the current `v3` flags with other Kubernetes core components for leader election and for metrics address.
Fixes #1839
>  ⚠️ (go/v3-alpha) Align flag names with Kubernetes Components

- pkg/plugins/golang/v3/webhook.go
Add make run option for webhooks
**Motivation**
- Keep the consistence across the project
- Allows users scaffold webhooks without run make targets
> :sparkles: add make run option for webhooks (go/v3-alpha)

- CONTRIBUTING.md
The CONTRIBUTING.md had reference to `travis` which is broken. The changes will reference GitHub actions instead of Travis.
> :book: Update the reference to github actions in CONTRIBUTING

- docs/book/src/reference/kind-config.yaml
- docs/book/src/reference/kind.md
This file used to be in the hack directory, this moves it to the reference directory.
Fixes #1871
Signed-off-by: Chris Hein <me@chrishein.com>
> :book: adding kind-config.yaml back for documentation

- pkg/plugins/golang/v3/scaffolds/init.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-addon/go.mod
- testdata/project-v3-config/Makefile
- testdata/project-v3-config/controllers/admiral_controller.go
- testdata/project-v3-config/controllers/captain_controller.go
- testdata/project-v3-config/controllers/firstmate_controller.go
- testdata/project-v3-config/controllers/laker_controller.go
- testdata/project-v3-config/go.mod
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3-multigroup/controllers/apps/pod_controller.go
- testdata/project-v3-multigroup/controllers/crew/captain_controller.go
- testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
- testdata/project-v3-multigroup/controllers/lakers_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
- testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
- testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
- testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
- testdata/project-v3-multigroup/go.mod
- testdata/project-v3/Makefile
- testdata/project-v3/controllers/admiral_controller.go
- testdata/project-v3/controllers/captain_controller.go
- testdata/project-v3/controllers/firstmate_controller.go
- testdata/project-v3/controllers/laker_controller.go
- testdata/project-v3/go.mod
- upgrade controller-rutime from v0.7.0-alpha.6 to v0.7.0-alpha.8 (go/v3-alpha)
**Motivation**
Keep v3-alpha updated/aligned with  controller-rutime for we achieve the goal of 1.20 k8s api for the next release
> :sparkles: upgrade controller-rutime from v0.7.0-alpha.6 to v0.7.0-alpha.8 (go/v3-alpha)

- docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
* This changes the name of the example finalizer used in the book to be a valid name
* I was using the book as a template and ran into errors by modeling my finalizer off of the provided example. This should hopefully help others avoid the same mistake!
* Addresses issue #1854
> 📖 Change example finalizer name to be valid

- docs/book/src/cronjob-tutorial/new-api.md
- docs/book/src/cronjob-tutorial/webhook-implementation.md
- docs/book/src/reference/generating-crd.md
- docs/book/src/reference/webhook-overview.md
Add CRD and webhook API version information to docs, framed as relevant to older cluster support.
Follow up from #1644 and https://github.com/kubernetes-sigs/kubebuilder/issues/1065#issuecomment-729180067
> :book: docs: add CRD and webhook API version information

- pkg/plugins/golang/v2/scaffolds/init.go
- testdata/project-v2-addon/go.mod
- testdata/project-v2-multigroup/go.mod
- testdata/project-v2/go.mod
- upgrade controller-runtime from v0.6.3 to v0.6.4
**Motivation**
Get bugfixes and solve tech debts
> :sparkles: upgrade controller-runtime from v0.6.3 to v0.6.4 (go/v2 only)

- pkg/plugins/golang/v3/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/config/manager/config.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/config/manager/controller_manager_config.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
- testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-addon/config/manager/controller_manager_config.yaml
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-addon/main.go
- testdata/project-v3-config/config/manager/controller_manager_config.yaml
- testdata/project-v3-config/config/manager/manager.yaml
- testdata/project-v3-config/main.go
- testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-multigroup/config/manager/controller_manager_config.yaml
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3-multigroup/main.go
- testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3/config/manager/controller_manager_config.yaml
- testdata/project-v3/config/manager/manager.yaml
- testdata/project-v3/main.go
Cherry-pick of #1795 
**Motivation**
Re-introduce the change to close the #1761 
Note that it was reverted because the CI was not doing tthe e2e tests with the v3-alpha plugin which is done now.
Fixes: #1761
> :sparkles: (go/v3-alpha) Add the liveness and readiness probe in the manager deployment

- pkg/plugins/golang/v2/webhook.go
- pkg/plugins/golang/v3/webhook.go
Change the help text on create webhook command to match the create api command.
**Motivation**
Users who is trying out kubebuilder layout with the --help command should able to run the commands generated by kubebuilder --help. Hence, the create api command GVK and create command GVK should be same in the help text.
> :sparkles: Change the webhook GVK in help text to match kb create api

- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/init.go
#1828 removed [`--help` handling](https://github.com/kubernetes-sigs/kubebuilder/pull/1828/files#diff-f47a5804e09ec7e41dff0b216fbc32078ca027c60c7d9bb09192fbe2af83064aL56) so that `kubebuilder -h` will only print
```console
$ kubebuilder -h
Usage of base:
--plugins string           plugins to run
--project-version string   project version
pflag: help requested
```
/kind bug
> :seedling: pkg/cli: fix lack of help when --help is set

- pkg/plugins/golang/v3/scaffolds/internal/templates/config/manager/config.go
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-config/config/manager/manager.yaml
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3/config/manager/manager.yaml
Fixed wrong the path of probes in a generated manifest.
I think it's natural to use `readyz` in `readinessprobe`.
#1904
> :bug: Fix the path of probes (go/v3-alpha)

- cmd/main.go
- generate_testdata.sh
- pkg/plugins/golang/v3/plugin.go
- test.sh
- test/e2e/v3/generate_test.go
- testdata/project-v3-addon/PROJECT
- testdata/project-v3-config/PROJECT
- testdata/project-v3-multigroup/PROJECT
- testdata/project-v3/PROJECT
This PR stabilizes plugin go/v3-alpha to go/v3 and makes it the default plugin.
- cmd/main.go: make go/v3 the default plugin
- *.sh: update tests to create projects for the correct plugin version
Closes #1834
> :warning: (go/v3) stabilize and default the plugin

- pkg/model/file/marker.go
:sparkles: add a new extension to markers in order to allow work with .yml
**Motivation**
- SDK Ansible based-operators works with the ext ".yml" as other languages such as python, it will allow us to create markers for these files and types. 
- https://github.com/operator-framework/operator-sdk/issues/4311
> :sparkles: add new extension to markers in order to allow work with .yml

- pkg/model/config/config.go
- pkg/model/config/config_test.go
- pkg/model/resource/options.go
- pkg/model/resource/resource.go
- pkg/plugins/golang/v2/api.go
- pkg/plugins/golang/v2/scaffolds/api.go
- pkg/plugins/golang/v2/webhook.go
- pkg/plugins/golang/v3/api.go
- pkg/plugins/golang/v3/scaffolds/api.go
- pkg/plugins/golang/v3/scaffolds/webhook.go
- pkg/plugins/golang/v3/webhook.go
- testdata/project-v3-addon/PROJECT
- testdata/project-v3-config/PROJECT
- testdata/project-v3-multigroup/PROJECT
- testdata/project-v3/PROJECT
Only does the changes required to store the new attributes crdVersion and webhookVersion in the format/layout define on  https://github.com/kubernetes-sigs/kubebuilder/issues/1772 and  https://github.com/kubernetes-sigs/kubebuilder/issues/1826.
**Motivation**
- https://github.com/kubernetes-sigs/kubebuilder/issues/1772
- https://github.com/kubernetes-sigs/kubebuilder/issues/1826
> :warning: change structure to store crdVersion and webhookversion (go/v3-alpha)

- generate_testdata.sh
- pkg/cli/cli.go
- pkg/cli/edit.go
- pkg/model/config/config.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/config/kdefault/webhook_manager_patch.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/config/webhook/kustomization.go
- pkg/plugins/golang/v3/scaffolds/webhook.go
- pkg/plugins/golang/v3/webhook.go
- testdata/project-v3/api/v1/webhook_suite_test.go
- testdata/project-v3/main.go
Add the --force option to overwrite already generated webhook code.
**Motivation**
Currently, user do not have a way to overwrite already scaffold code other than deleting the scaffold code manually.
> :sparkles: (go/v3) Add the --force option for the webhook

- pkg/model/config/config_test.go
Add the HasWebhook() unit tests to improve the coverage.
**Motivation**
Follow up of the PR #1903 where the HasWebhook() function is introduced.
> :seedling: Add the unit tests in pkg/model/config/config_test.go for HasWebhook 

- generate_testdata.sh
- pkg/plugins/golang/v2/api.go
- pkg/plugins/golang/v2/scaffolds/api.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/api/types.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/config/samples/crd_sample.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/controllers/controller.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/controllers/controller_suitetest.go
- pkg/plugins/golang/v3/api.go
- pkg/plugins/golang/v3/scaffolds/api.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/api/types.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/config/samples/crd_sample.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller_suitetest.go
- testdata/project-v2/main.go
- testdata/project-v3-config/main.go
- testdata/project-v3/main.go
Added changes to overwrite the files generated by kubebuilder create api when --force option is provided.
**Motivation**
--force command is failing on kubebuilder
Fixes: #1845
> :bug: Fix --force option to recreate the files by kubebuilder create api

- docs/book/src/component-config-tutorial/api-changes.md
- docs/book/src/cronjob-tutorial/cronjob-tutorial.md
Now it has no longer v3-alpha plugin and the init by default will use this version. So, we need to have the docs updated accordingly.
> :book: update the docs for v3 as default plugin version for the init

- pkg/plugins/golang/v2/init.go
- pkg/plugins/golang/v3/init.go
dep is no longer used by the project (we use go mod instead); remove
the help test that suggests we will suggest it.
> :sparkles: Remove misleading help that mentioned dep

- pkg/plugins/golang/v3/api.go
- testdata/project-v3-addon/go.mod
This PR upgrades go/v3's kubebuilder-declarative-pattern dependency to the k8s v1.19 equivalent tag.
/area dependency
> :sparkles: (go/v3) upgrade kubebuilder-declarative-pattern to k8s v1.19

- Makefile
- pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-config/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
This PR:
* Recycles the self-documenting help target from the base [Makefile](https://github.com/kubernetes-sigs/kubebuilder/blob/master/Makefile) into the makefile template that's rendered when `kubebuilder init` is invoked.
* Relocates the target descriptions in the template so that they can be leveraged by the help target.
* Corrects some minor typos and long lines in the base Makefile. 
This PR closes: #1867
> ✨ Add help dialog to makefile template

- pkg/plugins/golang/v3/init.go
When I encountered the error, I had to go to the source to understand
the problem.  Made the message more user-focused.
Also skipped printing the allowlist, both to fit into lint line-length
limits and to avoid overwhelming the user.
> :sparkles: Make directory-not-empty error more self-explanatory

- build/build.sh
- build/cloudbuild_kube-rbac-proxy.yaml
This PR adds a cloudbuild config for building a versioned `grc.io/kubebuilder/kube-rbac-proxy`.
- build/cloudbuild_kube-rbac-proxy.yaml: build and push a kube-rbac-proxy (v0.8.0) by retagging manifests
- build/build.sh: pull and retag images
> :seedling: build and push a kube-rbac-proxy (v0.8.0)

- build/cloudbuild_kube-rbac-proxy.yaml
entrypoint needs to explicitly be bash, instead of just being the
script.
> :seedling: Fix rbac proxy cloudbuild entrypoint

- build/build.sh
No seriously.  Terrible.  Horrible.  No good.
(it's not possible to simply append to an empty array using bash<4.4,
because a zero element array does not exist, EVEN IF YOU DECLARE IT,
apparently).
Instead, use a weird idiomatic hack with `+` expansion.  You need to use
this *specific* expansion, apparently -- other similar ones break for
weird reasons:
https://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u.
> :seedling: Bash is terrible

- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/init.go
- pkg/cli/root.go
Improve error reporting by printing the command usage
Fixes: #1913
Fixes: #1914
Fixes: #1915
> ✨ Build the command and use it to report user errors

- docs/book/src/cronjob-tutorial/testdata/project/main.go
- docs/book/src/multiversion-tutorial/testdata/project/main.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
- testdata/project-v3-addon/main.go
- testdata/project-v3-config/main.go
- testdata/project-v3-multigroup/main.go
- testdata/project-v3/main.go
**Describe**
:sparkles: rename probes endpoints (go/v3) 
**Motivation**
Make easier its understanding.
> :sparkles: rename probes endpoints (go/v3)

- build/build.sh
This PR enables the experimental docker CLI in the cloudbuild config via env variable so the `manifests` command can be used.
/cc @DirectXMan12
> :seedling: build/build.sh: enable experimental docker CLI for 'manifests'

- docs/book/src/component-config-tutorial/testdata/project/PROJECT
- docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- pkg/plugins/golang/v3/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
- test/e2e/v3/plugin_cluster_test.go
- test_e2e.sh
- test_e2e_local.sh
- testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-config/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
This PR upgrades kube-rbac-proxy image version from v0.5.0 to v0.8.0, which has a rootless feature and no breaking changes (afaik).
Closes #1785
> :sparkles: *: upgrade kube-rbac-proxy to v0.8.0

- pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller_suitetest.go
- testdata/project-v3-addon/controllers/suite_test.go
- testdata/project-v3-config/api/v1/webhook_suite_test.go
- testdata/project-v3-config/controllers/suite_test.go
- testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/controllers/apps/suite_test.go
- testdata/project-v3-multigroup/controllers/crew/suite_test.go
- testdata/project-v3-multigroup/controllers/foo.policy/suite_test.go
- testdata/project-v3-multigroup/controllers/sea-creatures/suite_test.go
- testdata/project-v3-multigroup/controllers/ship/suite_test.go
- testdata/project-v3-multigroup/controllers/suite_test.go
- testdata/project-v3/api/v1/webhook_suite_test.go
- testdata/project-v3/controllers/suite_test.go
The error message if the path to CRDs is missing is misleading.
envtest.Environment has an option to throw a sensible error here if the
path is wrong and for kubebuilder it would be likely we always want to
upload our CRDs.
> :sparkles: Use ErrorIfCRDPathMissing in EnvTest

- generate_testdata.sh
- pkg/model/resource/resource.go
- pkg/model/resource/resource_test.go
- pkg/plugins/golang/v3/api.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/api/types.go
- pkg/plugins/golang/v3/webhook.go
- testdata/project-v3/api/v1/admiral_types.go
- testdata/project-v3/api/v1/admiral_webhook.go
- testdata/project-v3/api/v1/webhook_suite_test.go
- testdata/project-v3/config/crd/bases/crew.testproject.org_admirales.yaml
- testdata/project-v3/config/crd/kustomization.yaml
- testdata/project-v3/config/crd/patches/cainjection_in_admirales.yaml
- testdata/project-v3/config/crd/patches/webhook_in_admirales.yaml
- testdata/project-v3/config/rbac/admiral_editor_role.yaml
- testdata/project-v3/config/rbac/admiral_viewer_role.yaml
- testdata/project-v3/config/rbac/role.yaml
- testdata/project-v3/config/webhook/manifests.yaml
- testdata/project-v3/controllers/admiral_controller.go
- testdata/project-v3/main.go
Adds the flags and the required marker to the types file.
Fixes: #1805
Closes: #1802
> ⚠ Add --plural flag (go/v3)

- pkg/plugins/golang/options.go
Ensure that the plural provided is valid.
Fixes: #1969
> 🐛 Validate the plugin flag

- pkg/plugins/golang/v3/scaffolds/internal/templates/config/manager/config.go
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-config/config/manager/manager.yaml
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3/config/manager/manager.yaml
This PR changes the manager pod template's security context `runAsUser: 65532`  to `runAsNonRoot: true`. User 65532 is already specified in a project's [Dockerfile](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Dockerfile#L25) which the [security context uses](https://pkg.go.dev/k8s.io/api/core/v1#SecurityContext) when `runAsUser` is unset, making the security context's value redundant (and prone to drift if that value is changed in the Dockerfile) in kubebuilder's case.
> :sparkles: (go/v3) change 'runAsUser: 65532'  to 'runAsNonRoot: true'

- pkg/plugins/golang/v3/init.go
Many users will be running version control; we should ignore .git
directories also therefore.
> :sparkles: Tolerate "dot" directories when checking if dir is empty

- VERSIONING.md
- cmd/main.go
- docs/book/src/component-config-tutorial/testdata/project/PROJECT
- docs/book/src/migration/project/v2_v3.md
- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/config/interface.go
- pkg/config/v2/config_test.go
- pkg/config/v3/config.go
- pkg/config/v3/config_test.go
- pkg/plugins/golang/options_test.go
- pkg/plugins/golang/v2/init.go
- pkg/plugins/golang/v2/plugin.go
- pkg/plugins/golang/v3/plugin.go
- test.sh
- test/e2e/v3/generate_test.go
- testdata/project-v3-addon/PROJECT
- testdata/project-v3-config/PROJECT
- testdata/project-v3-multigroup/PROJECT
- testdata/project-v3/PROJECT
Create the v3 config implementation that includes all missing fields.
Closes: #1772
Closes: #1826
Closes: #1959
> ✨ Add the rest of the missing fields and stabilize config v3

- pkg/cli/root.go
Sorted plugins key for the help
**Motivation**
Allow SDK to be aligned with KB. Because the result is not idempotent it brokes the CI/doc generation.
> :seedling: sort plugins key for the help

- pkg/plugins/golang/v2/api.go
- pkg/plugins/golang/v2/init.go
- pkg/plugins/golang/v3/api.go
- pkg/plugins/golang/v3/init.go
- pkg/plugins/golang/v3/webhook.go
Remove non-needed calls to `make` at the end of different command calls.
Closes: #1982
> ✨ Remove make calls from post-scaffold hooks

- pkg/config/errors.go
- pkg/config/errors_test.go
- pkg/config/v2/config.go
- pkg/config/v3/config.go
- pkg/config/v3/config_test.go
https://github.com/operator-framework/operator-sdk/pull/4402#discussion_r568028932
> ✨ Return a typed error in case DecodePluginConfig was unable to find the provided key

- pkg/model/resource/api.go
- pkg/model/resource/api_test.go
- pkg/model/resource/gvk.go
- pkg/model/resource/gvk_test.go
- pkg/model/resource/resource.go
- pkg/model/resource/resource_test.go
- pkg/model/resource/utils.go
- pkg/model/resource/webhooks.go
- pkg/model/resource/webhooks_test.go
- pkg/plugins/golang/options.go
- pkg/plugins/golang/options_test.go
- pkg/plugins/golang/v2/api.go
- pkg/plugins/golang/v2/options.go
- pkg/plugins/golang/v2/options_test.go
- pkg/plugins/golang/v2/webhook.go
- pkg/plugins/golang/v3/api.go
- pkg/plugins/golang/v3/webhook.go
Split resource validation between Options and Resource objects so that Resources built in different ways can still be validated.
Fixes: #1973
> ⚠ Resource validation

- pkg/plugins/golang/v2/scaffolds/api.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/controllers/controller.go
- plugins/addon/controller.go
- testdata/project-v2-addon/controllers/admiral_controller.go
- testdata/project-v2-addon/controllers/captain_controller.go
- testdata/project-v2-addon/controllers/firstmate_controller.go
- testdata/project-v2-multigroup/controllers/apps/pod_controller.go
- testdata/project-v2-multigroup/controllers/crew/captain_controller.go
- testdata/project-v2-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
- testdata/project-v2-multigroup/controllers/sea-creatures/kraken_controller.go
- testdata/project-v2-multigroup/controllers/sea-creatures/leviathan_controller.go
- testdata/project-v2-multigroup/controllers/ship/cruiser_controller.go
- testdata/project-v2-multigroup/controllers/ship/destroyer_controller.go
- testdata/project-v2-multigroup/controllers/ship/frigate_controller.go
- testdata/project-v2/controllers/admiral_controller.go
- testdata/project-v2/controllers/captain_controller.go
- testdata/project-v2/controllers/firstmate_controller.go
- testdata/project-v2/controllers/laker_controller.go
- testdata/project-v3-addon/controllers/admiral_controller.go
- testdata/project-v3-addon/controllers/captain_controller.go
- testdata/project-v3-addon/controllers/firstmate_controller.go
Add the documentation that was added to v3 plugin's controllers also to v2 plugin as they are only comments. This makes this change non-breaking because controllers scaffolded with v2 before this change will behave exactly the same as after this, but now they will have some extra documentation comments.
> 📖 Add documentation to v2 controllers

- pkg/cli/root.go
When creating the plugin table with their supported project versions, the supported project versions were being store as a slice in the same order as the plugin keys slice.
When #1984 sorted the plugin keys slice, it didn't modify the other slice accordingly.
> 🐛 Fix sorting issue with plugin versions and their supported project versions

- Makefile
- pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
- testdata/project-v2-addon/Makefile
- testdata/project-v2-multigroup/Makefile
- testdata/project-v2/Makefile
- testdata/project-v3-addon/Makefile
- testdata/project-v3-config/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
Changes:
- `Makefile`: remove 2 double white-spaces
- `pkg/plugins/golang/v2/*`: added `help` and `undeploy` targets. Changed `manager` target to `build` (kept an allias for backwards compatibility). Reoredered targets, added categories and improved some help messages.
- `pkg/plugins/golang/v3/*`: Changed `manager` target to `build`. Reoredered targets, added categories and improved some help messages.
By keeping a `manager` alias to `build` target in v2 projects, it can be considered non-breaking. The added targets (`help` and `undeploy`) won't be available on projects initialized before this, but they are not breaking changes as they are only additions.
Technically speaking, projects built with go/v3 can't `make manager` any more, they should use `make build` but `all` target is an …
> 🌱 Improve Makefile help and rename "manager" target to "build"

- README.md
- build/cloudbuild_tools.yaml
- build/thirdparty/darwin/Dockerfile
- build/thirdparty/linux/Dockerfile
- */Dockerfile: generalize for multiple platforms
- build/cloudbuild_tools.yaml: update with new Dockerfile args, prettify
- README.md: add new arches
**Note:** this PR also downgrades k8s version to v1.19.2 so arm64 and ppc64le builds occur for a v1.19 version. I will post a follow-up PR to upgrade the version back to v1.20.2 after this is merged.
Closes #966 
> :seedling: generalize tools Dockerfiles for arm64, ppc64le linux builds

- pkg/plugins/golang/v2/scaffolds/webhook.go
Fix go/v2 with config/v3 resources in config file to store webhook information
Fixes: #1996
> 🐛 Fix go/v2 with config/v3 resources in config file to store webhook information

- generate_testdata.sh
- pkg/model/file/funcmap.go
- pkg/model/resource/resource.go
- pkg/plugins/golang/options.go
- pkg/plugins/golang/options_test.go
- pkg/plugins/golang/v2/api.go
- pkg/plugins/golang/v2/options.go
- pkg/plugins/golang/v2/options_test.go
- pkg/plugins/golang/v2/scaffolds/api.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/controllers/controller.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/controllers/controller_suitetest.go
- pkg/plugins/golang/v2/webhook.go
- pkg/plugins/golang/v3/api.go
- pkg/plugins/golang/v3/scaffolds/api.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller_suitetest.go
- pkg/plugins/golang/v3/webhook.go
- testdata/project-v2-multigroup/config/rbac/role.yaml
- testdata/project-v2-multigroup/controllers/apps/deployment_controller.go
- testdata/project-v2-multigroup/controllers/apps/suite_test.go
- testdata/project-v2-multigroup/go.mod
- testdata/project-v2-multigroup/main.go
- testdata/project-v3-config/PROJECT
- testdata/project-v3-multigroup/PROJECT
- testdata/project-v3-multigroup/config/rbac/role.yaml
- testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
- testdata/project-v3-multigroup/controllers/apps/suite_test.go
- testdata/project-v3-multigroup/main.go
- testdata/project-v3/PROJECT
When an API is not scaffolded (`kubebuilder create api --resource=false --controller ...`) the resources are not being tracked in the config file. Tracking this in `config/v3` is doable as we can still know if the API was scaffolded by some of its fields, but as `config/v2` doesn't have this additional fields, it can't track this resources. The reason for this is that the pressence of a resource in `config/v2` means that the API was scaffolded at webhook validation (they require the API to be scaffolded) and this information won't be obtainable.
This change also detected that we were defining the `Path` field for those resources that do not have an API which was removed, and it allows to be a bit more intelligent when deploying core-resources.
Fixes #2001
Fixes #2002
> 🐛 (config/v3) Track in the project configuration file resources without API

- designs/extensible-cli-and-scaffolding-plugins-phase-1-5.md
This PR proposes a plugin phase 1.5 by submiting an EP.
Phase 1.5 should provide some of the goals defined for phase 2 in a shorter date.
You can read the EP with a nicer UX that in the chenged files [here](https://github.com/Adirio/kubebuilder/blob/plugin-phase-1-5/designs/extensible-cli-and-scaffolding-plugins-phase-1-5.md).
> 📖 Plugin phase 1.5 EP

- build/cloudbuild_tools.yaml
build/cloudbuild_tools.yaml: remove 'v' prefix from _KUBERNETES_VERSION to keep old tarball name format
> :seedling: revert tools tarball name to old format

- build/cloudbuild_tools.yaml
build/cloudbuild_tools.yaml: re-bump to k8s v1.20.2
> :seedling: build/cloudbuild_tools.yaml: re-bump to k8s v1.20.2

- OWNERS_ALIASES
As of https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/CONTRIBUTING-ROLES.md#becoming-an-approver
- I've been a reviewer for almost a year, couple of months are required
- I would say I've been the "main" reviewer or contributor of more than 5-10 substantial contributions
> 🌱 Add Adirio to aprovers

- designs/code-generate-image-plugin.md
- EP/proposal to add a new plugin to generate the code requires to address the common needs
**Motivation**
- Many operators will at the end have CRD's which will represent a deployment/pod of an image:tag. So, I am as oper user I'd like to have a feature to make this process easier. Also, see that it address common requests such as https://github.com/operator-framework/operator-sdk/pull/2158
- Reduce the learning curve since users are able to generate the basic operator following the good practices via this feature which makes more intuitive understand how the things work and know-how to improve/develop their solutions.  
- Address common questions over the basic features and how to for example; implement the tests, use envvars, RBAC permissions as watch features. 
- …
>  :book: proposal for new plugin to generate code ( `deploy-image.go.kubebuilder.io/v1beta1` )

- pkg/cli/root.go
By telling the root command that it should not error out if found unknown flags we ensure that the error that made us print the root help message is surfaced instead of being hidden behind the `unknown flag: --flag` bug.
Fixes: #2022
> 🐛 Fix the bug where an error was being hidden by a potentially valid flag not being recognized by the root command

- docs/book/src/cronjob-tutorial/testdata/emptyapi.go
- docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
- docs/book/src/cronjob-tutorial/testdata/emptymain.go
- docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
While working on the "Watching" documentation, I noticed that there were other examples in the book that had not yet been updated from v2 to v3.
This PR is pretty simple, and just updating the code differences with starting an empty project using v3.
For the finalizers, I added the RBAC finalizer permission as well, since that is available in v3.
The biggest difference is in `emptymain.go`, since there is a lot more generated code in v3 than in v2. I can scale the changes back for that file, but it now represents what a user would see when creating a new v3 project.
> 📖 Update static book examples to Kubebuilder v3.

- Makefile
By default coverage only is accounted for LoC in the same package as the tests.
If you provide `-coverpkg` you can specify a list of packages that will be taken into account when creating the coverage report.
This allows tests in a package to be used to provide coverage for other packages in the provided list.
As a side-effect, the list of files that are being covered is slightly different.
The following files were considered previously by coverage and are no longer:
All of them, exept for `pkg/plugins/golang/v2/options.go` were not being tested and had a 0% coverage, as this is being tested with integration tests. Loosing coverage on `pkg/plugins/golang/v2/options.go` which is at a 96.5% covered doesn't seem to big of an issue. Additionally, this file is going to disapear in plugin phase …
> 🌱 Enable cross-package coverage

- pkg/config/v3/config_test.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/main.go
The TODOs about v3 were already applied, removed them.
The TODO about the resource fields stored in the config file is out of date, updated it.
> 🌱 Update old TODOs that are no longer valid

- pkg/internal/validation/dns.go
- pkg/internal/validation/dns_test.go
As the title says, this PR adds tests to the DNS validation package.
The test cases are the same as in upstream.
> 🌱 Add tests to the DNS validation package

- .github/workflows/ci.yml
- docs/book/src/quick-start.md
- fix CI to use the correct go version 1.15+ < 1.16
- clarifies it in the quick-start since 1.16 was released and has breaking changes for the projects built. with and tool
> :seedling: fix CI to use the correct go version 1.15

- cmd/main.go
- pkg/cli/cli_test.go
- pkg/cli/options.go
- pkg/cli/options_test.go
Output of `go doc ./pkg/cli`:
Current state:
```
package cli // import "sigs.k8s.io/kubebuilder/v3/pkg/cli"
func WithCompletion(c *cli) error
type CLI interface{ ... }
func New(opts ...Option) (CLI, error)
type Option func(*cli) error
func WithCommandName(name string) Option
func WithDefaultPlugins(projectVersion config.Version, plugins ...plugin.Plugin) Option
func WithDefaultProjectVersion(version config.Version) Option
func WithExtraCommands(cmds ...*cobra.Command) Option
func WithPlugins(plugins ...plugin.Plugin) Option
func WithVersion(version string) Option
```
With this PR:
```
package cli // import "sigs.k8s.io/kubebuilder/v3/pkg/cli"
type CLI interface{ ... }
func New(opts ...Option) (CLI, error)
type Option func(*cli) error
func WithCommandName(name string) Option
func …
```
> ⚠️ Explicitly define WithCompletion as an Option

- pkg/config/interface.go
- pkg/config/v2/config.go
- pkg/config/v2/config_test.go
- pkg/config/v3/config.go
- pkg/config/v3/config_test.go
- pkg/plugin/util/helpers.go
- pkg/plugin/util/helpers_test.go
- pkg/plugins/golang/v3/api.go
- pkg/plugins/golang/v3/webhook.go
Extract the single version per config file out of config as it is a plugin restriction, not a project configuration file restriction.
Closes: #2046
> ⚠️ Decouple plugin requirements from Config interface

- .github/workflows/ci.yml
- Makefile
- pkg/internal/validation/dns.go
Currently, we are using older version of golangci-lint. 
To keep ourselves updated with the new changes and to not stumble upon any future surprises, I feel that we should be updating this golangci-lint version to latest.
BTW, this is my first contribution to this repo.
> 🌱  Update golangci lint

- pkg/plugins/golang/v2/api.go
- pkg/plugins/golang/v3/api.go
Rightnow the link does not contain the https in the URL, with this change it will be easy for the user to just click on the error message and view the content instead of copy-pasting the URL.
> 🐛  Add https to the webpage

- pkg/plugins/golang/v2/api.go
- pkg/plugins/golang/v2/init.go
- pkg/plugins/golang/v3/api.go
- pkg/plugins/golang/v3/init.go
- testdata/project-v2-addon/go.mod
- testdata/project-v2-multigroup/go.mod
- testdata/project-v2/go.mod
- testdata/project-v3-addon/go.mod
- testdata/project-v3-config/go.mod
- testdata/project-v3-multigroup/go.mod
- testdata/project-v3/go.mod
This PR adds an extra step in the API creation subcommand to update `go.mod` after scaffolding the API to make sure we have a fresh `go.mod` in cases of new dependencies introduced by the generated controllers.
* Go: 1.16 darwin/arm64
* Kubebuilder: version.Version{KubeBuilderVersion:"2.3.2", KubernetesVendor:"unknown", GitCommit:"5da27b892ae310e875c8719d94a5a04302c597d0", BuildDate:"2021-02-22T21:16:26-08:00", GoOs:"darwin", GoArch:"arm64"}
* operator-sdk: v1.4.2, commit: "4b083393be65589358b3e0416573df04f4ae8d9b
* Kubernetes: v1.19.4
Initially, I used the `operator-sdk` to create a new operator, but, after creating an API I stumbled upon the following issue:
```
$ operator-sdk init --domain example.com --repo github.com/example/memcached-operator
$ operator-sdk create api --group cache …
```
> ✨: Add go mod tidy to be executed after the scaffolding api

- pkg/plugins/golang/v3/scaffolds/init.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-addon/go.mod
- testdata/project-v3-config/Makefile
- testdata/project-v3-config/controllers/admiral_controller.go
- testdata/project-v3-config/controllers/captain_controller.go
- testdata/project-v3-config/controllers/firstmate_controller.go
- testdata/project-v3-config/controllers/laker_controller.go
- testdata/project-v3-config/go.mod
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
- testdata/project-v3-multigroup/controllers/crew/captain_controller.go
- testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
- testdata/project-v3-multigroup/controllers/lakers_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
- testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
- testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
- testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
- testdata/project-v3-multigroup/go.mod
- testdata/project-v3/Makefile
- testdata/project-v3/controllers/admiral_controller.go
- testdata/project-v3/controllers/captain_controller.go
- testdata/project-v3/controllers/firstmate_controller.go
- testdata/project-v3/controllers/laker_controller.go
- testdata/project-v3/go.mod
controller-runtime v0.7.2 contains a few bugfixes beneficial to users, especially if using v1 webhook configs (https://github.com/kubernetes-sigs/controller-runtime/pull/1329) or unstructured objects (https://github.com/kubernetes-sigs/controller-runtime/pull/1351).
/area dependency
> :sparkles: (go/v3) bump controller-runtime to v0.7.2

- pkg/cli/api.go
- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/cmd_helpers.go
- pkg/cli/completion.go
- pkg/cli/create.go
- pkg/cli/doc.go
- pkg/cli/edit.go
- pkg/cli/init.go
- pkg/cli/options.go
- pkg/cli/options_test.go
- pkg/cli/root.go
- pkg/cli/webhook.go
It also improves the documentation of all the exported pieces of this package.
Closes: #2078
> 🌱 Remove CLI interface and expose cli instead

- pkg/cli/completion.go
A recent PR bumped Cobra dependency to 1.1.1 which incudes support for Fish completion.
Previously, Fish completion was commented out as the Cobra version we were using didn't support it.
This PR adds support for Fish completion.
> ✨ Add fish completion

- pkg/cli/alpha.go
- pkg/cli/cli.go
- pkg/cli/options.go
- pkg/cli/options_test.go
SDK is providing an alpha command, we are doing the same, when we try to align them, they will collide.
This PRs provides a way to set extra alpha commands for third-party developers.
> ✨ Provide third-party devs the option to provide their own alpha subcommands

- README.md
The coverage report badge from coveralls was not present in the README.
This PRs adds it.
> 🌱 Add coverage badge from Coveralls

- pkg/cli/alpha.go
Alpha subcommand had a hardcoded reference to kubebuilder.
As kubebuilder may be used as a library by other CLI tools, the description should be more generic.
> 📖 Remove kubebuilder hardcoded reference in alpha subcommand description

- pkg/cli/alpha.go
- pkg/cli/cli_test.go
#2089 was adding the commands to the root command instead of to the alpha subcommand.
This PRs fixes the bug and adds a test to verify it in the future.
> 🐛 Fix alpha extra commands parent command

- pkg/cli/alpha.go
- pkg/cli/alpha/config-gen/cmd.go
- pkg/cli/completion.go
- pkg/plugins/golang/v2/api.go
- pkg/plugins/golang/v2/edit.go
- pkg/plugins/golang/v2/init.go
- pkg/plugins/golang/v2/webhook.go
- pkg/plugins/golang/v3/api.go
- pkg/plugins/golang/v3/edit.go
- pkg/plugins/golang/v3/init.go
- pkg/plugins/golang/v3/webhook.go
Stop using a mix of tabs and spaces in help messages and remove ending tabs.
/kind cleanup
> 🌱 Cleanup help messages

- pkg/config/v2/config.go
Master branch was not properly linted, and therefore the coverage report was not being uploaded.
Setting the emoji as 🌱 as it only affects the CI.
> 🌱 Fix coverage report on master

- designs/extensible-cli-and-scaffolding-plugins-phase-1-5.md
While implementing plugin phase 1.5 and aligning operator-SDK, several additional concepts that were not designed at first have raised. This PR improved on the plugin phase 1.5 design document including those changes.
Plugin phase 1.5 will be useful to achieve several goals in kubebuilder. For example, plugin chaining allows to split monolithic plugins into smaller ones, and plugin bundles maintain backwards compatibility towards the user.
- Splitting non-go-related and go-related scaffolding so that plugins for other languages can benefit from parts: #2015
- Add additional features as plugins instead of making the base plugin more and more complex:
- Finalizers: #2010
- Component config: #1790
- Declarative pattern: currently implemented through an experimental outdated plugin system …
> 📖 Improve plugin phase 1.5 EP

- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/config/interface.go
- pkg/config/store/yaml/store.go
- pkg/config/v2/config.go
- pkg/config/v2/config_test.go
- pkg/config/v3/config.go
- pkg/config/v3/config_test.go
- pkg/plugins/golang/v2/init.go
- pkg/plugins/golang/v3/init.go
- testdata/project-v3-addon/PROJECT
- testdata/project-v3-config/PROJECT
- testdata/project-v3-multigroup/PROJECT
- testdata/project-v3/PROJECT
Use a custom type to ensure backwards compatibility: older configuration files will unmarshall properly despite not being an array and will marshal to the new format.
/kind feature
> ✨ Enable the storage of multiple plugins as layout

- docs/book/src/component-config-tutorial/testdata/project/config/prometheus/monitor.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor.yaml
- docs/book/src/reference/metrics.md
- pkg/plugins/golang/v2/scaffolds/internal/templates/config/prometheus/monitor.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/config/prometheus/monitor.go
- testdata/project-v2-addon/config/prometheus/monitor.yaml
- testdata/project-v2-multigroup/config/prometheus/monitor.yaml
- testdata/project-v2/config/prometheus/monitor.yaml
- testdata/project-v3-addon/config/prometheus/monitor.yaml
- testdata/project-v3-config/config/prometheus/monitor.yaml
- testdata/project-v3-multigroup/config/prometheus/monitor.yaml
- testdata/project-v3/config/prometheus/monitor.yaml
By default the ServiceMonitor scrapes `port: https` https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v2/config/prometheus/monitor.yaml#L13, which is exposed by the auth proxy service https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v2/config/rbac/auth_proxy_service.yaml#L10-L12 and requires an https connection https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v2/config/default/manager_auth_proxy_patch.yaml#L15
Change the ServiceMonitor configuration to work with that by default as otherwise the scraping fails with a `400 Bad Request`.
Thanks to https://github.com/kubernetes-sigs/kubebuilder/issues/1253#issuecomment-597640633 for the required flags.
> 🐛 default service monitor configuration to use https

- pkg/cli/alpha/config-gen/cmd.go
When creating CLI docs using cobra's docs generator,
this doc is generated inconsistently depending on what
environment the command is run. This PR fixes that
problem by using a static path and saying where the
dynamic part comes from.
> :seedling: config-gen: command docs no longer depend on local environment

- .github/workflows/ci.yml
The GitHub actions CI workflow is run for both pull-requests (targeting the remote branch) and the merge commit push whey they re merged (targeting the branch where they were merged into). Pull-request-related results are exposed under the checks of the PR, which makes them pretty accessible. However, push-related results are only shown in the "Actions" tab and are usually not reviewed. As an example, a linting issue was introduced nearlly a month ago in master, which was passing the PR linting check as it only checks the modified code, but was not passing the push linting check. This means that coverage report was not being sent to coveralls about the master branch since the February 22nd, and we just realized today (March 16th).
This PR adds an additional debugging step that will create …
> 🌱  Enhance GitHub actions CI

- pkg/cli/cli.go
- pkg/cli/options.go
- pkg/cli/options_test.go
- pkg/cli/root.go
Create an `Option` that allows to modify the root's command description.
Closes: #1830
> ✨ Allow to modify the root's command description

- pkg/plugin/bundle.go
- pkg/plugin/bundle_test.go
- pkg/plugin/plugin.go
A `Bundle` is also a `Plugin`, but as unbundling is not done recursively, when using a `Bundle` as the input of other `Bundle`, it is not properly unbundled.
This PRs solves this by unbundling Bundles at Bundle creation time to avoid having to use recursive unbundling.
> ✨ Allow bundles to be used as input to other bundles

- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/config/registry.go
- pkg/config/registry_test.go
Ignore UnsupportedVersion error to allow extra commands to be able to actually run.
Fixes: #2125
> :bug: regression - extracommands require a valid PROJECT file again

- CONTRIBUTING.md
* Should be make test-unit now as of
https://github.com/kubernetes-sigs/kubebuilder/commit/8c0816155d88c475cd6b703267b0e7840776a0a2#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L90
Signed-off-by: Michelle Noorali <minooral@microsoft.com>
> :seedling: update refs to go-test make target

- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller_test.go
* a description of the change
test_suite.go -> suite_test.go
* the motivation for the change
simple typo
> :book: Fix typo 

- docs/book/src/cronjob-tutorial/testdata/project/Makefile
- docs/book/src/migration/manually_migration_guide_v2_v3.md
- docs/book/src/multiversion-tutorial/testdata/project/Makefile
- docs/book/src/reference/envtest.md
- pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-config/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
(go/v3) set the Makefile's SHELL variable to the system's bash binary, and set shell options pipefail and errexit. setup-envtest.sh needs bash, so the Makefile should provide best-effort support to find and use it. Docs were updated to include manual install instructions for envtest binaries, in case setup-envtest.sh cannot be used to download binaries.
There have been a few attempts to ameliorate setup-envtest.sh breakage on systems with a different shell as the `/bin/sh` (#1711, #1725, #1864). These have all been closed, so the problem persists.
/kind bug
Closes #2121 
> :sparkles: (go/v3) Makefile: set SHELL to the system's `bash` binary with shell opts

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
Validation appears to have increased slightly, and some deprecated
fields were switch up.  This made it impossible to file issues in
KubeBuilder, which is... suboptimal.
This fixes that, so we can once again open the receive bugs :-)
> :seedling: Fix issue templates

- Makefile
- docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
- test.sh
As per #2128, the book's `make test` target did not run.  There were two issues at hand:
1. The book was not updated to use the `sideEffects` and `admissionReviewVersions` fields in the `+kubebuilder:webhook` marker (required for v1 webhooks)
2. #2066 incorrectly interpreted advice on test clients and switch the reconciler over to use a live client (the reconciler should always use the manager's client, and in this case has to, because it relies on indicies).
This fixes both those issues, and also adds the book's tests to `make test` so that we don't break this in the future, and makes sure the CI is actually running `make test` instead of a copy of the same actions.
Fixes #2128 
Related to #2066 
Related to #2018
> :book: Fix advice on clients in tests, ensure that book gets tested

- VERSIONING.md
- This PR fixes markdown format in `VERSIONING.md` about refering to tools-branch link.
Before this PR, tools-branch link [is not expand the link](https://github.com/kubernetes-sigs/kubebuilder/blob/master/VERSIONING.md#tools-releases) on `VERSIONING.md`.
It looks like `[tools-releases branch][tools-branch]` in plain text.
> :book: Fix markdown format in VERSIONING.md

- CONTRIBUTING.md
- RELEASE.md
- VERSIONING.md
- Update the docs to have the info over the latest branch that tough to be used to v3
**Motivation**
- Closes : https://github.com/kubernetes-sigs/kubebuilder/issues/1860
> :book: update the docs over regards book-v3 branch

- build/build.sh
Previously, we weren't actually annotating the images in the manifest,
so we ended up with all the images set as linux-amd64 instead of their
respective bits.
This should fix that, annotating with arch before pushing, as per the
docker docs.
CC #1785
> docker manifests need to be annotated

- docs/book/functions/handle-version.js
- netlify.toml
This resolves an issue introduced in the redirect prep for v3 (#2062) that
broke our download redirects.
The problem is that v3 releases are `kubebuilder_${os}_${arch}`, whereas
v2 & v1 releases are `kubebuilder_${version}_${os}_${arch}.tar.gz`.
Since netlify can't handle wildcards that are part of a path component
(like `/2.:minorversion`) instead of a whole one (`:version`), we can't
select on major version directly in our redirects.
Instead, we introduce a function that handles this logic for us, and
then use netlify 200-pseudo-redirects to "mount the function on the
downloads part of the releases endpoint.
> :book: : Fix download redirects with functions

- docs/book/functions/handle-version.js
- netlify.toml
The local `netlify` dev server and documentation expect a top-level
configuration block named functions, but the remote netlify builder
expects a key under the build block instead.  Who knows why.
> :book: Fix netlify functions configuration

- docs/book/functions/handle-version.js
- netlify.toml
This fixes the split between v2 and v3 download artifacts, working around the fact that netlify doesn't allow redirect path fragments to contain partial wildcards (so we can't match on `/2.:minor/`, only `/:version/`).
To do so, we introduce a simple netlify function that looks at the path, and redirects as needed (`kubebuilder_${os}_${arch}` for v3+, `kubebuilder_${version}_${os}_${arch}.tar.gz` for v2 & v1). 
We use a 200-pseudo-redirect from the full `/releases/:version/:os/:arch` to make it look like the function is mounted on the releases endpoint, instead of redirecting to the function URL itself.
(cherry-pick of #2168 and #2166)
> :book: Netlify functions for download redirects

- docs/book/src/migration/manually_migration_guide_v2_v3.md
- docs/book/src/migration/migration_guide_v2tov3.md
- docs/book/src/migration/v2vsv3.md
- pkg/plugins/golang/declarative/v1/api.go
- pkg/plugins/golang/v3/scaffolds/init.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-addon/go.mod
- testdata/project-v3-config/Makefile
- testdata/project-v3-config/controllers/admiral_controller.go
- testdata/project-v3-config/controllers/captain_controller.go
- testdata/project-v3-config/controllers/laker_controller.go
- testdata/project-v3-config/go.mod
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
- testdata/project-v3-multigroup/controllers/crew/captain_controller.go
- testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
- testdata/project-v3-multigroup/controllers/lakers_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
- testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
- testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
- testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
- testdata/project-v3-multigroup/go.mod
- testdata/project-v3/Makefile
- testdata/project-v3/controllers/admiral_controller.go
- testdata/project-v3/controllers/captain_controller.go
- testdata/project-v3/controllers/laker_controller.go
- testdata/project-v3/go.mod
deps: Bump controller-runtime to 0.8.0
> :sparkles: bump controller-runtime to 0.8.3

- docs/book/utils/markerdocs/main.go
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>
Warning: redundant type from array, slice, or map composite literal
> :seedling: Fix a gofmt warning

- pkg/cli/alpha/config-gen/cert-generation-filter.go
- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go
- testdata/project-v3-addon/config/crd/patches/webhook_in_admirals.yaml
- testdata/project-v3-addon/config/crd/patches/webhook_in_captains.yaml
- testdata/project-v3-addon/config/crd/patches/webhook_in_firstmates.yaml
- testdata/project-v3-config/config/crd/patches/webhook_in_admirals.yaml
- testdata/project-v3-config/config/crd/patches/webhook_in_captains.yaml
- testdata/project-v3-config/config/crd/patches/webhook_in_firstmates.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_captains.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_cruisers.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_destroyers.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_frigates.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_healthcheckpolicies.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_krakens.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_lakers.yaml
- testdata/project-v3-multigroup/config/crd/patches/webhook_in_leviathans.yaml
- testdata/project-v3/config/crd/patches/webhook_in_admirales.yaml
- testdata/project-v3/config/crd/patches/webhook_in_captains.yaml
- testdata/project-v3/config/crd/patches/webhook_in_firstmates.yaml
The conversion webhook client config requires a list
of conversion review versions. This change scaffolds the
conversion webhook patch with default conversion review version
of v1.
> :sparkles: add default conversion review versions

- pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
- testdata/project-v3-addon/main.go
- testdata/project-v3-config/controllers/admiral_controller.go
- testdata/project-v3-config/controllers/captain_controller.go
- testdata/project-v3-config/controllers/laker_controller.go
- testdata/project-v3-config/main.go
- testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
- testdata/project-v3-multigroup/controllers/crew/captain_controller.go
- testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
- testdata/project-v3-multigroup/controllers/lakers_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
- testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
- testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
- testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
- testdata/project-v3-multigroup/go.mod
- testdata/project-v3-multigroup/main.go
- testdata/project-v3/controllers/admiral_controller.go
- testdata/project-v3/controllers/captain_controller.go
- testdata/project-v3/controllers/laker_controller.go
- testdata/project-v3/main.go
Use log provided by controller-runtime in reconciliation loop.
Enough information is filled by following.
https://github.com/kubernetes-sigs/controller-runtime/blob/b704f447ea7c8f7059c6665143a4aa1f6da28328/pkg/builder/controller.go#L311
https://github.com/kubernetes-sigs/controller-runtime/blob/ce2f0c92d77e05609fab003663f2b5bb9c1990d7/pkg/internal/controller/controller.go#L99
>  ✨  Use log from context

- docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/webhook_in_cronjobs.yaml
Update tutorials in book to scaffold default conversion review version.
follow up: #2176 
Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>
> :book: add default conversion review versions to kb book

- docs/book/src/cronjob-tutorial/api-design.md
* Description of the change: 
Fix typo in docs/book/src/cronjob-tutorial/api-design.md (significand -> significant)
* Motivation for the change: 
Fixing typo and begin with contribution
> :book: Fix typo in api-design.md

- docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml
- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/kustomization.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/config/crd/kustomization.go
- testdata/project-v2-addon/config/crd/kustomization.yaml
- testdata/project-v2-multigroup/config/crd/kustomization.yaml
- testdata/project-v2/config/crd/kustomization.yaml
- testdata/project-v3-addon/config/crd/kustomization.yaml
- testdata/project-v3-config/config/crd/kustomization.yaml
- testdata/project-v3-multigroup/config/crd/kustomization.yaml
- testdata/project-v3/config/crd/kustomization.yaml
Several comments for enabling cert-manager in the kustomization config
incorrectly said `[CERTMANAGER] To enable webhook`
This was probably a copy/paste error.
> 🐛 fix: incorrect cert-manager kustomize comments

- .github/workflows/apidiff.yml
- CONTRIBUTING.md
- pkg/cli/alpha/config-gen/cmd.go
- test/e2e/utils/test_context.go
- test/e2e/v3/plugin_cluster_test.go
> 🐛 Fix CI for go 1.16

- docs/book/src/introduction.md
Hi there!
Not sure if this has been brought up before but now that we're on v3 I think it'd be nice to also link to the v2 version of the documentation for those who are temporarily stuck on v2 like me :sweat_smile:
> :book: Link to v2 book as well from intro page

- pkg/cli/alpha/config-gen/cmd.go
Add v1alpha1 to the apiVersion in the documentation for the config-gen command.
This is necessary because the install-plugin sub-command installation location must match the api group and api version in the plugin configuration.
> 🐛 Fix config-gen documentation bug

- docs/book/src/component-config-tutorial/testdata/project/.dockerignore
- docs/book/src/cronjob-tutorial/testdata/project/.dockerignore
- docs/book/src/multiversion-tutorial/testdata/project/.dockerignore
- pkg/plugins/golang/v3/scaffolds/internal/templates/dockerignore.go
- testdata/project-v3-addon/.dockerignore
- testdata/project-v3-config/.dockerignore
- testdata/project-v3-multigroup/.dockerignore
- testdata/project-v3/.dockerignore
This change ensures that the scaffolded `.dockerignore` file makes Docker ignore non-Go files.
This avoids large files like test binaries being unnecessarily included in Docker's build context.
Fixes #2073.
> 🐛 fix: ignore non-go files during Docker build

- docs/book/src/reference/generating-crd.md
A typo causes a broken link
https://github.com/kubernetes-sigs/kubebuilder/blob/18b38aafbdf0fe844029d68452a0020729ead97d/docs/book/src/reference/generating-crd.md#L66
https://github.com/kubernetes-sigs/kubebuilder/blob/18b38aafbdf0fe844029d68452a0020729ead97d/docs/book/src/reference/generating-crd.md#L240
> 📖 docs: fix the broken link in the generating-crd.md

- .github/ISSUE_TEMPLATE/bug_report.yaml
Seems like `--version` is an old flag that has been replaced with `version` command
> :book: Fix `version` command

- docs/book/src/cronjob-tutorial/cronjob-tutorial.md
Add the `--repo` flag to init command of the cronjob tutorial.
https://github.com/kubernetes-sigs/kubebuilder/blob/e8715b32a41b7465e9c8cd1d36c25f27453d412f/docs/book/src/cronjob-tutorial/cronjob-tutorial.md#L46-L52
which is the same as the create a project example in quick start.
https://github.com/kubernetes-sigs/kubebuilder/blob/4b171da5846bc40772c0025c1033427dde536115/docs/book/src/quick-start.md#L56-L60
> 📖 Add the --repo flag to init example of the cronjob tutorial

- docs/book/src/reference/artifacts.md
Explicitly mention "Kubernetes version" in artifacts documentation so users don't get confused with Kubebuilder version.
Fixes #2244
Signed-off-by: Rashmi Gottipati <chowdary.grashmi@gmail.com>
> 📖 Clarify artifacts doc to explicitly mention Kubernetes version

- docs/book/src/reference/metrics.md
Hi, I fixed display name of https://github.com/brancz/kube-rbac-proxy(kube-auth-proxy -> kube-rbac-proxy).
This name can be a check on following page: https://book.kubebuilder.io/reference/metrics.html
> 📖 Fix name: kube-auth-proxy -> kube-rbac-proxy

- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/config.go
- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/auth_proxy_service.go
- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/webhook/service.go
- testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-addon/config/rbac/auth_proxy_service.yaml
- testdata/project-v3-config/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-config/config/manager/manager.yaml
- testdata/project-v3-config/config/rbac/auth_proxy_service.yaml
- testdata/project-v3-config/config/webhook/service.yaml
- testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3-multigroup/config/rbac/auth_proxy_service.yaml
- testdata/project-v3-multigroup/config/webhook/service.yaml
- testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3/config/manager/manager.yaml
- testdata/project-v3/config/rbac/auth_proxy_service.yaml
- testdata/project-v3/config/webhook/service.yaml
- explicitly specify port protocol where missing
- larger resource limit for controller manager
With the original default manifest, the server-side-apply would fail since the required `protocol` field is missing.
This is actually a k8s [bug](https://github.com/kubernetes-sigs/structured-merge-diff/issues/130) and should not be omitted before 1.20.
The default controller manager resource limit is too low for downloading small amount (~30kb) of http resource. It results a OOMKilled Pod status and no logs could be found.
Sometimes you got the CrashLoopBackOff status but no logs found, which took me sometime to figure it out.
We can watch the status transition via `kubectl get po -w`:
```sh
bootstrap-controller-manager-8f88c7b5b-gplpg   2/2     Running            4          3m59s …
```
> ✨ fix(scaffolds): better defaults

- scripts/install.sh
Clean up extra spaces, although these errors are not important, they affect the code specification.
> 🌱 Clean up extra spaces

- pkg/model/resource/resource.go
This makes it easier to figure out what the actual values should be.
When using from within `operator-sdk` I faced an error such as the following when scaffolding a webhook on a project when some directories were moved around:
```
FATA[0000] failed to create webhook: unable to scaffold with "kustomize.common.kubebuilder.io/v1": error updating resource: unable to update Resource with another with non-matching Path 
```
> ✨ Include additional info in error messages.

- docs/book/src/reference/markers/crd.md
Fixes: https://github.com/kubernetes-sigs/kubebuilder/issues/2276
The [Generating CRDs](https://github.com/kubernetes-sigs/kubebuilder/blob/cb1b6008f16ad5b4f56b019600f285e902215795/docs/book/src/reference/generating-crd.md) link is broken, a small correction to fix it.
> 📖 Update generating crd link in docs

- pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-config/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3/Makefile
Currently, while setting up envtest and running controller
tests in go/v3 projects, we look for the binary in the default
location. With the changes made in `setup-envtest`, the kb assets
are downloaded at tmp/k8s/<os_specific_location>. This fix sets
the KUBEBUILDER_ASSETS var to point to the location where they
are downloaded so that `make test` does not fail.
More details on the issue: https://github.com/operator-framework/operator-sdk/issues/5090
> :bug: add the path to Kubebuilder assets in go/v3 projects

- pkg/plugins/golang/go_version.go
- pkg/plugins/golang/go_version_test.go
- pkg/plugins/golang/v2/init.go
- pkg/plugins/golang/v3/init.go
Each plugin should be able to specify its own Go version requirements, which may drift.
/kind bug
> :bugfix: chore(golang): refactor go version check for per-plugin configuration

- .golangci.yml
- Makefile
Update the version of golangci-lint to the latest version.
This change updates both the version that is downloaded, the config file to account for deprecated linters in 1.41, and fixes some issues found by `revive` (which replaces `golint`.)
`make lint` and `make test` both pass with no issues.
**Motivation**
Although the version in current use isn't "old", there are some linters that aren't maintained anymore, or have been supersededded by other linters.
The thought is that the latest version will be more likely to catch more "issues" - before they make it into a release.
**Fixes**
Fixes #2274
> 🌱 Bump the linter version

- docs/book/book.json
Adds a legacy banner to the top of v1 book.
It is an aid/warning to users visiting the v1 site that they are not on the current version of the book and provides them with a link to the current version if required.
Here is a screenshot of the banner or you can view the docs preview by following the steps in [How to preview the changes performed in the docs](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#how-to-preview-the-changes-performed-in-the-docs):
Fixes #1963 
**Note to reviewers:** To override GitBook templates/themes requires using a [GitBook plugin](https://snowdreams1006.github.io/gitbook-official/en/plugins/). A GitBook plugin is a node package which can be published on NPM or can be hosted on GitHub. I have hosted it on …
> 📖 : Add legacy banner to v1 book

- docs/book/src/quick-start.md
Signed-off-by: yuswift <yuswift2018@gmail.com>
Fixes #2207 
As #2182 upgraded the go version to v1.16, the quickstart prerequisites need to be updated too.
> 📖  Update go Prerequisites for the latest release

- docs/book/theme/header.hbs
Adds a legacy banner to the top of v2 book.
It is an aid/warning to users visiting the v2 site that they are not on the current version of the book and provides them with a link to the current version if required.
Here is a screenshot of the banner or you can view the docs preview by following the steps in [How to preview the changes performed in the docs](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#how-to-preview-the-changes-performed-in-the-docs):
Note: Related to #2289
> 📖 : Add legacy banner to v2 book

- docs/book/src/reference/markers.md
The `+kubebuilder:validation:Default` marker does not appear in the output of `controller-gen crd -www` so it was probably just an invented example.
Let's use an actual existing marker here to prevent the non-existing one from being cargo-culted into other projects any more.
> :book: Use an existing marker for the struct value example.

- docs/book/src/quick-start.md
This PR is a cherry pick of commit #2257 that updated the QuickStart prerequisites. 
As #2182 upgraded the go version to v1.16, the QuickStart documentation needed to be updated too.
> 📖  Update go Prerequisites for the latest release 

- designs/extensible-cli-and-scaffolding-plugins-phase-2.md
Description of the change
This PR adds an enhancement proposal for Kubebuilder Phase 2 Plugins
Signed-off-by: Rashmi Gottipati <chowdary.grashmi@gmail.com>
> 📖 Plugin Phase 2 Enhancement Proposal

- netlify.toml
The release redirect rule uses a self-defined JS handler function because releases prior to v3 had a different URL structure not handle-able by Netlify's static redirect definitions. The handler checks for a `releases` resource path component in the request URL, which doesn't exist in the event path provided to the handler (the API may have changed, not sure of the cause). This PR explicitly adds this resource path component to the redirect URL.
Closes #2320 
Closes #2311
> :book: fix(netlify): fix broken redirect resource

- pkg/plugin/external/types.go
* a description of the change
Add a spec for Phase 2 Plugins by defining the contract between kubebuilder and the external plugin based on what data kubebuilder passes to the external plugin and receives from the external plugin. 
* the motivation for the change
Creating this spec based on the POC work that was done (more details in the EP: https://github.com/kubernetes-sigs/kubebuilder/pull/2243). 
Signed-off-by: Rashmi Gottipati <chowdary.grashmi@gmail.com>
> ✨ Spec for Phase 2 Plugins

- build/.goreleaser.yml
- docs/book/src/migration/manually_migration_guide_v2_v3.md
- docs/book/src/reference/envtest.md
The currently documented and compile-time-set k8s version is incorrect. It should be a 1.21.z version.
/kind bug
> :book: fix(release,book): fix documented k8s version, 1.19 -> 1.21

- build/cloudbuild_tools.yaml
I'd like to see if a newer 1.21 patch release will fix https://github.com/kubernetes-sigs/controller-runtime/issues/1571.
> :seedling: chore(deps): build k8s 1.21.4

- docs/book/src/cronjob-tutorial/testdata/emptymain.go
This is a simple fix to add the color after `err` so the short assignment operator (`:=`) is used. 
Fixes: #2337
> :book: Fix Tutorial Section 1.2 Missing Colon

- test/e2e/local.sh
- test/e2e/setup.sh
Increases the `go test` timeout value by 10 mins so that e2e tests can run locally. 
At present, they are timing out which makes it impossible to run them successfully.
Fixes #2355 
Note: Also, updated the default Kubernetes version to the latest patch release of 1.18.
> :bug: Fix e2e tests that timeout when run locally

- docs/book/src/cronjob-tutorial/testdata/emptymain.go
This is a simple fix to add another color after err so the short assignment operator (:=) is used.
Fixes: #2337
In the context of the emptymain.go the colon was intentionally left out, but in the context of the tutorial the color was necessary as a replacement for the cluster-scoped and namespaced-scoped manager instantiations
> :book: Fix Tutorial Section 1.2 Missing Colon (2/2)

- cmd/main.go
Registers the existing `base.go.kubebuilder.io/v3` plugin so that it is usable in the `kubebuilder` CLI, for users who do not use Kustomize.
Updated supported plugin table:
```
Plugin keys | Supported project versions
------------------------------------+----------------------------
base.go.kubebuilder.io/v3 |                          3
declarative.go.kubebuilder.io/v1 |                       2, 3
go.kubebuilder.io/v2 |                       2, 3
go.kubebuilder.io/v3 |                          3
kustomize.common.kubebuilder.io/v1 |                          3
```
Closes #2349 
Signed-off-by: Adam Snyder <armsnyder@gmail.com>
> ✨Include base.go.kubebuilder.io/v3 plugin in CLI

- pkg/machinery/scaffold.go
- pkg/machinery/scaffold_test.go
- testdata/project-v2-addon/controllers/suite_test.go
- testdata/project-v2/controllers/suite_test.go
- testdata/project-v3-addon/controllers/suite_test.go
- testdata/project-v3-config/controllers/suite_test.go
- testdata/project-v3-config/main.go
- testdata/project-v3-v1beta1/api/v1/webhook_suite_test.go
- testdata/project-v3/api/v1/webhook_suite_test.go
- testdata/project-v3/controllers/suite_test.go
- testdata/project-v3/main.go
Signed-off-by: Adam Snyder <armsnyder@gmail.com>
Scaffolding can only detect existing generated code if the code fragments are single-line. As a result, multi-line scaffolding can be inserted into code more than once. This fix improves the scaffolding to detect multi-line code fragments and not inject them.
Fixes #2326
> 🐛 Improve scaffolding to filter existing multiline code fragments

- docs/book/src/cronjob-tutorial/running-webhook.md
- docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
Description:
Update the config to make the example work.
Motivation:
The current [Deploy Webhooks](https://book.kubebuilder.io/cronjob-tutorial/running-webhook.html#deploy-webhooks) section is not working when I try to follow the book. 
Return the following error:
```
Error: var '{CERTIFICATE_NAME cert-manager.io_v1_Certificate {metadata.name}}' cannot be mapped to a field in the set of known resources
error: no objects passed to apply
make: *** [deploy] Error 1
```
What issue it fixes:
- Fixes https://github.com/kubernetes-sigs/kubebuilder/issues/2357
> :book:Update the example to enable webhook and cert manager

- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/config.go
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-config/config/manager/manager.yaml
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3-v1beta1/config/manager/manager.yaml
- testdata/project-v3/config/manager/manager.yaml
Add todo(user) to make clear the need to optimize the values of the manager resources according to the needs
Related to: https://github.com/kubernetes-sigs/kubebuilder/issues/2347
> :sparkles: Add todo(user) to make clear the need to optimize the values of the manager resources according to the needs

- docs/book/src/introduction.md
Fixes a small misspelling in the book introduction. 
Replacing `principals` with `principles`.
> :book: Fix misspelling in book introduction

- docs/book/src/cronjob-tutorial/cert-manager.md
Pretty much what the title says.
The outdated link has been replaced with an new link.
> 📖  Update cert-manager install url because it changed

- docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
This PR removes `removeString()` from the document since it's not being used in the example since e0b66dca3dc2e3c2c33ecda85183cfe6ae498a7d. The function is a leftover from an old version of the document. In current version, `controllerutil.RemoveFinalizer()` is being used for removing the finalizer.
> 📖 Remove unused removeString function from documentation

- docs/book/src/cronjob-tutorial/running-webhook.md
Signed-off-by: lonelyCZ <531187475@qq.com>
I found a wrong word in document and fixed it.
> 📖Update wrong word til to till

- CONTRIBUTING.md
It would be better if the new contributors who want to contribute to documentation, can have a view at the K8s style guide. So adding it to the CONTRIBUTING.md makes it easier.
fixes #2423
> 📖Add style guide to the Contribution doc

- docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
It would be nice t remove containsString helper function from the docs/book/src/cronjob-tutorial/testdata/finalizer_example.go and utilize controllerutil.ContainsFinalizer instead. Many newcomers copy/paste this example into the code, but it a bit stale/redundant.
fixes #2425
> :book: Utilize controllerutil.ContainsFinalizer inside kubebuilder book CronJob finalizer example

- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
- testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-config/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-v1beta1/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
Signed-off-by: Frederic Giloux <fgiloux@redhat.com>
This change introduces default resource requests and limits for the kube-rbac-proxy container scaffolded by KubeBuilder. It also provides a hint to users that this should get amended to match the specific requirements.
**Motivation**
This is similar to what is already done for the controller-manager.
- Provides information to the scheduler for better pod placement
- Prevents the pod of getting evicted or the container of getting OOM killed as first on the line when there is memory pressure on the node but the pod/container does not consume more than what it is supposed to
- Allows the pod to play well with Quotas and LimitRanges without relying on LimitRange defaults
Fixes #2428
> :sparkles: Add resource requests and limits to kube-rbac-proxy

- docs/book/src/component-config-tutorial/define-config.md
Fix link for controller manager component config in kubebuilder book.
Closes: #2424
> :book: fix link for controllermanager component config

- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
- testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-config/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-v1beta1/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
This change removes the debug logging flag from the kube-rbac-proxy patch that is generated by default, fixing #2434.
As mentioned in the issue, debug logging outputs bearer tokens of the service account that kube-rbac-proxy is using, which can be used to authenticate and perform any authorized actions that your manager is configured for.
I suppose it's okay to assume that folks using kubebuilder should be auditing the generated configs and catching this type of thing, but for folks (like me) that didn't catch it, defaulting to normal logging levels can prevent some headache.
> ✨ (kustomize/v1) reduce the debug log level for the sidecar container kube-rbac-proxy from 10 to 0

- pkg/plugins/common/kustomize/v1/init.go
- pkg/plugins/golang/v2/init.go
- pkg/plugins/golang/v3/init.go
Description: 
Fix a small typo in the `kubebuilder init --help` response. 
Closes: #2444
> :book: update docs to fix typo

- build/cloudbuild_tools.yaml
- build/thirdparty/darwin/Dockerfile
- build/thirdparty/linux/Dockerfile
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
> 🌱 Build kubebuilder-tools for Kubernetes 1.23.1

- docs/book/src/component-config-tutorial/api-changes.md
Signed-off-by: yuswift <yuswift2018@gmail.com>
>  📖: fix the missing of ')' in component config

- build/thirdparty/darwin/Dockerfile
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
Blocks #2471 .
The issue is ENVTEST_K8S_VERSION is set to 1.23 in all testdata makefiles, but  darwin binaries are missing for that version.
I think the issue could be that the last cloudbuild pipeline failed because of timeout? I am not sure ...
> 🌱: upgrade docker image for darwin to 1.17

- docs/book/src/cronjob-tutorial/cronjob-tutorial.md
The reference links for `GOPATH` and `Go modules blogpost` under https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html#scaffolding-out-our-project seems to be missing.
This PR adds these reference links.
Signed-off-by: Burak Sekili <buraksekili@gmail.com>
> 📖  - Update reference links under CronJob tutorial

- VERSIONING.md
Description: 
In `VERSIONING.md` there are two links to the book that are broken, this PR updates the links to point to the (allegedly) correct location.
> 📖 Fix broken links to CLI plugin versioning

- docs/book/src/quick-start.md
This PR fixes #2488 by documenting in the kubebuilder book that releases 3.3 and above need go v1.17 and above.
(It seems my vscode also removed some spaces, I could cancel that part).
> :book: Update go prerequisites for the 3.3 release

- docs/book/src/quick-start.md
Backport pull-request #2489 to branch book-v3.
This pull-requests contains improvements to the prerequisites needed to use kubebuilder 3.3 in the book.
> :book: Backport update of go prerequisites for the 3.3 release

- docs/book/src/reference/metrics.md
Remove namespace from ClusterRoleBinding as it is not required to pass namespace with cluster-level resources
> 📖  Remove namespace from ClusterRoleBinding

- build/cloudbuild_tools.yaml
It would be great to have a 1.23.x kubebuilder tools release which is not affected by the CRD issue (https://github.com/kubernetes/kubernetes/issues/107690).
> 🌱 Build kubebuilder-tools for Kubernetes 1.23.3

- Makefile
- docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller_test.go
- docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
- test/check-license.sh
- test/common.sh
Fixes https://github.com/kubernetes-sigs/kubebuilder/issues/1891 
Adds a script that iterates through all .go and .sh files and checks if a license exists in the first 4 lines. Similar script to the SDK https://github.com/operator-framework/operator-sdk/blob/master/hack/check-license.sh with some changes.
> 🌱 Add script for checking licenses

- docs/book/src/component-config-tutorial/api-changes.md
- docs/book/src/component-config-tutorial/tutorial.md
component-config-tutorial link on the book is broken :)
It's pointing to componentconfig-tutorial, missing the dash (-).
Also, some links / references are broken, I'm force pointing here to the correct location in GH repo but can investigate further how should this be done
> 📖  Fix link for component-config-tutorial

- docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
Fix incomplete instruction for validating webhook.
The current instruction about the validating webhook has incomplete
sentence which is confusing. Fixed that.
> :book: Fix incomplete instruction for validating webhook

- build/.goreleaser.yml
- build/cloudbuild_snapshot.yaml
More and more users are now using M1 chips for development so publishing
kubebuilder-tools in darwin/arm64 arch will enable them to use the
project natively on their machines without needing to apply custom ways
of solving missing dependencies.
Have seen many issues on different projects that utilize `kubebuilder` regarding missing
binaries in `darwin/arm64` arch so I thought to push this. Example Project: `operator-sdk`, `cluster-api`, etc.
- https://github.com/kubernetes-sigs/kubebuilder/issues/2505
- https://github.com/kubernetes-sigs/controller-runtime/issues/1657
- https://github.com/kubernetes-sigs/controller-runtime/issues/1809
> :sparkles: [build] Add support for darwin/arm64 arch

- docs/book/src/reference/markers.md
* Adds a note in the markers, to clarify the difference between `// +optional ` and `// +kubebuilder:validation:Optional`
* To avoid any further confusion by future contributors or users
* Fixes #2520 
- 📖 (:book:): documentation
> 📖Add info about markers

- docs/book/src/component-config-tutorial/define-config.md
It seems the link to ControllerManagerConfigurationSpec does not work and we need to use `[]` instead of `()` to navigate to the correct page. Thanks!
https://book.kubebuilder.io/component-config-tutorial/define-config.html
> 📖 Fix link for ControllerManagerConfigurationSpec

- DESIGN.md
Spotted a small typo in the DESIGN.md document. Wasn't sure if `others` or `other people` sounded better. Went with `others`.
The reason I'm making this change is that it's a simple fix in a document that many newcomers to the project are directed to.
> :book: fix typo in DESIGN.md doc

- docs/book/src/reference/watching-resources/externally-managed.md
"another (singular) is changed"  is grammatically more correct than using the plural form as the subject.
> 📖 docs: fix tiny English grammar in section "watching resources"

- docs/book/src/quick-start.md
I want to make a small improvement to the quickstart docs.
The abbreviations `CR` and `CRD` should be written out the first time they are mentioned, while atm they are written out in the middle of the document. I also think that the current writing of (CR)Custom Ressource seemed odd. Wiriting it out first followed by the abbreviation in parentheses seems to be more common and is also described as the correct way [here](https://ell.stackexchange.com/questions/18197/which-goes-in-parentheses-an-abbreviation-or-a-full-form).
Closes #2539.
> 📖 docs: fix abbreviation style in quickstart

- test/common.sh
I'm currently working on adding a PR e2e test for K8S 1.23.3. Since the CI pipeline will be using that version, it makes sense to use that version for the local e2e tests as well.
Addresses #2509
> :seedling: Other: update latest k8s version in local tests to 1.23.3

- docs/book/src/cronjob-tutorial/gvks.md
- docs/book/src/quick-start.md
As I keep on going through the kubebuilder book (which is an amazing resource btw, great job) I found some small mistakes that could be improved.
In quickstart
* Fix typo `UnDeploy`
In gvks.md
* Just use the abbreviation of CRD here as it has already been explained (just a few lines above)
* remove an unnecessary word
Since all of these are really small changes, I hope it's okay that I group them in a single PR.
>  📖 docs: add small improvements to docs

- docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go
Fix wordings in cronjob_webhook.go about validation methods for better
readability and consistency.
> :book: Fix wordings in cronjob_webhook.go

- pkg/plugins/golang/v3/init.go
Hey @camilamacedo86 🙂 
Here is the new PR. Hope this time it works absolutely fine.
> 🐛 For go/v3, ensure that the plugin can only be used with its go supported version >= 1.17 and < 1.18

- pkg/plugins/golang/v3/init.go
Allow run tool with go 1.17
We are facing issues in the prow ci because infra was updated and using go 1.18
> :seedling: allowing run tool with go 1.18 to test against prow

- docs/book/src/reference/kind-config.yaml
Update the apiVersion of the [kind-config.yaml](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/reference/kind-config.yaml) to match the current kind version's config format.
`v1alpha3` is no longer supported since kind v0.9.0
Fixes error:
`ERROR: failed to create cluster: unknown apiVersion: kind.sigs.k8s.io/v1alpha3`
* https://github.com/kubernetes-sigs/kind/releases/tag/v0.9.0
> 📖 Update kind apiVersion

- docs/book/src/SUMMARY.md
- docs/book/src/plugins/available-plugins.md
- docs/book/src/plugins/declarative-v1.md
As discussed in #2542 I'm proposing a documentation for the `declarative` plugin here. 
This is just a first draft an I'm open for suggestions as to what can be improved.
Also feel free to point out if anything seems incorrect.
I think the subcommands section should contain more detail but I'm unsure as to what else to say there.
> 📖 Add documentation for declarative plugin

- .gitignore
- OWNERS_ALIASES
- build/cloudbuild_kube-rbac-proxy.yaml
🌱 Bump kube-rbac-proxy version from v0.8.0 to v0.9.0
**Motivation**
Check if we will be able to use this helper to build/push the kube-rbac-proxy from the latest versions
> 🌱 Bump kube-rbac-proxy version from v0.8.0 to v0.9.0

- build/cloudbuild_kube-rbac-proxy.yaml
Bump : [0.11.0](https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.11.0) to generate this image
> 🌱 bump kube-rbac-proxy version version v0.11.0

- pkg/plugins/golang/v3/commons.go
- pkg/plugins/golang/v3/scaffolds/init.go
- testdata/project-v3-addon/go.mod
- testdata/project-v3-config/controllers/admiral_controller.go
- testdata/project-v3-config/controllers/captain_controller.go
- testdata/project-v3-config/controllers/firstmate_controller.go
- testdata/project-v3-config/controllers/laker_controller.go
- testdata/project-v3-config/go.mod
- testdata/project-v3-multigroup/controllers/apps/deployment_controller.go
- testdata/project-v3-multigroup/controllers/crew/captain_controller.go
- testdata/project-v3-multigroup/controllers/fiz/bar_controller.go
- testdata/project-v3-multigroup/controllers/foo.policy/healthcheckpolicy_controller.go
- testdata/project-v3-multigroup/controllers/foo/bar_controller.go
- testdata/project-v3-multigroup/controllers/lakers_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/kraken_controller.go
- testdata/project-v3-multigroup/controllers/sea-creatures/leviathan_controller.go
- testdata/project-v3-multigroup/controllers/ship/cruiser_controller.go
- testdata/project-v3-multigroup/controllers/ship/destroyer_controller.go
- testdata/project-v3-multigroup/controllers/ship/frigate_controller.go
- testdata/project-v3-multigroup/go.mod
- testdata/project-v3-v1beta1/controllers/admiral_controller.go
- testdata/project-v3-v1beta1/go.mod
- testdata/project-v3/controllers/admiral_controller.go
- testdata/project-v3/controllers/captain_controller.go
- testdata/project-v3/controllers/firstmate_controller.go
- testdata/project-v3/controllers/laker_controller.go
- testdata/project-v3/go.mod
> ✨ (go/v3) : Upgrade controller-runtime from v0.11.0 to v0.11.2 (k8s api dependencies consequently upgraded from 1.23.0 to 1.23.5)

- VERSIONING.md
- docs/book/src/SUMMARY.md
- docs/book/src/plugins/plugins-versioning.md
Move the content from We can remove the content from https://github.com/kubernetes-sigs/kubebuilder/blob/master/VERSIONING.md regards to plugin versioning to the plugin sections on the docs. 
**Motivation**
As discussed in #2569 I have added the documentation for plugins versioning. Please do let me know if any changes are required
> 📖 add to the website the plugins versioning documentation

- docs/book/src/cronjob-tutorial/testdata/project/api/v1/webhook_suite_test.go
- docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go
- docs/book/src/multiversion-tutorial/testdata/project/api/v1/webhook_suite_test.go
- docs/book/src/multiversion-tutorial/testdata/project/api/v2/webhook_suite_test.go
- docs/book/src/multiversion-tutorial/testdata/project/controllers/suite_test.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
- testdata/project-v3-config/api/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/crew/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/ship/v2alpha1/webhook_suite_test.go
- testdata/project-v3-multigroup/apis/v1/webhook_suite_test.go
- testdata/project-v3-v1beta1/api/v1/webhook_suite_test.go
- testdata/project-v3/api/v1/webhook_suite_test.go
According to pr: https://github.com/kubernetes-sigs/kubebuilder/pull/2573, 
It modifies the controller suite test, but not the webhook suite test and documentation, 
so I added the modifications.
> 🐛 fix: suite test using global cfg and update docs

- docs/book/src/SUMMARY.md
- docs/book/src/plugins/available-plugins.md
- docs/book/src/plugins/declarative-v1.md
- docs/book/src/plugins/go-v2-plugin.md
- docs/book/src/plugins/go-v3-plugin.md
As mentioned in the issue #2542 I have added the documentation for the go/v2, go/v3 and also the available plugins page.
I have tried my best to follow all the checkpoints mentioned in the issue, but please let me know if any changes are required.
> 📖 Documentation for go/v2 and go/v3 plugin

- pkg/plugins/golang/v3/scaffolds/init.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go
- testdata/project-v3-addon/README.md
- testdata/project-v3-config/README.md
- testdata/project-v3-multigroup/README.md
- testdata/project-v3-v1beta1/README.md
- testdata/project-v3/README.md
This adds a new file to the go/v3 scaffolding templates for scaffolding a README.md file. The new file can be found at `pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go`
The file `pkg/plugins/golang/v3/init.go` was modified to add the scaffolding of the README.md file to the go/v3 `init` process.
As per issue #2597 :
> This suggestion came from new users. The idea would be to provide by default a README to the projects so that, we could:
>
>   - encourage authors to create the README.md
>   - provide on the README.md the default make file targets and help skill up on how to use it
>   - additionally, for other projects such as SDK which uses KB as lib and adds on top nice helpers; would be possible for it to supplement the README with default info such as "how to build/update …
> :sparkles: (go/v3): Add README.md template to scaffolding templates

- pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go
`golanci-lint` was failing because of the code present in`pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go`. Made changes to fix the issue.
Closes: #2625
> 🌱Made changes to prevent golanci-lint failing

- docs/book/src/multiversion-tutorial/deployment.md
Currently, link for [CRD-version-pref](https://book.kubebuilder.io/multiversion-tutorial/deployment.html#kubectl-and-preferred-versions) is not renderd as markdown format.
It's showed ` [CRD docs][CRD-version-pref] ` literaly.
This is because `deployment.md` does not have cite about `CRD-version-pref`.
This PR fixes the link for `CRD-version-pref`.
I referred link URL from [this PR](https://github.com/kubernetes-sigs/kubebuilder/pull/2384/files#diff-5450fdfc6c1e06b3e8f71ecd3b3025734f6098366820c52844672587c9d194abL123).
> :book: Fix doc link for CRD-version-pref

- docs/book/src/quick-start.md
go version does not support v1.18, but docs does not expain it.
when i tried to use go v1.18.1 and kubebuilder v3.30， it has errors.
so need to add it in docs so that user can know it.
Fixes: https://github.com/kubernetes-sigs/kubebuilder/issues/2623
> 📖 add info in docs: go version v1.18+ has not been supported yet

- pkg/plugin/util/testdata/exampleFile.txt
- pkg/plugin/util/util.go
- pkg/plugin/util/util_test.go
Function [`InsertCode`](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/util/util.go#L67-L79) should return error when `strings.Index(string(contents), target)` == -1
**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2639
> 🐛(Kubebuilder lib) : Function InsertCode should return error when target string is not found in content

- build/cloudbuild.yaml
:seedling: use github token to build assets on release
**Motivation**
Try to fix the release issue where the assets have not been uploaded to the release draft.
> :seedling: use github token to build assets on release

- pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
- testdata/project-v3-config/api/v1/webhook_suite_test.go
- testdata/project-v3/api/v1/webhook_suite_test.go
Every time we create webhook for existing project, the following duplicated code are injected.
```go
err = admissionv1beta1.AddToScheme(scheme)
Expect(err).NotTo(HaveOccurred())
```
> 🐛 For go/v3 plugin: Avoid to add duplicated code fragments

- build/cloudbuild.yaml
- build/cloudbuild_local.yaml
- build/cloudbuild_snapshot.yaml
upgrade goreleaser to latest version to fix issues
Following the error faced:
```
64le/kubebuilder
:       • building                 
:  binary=/workspace/dist/kubebuilder_darwin_amd64/kubebuilder
:       • building                  binary=/workspace/dist/kubebuilder_linux_amd64/kubebuilder
:    ⨯ release failed after 39.40s error=failed to build for darwin_arm64: pkg/cli/alpha/config-gen/cmd.go:23:2: package embed is not in GOROOT (/usr/local/go/src/embed)
: /go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.6/fn/framework/parser/parser.go:7:2: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)
: 
2022/04/29 09:43:44 Step  finished
2022/04/29 09:43:45 status changed to "ERROR"
ERROR
ERROR: build step 0 "goreleaser/goreleaser:v0.147" failed: exit status 1
2022/04/29 …
```
> :seedling: upgrade goreleaser to latest version to fix issues

- build/cloudbuild.yaml
Reverts kubernetes-sigs/kubebuilder#2651
It caused the issue: 
```
Failed to trigger build: failed unmarshalling build config build/cloudbuild.yaml: illegal base64 data at input byte 0
```
> 🌱 Revert ":seedling: use github token to build assets on release"

- build/cloudbuild.yaml
- pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go
🌱 : Sync with master to prepare for 3.4.1 patch release
**Motivation**
We checked that the changes made in the cloud build do not workout so we are reverting them prior to the release 3.4.1 . See: https://github.com/kubernetes-sigs/kubebuilder/pull/2663
> 🌱 : Sync with master to prepare for 3.4.1 patch release

- build/build_kubebuilder.sh
Ignore release notes in the release to fix it
**Motivation**
See: https://github.com/kubernetes-sigs/kubebuilder/issues/2667
Currently, the releases have been not generated in the Google Cloud build because the script tries to install the go module to generate the release notes and then use it. But it cannot work. See; https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/go/README.md#note-1-workspace-and-go
Then, the idea here just stops trying to generate the release notes and update the release page automatically because it can be done easily manually. However, building the assets is more complicated. 
So, let's keep the release building the assets and adding only them to the release page so that we can add the changelog manually for now.
> :seedling: Ignore release notes in the release to fix it

- .github/workflows/verify.yml
update kubernetes-sigs/kubebuilder-release-tools from 0.1.1 to 0.2.0
closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1833
> 🌱 : update kubernetes-sigs/kubebuilder-release-tools from 0.1.1 to 0.2.0

- build/cloudbuild_snapshot.yaml
🌱 : increase the timeout for snapshot releases from master
**Tested locally** (it will fix all current issues)
```
cloud-build-local --config=build/cloudbuild_snapshot.yaml --dryrun=false --write-workspace=./cloudbuild .
2022/05/08 09:50:46 Warning: The server docker version installed (20.10.8) is different from the one used in GCB (19.03.8)
2022/05/08 09:50:46 Warning: The client docker version installed (20.10.8) is different from the one used in GCB (19.03.8)
Using default tag: latest
latest: Pulling from cloud-builders/metadata
Digest: sha256:1637a9488e321e52f86e6dfef1b7f47396c75d439e3c1566a9a85a4ac289e6ee
Status: Image is up to date for gcr.io/cloud-builders/metadata:latest
gcr.io/cloud-builders/metadata:latest
2022/05/08 09:50:56 Started spoofed metadata server …
```
> 🌱 : increase the timeout for snapshot releases from master

- pkg/plugins/golang/v2/scaffolds/internal/templates/dockerfile.go
- testdata/project-v2-addon/Dockerfile
- testdata/project-v2-multigroup/Dockerfile
- testdata/project-v2/Dockerfile
The ` GO111MODULE=on ` was removed from go/v2 with the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/2507
However, projects scaffolds with go/v2 are using golang 1.13 which requires this option
> :bug: (go/v2) fix issue introduced by removing the GO111MODULE=on from Dockerfile

- RELEASE.md
update RELEASE doc to provide the info about how the releases are done
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2580
> :book: update RELEASE doc to provide the info about how the releases are done

- build/cloudbuild_snapshot.yaml
increase goreleaser for snapshot timeout in 30 min 
**Motivation**
Ensure that snapshot releases can run succeffuly on google cloud
> :seedling: increase goreleaser for snapshot timeout in 30 min

- .github/workflows/apidiff.yml
- .github/workflows/lint.yml
- .github/workflows/unit-tests.yml
- test/check-docs-only.sh
There is no need of running all jobs when the changes are only in docs. This PR skips the github actions which are not required in those cases.
**Examples :** 
PR making changes in go files runs all tests: https://github.com/NikhilSharmaWe/kubebuilder/pull/31
PR making changes in md files skip jobs which are not required: https://github.com/NikhilSharmaWe/kubebuilder/pull/30
Fixes Part of: #2591
> 🌱 [ci]: Skipping jobs which are not required when the changes are in only docs

- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/controller_manager_config.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
- testdata/project-v3-addon/config/manager/controller_manager_config.yaml
- testdata/project-v3-addon/main.go
- testdata/project-v3-config/config/manager/controller_manager_config.yaml
- testdata/project-v3-multigroup/config/manager/controller_manager_config.yaml
- testdata/project-v3-multigroup/main.go
- testdata/project-v3-v1beta1/config/manager/controller_manager_config.yaml
- testdata/project-v3-v1beta1/main.go
- testdata/project-v3/config/manager/controller_manager_config.yaml
- testdata/project-v3/main.go
> ✨(kustomize/v1, go/v3) : Add new LeaderElectionReleaseOnCancel as true option commented to let users know when they can use it

- docs/book/src/plugins/kustomize-v1.md
- pkg/plugins/common/kustomize/v1/init.go
(kustomize/v1) add validation to let users know when the architecture used to run the plugin is not supported
**Motivation**
We have seen many users get stuck. So, the idea here is clarifying for contributors, KB lib consumers and end-users what are the current support architectures by kustomize/v1. Example: https://github.com/operator-framework/operator-sdk/issues/5785
> :sparkles: (kustomize/v1) add validation to let users know when the architecture used to run the plugin is not supported

- build/cloudbuild_tools.yaml
Bumps Kubernetes version to v1.24.1
> 🌱 Build kubebuilder-tools for Kubernetes 1.24.1

- build/thirdparty/darwin/Dockerfile
- build/thirdparty/linux/Dockerfile
For kubebuilder-tools:
- upgrade the go version from 1.17 to 1.18, 
- alphine image from 3.8 to 3.16 
- etc from v3.5.1 to v3.5.4
**motivation**
solve tech-debts
solve issue to build the kubebuilder tools for k8s 1.24.1, see:
```
Step #0: Step 12/21 : RUN make WHAT=cmd/kube-apiserver &&     cp _output/local/bin/${KUBE_BUILD_PLATFORMS}/kube-apiserver $DEST
Step #0:  ---> Running in 9877f1b79125
Step #0: 
Step #0: Detected go version: go version go1.17.11 linux/amd64.
Step #0: Kubernetes requires go1.18.1 or greater.
Step #0: Please install go1.18.1 or later.
Step #0: 
Step #0: !!! [0607 09:16:49] Call tree:
Step #0: !!! [0607 09:16:49]  1: /kubernetes/hack/lib/golang.sh:787 kube::golang::setup_env(...)
Step #0: !!! [0607 09:16:49]  2: hack/make-rules/build.sh:27 …
```
> 🌱 For kubebuilder-tools, upgrade go version from 1.17 to 1.18, alphine image from 3.8 to 3.16 and etcd from v3.5.1 to v3.5.4

- pkg/plugins/golang/v3/scaffolds/init.go
- testdata/project-v3-addon/Makefile
- testdata/project-v3-addon/config/crd/bases/crew.testproject.org_admirals.yaml
- testdata/project-v3-addon/config/crd/bases/crew.testproject.org_captains.yaml
- testdata/project-v3-addon/config/crd/bases/crew.testproject.org_firstmates.yaml
- testdata/project-v3-config/Makefile
- testdata/project-v3-config/config/crd/bases/crew.testproject.org_admirals.yaml
- testdata/project-v3-config/config/crd/bases/crew.testproject.org_captains.yaml
- testdata/project-v3-config/config/crd/bases/crew.testproject.org_firstmates.yaml
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3-multigroup/config/crd/bases/crew.testproject.org_captains.yaml
- testdata/project-v3-multigroup/config/crd/bases/fiz.testproject.org_bars.yaml
- testdata/project-v3-multigroup/config/crd/bases/foo.policy.testproject.org_healthcheckpolicies.yaml
- testdata/project-v3-multigroup/config/crd/bases/foo.testproject.org_bars.yaml
- testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_krakens.yaml
- testdata/project-v3-multigroup/config/crd/bases/sea-creatures.testproject.org_leviathans.yaml
- testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_cruisers.yaml
- testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_destroyers.yaml
- testdata/project-v3-multigroup/config/crd/bases/ship.testproject.org_frigates.yaml
- testdata/project-v3-multigroup/config/crd/bases/testproject.org_lakers.yaml
- testdata/project-v3-with-kustomize-v2/Makefile
- testdata/project-v3-with-kustomize-v2/config/crd/bases/crew.testproject.org_admirals.yaml
- testdata/project-v3-with-kustomize-v2/config/crd/bases/crew.testproject.org_captains.yaml
- testdata/project-v3-with-kustomize-v2/config/crd/bases/crew.testproject.org_firstmates.yaml
- testdata/project-v3/Makefile
- testdata/project-v3/config/crd/bases/crew.testproject.org_admirales.yaml
- testdata/project-v3/config/crd/bases/crew.testproject.org_captains.yaml
- testdata/project-v3/config/crd/bases/crew.testproject.org_firstmates.yaml
**description**
:sparkles: (go/v3) upgrade controller-gen from 0.8.0 to 0.9.0
Follow up of: https://github.com/kubernetes-sigs/kubebuilder/pull/2679
Motivates by: https://github.com/kubernetes-sigs/kubebuilder/issues/2559
> ⚠️ : (go/v3) upgrade controller-gen from 0.8.0 to 0.9.0

- build/cloudbuild_kube-rbac-proxy.yaml
Bump : [v0.12.0](https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.12.0) to generate this image.
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>
> Bump kube-rbac-proxy to v0.12.0

- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/config.go
- pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go
- testdata/project-v3-addon/config/manager/manager.yaml
- testdata/project-v3-config/config/manager/manager.yaml
- testdata/project-v3-multigroup/config/manager/manager.yaml
- testdata/project-v3-v1beta1/config/manager/manager.yaml
- testdata/project-v3-with-kustomize-v2/config/manager/manager.yaml
- testdata/project-v3/config/manager/manager.yaml
**description**
:seedling: remove the trailing-spaces
**Motivation**
Ansible operators fails in in the molecule tests with
> :seedling: remove the trailing-spaces

- docs/book/src/migration/manually_migration_guide_v2_v3.md
- docs/book/src/migration/migration_guide_v2tov3.md
- docs/book/src/migration/v2vsv3.md
Upgrade migration guide accordingly with the latest changes
**Motivation**
Solve tech-debt
Warning users to not use v1beta1 or go/v2 plugin
> :book: update migration guide

- RELEASE.md
update the release doc and steps to ensure that is aligned with the other projects
**Motivation**
Before `3.5.*` release this project was released based on `MAJOR`. The change on the 
the process was done to ensure that we have an aligned process under the org (similar to `controller-runtime` and 
`controller-tools`) and to make easier the process to produce patch releases.
> :book: update the release doc and steps to ensure that is aligned with the other projects

- OWNERS_ALIASES
Adding myself to the reviewer's list
**Motivation**
Get the permissions
> 🌱 adding jmrodri as reviewer

- pkg/plugins/common/kustomize/v2/plugin.go
- testdata/project-v3-with-kustomize-v2/Makefile
:sparkles: (kustomize/v2-alpha) bump kustomize version from v4.5.3 to v4.5.5
We provide it with the latest one available
> :sparkles: (kustomize/v2-alpha) bump kustomize version from v4.5.3 to v4.5.5

- CONTRIBUTING.md
Hi, 
I noticed that the kustomize install link in the contributing doc was broken, so this commit replaces it with a working link.
> 📖 Fix broken kustomize install link

- docs/book/src/quick-start.md
Remove the suggestion to call kustomize/v2-alpha,base.go.kubebuilder.io/v3 directly.
We probably will create a bundle go/v4-alpha and we do not want to support afterwards the workaround 
or provide migration steps from it.
> :book: quick start updates

- pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/certmanager/certificate.go
- pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablecainjection_patch.go
- pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/enablecainection_patch.go
- pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
- testdata/project-v3-with-kustomize-v2/config/certmanager/certificate.yaml
- testdata/project-v3-with-kustomize-v2/config/crd/patches/cainjection_in_admirals.yaml
- testdata/project-v3-with-kustomize-v2/config/crd/patches/cainjection_in_captains.yaml
- testdata/project-v3-with-kustomize-v2/config/crd/patches/cainjection_in_firstmates.yaml
- testdata/project-v3-with-kustomize-v2/config/default/kustomization.yaml
- testdata/project-v3-with-kustomize-v2/config/default/webhookcainjection_patch.yaml
- Replace every instance of $(SOMETHING) with any arbitrary placeholder value.
- Replace: `bases:` with `resources:`
- Replace:
```#commonLabels:
```
With:
```
#labels:
#- includeSelectors: true
```
> :sparkles: (kustomize/v2-alpha) fixes in the scaffold to follow the changes in the MAJOR release of kustomize

- test/e2e/kind-config-v1.18.yaml
- test/e2e/kind-config-v1.19.yaml
- test/e2e/setup.sh
- test/e2e/v3/plugin_cluster_test.go
Closes #2731 
This addresses https://github.com/kubernetes-sigs/kubebuilder/pull/2723#discussion_r898208391
Move to using an explicit Token generated for the SA by invoking the `kubectl create token` command.
> :seedling: GIT-2731: enable TokenRequest for ServiceAccount token generation

- pkg/cli/options.go
- pkg/cli/options_test.go
- pkg/plugin/external/types.go
- pkg/plugins/external/api.go
- pkg/plugins/external/edit.go
- pkg/plugins/external/external_test.go
- pkg/plugins/external/helpers.go
- pkg/plugins/external/init.go
- pkg/plugins/external/webhook.go
This change implements the `BindFlags()` method for the external plugin `init`, `create api`, `create webhook`, and `edit` subcommands.
It has 2 methods in which flags can be bound:
1. An external plugin defines a `flags` subcommand that accepts boolean flags to represent which subcommand to return flags to Kubebuilder for. (ex: `flags --init`)
2. All flags passed by a user are bound when an external plugin is used. This method also adds a default usage message to the flags stating that Kubebuilder was unable to verify the flags passed by a user and suggests that the user consult the external plugin documentation for more information.
The logic flow that is taken is:
```mermaid
flowchart TD
A[BindFlags] --> B[Request Flags from External Plugin];
B ----> C{Error?};
C -- Yes --> D[Parse all …
```
> :sparkles: external plugins(plugin phase 2): add support to pass CLI flags

- build/thirdparty/darwin/Dockerfile
This patch updates the Dockerfile used to produce the kubebuilder asset bundle to support darwin/arm64, as well as possible, other, future OS/Architecture combinations, with support for building etcd as well.
This patch will build kubectl and etcd from source in the case either is not found using their prebuilt URL locations.
Testing includes:
1. Building the asset bundle:
```shell
$ docker build --build-arg 'ARCH=arm64' --build-arg 'KUBERNETES_VERSION=v1.24.2' -t envtest-darwin-arm64 .
[+] Building 148.1s (17/17) FINISHED                                                                                
=> [internal] load build definition from Dockerfile                                                           0.0s
=> => transferring dockerfile: 2.48kB …
```
> ✨ For kubebuilder-tools : add support to darwin/arm64, and other future OS/Arch asset bundles + etcd

- test/e2e/utils/test_context.go
- test/e2e/v3/generate_test.go
- test/e2e/v3/plugin_cluster_test.go
improve e2e tests to ensure that pods are restricted
**Motivation**
Ensure that pods are restricted and do not violate : 
```
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "test" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "test" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "test" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "test" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
pod/example created
```
> :seedling: improve e2e tests to ensure that pods are restricted

- pkg/plugins/golang/v3/scaffolds/init.go
The plugin responsable for define the Kustomize Version is the Kustomize one. 
If you have consumer Kubebuilder as a lib ensure that you properly get the version from the Kustomize Plugin instead of Golang base language. Note that to create helpers and/or plugin versions that are able to deal with more than on version you can, example:
```go
kustomizeVersion = kustomizecommonv1.KustomizeVersion
kustomizev2 := kustomizecommonv2alpha.Plugin{}
pluginKeyForKustomizeV2 := plugin.KeyFor(kustomizev2)
for _, pluginKey := range s.config.GetPluginChain() {
if pluginKey == pluginKeyForKustomizeV2 {
kustomizeVersion = kustomizecommonv2alpha.KustomizeVersion
break
}
}
....
&templates.Makefile{
....
KustomizeVersion:         kustomizeVersion,
....
},
```
> :bug: (API) remove KustomizeVersion const from golang plugin ( the version is defined in the kustomize plugins which is responsable for )

- pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/certmanager/kustomizeconfig.go
- pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/webhook/kustomizeconfig.go
- testdata/project-v3-with-kustomize-v2/config/certmanager/kustomizeconfig.yaml
- testdata/project-v3-with-kustomize-v2/config/webhook/kustomizeconfig.yaml
`vars` field will be deprecated in near future and we are planning to use replacements in `v2-alpha` instead of `vars`.
These changes will remove `varReference` field completely. The default config data for vars is located in the `varReference` field. There is no need to include it in `v2-alpha`
it fixes #2789 
Is this in a document that has been referenced by the configurations field because those are [transformer configurations](https://github.com/kubernetes-sigs/kustomize/blob/de5210b43a90e80c2b9511a01ac62efbb193896e/examples/transformerconfigs/README.md#transformer-configurations). **varReference are unused because we have removed all vars from the Kustomizations**. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/ …
> ✨ (kustomize/v2-alpha): remove unnecessary varReference for setup cert-manager

- docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
- pkg/cli/alpha/config-gen/templates/patches/controller-manager/01-auth-proxy.template.yaml
- pkg/cli/alpha/config-gen/testdata/componentconfig/expected.yaml
- pkg/cli/alpha/config-gen/testdata/default/expected.yaml
- pkg/cli/alpha/config-gen/testdata/enablecertmanager/expected.yaml
- pkg/cli/alpha/config-gen/testdata/enableconversionwebhooks/expected.yaml
- pkg/cli/alpha/config-gen/testdata/enableprometheus/expected.yaml
- pkg/cli/alpha/config-gen/testdata/enablewebhooks/expected.yaml
- pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
- pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
- testdata/project-v2/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-addon-and-grafana/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-config/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3-with-deploy-image/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v3/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v4-addon-and-grafana/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v4-config/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v4-multigroup/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v4-with-deploy-image/config/default/manager_auth_proxy_patch.yaml
- testdata/project-v4/config/default/manager_auth_proxy_patch.yaml
upgrade gcr.io/kubebuilder/kube-rbac-proxy from v0.12.0 to  v0.13.0
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2801
> :sparkles: upgrade gcr.io/kubebuilder/kube-rbac-proxy from v0.12.0 to  v0.13.0

- docs/book/src/component-config-tutorial/testdata/project/Makefile
- docs/book/src/cronjob-tutorial/testdata/project/Makefile
- docs/book/src/migration/manually_migration_guide_v2_v3.md
- docs/book/src/multiversion-tutorial/testdata/project/Makefile
- pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
- testdata/project-v3-addon-and-grafana/Makefile
- testdata/project-v3-config/Makefile
- testdata/project-v3-multigroup/Makefile
- testdata/project-v3-with-deploy-image/Makefile
- testdata/project-v3/Makefile
- testdata/project-v4-addon-and-grafana/Makefile
- testdata/project-v4-config/Makefile
- testdata/project-v4-multigroup/Makefile
- testdata/project-v4-with-deploy-image/Makefile
- testdata/project-v4/Makefile
I just created a new project with kubebuilder, and got confused over a comment in the scaffolded Makefile:
````
````
This was added in https://github.com/kubernetes-sigs/kubebuilder/pull/2149, but later replaced with `go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest`.
>  :bug: (go/v3): remove a no longer applied comment from Makefile

- pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
- pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
- test/e2e/deployimage/plugin_cluster_test.go
- testdata/project-v3-with-deploy-image/config/rbac/role.yaml
- testdata/project-v3-with-deploy-image/controllers/busybox_controller.go
- testdata/project-v3-with-deploy-image/controllers/memcached_controller.go
- testdata/project-v3-with-deploy-image/main.go
- testdata/project-v4-with-deploy-image/config/rbac/role.yaml
- testdata/project-v4-with-deploy-image/controllers/busybox_controller.go
- testdata/project-v4-with-deploy-image/controllers/memcached_controller.go
- testdata/project-v4-with-deploy-image/main.go
Add finalizers for the Custom Resource created for deleting the deployment under before deleting the CR.
> ✨deploy-image/v1-alpha: add finalizers for the Custom Resource created

- pkg/machinery/funcmap.go
- pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
- pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
- testdata/project-v3-with-deploy-image/config/manager/manager.yaml
- testdata/project-v3-with-deploy-image/controllers/busybox_controller.go
- testdata/project-v3-with-deploy-image/controllers/memcached_controller.go
- testdata/project-v4-with-deploy-image/config/manager/manager.yaml
- testdata/project-v4-with-deploy-image/controllers/busybox_controller.go
- testdata/project-v4-with-deploy-image/controllers/memcached_controller.go
This PR works on scaffolding an env var for storing the image informed while creating the API by `deploy-image/v1alpha` plugin, and that env var can be used to get the image where it is needed.
> ✨deploy-image/v1alpha: add env var for storing the image name

- docs/book/src/plugins/grafana-v1-alpha.md
- pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
- pkg/plugins/optional/grafana/v1alpha/scaffolds/init.go
- pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/resources.go
- testdata/project-v3-addon-and-grafana/grafana/controller-resources-metrics.json
- testdata/project-v4-addon-and-grafana/grafana/controller-resources-metrics.json
Add function of Grafana plugin to scaffold new dashboard manifest of cpu&memory. Changes include:
- Add scaffolder to generate manifest
- Update e2e test cases to cover the feature
- Documentation of the new feature
Enhance the function of Grafana plugin to observe controller in multiple perspectives.
> :sparkles: (grafana/v1-alpha) : add a new dashboard to show CPU and Memory usage for Pods

- pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
- pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
- pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
- testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go
- testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go
This PR makes corrections in the `**controller_test.go` scaffolds for the `deploy-image/v1alpha` plugin.
> ✨deploy-image/v1alpha: made corrections in **controller_test.go scaffolds

- pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go
- testdata/project-v3-with-deploy-image/api/v1alpha1/busybox_types.go
- testdata/project-v3-with-deploy-image/api/v1alpha1/memcached_types.go
- testdata/project-v3-with-deploy-image/config/crd/bases/example.com.testproject.org_busyboxes.yaml
- testdata/project-v3-with-deploy-image/config/crd/bases/example.com.testproject.org_memcacheds.yaml
- testdata/project-v4-with-deploy-image/api/v1alpha1/busybox_types.go
- testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_types.go
- testdata/project-v4-with-deploy-image/config/crd/bases/example.com.testproject.org_busyboxes.yaml
- testdata/project-v4-with-deploy-image/config/crd/bases/example.com.testproject.org_memcacheds.yaml
Adds markers for the size spec for the Custom Resource in the `deploy-image/v1alpha` plugin which will set constraints for its value.
> ✨deploy-image/v1alpha: add validation markers for size spec

- pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
- testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go
- testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go
- testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go
- testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go
Provide implementation on the controller test which is checking the controller reconciliation
> :sparkles: (deploy.image/v1-alpha): improve controller-test reconciliation
