kubernetes-sigs/kubebuilder

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go, testdata/project-v3-with-deploy-image/controllers/busybox_controller.go, testdata/project-v3-with-deploy-image/controllers/memcached_controller.go, testdata/project-v4-with-deploy-image/controllers/busybox_controller.go, testdata/project-v4-with-deploy-image/controllers/memcached_controller.go
- Improve the logs
- Improve layout to not fail in lll lint checker
- simplify calls with errors ( if err := action; err != nil )
- order the imports
- return an error if be unable to create the deployment to re-queue
- small improvements in the comments
=> :sparkles: (deployimage/v1-alpha): small improvements on the controller scaffold

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go, testdata/project-v3-with-deploy-image/controllers/busybox_controller.go, testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go, testdata/project-v3-with-deploy-image/controllers/memcached_controller.go, testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go, testdata/project-v4-with-deploy-image/controllers/busybox_controller.go, testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go, testdata/project-v4-with-deploy-image/controllers/memcached_controller.go, testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go
This PR fixes some issues which are:
a) The scenario where we should only add the Recorder to be passed to the controller when the API/controller was scaffolded with the plugin
b) The scenario where we are scaffolding an extra }} in the controller by mistake in the logs 
c) Fix log typo
=> :bug: deploy-image/v1alpha: fix small issues

docs/book/src/plugins/grafana-v1-alpha.md, pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go, testdata/project-v3-addon-and-grafana/grafana/controller-runtime-metrics.json, testdata/project-v4-addon-and-grafana/grafana/controller-runtime-metrics.json
- Add panels of Work Queue status in the controller-runtime dashboard
- Group  panels into different rows
Enhance the dashboard from grafana plugin with more panels in different perspective.
=> :sparkles:: Add workqueue panels to dashboard

docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/migration/manually_migration_guide_v2_v3.md, docs/book/src/multiversion-tutorial/testdata/project/Makefile, pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go, testdata/project-v2/Makefile, testdata/project-v3-addon-and-grafana/Makefile, testdata/project-v3-config/Makefile, testdata/project-v3-multigroup/Makefile, testdata/project-v3-with-deploy-image/Makefile, testdata/project-v3/Makefile, testdata/project-v4-addon-and-grafana/Makefile, testdata/project-v4-config/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4/Makefile
Change the Makefile targets controller-gen and envtest no longer try to download the binary when they can be found in the project/bin directory.
Closes: #2843
=> :bug: (go/v3, go/v4-alpha): fix makefile targets do not re-install binaries when they are found in the project bin directory

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go, testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go, testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go, testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go, testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go
Thank you for your nice examples!! (linked from https://github.com/kubernetes-sigs/kubebuilder/discussions/2836#discussioncomment-3259637)
I just removed unnecessary if check
=> 🐛 Nit: trim unncessary if check in templates/controllers/controller-test.go

README.md
Reverts kubernetes-sigs/kubebuilder#2848
Prior to do the release
=> :seedling: Add back info about Apple Silicon support to the README ( prior release )

README.md, docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/migration/manually_migration_guide_v2_v3.md, docs/book/src/multiversion-tutorial/deployment.md, docs/book/src/multiversion-tutorial/testdata/project/Makefile, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go, pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go, testdata/project-v2/Makefile, testdata/project-v3-addon-and-grafana/Makefile, testdata/project-v3-addon-and-grafana/grafana/controller-runtime-metrics.json, testdata/project-v3-config/Makefile, testdata/project-v3-multigroup/Makefile, testdata/project-v3-with-deploy-image/Makefile, testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go, testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go, testdata/project-v3/Makefile, testdata/project-v4-addon-and-grafana/Makefile, testdata/project-v4-addon-and-grafana/grafana/controller-runtime-metrics.json, testdata/project-v4-config/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go, testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go, testdata/project-v4/Makefile
update branch release-3.6 with the latest changes made on master to prepare it for the next release
=> 🌱 : update branch release-3.6 with the latest changes made on master to prepare it for the next release

docs/book/src/plugins/kustomize-v2-alpha.md
I noticed that the docs have plain hyperlinks instead of the expected formatted ones on this page, so just making a PR to fix it:
> If you want to use [replacements][https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/] since [vars][https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/vars/] are deprecated and might be removed soon
=> 📖 fix broken hyperlinks in kustomize/v2-alpha docs

docs/book/src/plugins/deploy-image-plugin-v1-alpha.md
Added a note in deploy-image plugin documentation that users should keep in mind while running the operator locally.
=> 📖adding a note in deploy-image plugin doc

docs/book/src/reference/metrics.md
Fixes #2646.
Right now, when following the [documentation](https://book.kubebuilder.io/reference/metrics.html#exporting-metrics-for-prometheus) to export metrics for Prometheus, only a `ServiceMonitor` is created, but Prometheus does not have permission to access this resource. 
To fix this issue, this PR adds a `ClusterRole` and a `ClusterRoleBinding` for Prometheus `ServiceAccount` to be able to access the needed resources.
=> :book: describe need of RBAC permissions to allow Prometheus Operator to have access to the metrics

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go, testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go, testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go, testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go, testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go
Added a todo comment for users in controller_test.go file for deploy-image/v1-alpha plugin, highlighting the limitations of the envtest.
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2856
=> ✨deploy-image/v1-alpha: add a todo comment for users stating envtest limitations

docs/book/src/reference/envtest.md
Envtest doesn't support deletion of namespaces, and this can trip people up from time to time.  Added a description of why and how to deal with test isolation.
I added this after a member suggested I wrote a FAQ entry.  I felt this made more sense to place directly in the book where envtest is being discussed.
I have not added the code sample yet, since I wanted to get some feedback on if this was too much detail.
=> :book: Adds section on envtest limitations

docs/book/src/reference/envtest.md
Replaced "Namesapce" with "Namespace"
Not much to say here except sorry for the extra work.  Somewhat important because it will be a hypertext target.
=> 📖 Fix typo in headline "Namespace"

.github/workflows/lint.yml, Makefile
Signed-off-by: Bryce Palmer <bpalmer@redhat.com>
- Update `golangci/golangci-lint-action` to `v3`
- Update `golangci-lint` version used to `v1.48`
- Add `actions/setup-go@v3` to setup Go for the `golangci/golangci-lint-action` action
=> :seedling: update golangci-lint action

pkg/cli/options.go
This mini-PR simply fixes the Plugins Root Directory for darwin hosts for external Plugins.
Without this change the Plugin Discovery will always look in a non-existing Library Directory, causing the Lookup to permanently fail. A suggestion here would be to introduce the "Lookup Plugins" command that was discussed previously in the Discussion around https://github.com/kubernetes-sigs/kubebuilder/issues/2600 to also make this debuggable without having to change log messages or introducing a cli debug flag
=> :bug: "Application Support" whitespace for mac plugins

docs/book/src/reference/kind.md
The word "master" is deprecated to represent the control-plane node. Synched with [Kubernetes website]( https://kubernetes.io/docs/home/) for consistency.
/kind cleanup
Fixes #1582
=> :book:  Replace "master" with "control-plane"

pkg/plugins/external/external_test.go, pkg/plugins/external/helpers.go
This fixes #2809 by introducing filter functions for plugin arguments. It currently includes two filter functions, one for the already existing implicit filter of "--help" and one for the GVK filter with "--group", "--version", "--kind". It is an arbitrary filter function so it can later on also support other filter requirements if necessary.
Tests are adjusted, but I added some tests for the filter functions. The existing helper Test for the Binding of Args I expanded to make use of the filter Functions as this is the use case in the actual method call in the CLI.
=> :bug: Add external plugin arg filter funcs and add filters for "--group", "--version", "--kind"

pkg/cli/alpha/config-gen/cmd.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
This Mini-PR fixes the go `fmt` complains from run https://github.com/kubernetes-sigs/kubebuilder/actions/runs/2876147334 by running format over them.
=> 🌱  fix `fmt` lint issues on `master`

test/e2e/deployimage/plugin_cluster_test.go
In the e2e tests for `deploy-image/v1-alpha`, label `app.kubernetes.io/name` for pod and deployment for the Kind looks for value `string.ToLower(kbc.Kind)` but it should be only `kbc.Kind`. This PR is made to fix that.
See https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-with-deploy-image/controllers/memcached_controller.go#L385 for example, we add `Memcached` not `memcached` to label `app.kubernetes.io/name`.
=> 🌱  deploy-image/v1-alpha e2e tests: fix the value of label app.kubernetes.io/name e2e tests use the Kind without be in lower case

pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go, testdata/project-v3-addon-and-grafana/Makefile, testdata/project-v3-config/Makefile, testdata/project-v3-multigroup/Makefile, testdata/project-v3-with-deploy-image/Makefile, testdata/project-v3/Makefile, testdata/project-v4-addon-and-grafana/Makefile, testdata/project-v4-config/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4/Makefile
The controller runtime allows us to check out the binary assets to [an explicit location ](https://github.com/kubernetes-sigs/controller-runtime/blob/bcde6f084dd15ef93bee2a2e4668184e7472eddd/tools/setup-envtest/main.go#L50) [instead of specific locations on each OS](https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest#where-does-it-put-all-those-binaries). 
It's clear and obvious where the binaries are downloaded and would get automatically cleaned up if run in a CI pipeline. Additionally, other binaries are downloaded to the same `LOCALDIR`
Motivates by the comment: https://github.com/kubernetes-sigs/kubebuilder/issues/2389#issuecomment-1211133745
=> :sparkles: feat(envtest): checkout k8s binaries to explicit location

.github/workflows/lint.yml, Makefile
Updates the lint Makefile target updating the golangci-lint version from `1.48.0` to `1.49.0`. 
EDIT: First pr failed due to short description. Hopefully better now. Sorry for retrigger.
=> 🌱 Bump golangci-lint version (1.48.0 -> 1.49.0)

pkg/machinery/interfaces.go, pkg/machinery/mixins.go, pkg/machinery/scaffold.go, pkg/machinery/scaffold_test.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/resources.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go, testdata/project-v3-addon-and-grafana/grafana/controller-resources-metrics.json, testdata/project-v4-addon-and-grafana/grafana/controller-resources-metrics.json
This change add `SetDelim()` and `GetDelim()` to `Template` interface, give the developer the ability to config an alternative delimiters (by default is `{{` and `}}`) for template parsing.
The current `controllerResourcesTemplate`, `controllerRuntimeTemplate` provided as a grafana dashboard with json format, and it contains some annotations syntax which use `{{ }}` and it's collide with default delimiters for template parsing. 
In order to parse correctly, at the moment, the template data have to write like this:
```
"legendFormat": "P90 {{"{{name}}"}} {{"{{instance}}"}} "
```
It is quite confusing to developers at first glance, and ever harder to do further encoding process like `json.Valid`, `json.Compact`.
By providing an alternative delimiters allow developer write template content …
=>  ✨ Allow template to change parser delimiters

docs/book/src/reference/envtest.md
The controller runtime allows us to check out the binary assets to [an explicit location ](https://github.com/kubernetes-sigs/controller-runtime/blob/bcde6f084dd15ef93bee2a2e4668184e7472eddd/tools/setup-envtest/main.go#L50)[instead of specific locations on each OS](https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest#where-does-it-put-all-those-binaries). Updating the envtest docs to specify the new binary location defined in the [Makefile](https://github.com/kubernetes-sigs/kubebuilder/blob/2e93b289979c226ebd499a3e64ee6566ca5c12a2/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go#L118). 
Closes #2389
=> :book: feat(docs): update envtest docs

.golangci.yml
There are 3 linters that are enabled in golangci-lint today which causes warnings when running the linter. 
```
make lint
(...)
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
```
This pr removes the deprecated linters. Since `unused` is enabled no additional linters are enabled.
https://golangci-lint.run/usage/linters/
=> 🌱 Remove deprecated linters: deadcode, varcheck, structcheck

docs/book/src/plugins/grafana-v1-alpha.md, pkg/plugin/util/util.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/init.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/custom.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/custom_metrics.go, test/e2e/grafana/e2e_suite_test.go, test/e2e/grafana/generate_test.go, test/e2e/setup.sh, test/e2e/utils/test_context.go, testdata/project-v3-addon-and-grafana/grafana/custom-metrics/config.yaml, testdata/project-v4-addon-and-grafana/grafana/custom-metrics/config.yaml
This is the experimental practice to see how possible if we can bring dashboards for custom metrics through the Grafana Plugin.
The user can add the desired metrics in `grafana/custom-metrics/config.yaml`:
```yaml
---
customMetrics: []
```
(If you execute the plugin for the first time(either by `init` or `edit`), the above config template will be automatically generated.)
The plugin triggered by `edit` subcommand will read the `config.yaml` and generate `grafana/custom-metrics/custom-metrics-dashboard.json`, which can be directly import in the Grafana Web UI.
Users get the config entry when initialize the project or introduce the `grafana-plugin` for the first time:
```shell
kubebuilder init --plugins=grafana.kubebuilder.io/v1-alpha
kubebuilder edit …
```
=> :sparkles: Experimental practice to scaffold dashboard manifest for custom metrics

build/cloudbuild_tools.yaml
Updates the `tools-releases` branch Kubernetes version to (1.24.2 -> 1.25.0).
Part of #2908
cc @sbueringer @camilamacedo86
=> :sparkles: Update Kubernetes version (1.24.2 -> 1.25.0)

build/thirdparty/darwin/Dockerfile, build/thirdparty/linux/Dockerfile
For darwin update the builder image to `golang:1.19` since it's needed for Kubernetes 1.25
For linux update the final image container to `alpine:3.16` (latest) to be the same as current darwin
No etcd update since it's already latest and greatest: https://github.com/etcd-io/etcd/releases?q=3.5&expanded=true
=> ✨ Update linux and darwin Dockerfile baseimages

docs/book/src/quick-start.md, pkg/plugins/golang/v3/init.go
This PR will update the documentation to indicate that the latest release of `kubebuilder` requires `Go 1.18+` in order to build the needed manifest files.
Fixes #2902
=> 📖 feat(docs): golang version minimum is now go1.18

CONTRIBUTING.md
This PR updates the contribution guide to notify the k8s version policy for testing.
Helps resolve https://github.com/kubernetes-sigs/kubebuilder/issues/2921
=> 📖 docs: guide to manage k8s version for testing

docs/book/utils/litgo/literate.go, docs/book/utils/plugin/plugin.go, pkg/cli/alpha/config-gen/cmd.go, pkg/cli/alpha/config-gen/types.go, pkg/cli/cli_test.go, pkg/plugin/util/util.go, pkg/plugins/golang/declarative/v1/init.go, pkg/plugins/golang/v3/commons.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go, test/e2e/utils/test_context.go
This PR fixes the following error by removing deprecated io/ioutil and using os, io instead.
```
pkg/cli/alpha/config-gen/cmd.go:22:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
"io/ioutil"
```
- Update ioutil.ReadAll => io.ReadAll
- Update ioutil.ReadFile => os.ReadFile
- Update ioutil.WriteFile => os.WriteFile
Helps resolve https://github.com/kubernetes-sigs/kubebuilder/issues/2928
=> 🌱 :  (fix golint) - Remove deprecated io/ioutil and use os, io instead

.github/workflows/apidiff.yml
Use the same version of joelanford/go-apidiff in the Makefile and github workflow. 
In the Makefile version 0.4.0 is used:
https://github.com/kubernetes-sigs/kubebuilder/blob/d67473979371c60b213742a9a7f19cf67b6bab43/Makefile#L95
=> 🌱 Use same joelanford/go-apidiff version (v0.4.0) in workflow and Makefile

.github/workflows/release.yml, RELEASE.md
Currently, we have been doing the releases manually because the token added to allow us to update the release draft with the manifests when it is done via the google cloud no longer works.
Therefore, this PR sort it out by moving to GitHub actions as discussed in the past
See: the built is working just the publish fails because it was done from the fork: https://github.com/camilamacedo86/kubebuilder/actions/runs/3043272293/jobs/4902353947#step:7:88
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2413
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2667
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2768
=> :seedling: fix release by adding github action

build/thirdparty/darwin/Dockerfile, build/thirdparty/linux/Dockerfile
Update etcd bin from 3.5.4 to 3.5.5 (envtools)
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2946
=> :sparkles: Update etcd bin from 3.5.4 to 3.5.5 (envtools)

docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
The currently shown code leads to a nil pointer.
As it's shown on the website as an example, it's first not clear that the documentation is wrong.
Fixes #2508.
=> :book: Fix nil pointer in Finalizer example

docs/README.md
Notify users to install `controller-gen` for building book locally.
Resolve: https://github.com/kubernetes-sigs/kubebuilder/issues/2955
=> 📖: notify `controller-gen` installation for building book 

docs/book/src/cronjob-tutorial/running.md
Updated the docs with the `export` keyword to enable the webhook. 
As the controller is failing because the webhook is not exported correctly.  
So, the following changes are updated in the kubebuilder - https://book.kubebuilder.io/cronjob-tutorial/running.html#running-webhooks-locally so webhooks can be exported before the make run -
```
export ENABLE_WEBHOOKS=false
make run
```
Fixes: #2837
=> :book: Updated the docs with the export keyword to enable the webhook.

.github/ISSUE_TEMPLATE/feature_request.yaml, build/.goreleaser.yml
Updates the kubernetes version from 1.24.1 -> 1.25.0 in the kubebuilder cli pipeline to align it with the rest of the repo.
I also sneaked in a minor spelling fix that I noticed but felt excessive to give a separate pr.
=> :sparkles: update kubebuilder cli kubernetes version

docs/book/src/quick-start.md
``` curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$\(go env GOOS)/$\(go env GOARCH) ```
Error
syntax error near unexpected token `)'
=> 🐛 (:bug:): bugfix fixing the kubebuilder install locally curl request

.github/dependabot.yml
add dependency bot updates
Help us check what is outdated
=> 🌱 add dependency bot updates

README.md, build/thirdparty/windows/Dockerfile
This PR adds support for Windows builds in tools-releases, so that these can be used via setup-envtest. If this is merged, it will require enabling it in the GCP Cloud Build (I have no experience with that part).
I'm currently using the branch behind this PR in https://github.com/kluctl/kubebuilder-tools-releases-windows, which simply clones my kubebuilder fork, checks out the tools-releases-windows branch and manually runs the Docker build for the Windows release. I do this to trick setup-envtest into accepting the downloaded binaries when invoking it with `-i`, which will then later allow me to simply drop the manual downloading. You can find all this here: https://github.com/kluctl/kluctl/blob/main/Makefile#L60.
When this PR gets merged and GCP Cloud Build is updated as well, I will …
=> feat: Add windows support to tools-releases

pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/config.go, pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/manager/config.go, testdata/project-v3-addon-and-grafana/config/manager/manager.yaml, testdata/project-v3-config/config/manager/manager.yaml, testdata/project-v3-multigroup/config/manager/manager.yaml, testdata/project-v3-with-deploy-image/config/manager/manager.yaml, testdata/project-v3/config/manager/manager.yaml, testdata/project-v4-addon-and-grafana/config/manager/manager.yaml, testdata/project-v4-config/config/manager/manager.yaml, testdata/project-v4-multigroup/config/manager/manager.yaml, testdata/project-v4-with-deploy-image/config/manager/manager.yaml, testdata/project-v4/config/manager/manager.yaml
There are 2 places where we must revert the sign which we missed as part of old PR https://github.com/kubernetes-sigs/kubebuilder/pull/2826
```
{{- if not .ComponentConfig }}
args:
- --leader-elect
{{- end }}
```
it should be now modified to
```
{{- if .ComponentConfig }}
args:
- --leader-elect
{{- end }}
```
As of now, we are scaffolding the controller_manager_config.yaml file only when the flag --component-config is passed.
This fixes #3009
=> 🐛: fixed bug for component-config flag

pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go, testdata/project-v3-addon-and-grafana/Makefile, testdata/project-v3-config/Makefile, testdata/project-v3-multigroup/Makefile, testdata/project-v3-with-deploy-image/Makefile, testdata/project-v3/Makefile, testdata/project-v4-addon-and-grafana/Makefile, testdata/project-v4-config/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4/Makefile
Fixes #3016
In the doc of xxx_types.go, the comment said:
```
Important: Run "make" to regenerate code after modifying this file
```
But after the spec and status struct modified, run `make` did not generate manifests fields.
So this PR update `make` (default to `make build`) with manifests generation.
Plugins go/v3 and go/v4-alpha are updated.
=> :sparkles: Update `make build` cmd with manifests generation

docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_types.go, docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller_test.go, docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_types.go, docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_types.go, pkg/plugin/util/testdata/exampleFile.txt
Issue: https://github.com/kubernetes-sigs/kubebuilder/issues/3031
Update tutorial to use the batchv1 API version for cronjob.
=> 📖 update cronjob to use batchv1 api instead of v1beta1

.golangci.yml, pkg/plugins/external/api.go, pkg/plugins/external/edit.go, pkg/plugins/external/external_test.go, pkg/plugins/external/init.go, pkg/plugins/external/webhook.go, pkg/plugins/golang/declarative/v1/init.go
Enables the revive unused-parameter check and fixes all the findings. This is one of the recommended checks to have enabled but wasn't enabled in #3034 due to many findings.
=> 🌱 Enable revive unused-parameter check and fix findings

docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
Change `these is` to `these are` in a comment in cronjob_controller.go.
The verb `is` is singular, whereas `are` is plural. The comment is there to document iterating over multiple failed jobs. So, it would be appropriate to use a plural verb.
Here's to comment for context:
>	// NB: deleting these is "best effort" -- if we fail on a particular one,
>	// we won't requeue just to finish the deleting.
=> 📖 Fix grammar in comment

.github/workflows/lint.yml, Makefile
This pr ensures the GitHub workflow uses the same minor version of golangci-lint as installed by the Makefile as can be seen here: https://github.com/kubernetes-sigs/kubebuilder/blob/523907a7e70a7b3d02c2df91382f6b1ee2ca4c54/Makefile#L86
=> 🌱 Update github workflow to use same golangci-lint minor version as Makefile

pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
Signed-off-by: Mikhail Sidorov <mixity@yandex.ru>
Added buildx argument to a Makefile template, which should resolve the bug of docker-buildx target not working
Fixes #3045
=> :bug:  Fix docker buildx makefile target missing arg (.)

pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/prometheus/monitor.go, pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/rbac/leader_election_role.go, testdata/project-v3-addon-and-grafana/Makefile, testdata/project-v3-config/Makefile, testdata/project-v3-multigroup/Makefile, testdata/project-v3-with-deploy-image/Makefile, testdata/project-v3/Makefile, testdata/project-v4-addon-and-grafana/Makefile, testdata/project-v4-addon-and-grafana/config/prometheus/monitor.yaml, testdata/project-v4-addon-and-grafana/config/rbac/leader_election_role.yaml, testdata/project-v4-config/Makefile, testdata/project-v4-config/config/prometheus/monitor.yaml, testdata/project-v4-config/config/rbac/leader_election_role.yaml, testdata/project-v4-multigroup/Makefile, testdata/project-v4-multigroup/config/prometheus/monitor.yaml, testdata/project-v4-multigroup/config/rbac/leader_election_role.yaml, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-deploy-image/config/prometheus/monitor.yaml, testdata/project-v4-with-deploy-image/config/rbac/leader_election_role.yaml, testdata/project-v4/Makefile, testdata/project-v4/config/prometheus/monitor.yaml, testdata/project-v4/config/rbac/leader_election_role.yaml
Fix a typo issue in the labels added to the manifests into the (kustomize/v2-alpha)
The same type of issue is not faced with the kustomize/v1 plugin, see: https://github.com/kubernetes-sigs/kubebuilder/search?q=app.kubernets.io%2Fname
Ensure that the labels added to the manifests scaffolds under the config with the plugin go/v4-alpha are correctly (not missing the `e`):
`
=> 🐛 (kustomize/v2-alpha): Fix typo issue in the labels added to the manifests

.gitignore, docs/book/book.toml, docs/book/theme/index.hbs
Add `git-repo` and `git-edit` icons on the top-right page, to let other users to go to KB project quickly, and
go to the edit page easily if want to modify the doc.
Tested with `mdbook serve` locally, works fine.
=> :seedling: Add KB project git-repo and edit icons

docs/book/src/SUMMARY.md, docs/book/src/faq.md
Fixes #1318 #1723 #3016 #3028
Add a FAQ section in the KB docs, and include some of the representational reported issues.
Will update it continuously, to help more users.
Also add `git-repo` and `git-edit` icons on the top-right page.
Tested with `mdbook serve` locally, works fine.
=> :book: Add kubebuilder FAQ section

.github/workflows/apidiff.yml, Makefile
Minor chore pr to just keep dependencies up to date. Updates joelanford/go-apidiff from v0.4.0 to v0.5.0. 
Release notes seem safe: https://github.com/joelanford/go-apidiff/releases/tag/v0.5.0
=> 🌱  Update joelanford/go-apidiff (v0.4.0 -> v0.5.0)

docs/book/src/plugins/creating-plugins.md
Add a section in `create-plugin` to provide references for users who create the plugin to scaffold on top of what `create api` brings.
Resolve: https://github.com/kubernetes-sigs/kubebuilder/issues/2874
=> 📖  docs: supplement plugin creation

pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go, testdata/project-v3-addon-and-grafana/Makefile, testdata/project-v3-config/Makefile, testdata/project-v3-multigroup/Makefile, testdata/project-v3-with-deploy-image/Makefile, testdata/project-v3/Makefile, testdata/project-v4-addon-and-grafana/Makefile, testdata/project-v4-config/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4/Makefile
**Description of the change:**
Test if the installed versions of `kustomize` and `controller-gen` match the ones provided in the Makefile corresponding variables `KUSTOMIZE_VERSION` and `CONTROLLER_TOOLS_VERSION` to determine whether to re-install or not.
**Motivation for the change:**
Prevent running `controller-gen` and `kustomize` commands with a version that does not match the one specified in the corresponding variables. (details of scenario in #3068)
* Fixes #3068
=> :sparkles: add version check for makefile template tools

pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go, testdata/project-v3-addon-and-grafana/Makefile, testdata/project-v3-config/Makefile, testdata/project-v3-multigroup/Makefile, testdata/project-v3-with-deploy-image/Makefile, testdata/project-v3/Makefile, testdata/project-v4-addon-and-grafana/Makefile, testdata/project-v4-config/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4/Makefile
**Description of the change:**
Add backslash (\) character to the `kustomize` recipe to fix `unexpected end of file` error
**Motivation for the change:**
Fix the error that caused these tests to fail: https://github.com/kubernetes-sigs/kubebuilder/pull/3077#issuecomment-1317613311
* Fixes #3068
=> :bug: fix unexpected end of file error in makefiles

build/cloudbuild_kube-rbac-proxy.yaml
Add v0.13.1 that fixes few CVEs. Details in kube-rbac-proxy releae notes https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.13.1
Fixes: #3094
=> :seedling: Bump  kube-rbac-proxy from v0.13.0 to v0.13.1

CONTRIBUTING.md
Add instruction to notify specifying plugins if a PR is "plugin" scoped.
Make the commit message more readable and consistent.
=> 📖 : suggest specify plugin for pr

docs/book/src/component-config-tutorial/testdata/project/api/v2/projectconfig_types.go, docs/book/src/component-config-tutorial/testdata/projectconfig_types.go
Fixes a typo in the component config tutorial (`contfigurations` -> `configurations`).
=> 📖 docs: fix typo in the component config tutorial

docs/book/src/migration/manually_migration_guide_gov3_to_gov4.md, docs/book/src/migration/v3vsv4.md, pkg/plugins/common/kustomize/v2-alpha/scaffolds/api.go, pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/samples/kustomization.go, testdata/project-v4-config/config/samples/kustomization.yaml, testdata/project-v4-declarative-v1/config/samples/kustomization.yaml, testdata/project-v4-multigroup/config/samples/kustomization.yaml, testdata/project-v4/config/samples/kustomization.yaml
Scaffold `config/samples/kustomization.yaml` which helps deploying sample CRs at ease.
Resolve https://github.com/kubernetes-sigs/kubebuilder/issues/1573
=> ✨ feat  : add kustomize file for crd sample

docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml, pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go, pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go, pkg/plugins/golang/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go, testdata/project-v2/config/default/manager_auth_proxy_patch.yaml, testdata/project-v3-config/config/default/manager_auth_proxy_patch.yaml, testdata/project-v3-declarative-v1/config/default/manager_auth_proxy_patch.yaml, testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml, testdata/project-v3-with-deploy-image/config/default/manager_auth_proxy_patch.yaml, testdata/project-v3-with-metrics/config/default/manager_auth_proxy_patch.yaml, testdata/project-v3/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-config/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-declarative-v1/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-multigroup/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-with-deploy-image/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-with-metrics/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4/config/default/manager_auth_proxy_patch.yaml
Upgrade gcr.io/kubebuilder/kube-rbac-proxy from 0.13.0 to 0.13.1 to address CVE
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3094
=> ✨ Upgrade gcr.io/kubebuilder/kube-rbac-proxy from 0.13.0 to 0.13.1 to address CVE

docs/book/src/component-config-tutorial/testdata/project/config/manager/manager.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml, docs/book/src/reference/platform.md, pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/config.go, pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/manager/config.go, testdata/project-v3-config/config/manager/manager.yaml, testdata/project-v3-declarative-v1/config/manager/manager.yaml, testdata/project-v3-multigroup/config/manager/manager.yaml, testdata/project-v3-with-deploy-image/config/manager/manager.yaml, testdata/project-v3-with-metrics/config/manager/manager.yaml, testdata/project-v3/config/manager/manager.yaml, testdata/project-v4-config/config/manager/manager.yaml, testdata/project-v4-declarative-v1/config/manager/manager.yaml, testdata/project-v4-multigroup/config/manager/manager.yaml, testdata/project-v4-with-deploy-image/config/manager/manager.yaml, testdata/project-v4-with-metrics/config/manager/manager.yaml, testdata/project-v4/config/manager/manager.yaml
This is a simple improvement just removing a trailing space causing yamllint to fail on a newly scaffolded project.
=> 📖 : Remove trailing space making yamllint fail on new project

pkg/plugins/common/kustomize/v2-alpha/scaffolds/api.go, pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/samples/kustomization.go, testdata/project-v4-config/config/samples/kustomization.yaml, testdata/project-v4-declarative-v1/config/samples/kustomization.yaml, testdata/project-v4-multigroup/config/samples/kustomization.yaml, testdata/project-v4/config/samples/kustomization.yaml
Instead of overwriting the file, we can use a marker so we will just append new values instead. 
- allow manual changes
- fix: does not track values for core types (such as deployment)
- fix layout of the scaffold
=> 🐛  (kustomize/v2-alpha): use marker to track samples and do not create tracks for core types

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go, testdata/project-v4-with-deploy-image/config/crd/patches/cainjection_in_busyboxes.yaml, testdata/project-v4-with-deploy-image/config/crd/patches/cainjection_in_memcacheds.yaml, testdata/project-v4-with-deploy-image/config/samples/kustomization.yaml
(deployimage/v1-alpha): fix error to scaffold go/v4-alpha projects
Note that the deploy image was not using the kustomize/v2-alpha and go/v4-alpha scaffolds when the project layout was using those versions.
=> 🐛 (deployimage/v1-alpha): fix error to scaffold go/v4-alpha projects

docs/book/src/component-config-tutorial/tutorial.md
This change replaces the restricted-access `ComponentConfig` design doc [link](https://docs.google.com/document/d/1FdaEJUEh091qf5B98HM6_8MS764iXrxxigNIdwHYW9c/), found in the `ComponentConfig` tutorial of the Kubebuilder book, with the [public](https://github.com/kubernetes/community/blob/master/archive/wg-component-standard/component-config/README.md) one.
=> 📖 Replace restricted-access ComponentConfig design doc link with the public one

build/cloudbuild_tools.yaml, build/thirdparty/darwin/Dockerfile, build/thirdparty/linux/Dockerfile, build/thirdparty/windows/Dockerfile
This PR updates the kubernetes version in the `tools-releases` branch to 1.26.0 from 1.25.0.
It also bumps the etcd binary from v3.5.5 to v3.5.6.
=> ✨ Update Kubernetes version from 1.25.0 to 1.26.0 for kubebuilder artefacts and bump etcd to v3.5.6

pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go, pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go, testdata/project-v3-config/README.md, testdata/project-v3-declarative-v1/README.md, testdata/project-v3-multigroup/README.md, testdata/project-v3-with-deploy-image/README.md, testdata/project-v3-with-grafana/README.md, testdata/project-v3/README.md, testdata/project-v4-config/README.md, testdata/project-v4-declarative-v1/README.md, testdata/project-v4-multigroup/README.md, testdata/project-v4-with-deploy-image/README.md, testdata/project-v4-with-grafana/README.md, testdata/project-v4/README.md
👋 Thanks for your work on `kubebuilder`! This is an attempt to address issue #3121 , assuming you all regard that as worthwhile. As such, it layers in a few spelling, grammar, and formatting improvements to the `README.md` file templates:
* correctly spell "until"
* correct grammar
* add previously-absent puncuation
* remove trailing whitespace
Thanks!
=> 🐛 Improve README template spelling and grammar

docs/book/src/SUMMARY.md
The FAQ section should be moved to the bottom of the page after the plugins section finishes.
Fixes #3130
=> 📖 Update SUMMARY.md

docs/book/src/reference/envtest.md
Signed-off-by: ShivamTyagi12345 <mergesuccessful@gmail.com>
Fixes
- #3116
The changes addressed in the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/2857/files are not in the master branch. The PR cherry-picks (CopyPastes) it to the master branch and ensure we have them there.
=> 📖 Making section on envtest limitations visible in Master

docs/book/src/plugins/creating-plugins.md
fix _Available Plugins_ link to the correct `.md` file
fix #3138 
Link will lead to this page, https://github.com/kubernetes-sigs/kubebuilder/compare/available-plugins.md?expand=1
Link will lead to this page, https://book.kubebuilder.io/plugins/available-plugins.html
result on my local after change
=> 📖  fix "Available Plugins" link

build/thirdparty/linux/Dockerfile
fix kubebuilder-tools for Linux env
since the release of k8s 1.26 it is no longer working
=> :bug: fix kubebuilder-tools for linux env

docs/book/src/quick-start.md
This tiny PR fixes a typo in the curl command:
```
- curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$\(go env GOOS\)/$\(go env GOARCH\)
+ curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
```
=> :book: fix typo in curl command

docs/book/src/migration/migration_guide_gov3_to_gov4.md
The kubebuilder command was missing the "--" infront of plugins. This meant that it used the go/v3 layout.
=> 📖 fix-missing dashes infront of plugins

docs/book/src/component-config-tutorial/testdata/project/README.md, docs/book/src/cronjob-tutorial/testdata/project/README.md, docs/book/src/multiversion-tutorial/testdata/project/README.md
Fixes untile -> until in wherever I could find it in the coderepo.
The typo is no longer present in the readme-generation code, #3122 solved that.
=>  📖 fix untile typo in readmes

RELEASE.md
remove the workaround steps from the release doc.
these steps are from the legacy method, which is no longer used
=> :book: remove the workaround steps from the release doc

docs/book/src/migration/manually_migration_guide_gov3_to_gov4.md
* the markdown formatting of the file manually_migration_guide_gov3_to_gov4.md was incorrect hence leading to a bad layout
especially in the last section .
* it fixes the issue #3167
* feel free to point out any discrepancy
=> 📖 [docs] : corrected layout of manually_migration_guide_gov3_to_gov4.md

docs/book/src/migration/migration_guide_gov3_to_gov4.md, docs/book/src/plugins/go-v4-plugin.md, docs/book/src/plugins/kustomize-v2-alpha.md, pkg/plugins/common/kustomize/v2-alpha/init.go, pkg/plugins/common/kustomize/v2-alpha/plugin.go, testdata/project-v4-config/Makefile, testdata/project-v4-declarative-v1/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4/Makefile
1. Bump kustomize from 4.5.7 to 5.0.0 for kustomize v2-alpha plugin
2. Update related samples
3. Update related docs
Aims to solve https://github.com/kubernetes-sigs/kubebuilder/issues/3198
=> ⚠️ (kustomize/v2-alpha, go/v4-alpha): Upgrade kustomize from 4.5.7 to 5.0.0

.gitignore, build/cloudbuild_tools.yaml, build/thirdparty/darwin/Dockerfile, build/thirdparty/linux/Dockerfile, build/thirdparty/windows/Dockerfile
- upgrade k8s version from 1.26.0 to 1.26.1
-  etcd from v3.5.6 to v3.5.7
=> :sparkles: upgrade k8s version from 1.26.0 to 1.26.1 and etcd from v35.6 to v3.5.7

pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v3-config/Makefile, testdata/project-v3-declarative-v1/Makefile, testdata/project-v3-multigroup/Makefile, testdata/project-v3-with-deploy-image/Makefile, testdata/project-v3-with-grafana/Makefile, testdata/project-v3/Makefile, testdata/project-v4-config/Makefile, testdata/project-v4-declarative-v1/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
The security management software IBM runs flags this line as a vulnerability and kill -9's it whenever you try to execute it (by running make bundle-build or using any of the operator sdk commands that use that make task). As a result, IBMers currently can't make use of that functionality. This changes up the line a little to be more palatable to  our security software.
=> :sparkles: (go/v3,go/v4-alpha): instead of call script to install kustomize download it first

docs/book/src/component-config-tutorial/testdata/project/Makefile
Align the `makefile` scaffolded in component-config-tutorial with the latest Kubebuilder.
Resolve the CI `check testdata` error on master branch.
=> 📖 fix: sync docs tutorial with latest kb

pkg/plugins/external/external_test.go, pkg/plugins/external/helpers.go
This PR aims to fix an issue that is causing the `PluginRequest.Universe` not to be populated before Kubebuilder serializes `PluginRequest` and sends it to external plugins through STDIN.
To construct `PluginRequest.Universe`, the fix will scan the root directory of the project, read every file, and then add an entry to the `PluginRequest.Universe` map, where the key will be the relative path to the file, and the value the content of the file.
fixes: #3214
=> 🐛 (Kubebuilder External Plugins API): fix populate PluginRequest.Universe which is empty

.github/workflows/lint.yml, Makefile
fixes #3239 
- Update `golangci/golangci-lint-action` to use `v1.51`
- Update Makefile's `golangci-lint` version to `v1.51.2`
=> 🌱 Update golangci-lint to latest version

docs/book/src/plugins/go-v3-plugin.md, pkg/plugins/golang/v4/plugin.go
deprecated go/v3 plugin
Motivation: https://github.com/kubernetes-sigs/kubebuilder/issues/3117
=> :warning: (go/v3) deprecate go/v3 in favor of go/v4

pkg/cli/options.go, pkg/cli/options_test.go, pkg/cli/root.go
This PR aims to fix a bug that's causing external plugin discovery to fail in Linux systems when `XDG_CONFIG_HOME` environment variable is set.
fixes: #3224
=> 🐛 (API - External Plugins):  Fix external plugin discovery on Linux

pkg/plugin/util/helpers.go
These deprecation messages will reappear in the next release wherein go/v3 is deprecated in favor of go/v4. Till then these warnings are not necessary.
Please refer here: https://github.com/operator-framework/helm-operator-plugins/actions/runs/4342983995/jobs/7584462203#step:6:52 - for users with KB 3.9.0, these warnings are unnecessary. They should be re-introduced in the KB version which has go/v3 deprecated.
=> 🐛 Clarify deprecate documentation for API methods which are served to work with CRD/WebHook API versions v1beta1

docs/book/src/cronjob-tutorial/testdata/project/config/manager/kustomization.yaml
#3249 
Delete cronjob tutorial Incorrect code in kustomization.yaml, that will lead to `make deploy` error
=> 📖 : delete cronjob tutorial Incorrect kustomization.yaml

build/cloudbuild_kube-rbac-proxy.yaml
Build new tag version 0.14.0 for kube-rbac-proxy image More info: https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.14.0
=> :sparkles: Build new tag version 0.14.0 for kube-rbac-proxy image

pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go, pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller_suitetest.go, pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_suitetest.go, pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go
This PR removes the stale import: "pkg/envtest/printer" that is not needed after migrating to ginko/v2.
Controller-runtime v0.14.0+ has migrated to use ginko/v2 and thereby removed "printer" package. The imports were still being scaffolded though not used in the codebase.
This was causing the error mentioned [here](https://kubernetes.slack.com/archives/CAR30FCJZ/p1678204565778959) by one of the community users.
=> :bug: [fix: go/v3, go/v4] Remove stale imports

pkg/plugin/util/helpers.go
Fix Linter errors for deprecation message
=> :seedling: [fix] Linter errors for deprecation message

pkg/plugins/golang/v3/plugin.go, pkg/plugins/golang/v4/plugin.go
The message was added to the wrong plugin version
This PR only fix and ensure that the message is the right one.
=> 🐛  fix: deprecate message should be in go/v3

docs/book/install-and-build.sh, docs/book/src/cronjob-tutorial/controller-implementation.md, docs/book/src/cronjob-tutorial/main-revisited.md, docs/book/src/cronjob-tutorial/testdata/generate_cronjob.sh, docs/book/src/cronjob-tutorial/testdata/project/Dockerfile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/PROJECT, docs/book/src/cronjob-tutorial/testdata/project/api/v1/webhook_suite_test.go, docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go, docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/certificate.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/certmanager/kustomizeconfig.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/manager/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/rbac/service_account.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/samples/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/webhook/kustomizeconfig.yaml, docs/book/src/cronjob-tutorial/testdata/project/go.mod, docs/book/src/cronjob-tutorial/testdata/project/go.sum, docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go, docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go, docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go, docs/book/src/cronjob-tutorial/writing-tests.md
update cronjob tutorial sample to use go/v4
Ensure that docs are using go/v4 and no longer go/v3
Motivation: https://github.com/kubernetes-sigs/kubebuilder/issues/3117
=> :book: update cronjob tutorial sample to use go/v4

cmd/main.go, docs/book/src/quick-start.md, hack/docs/internal/generate_component_config.go
Make go/v4 layout the default layout of kubebuilder CLI
Now, new projects init without inform plugin will be created using go/v4 by default.
NOTE: It does not break the behaviour for those with a project scaffold with go/v3. It only makes the default scaffold of the the CLI to be go/v4 
https://github.com/kubernetes-sigs/kubebuilder/issues/3117
https://github.com/kubernetes-sigs/kubebuilder/discussions/3217
=> ✨  : make go/v4 to be default Kubebuilder CLI scaffold

pkg/plugins/common/kustomize/v1/api.go, pkg/plugins/common/kustomize/v1/create.go, pkg/plugins/common/kustomize/v1/init.go, pkg/plugins/common/kustomize/v1/plugin.go, pkg/plugins/common/kustomize/v1/webhook.go, pkg/plugins/golang/v3/api.go, pkg/plugins/golang/v3/commons.go, pkg/plugins/golang/v3/edit.go, pkg/plugins/golang/v3/init.go, pkg/plugins/golang/v3/plugin.go, pkg/plugins/golang/v3/webhook.go
deprecate kustomize/v1 and go/v3 packages 
https://github.com/kubernetes-sigs/kubebuilder/issues/3117
https://github.com/kubernetes-sigs/kubebuilder/discussions/3217
=> :sparkles: (API) deprecate kustomize/v1 and go/v3 packages

hack/docs/internal/generate_component_config.go, test/testdata/generate.sh
Fix merge conflict that brokes testdata
Motivation: unblock other prs
=> 🌱 fix testdata / merge conflict

designs/extensible-cli-and-scaffolding-plugins-phase-2.md, pkg/plugin/external/types.go
The `Help` field in `PluginResponse` was replaced with `Metadata` on fc97428.
But `Help` is used in the design document and the comment on the code still now.
This PR updates the external plugin v2 design doc and comment to use the `Metadata` field in `PluginResponse` instead `Help` field.
=> :book: Replace "Help" field in EP doc with "Metadata" field

.github/workflows/apidiff.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml
Resolve  #3297 
Update workflows  to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=skip::$(test/check-docs-only.sh $REF)"
```
**TO-BE**
```yml
echo "skip=$(test/check-docs-only.sh $REF)" >> $GITHUB_OUTPUT
```
=> :seedling: Replace deprecated command with environment file

cmd/main.go, pkg/cli/cli.go, pkg/plugin/bundle.go, pkg/plugin/bundle_test.go, pkg/plugins/common/kustomize/v2/plugin.go, pkg/plugins/external/plugin.go, pkg/plugins/golang/declarative/v1/plugin.go, pkg/plugins/golang/deploy-image/v1alpha1/plugin.go, pkg/plugins/golang/v4/plugin.go, pkg/plugins/optional/grafana/v1alpha/plugin.go
This PR enforces the deprecated interface to be implemented so that Bundle Plugins can also be deprecated.
If you are using Kubebuilder as lib, then:
- a) Add an empty string for all bundles plugins which are not deprecated:
Example:
```go
// Bundle plugin which built the golang projects scaffold by Kubebuilder go/v4 with kustomize alpha-v2
gov4Bundle, _ := plugin.NewBundle(golang.DefaultNameQualifier, plugin.Version{Number: 4},
"", // Here you must pass an empty string. If you inform an string value here then that means this plugin is deprecated and this string will be used to create the notice message
kustomizecommonv2alpha.Plugin{},
golangv4.Plugin{},
)
``` 
- b) Ensure that you implement the Deprecate interface in all plugins
```go
func (p Plugin) DeprecationWarning() string {
return …
```
=> :warning: 🐛 (API) fix deprecate interface to allow bundle plugin has deprecation message

.github/workflows/apidiff.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml
This fixes the issue with the [CI] doc check being cancelled, instead of being skipped.
#3268
=> 🌱  [ci] : fix the issue with [CI] doc check being cancelled instead of being skipped

.github/workflows/apidiff.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml
Remove the job to skip the checks when only docs are changed because it is broken and blocking the PRs from merging. We can review it and fix it afterwords.
=> 🌱 ci: remove check docs only since it is blocking the ci

docs/book/src/multiversion-tutorial/deployment.md
I followed the instructions in the documentation to deploy the webhook. When I got to the step `kubectl apply -f config/samples/batch_v2_cronjob.yaml`, kubectl reported an error:
```bash
$ kubectl apply -f config/samples/batch_v2_cronjob.yaml
Error from server (InternalError): error when creating "config/samples/batch_v2_cronjob.yaml": Internal error occurred: failed calling webhook "mcronjob.kb.io": failed to call webhook: Post "https://kubebuildertutorial-webhook-service.kubebuildertutorial-system.svc:443/mutate-batch-tutorial-kubebuilder-io-v1-cronjob?timeout=10s": x509: certificate signed by unknown authority
```
After debugging, I found that I also need to apply the `webhookcainjection_patch.yaml` patch to let `cert-manager` work as expected.
=> 📖: Update multiversion-tutorial/deployment.md to enable CA injection when deploying webhook

docs/book/src/migration/v3vsv4.md
After the release by checking the migration guide, we see that the links are broken and that the note/warning about go/v4-alpha not being stable is still present. This PR just address those nits.
=> :book: fix migration guide after go/v4 stabilization and links

docs/book/src/plugins/go-v4-plugin.md
This doc is outdated and this PR update the doc after its stabilization.
Fix docs
=> :book: fix/update go/v4 plugin page doc after the stabilization

docs/book/src/SUMMARY.md, docs/book/src/plugins/kustomize-v1.md, docs/book/src/plugins/kustomize-v2.md
Fix the kustomize v2 links on the left side.
Update info accordingly after plugin updates
=> :book: fix kustomize-v2 index link

docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml, pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go, testdata/project-v3/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-config/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-declarative-v1/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-multigroup/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-with-deploy-image/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-with-grafana/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4/config/default/manager_auth_proxy_patch.yaml
This PR removes the multi-arch node affinity from auth proxy patch in `kustomize/v1` plugin, since scheduling affects on pod level, not the pod level and it is affecting both the `kube-rbac-proxy-patch` and `manager` container.
Fixes: #3272
=>  🐛 (kustomize/v1, kustomize/v2): remove multi arch node affinity patch from auth proxy

build/cloudbuild_kube-rbac-proxy.yaml
Build new tag version 0.14.1 for kube-rbac-proxy image More info: https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.14.1
=> :sparkles: bump kube-rbac-proxy to v0.14.1

cmd/main.go, docs/book/src/plugins/creating-plugins.md, docs/book/src/plugins/extending-cli.md, docs/book/src/plugins/kustomize-v1.md, docs/book/src/plugins/kustomize-v2.md, pkg/plugin/bundle.go, pkg/plugin/bundle_test.go
This PR changes the [NewBundle](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugin/bundle.go#L33-L59) method to work with options. The pattern will like:
```
func NewBundle(opts ...BundleOptions) (Bundle, error)
```
and new bundles will be created like:
```
bundle, err := NewBundle(
WithName("name"),
WithVersion(plugin.Version{Number: 4}),
WithPlugins(plugins ...Plugin),
WithDeprecationMessage("Deprecated!"),
)
```
Fixes: #3307
=> ✨Change `NewBundle` method to build bundles through working with options

pkg/plugin/bundle.go
(API) deprecate the old func to create a new BundlePlugin in favour of the new one, which uses as arg BundleOptions.
Replace:
```go
mylanguagev1Bundle, _ := plugin.NewBundle(language.DefaultNameQualifier, plugin.Version{Number: 1},
kustomizecommonv1.Plugin{}, // extend the common base from Kubebuilder
mylanguagev1.Plugin{},
```
With:
```go
mylanguagev1Bundle, _ := plugin.NewBundle(plugin.WithName(language.DefaultNameQualifier),
plugin.WithVersion(plugin.Version{Number: 1}),		  
plugin.WithPlugins(kustomizecommonv1.Plugin{}, 
mylanguagev1.Plugin{}),
```
More info: https://github.com/kubernetes-sigs/kubebuilder/pull/3312
=> :warning: (API) deprecate the old func to create a new BundlePlugin in favour of the new one, which uses as arg BundleOptions

docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go, testdata/project-v4-config/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-declarative-v1/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-multigroup/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-with-deploy-image/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-with-grafana/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4/config/default/manager_auth_proxy_patch.yaml
Upgrade image gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1 to gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
=> :sparkles: (go/v4) Upgrade image gcr.io/kubebuilder/kube-rbac-proxy from v0.13.1 to v0.14.1

pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go, testdata/project-v4-config/internal/controller/suite_test.go, testdata/project-v4-declarative-v1/internal/controller/suite_test.go, testdata/project-v4-multigroup/internal/controller/apps/suite_test.go, testdata/project-v4-multigroup/internal/controller/crew/suite_test.go, testdata/project-v4-multigroup/internal/controller/fiz/suite_test.go, testdata/project-v4-multigroup/internal/controller/foo.policy/suite_test.go, testdata/project-v4-multigroup/internal/controller/foo/suite_test.go, testdata/project-v4-multigroup/internal/controller/sea-creatures/suite_test.go, testdata/project-v4-multigroup/internal/controller/ship/suite_test.go, testdata/project-v4-multigroup/internal/controller/suite_test.go, testdata/project-v4-with-deploy-image/internal/controller/suite_test.go, testdata/project-v4/internal/controller/suite_test.go
fix the name controllers test function which has been scaffolded as` func TestAPIs(t *testing.T) {` for the controllers.
=> :bug: (go/v4, deployimage): fix the name controllers test function

pkg/plugins/golang/v4/scaffolds/api.go
This pull request addresses issue #3373, which prevented kubebuilder from creating an API when no boilerplate file was present.
I have tested the changes locally with the following steps:
1. Rebuilt the Kubebuilder binary with updated code
2. Used Kubebuilder to initialize a new project
3. Deleted the 'boilerplate' file
4. Modified the 'generate' target in the Makefile as follows:
```makefile
.PHONY: generate
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
$(CONTROLLER_GEN) object paths="./..."
```
5. Executed the 'create api' command.
Additionally, I tried to make some changes that enable the 'create api' command to modify the 'Makefile' when there's no boilerplate file and let the user skip step 4 altogether, making …
=> 🐛 (go/v4): Scaffold when no boilerplate file

docs/book/src/component-config-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-config/Makefile, testdata/project-v4-declarative-v1/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
- This allows building with other container tools like podman. Keeps docker as the default.
=> :sparkles: (go/v4): Allows container tool to be configured in Makefile 

CONTRIBUTING.md, docs/book/src/quick-start.md
Since the master branch has updated the go version to v1.20, we can also update that in the docs.
=> 📖: Update go version in docs to v1.20

pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/internal/templates/hack/boilerplate.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
Fix #3377
Now it would not scaffold any header if we use 'none' in license option.
=> 🐛: (go/v4) Scaffold no header when lincense is type none

docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go, testdata/project-v4-config/config/crd/kustomization.yaml, testdata/project-v4-declarative-v1/config/crd/kustomization.yaml, testdata/project-v4-multigroup/config/crd/kustomization.yaml, testdata/project-v4-with-deploy-image/config/crd/kustomization.yaml, testdata/project-v4/config/crd/kustomization.yaml
Fixes #3372 
See that the default scaffolds:
Warning:
'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run
"kustomize edit fix' to update
your Kustomization automatically.
Therefore I replaced patchesStrategicMerge by patches in the kustomize/v2 templates code.
=> ✨ (kustomize/v2) Remove deprecated syntax usage by replacing patchesStrategicMerge with patches

docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/migration/migration_guide_gov3_to_gov4.md, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-config/Makefile, testdata/project-v4-declarative-v1/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
This change will change the method of installation from downloading the script to using `go install`
Fixes https://github.com/kubernetes-sigs/kubebuilder/issues/2822
=> ✨ Updated Makefile to support go install kustomize

docs/book/src/quick-start.md
Currently looks like this [on this page](https://book.kubebuilder.io/quick-start.html).
=> :book: fix formatting in quick start

docs/book/src/multiversion-tutorial/api-changes.md
Description:
This PR will improve the document by adding instructions when creating a new version API
Motivation:
When going through the documentation, I saw for the first chapter the prompt was given (https://github.com/kubernetes-sigs/kubebuilder/blob/3c8a6264f45edaaf9c2f1c9ce82ce7de26c16097/docs/book/src/cronjob-tutorial/new-api.md?plain=1#L11) but it wasn't given for chapter 2
so it confused me when running `kubebuilder create api --group batch --version v2 --kind CronJob`  which will output **error**  when I  chose y for both "Create Resource" and "Create Controller`
"Create Controller" is created on chapter 1 so it's no needed over here
=> 📖 Added user prompt for multi version api doc

docs/book/src/reference/webhook-for-core-types.md
Description: Added link for cronjob tutorial
Motivation: When reading through kubebuilder book, I saw the the Cronjob tutorial was mentioned but there was no link that points to it
=> 📖 Added link for cronjob tutorial

pkg/cli/completion_test.go, pkg/cli/version.go, pkg/cli/version_test.go
This PR introduces the files changes in `completion.go` and `version.go` that will enhance the test coverage.
Fixes: #3211 
Result -
```
> go test pkg/cli/suite_test.go                                                                                                                                   3s
ok      command-line-arguments 
> go test -coverprofile=coverage.out ./...
ok      sigs.k8s.io/kubebuilder/v3/pkg/cli      0.168s  coverage: 84.1% of statements
> go tool cover -func=coverage.out
sigs.k8s.io/kubebuilder/v3/pkg/cli/completion.go:26:    newBashCmd                      100.0%
sigs.k8s.io/kubebuilder/v3/pkg/cli/completion.go:45:    newZshCmd                       100.0%
sigs.k8s.io/kubebuilder/v3/pkg/cli/completion.go:64:    newFishCmd                      100.0% …
```
=> :seedling: Added the test-coverage for completion.go and version.go inside cli pkg

docs/book/src/quick-start.md
Copying and pasting the `curl` line in the installation docs conflicts with zsh (or perhaps ohmyzsh, and perhaps only on Mac), which incorrectly escapes parentheses. 
```sh
curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
```
becomes:
```sh
curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$\(go env GOOS)/$(go env GOARCH)
```
Which of course doesn't have the desired result and errors out.
Double-quoting the URL should ensure the interpolated shell commands have the desired outcome. Tested on zsh and bash.
=> 📖 Quote download URL in quickstart docs

docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml, hack/docs/internal/cronjob-tutorial/generate_cronjob.go
Fixes https://github.com/kubernetes-sigs/kubebuilder/issues/3426
=> 📖 Fixed manager_webhook_patch not uncommented

docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-config/Makefile, testdata/project-v4-declarative-v1/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
- This allows multiple different kubectl installs to be used.
=> ✨ (go/v4): Allows kubectl to be configured in Makefile

test/e2e/ci.sh, test/e2e/externalplugin/e2e_suite_test.go, test/e2e/externalplugin/generate_test.go, test/e2e/local.sh, test/e2e/setup.sh
Add e2e tests for sample external plugin
Validate the functionality and the behavior of the sample external plugin.
=> 🌱 Add e2e tests for sample external plugin

pkg/config/v3/config.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
=> 📖 : fix function name in comments

docs/book/src/quick-start.md
- The path to the generated `controller` file is incorrect in the quick start 
- Fixed the path by prefixing it with `internal/`
=>  📖 : doc fix path error

pkg/cli/alpha.go, pkg/cli/alpha/generate.go, pkg/rescaffold/migrate.go
This is the first part of the whole project: 
only the alpha command and be able to re-scaffold the init command for example for the layout.
The demo video is here:
https://github.com/kubernetes-sigs/kubebuilder/assets/69566909/26b10af4-6456-4931-ada7-22a1fc3196db
=> ✨re-scaffold the project with a new command 

docs/book/src/SUMMARY.md, docs/book/src/reference/raising-events.md
Description: Add the documentation to help out users know how to implement and raise events.
NOTE: we had this document in v1 docs but it is outdated and we are shaping it accordingly.
This is https://github.com/kubernetes-sigs/kubebuilder/pull/3375 original pr but during squashing commits I messed up the original file and this is backup.
=> :book: Raising event doc page created

docs/book/src/reference/raising-events.md
The documentation page of raising events had some minor issues. Which are solved here.
=> :book: Update Raising events doc page

README.md, build-legacy/build.sh, build-legacy/cloudbuild_kube-rbac-proxy.yaml
This PR moves the current implementation to build-legacy and adds a new directory to build the images for the new k8s registry within its infrastructure. More info: https://github.com/kubernetes-sigs/kubebuilder/issues/3230
Closes: https://github.com/kubernetes-sigs/kubebuilder/pull/3246/files
=> :sparkles: add new build for new k8s registry infra-prow

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go, testdata/project-v4-with-deploy-image/internal/controller/busybox_controller_test.go, testdata/project-v4-with-deploy-image/internal/controller/memcached_controller_test.go
This PR removes from the controller test implemented by the Deploy Image plugin.
Improves the before and after each test by applying the CR on it to ensure better practices since, for each reconciliation test, we ought to apply the resource. So, also remove the CR applied after the tests are executed.
=> ✨ (deployImage) improve the controller tests scaffolded

go.mod, go.sum, pkg/cli/options.go, pkg/cli/options_test.go
1. Introduce the usage of env variable `KB_PLUGINS_PATH` to define a customized path to store external plugins.
1. Add corresponding unit tests
```
~/programming/temp/my-external-plugins  
❯ tree .
.
└── sampleexternalplugin
└── v1
└── sampleexternalplugin
~/programming/temp/my-external-plugins                                                                                                                                                
❯ KB_PLUGIN_PATH="/Users/eileen/programming/temp/my-external-plugins" \
kubebuilder init --plugins=sampleexternalplugin/v1
```
Make the external plugin path configurable so that users can easily manage their external plugins.
=> ✨ Make external plugin path configurable

.github/workflows/apidiff.yml, .github/workflows/lint.yml, .github/workflows/testdata.yml, .github/workflows/unit-tests-legacy.yml, .github/workflows/unit-tests.yml, docs/book/src/cronjob-tutorial/testdata/project/go.sum, go.mod, go.sum, pkg/plugins/golang/declarative/v1/api.go
- fix ci testdata which is outdated because go version. The go mod result is no longer the same with go 1.20.5 release 
- Remove job to open PR from CI since it is uses secret which is not safe and is not useful either
- Unblock PRs
- Cleanup
=> 🌱 : fix ci testdata which is outdated because go version and remove job to open PR

pkg/machinery/interfaces.go, pkg/machinery/mixins.go, pkg/plugins/common/kustomize/v2/init.go
Deprecated component-config flag  and component-config API methods
Following up of: https://github.com/kubernetes-sigs/kubebuilder/pull/3442/files
Closes: https://github.com/kubernetes-sigs/kubebuilder/pull/3023
Closes: https://github.com/kubernetes-sigs/kubebuilder/pull/3022
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3418
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2782
=> ⚠️ (kustomize/v2) - deprecate component-config flag and component-config API methods

test/e2e/deployimage/plugin_cluster_test.go, test/e2e/v4/plugin_cluster_test.go
Adding checks to e2e tests to verify make manifest and generate command
=> 🌱  Adding checks to e2e tests to verify make manifest and generate command

docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go, pkg/plugins/golang/declarative/v1/api.go, test/e2e/v4/generate_test.go, testdata/project-v4-declarative-v1/config/crd/kustomization.yaml, testdata/project-v4-multigroup/config/crd/kustomization.yaml, testdata/project-v4-with-deploy-image/config/crd/kustomization.yaml, testdata/project-v4/config/crd/kustomization.yaml
This commit fixes the syntax error introduced in #3374 where pathcesStrategicMerge was replaced with patches, which now requires that every patch additionally have a "path" key when multiple patches are specified in a file.
Fixes #3425
=> :bug: Fix kustomize syntax during conversion to patches

docs/book/src/component-config-tutorial/testdata/project/.gitignore, docs/book/src/cronjob-tutorial/testdata/project/.gitignore, pkg/plugins/golang/v2/scaffolds/internal/templates/gitignore.go, pkg/plugins/golang/v3/scaffolds/internal/templates/gitignore.go, pkg/plugins/golang/v4/scaffolds/internal/templates/gitignore.go, testdata/project-v2/.gitignore, testdata/project-v3/.gitignore, testdata/project-v4-declarative-v1/.gitignore, testdata/project-v4-with-deploy-image/.gitignore, testdata/project-v4-with-grafana/.gitignore
VS Code is a very popular editor, putting a directory specific to it in generated `.gitignore` files seems to be a nice improvement for end users.
=> ✨ Add .vscode to autogenerated .gitignore files

pkg/rescaffold/migrate.go, test/e2e/alphagenerate/generate_test.go
The alpha generate command has initial function that re-scaffold the project.
Now we can add the 'multigroup' flag to support multi APIs.
=> ✨  Add multigroup flag in alpha generate subcommand

docs/book/src/cronjob-tutorial/testdata/project/api/v1/webhook_suite_test.go, docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, pkg/plugins/golang/v4/scaffolds/api.go, pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_suitetest.go, pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go, pkg/plugins/golang/v4/scaffolds/webhook.go, testdata/project-v4-declarative-v1/internal/controller/suite_test.go, testdata/project-v4-multigroup/api/crew/v1/webhook_suite_test.go, testdata/project-v4-multigroup/api/ship/v1/webhook_suite_test.go, testdata/project-v4-multigroup/api/ship/v2alpha1/webhook_suite_test.go, testdata/project-v4-multigroup/api/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/controller/apps/suite_test.go, testdata/project-v4-multigroup/internal/controller/crew/suite_test.go, testdata/project-v4-multigroup/internal/controller/fiz/suite_test.go, testdata/project-v4-multigroup/internal/controller/foo.policy/suite_test.go, testdata/project-v4-multigroup/internal/controller/foo/suite_test.go, testdata/project-v4-multigroup/internal/controller/sea-creatures/suite_test.go, testdata/project-v4-multigroup/internal/controller/ship/suite_test.go, testdata/project-v4-multigroup/internal/controller/suite_test.go, testdata/project-v4-with-deploy-image/api/v1alpha1/webhook_suite_test.go, testdata/project-v4-with-deploy-image/internal/controller/suite_test.go, testdata/project-v4/api/v1/webhook_suite_test.go, testdata/project-v4/internal/controller/suite_test.go
Fix the scaffold to allow running the tests directly. Currently, it will fail because we install the required binaries at the bin directory inside of the project but that is not the default path configured in controller-runtime.
=> :bug:(go/v4, deployImage): fix scaffold to allow run the tests directly. Currently, is only possible run via the makefile targets

go.mod, go.sum, pkg/rescaffold/migrate.go, test/e2e/alphagenerate/generate_test.go
Support Grafana Plugin migration in the alpha generate subcommand. 
This is the first step, which will only call 'kubebuilder' command.
=> ✨ Add Grafana Plugin migration in alpha generate subcommand -- Step 1

docs/book/src/quick-start.md
=> 📖 Docs update quick-start.md use "kubectl -k apply"

docs/book/src/component-config-tutorial/testdata/project/README.md, docs/book/src/cronjob-tutorial/testdata/project/README.md, pkg/plugins/golang/v3/scaffolds/internal/templates/readme.go, pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go, testdata/project-v3/README.md, testdata/project-v4-declarative-v1/README.md, testdata/project-v4-multigroup/.gitignore, testdata/project-v4-multigroup/README.md, testdata/project-v4-with-deploy-image/README.md, testdata/project-v4-with-grafana/README.md, testdata/project-v4/.gitignore, testdata/project-v4/README.md
Use `-k` instead of `-f` when instructing users to call `kubectl apply` for *config/samples*.
The *config/samples* consists of kustomize manifests, and `kubectl apply -k` typically processes for a kustomization directory.
This is a following up from https://github.com/kubernetes-sigs/kubebuilder/issues/3499
=> 📖 : apply kustomize dir with correct flags

test/e2e/utils/test_context.go
Updated destroy function to run docker only when image name is present. This removes the log error while generating docs.
Partial address: https://github.com/kubernetes-sigs/kubebuilder/issues/3435
=> :seedling:  Update destroy function 

go.mod, go.sum, pkg/rescaffold/migrate.go, test/e2e/alphagenerate/generate_test.go
Support Grafana Plugin migration in the alpha generate subcommand. 
This is the second step, which will copy the config.yaml in metrics.
=> ✨ Add Grafana Plugin migration in alpha generate subcommand -- Step 2

docs/book/src/SUMMARY.md, docs/book/src/plugins/external-plugins.md
Add docs for the external plugin tutorial.
1. Guide users to write, install, and use their own external plugins.
2. Part of the efforts of https://github.com/kubernetes-sigs/kubebuilder/discussions/3309
3. Record my experiment & tips along with my practice over the external plugin with JavaScript:
https://github.com/Eileen-Yu/kb-js-plugin
=>  📖 Add tutorial for external plugin

pkg/cli/cli.go, pkg/cli/cli_test.go
Fixes #3473 
Currently, when initializing in a project with deprecated plugins the kubebuilder cli will immediately output a deprecation notice to stdout before even parsing the command. While this is acceptable and even desirable for interactive usage of the cli, it will "randomly" (i.e. dependent on $PWD and not on the command) break automated usage of the kubebuilder output. This, again is fine if kubebuilder makes no guarantees of stable machine readable output, but this does not hold for the completion sub commands which are only ever parsed by machines: The output of "kubebuilder completion <shell>" must always only output the exact script generated by cobra and the cobra internal commands __complete and __completeNoDesc must only only return an exact list of completion options.
In …
=> :bug: fix(completion): Fix completion in deprecated projects

pkg/plugins/external/helpers.go
Ensure the path specified in `PluginResponse.Universe` is created before the real scaffolding logic.
Example:
For the Universe:
```
universe["some/dir/file.yaml"] = `...`
```
Create `/home/user/foo-test/some/dir` before scaffolding so as to avoid errors like:
```
2023/08/02 11:56:23 failed to initialize project: unable to scaffold with "foo/v1": open /home/user/foo-test/some/dir/file.yaml: no such file or directory
```
Aims to fix the corresponding issue https://github.com/kubernetes-sigs/kubebuilder/issues/3518
=> 🐛 Ensure external plugin can scaffold files in new directories

test/e2e/utils/test_context.go
In generating docs, if there is no image present we can skip running docker command and this was covered in https://github.com/kubernetes-sigs/kubebuilder/pull/3508
but if the image name is  of  single character or in anyother edge case the code would crash. 
In this pr I have covered the Edge cases. 
Following up on: https://github.com/kubernetes-sigs/kubebuilder/pull/3508#discussion_r1279543133
=> :seedling: Image name edge cases covered

hack/docs/internal/component-config-tutorial/generate_component_config.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go
There was same logs at different place which results in difficulty to debug. 
Updated the unique logs to give better understanding.
Partially fixes: #3435
PS: I am moving forward with this #3506 pr.
=> :seedling: logs info updated

docs/book/book.toml, docs/book/install-and-build.sh, netlify.toml
Fix CI which is broken with issues to get install controller-gen to build the docs due to the fact it is using an old version of Golang.
=> :bug: fix doc preview

Makefile, hack/docs/check.sh, hack/docs/generate.sh, hack/docs/generate_samples.go
This PR aims to ensure that the `Kubebuilder binary` used for docs generation is built from the source code so that the docs can be updated corresponding to the latest code change.
- Create a new `hack/docs/generate.sh` that builds the kb executable from source code and run the go code to re-generate docs samples
- Modify the target `generate-docs` to call `hack/docs/generate.sh`
- Modify the target `check-docs` to drop unnecessary import and call `hack/docs/generate.sh`
- Change the go code to use kb binary `/tmp/kubebuilder/bin/kubebuilder` which is generated by `build_kb` (instead of the default kb from user's os env).
Partially resolve https://github.com/kubernetes-sigs/kubebuilder/issues/3435
See comments:
1. https://github.com/kubernetes-sigs/kubebuilder/issues/3435#issuecomment-1646 …
=> 🐛: sync kb binary from source code for docs

Makefile, docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/multiversion-tutorial/testdata/project/Makefile, docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/Makefile, pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v2/Makefile, testdata/project-v3/Makefile, testdata/project-v4-declarative-v1/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
Fixes #3540 
This PR fixes some grammar errors in the scaffolded makefiles.
=> 🐛 fix grammar in scaffolded makefiles

docs/book/utils/markerdocs/html.go
**Issue #3534**
- we are using `markerdocs` as [mdBook preprocessor](https://rust-lang.github.io/mdBook/for_developers/preprocessors.html)  to generate most of our `References` section (e.g. [CRD Validation](https://book.kubebuilder.io/reference/markers/crd-validation))
- this preprocessor writes HTML but the text fields also contain markdown (e.g. [this line](https://github.com/kubernetes-sigs/controller-tools/blob/498444bd78eb90dbdf228dfd9ad333d68fe354e7/pkg/crd/markers/validation.go#L220))
- we call `html.EscapeString()` on the output of the preprocessor (see [here](https://github.com/kubernetes-sigs/kubebuilder/blob/68abac1dfb5550f7159dec4ce600cd9b6db925bb/docs/book/utils/markerdocs/html.go#L44))
- the preprocessed output is then parsed as markdown by mdBook
Basically, mdBook handles …
=> 📖  fix escaped html in markdown code segments

build/cloudbuild_tools.yaml
=> ✨ Build kubebuilder-tools for k8s 1.28.0

build/thirdparty/windows/Dockerfile
I think alpine 3.18 is the same as 3.18.3: https://hub.docker.com/_/alpine/tags
So just bumping it to 3.18 and the other Dockerfiles are already on 3.18
=> 🌱 Bump to alpine 3.18

docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-declarative-v1/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
fix makefile target to build images ensuring its single responsibility
When we call make build we want only to build the image and run the tests is not a pre-requirement. It can make take too long to build the image.
=> :bug: (go/v4) fix makefile target to build images ensuring its single responsibility

pkg/config/v3/config.go, pkg/config/v3/config_test.go
Make `cfg` from an internal struct to be a public one.
Externalize `cfg` to make it be accessible for external plugin.
Part of effort for https://github.com/kubernetes-sigs/kubebuilder/issues/3553
=> ✨  Externalize config struct to be available for external plugin

pkg/rescaffold/migrate.go
Improve logs from alpha command generate
Looking for an standards
Improve the UX
=> :sparkles: improve logs from alpha command generate

pkg/cli/cli.go
Currently the deprecation notice is blue. However, the standard and common practice is to use yellow for warnings and deprecations. Changing that accordingly. See:
=> :bug: change deprecated warning to yellow

docs/book/src/SUMMARY.md, docs/book/src/plugins/external-plugins.md
Suggestion to replace `Extending Kubebuilder with external plugins` with `Creating external plugins`. It seems more aligned with the other titles and more clear about its purpose
=> 📖 : changing title for external plugins

pkg/plugins/golang/deploy-image/v1alpha1/api.go, pkg/plugins/golang/deploy-image/v1alpha1/plugin.go, pkg/rescaffold/migrate.go, test/e2e/alphagenerate/generate_test.go
Description:
Support Deploy Plugin migration in the alpha generate subcommand.
=> ✨ Add support to re-scaffolds projects with  alpha generate subcommand to deployImage plugin

docs/book/src/reference/rescaffold.md
Add a document for guiding users.
=> 📖 Add document for Alpha generate command

docs/book/src/component-config-tutorial/tutorial.md
* **Description:** Add an alternate to ComponentConfig in Docs
* **Motivation:** As ComponentConfig has been deprecated, it was needed to provide an alternate solution
* **Fixes:** #3457 
**Type:** 
- 📖 (:book:): documentation
=> 📖 Fix ComponentConfig

Makefile
sometimes, the permission of files in testdata dir is 555 without write permission.
if no write permission to those binary file, error occurs 'etcd: Permission denied'
=> 🌱  (make generate) : fix error of 'Permission denied' about binary file

hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/cronjob-tutorial/main_revisited.go, pkg/plugins/golang/v4/scaffolds/internal/templates/main.go, testdata/project-v4-multigroup/cmd/main.go, testdata/project-v4-with-deploy-image/cmd/main.go, testdata/project-v4/cmd/main.go
Fixes #3559
describe: fix issue that webhook generated code in cmd/main.go ignored checking the env ENABLE_WEBHOOKS
Test result :
```
➜  guestbook git:(dev) ✗ export ENABLE_WEBHOOKS=false; make run
test -s /Users/wlh/go/src/github.com/lowang-bh/demo/guestbook/bin/controller-gen && /Users/wlh/go/src/github.com/lowang-bh/demo/guestbook/bin/controller-gen --version | grep -q v0.13.0 || \
GOBIN=/Users/wlh/go/src/github.com/lowang-bh/demo/guestbook/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.13.0
/Users/wlh/go/src/github.com/lowang-bh/demo/guestbook/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Users/wlh/go/src/github.com/lowang-bh/demo/guestbook/bin/controller-gen …
```
=> 🐛 (go/v4): Start to check ENABLE_WEBHOOKS envvar into main.go to fix issue when webhooks are used

pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go, pkg/plugins/golang/v2/scaffolds/internal/templates/config/crd/patches/enablecainjection_patch.go, testdata/project-v4-multigroup/config/crd/kustomization.yaml
Fixes #3502
The comments about path of patch file name in `config/crd/kustomization.yaml` is not correct when enable multigroup
make test passed.
=> 🐛  (kustomize/v2,go/v4): fix kustomization yaml's webhooks patches file names for multgroup layouts

docs/book/src/SUMMARY.md, docs/book/src/migration/migration_guide_gov3_to_gov4.md, docs/book/src/reference/rescaffold.md
- Ensure that you describe how the command work and show examples of it usage
- Add the command to the migration guide as a help
- Add links of reference for the command
- Add the doc to the index
=> 📖 supplement doc over alpha generate command

docs/book/src/cronjob-tutorial/cert-manager.md, docs/book/src/migration/legacy/v1vsv2.md, docs/book/src/multiversion-tutorial/deployment.md, docs/book/src/reference/envtest.md, test/e2e/utils/test_context.go
cert-manager became a CNCF project in 2022 [1]. The existing links to cert-manager, with Jetstack ownership, redirect to the new ownership.
The updated links have been verified to be working.
There was one file that had EOL whitespace formatting corrected.
FIXES #3607
[1] https://www.cncf.io/blog/2022/10/19/cert-manager-becomes-a-cncf-incubating-project/
=> 📖 docs(cert-manager): Change ownership links

docs/book/src/reference/webhook-for-core-types.md
This PR updates the documentation around adding a `Decoder` to your `Admission.Handle()` method for a webhook that deals with Core Types.
The existing documentation references creating an `InjectDecoder` method, which is no longer supported in newer versions of `controller-runtime`. These updates to the docs follow the latest method specified in the `controller-runtime` library.
fixes #3604
=> 📖 Update docs for using Decoder with Core Type Webhook

docs/README.md, docs/book/src/faq.md, docs/book/src/introduction.md, docs/book/src/quick-start.md, docs/book/src/reference/good-practices.md, docs/book/src/reference/raising-events.md, docs/book/src/reference/watching-resources/operator-managed.md
It has some improvements and fixes in the doc
the motivation: While reading the documentation, I noticed some parts that could be improved or fixed (missing links).
=> 📖 Improvements in the Documentation

Makefile
I meet this issue on apple m2  macbook. I don't know why. After run`make install` and then run new installed kb, it will still be killed, until I remove the old one and reinstall it.
```
[1]    59938 killed     $GOPATH/bin/kubebuilder version
```
After rm it and re-install
=> 🌱 runtime error on darwin arm64 machine: killed

test/e2e/utils/test_context.go
To generate the URL at a uniq location.
=> 🌱 unify promethuse-operator url

docs/book/src/faq.md
Fixes: #3460 
Make install fails when crd description exceeds limit. Workaroud and why the error occur is added as suggested in [this](https://github.com/kubernetes-sigs/kubebuilder/issues/3460#issuecomment-1624883989) comment
=> :book: Add Make install workaround 

docs/book/src/SUMMARY.md, docs/book/src/getting-started.md
This PR introduces an overview or summary to assist users in getting started more smoothly. We've designed this document to address the most frequently asked initial questions.
While the tutorials offer in-depth information, this document aims to provide a broad understanding in a more concise manner.
See the preview: https://deploy-preview-3596--kubebuilder.netlify.app/getting-started
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3203
=> 📖 Add getting started doc

docs/book/src/component-config-tutorial/testdata/project/README.md, docs/book/src/cronjob-tutorial/testdata/project/README.md, pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go, testdata/project-v4-multigroup/README.md, testdata/project-v4-with-deploy-image/README.md, testdata/project-v4-with-grafana/README.md, testdata/project-v4/README.md
- Fix the readme instructions
- Ensure that you have a Prerequisites section
- Remove the KIND info (we should not suggest the k8s vendor)
- Remove the kubebuilder doc link and commands to update api since it does not seems to make sense in the readme and either if it would be added then, would be required a lot of more details such as how to generate RBAC and etc.
=> 🐛 (go/v4): fix readme content and instructions

hack/docs/internal/cronjob-tutorial/generate_cronjob.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, test/e2e/v4/generate_test.go, testdata/project-v4-multigroup/config/crd/kustomization.yaml, testdata/project-v4-multigroup/config/default/kustomization.yaml, testdata/project-v4-with-deploy-image/config/crd/kustomization.yaml, testdata/project-v4-with-deploy-image/config/default/kustomization.yaml, testdata/project-v4/config/crd/kustomization.yaml, testdata/project-v4/config/default/kustomization.yaml
We should NOT let the webhook configuration be commented on when a webhook is created. Therefore, this PR ensures that when we run kubebuilder to create a webhook we will uncomment the required places under the config so that webhooks are enabled by default.
=> :bug:  (kustomize/v2,go/v4): fix uncomment kustomize files config accordinly when webhooks are generate

docs/book/src/reference/admission-webhook.md
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/616
=> :book: add info about status and webhooks

docs/book/src/reference/webhook-for-core-types.md
Fixes the reference of the struct var in the documentation as added in https://github.com/kubernetes-sigs/kubebuilder/pull/3613/files
=> :book: Fix variable reference in docs

docs/book/src/plugins/external-plugins.md
This was confusing to me, so I tried to make it less confusing.
See https://sigs.k8s.io/kubebuilder-release-tools for more information.
=> :book: Clarify plugin executable locations

docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup-with-deploy-image/config/crd/kustomization.yaml, testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml, testdata/project-v4-multigroup/Makefile, testdata/project-v4-multigroup/config/crd/kustomization.yaml, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
Create a variable to make clear the version used in the target.
Also, to allow  golangci-lint version to be customizable
=> :sparkles: (go/v4) allow golangci-lint version into the Makefile to be customizable

pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, testdata/project-v4-multigroup-with-deploy-image/config/crd/kustomization.yaml, testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml, testdata/project-v4-multigroup/config/crd/kustomization.yaml
The testdata and lint must be fixed 
A merge was made and it gets outdated.
=> 🌱 fix testdata get outdated

docs/book/src/component-config-tutorial/testdata/project/config/rbac/role.yaml, pkg/plugins/common/kustomize/v2/scaffolds/api.go, pkg/plugins/common/kustomize/v2/scaffolds/init.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/role.go, testdata/project-v4-with-grafana/config/default/kustomization.yaml, testdata/project-v4-with-grafana/config/rbac/role.yaml
A project might have no CRDs generate their for:
- We should scaffold the project with the config/default/kustomization.yaml with crd commented when we run init
- We should generate the basic Role since controller-gen is only able to do that when markers are found in the controllers
- We should uncomment the crd config from config/default/kustomization.yaml when api is generated.
=> 🐛 (kustomize/v2, go/v4): fix role and kustomize build when no CRDs are added to the project

docs/book/src/reference/admission-webhook.md
Add link from upstream as reference
c/c @varshaprasad96 this one address your comment in: https://github.com/kubernetes-sigs/kubebuilder/pull/3612
=> 📖 add link from k8s to clarify admission webhooks

build-legacy/cloudbuild_kube-rbac-proxy.yaml, build/cloudbuild_kube-rbac-proxy.yaml
The 0.14.4 version of kube-rbac-proxy contains the fix for CVE-2023-44487 by bumping golang.org/x/net.
For more details visit: https://github.com/brancz/kube-rbac-proxy/pull/261
=> (:bug:): [build] Build new kube-rbac-proxy image

docs/book/src/cronjob-tutorial/testdata/emptymain.go
This PR proposes an update to the documentation available at https://book.kubebuilder.io/cronjob-tutorial/empty-main.html#every-journey-needs-a-start-every-program-needs-a-main. The reason for this revision is that the current documentation still references deprecated cache settings, such as `cache.MultiNamespacedCacheBuilder`.
With the release of controller-runtime v0.15.0, several Manager Options have undergone refactoring and deprecation. As a result, the documentation needs an update since it still refers to old Manager Options.
Fixes #3662
=> 📖 Addressing Deprecated Manager Options

build-legacy/cloudbuild_kube-rbac-proxy.yaml, build/cloudbuild_kube-rbac-proxy.yaml
The recent release of brancz/kube-rbac-proxy
introduces options to disable http/2 or fine tune
its configuration.
More details refer: https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.15.0
=> ✨ [Add] Bump kube-rbac-proxy to 0.15.0

docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/component-config-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, pkg/plugins/common/kustomize/v2/plugin.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, test/e2e/v4/generate_test.go, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup-with-deploy-image/config/default/kustomization.yaml, testdata/project-v4-multigroup/Makefile, testdata/project-v4-multigroup/config/default/kustomization.yaml, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-deploy-image/config/default/kustomization.yaml, testdata/project-v4-with-grafana/Makefile, testdata/project-v4-with-grafana/config/default/kustomization.yaml, testdata/project-v4/Makefile, testdata/project-v4/config/default/kustomization.yaml
Hi!
It fixes #3539 
P.S. I hope I've chosen the right title this time. :sweat_smile:
=> 🐛 (kustomize/v2,go/v4): Remove use of deprecated patchesStrategicMerge / ✨ Upgrade kustomize version from v5.1.1 to v5.2.1

build/cloudbuild_tools.yaml, build/thirdparty/darwin/Dockerfile, build/thirdparty/linux/Dockerfile, build/thirdparty/windows/Dockerfile
- Bump k8s version from v28.0 to v28.3
- Bump windows with Golang from 2.19 to 2.20
- Update ETCD from v3.5.9 to v3.5.10
=> ✨ Bump k8s, etcd and golang to generate new tools/envtest versions

docs/book/src/cronjob-tutorial/testdata/finalizer_example.go, docs/book/src/multiversion-tutorial/api-changes.md, docs/book/src/reference/completion.md, docs/book/src/reference/platform.md, docs/book/src/reference/raising-events.md, docs/book/src/reference/webhook-overview.md
I've recently come across some issues while reading the Kubebuilder document.
This PR mainly addresses:
- formatting issues that do not properly render code blocks
- broken links that reference the Cronjob code
- minor typos and grammar for a smoother reading experience
=> 📖 Docs fixes for code blocks, links and minor typos

README.md
* Heading `Kubebuilder` starts off with explaining Kubebuilder is a framework
* Subheading which explains Kubebuilder can also be used as a library was previously `Kubebuilder is also a framework`, now changed to `Kubebuilder is also a library` making it more coherent.
=> :book: README.md: Fix first subheading under the Kubebuilder heading

docs/book/src/plugins/grafana-v1-alpha.md, pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go, testdata/project-v4-with-grafana/grafana/controller-runtime-metrics.json
Add panels to show:
- work queue depth
- number of workers in use
- unfinished seconds
Slightly changed panels position for better UI.
This PR aims to partially resolve #3651
=> :sparkles: Enrich Grafana plugin panels

docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, test/common.sh, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
We upgrade the k8s version from 1.28.0 to 1.28.3 but we did not bumped the envtest. More info, check the PR to generate the artifacts: https://github.com/kubernetes-sigs/kubebuilder/pull/3679
=> :bug: Upgrade envtest from 0.28.0 to 0.28.3 to ensure that versions used  are aligned

docs/book/src/reference/envtest.md
noticed small syntax error in docs for cert manager and prometheus  in the envtest section.
fixed for accuracy.
=>  📖 fixes: syntax error in cert manager code example

docs/book/src/component-config-tutorial/testdata/project/README.md, docs/book/src/cronjob-tutorial/testdata/project/README.md, pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go, testdata/project-v4-multigroup-with-deploy-image/README.md, testdata/project-v4-multigroup/README.md, testdata/project-v4-with-deploy-image/README.md, testdata/project-v4-with-grafana/README.md, testdata/project-v4/README.md
Update README template for golang/v4 plugin (v2 and v3 are deprecated and will be removed soon).
Use right command.
No related issues
=> :bug: (go/v4): fix make help instruction in the README

docs/book/src/component-config-tutorial/testdata/project/.gitignore, docs/book/src/cronjob-tutorial/testdata/project/.gitignore, pkg/plugins/golang/v4/scaffolds/internal/templates/gitignore.go, testdata/project-v4-multigroup-with-deploy-image/.gitignore, testdata/project-v4-multigroup/.gitignore, testdata/project-v4-with-deploy-image/.gitignore, testdata/project-v4-with-grafana/.gitignore, testdata/project-v4/.gitignore
Update gitignore template  for golang/v4 plugin (v2 and v3 are deprecated and will be removed soon) to be up to date with https://github.com/github/gitignore/blob/main/Go.gitignore
Use the default template of GitHub
No related issues
=> :bug: (go/v4) update gitignore template comments and fix some nit typo issues

build/cloudbuild_tools.yaml, build/thirdparty/darwin/Dockerfile, build/thirdparty/linux/Dockerfile, build/thirdparty/windows/Dockerfile
**Description:**
* Bump k8s version from v1.28.3 to v1.29.0
* Update ETCD from v3.5.10 to v3.5.11
=> ✨ Bump k8s and etcd to generate new tools/envtest versions

docs/book/src/component-config-tutorial/testdata/project/Dockerfile, docs/book/src/cronjob-tutorial/testdata/project/Dockerfile, pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go, testdata/project-v4-multigroup-with-deploy-image/Dockerfile, testdata/project-v4-multigroup/Dockerfile, testdata/project-v4-with-deploy-image/Dockerfile, testdata/project-v4-with-grafana/Dockerfile, testdata/project-v4/Dockerfile
Update Dockerfile template for golang/v4 plugin (v2 and v3 are deprecated and will be removed soon).
Use recommended Docker syntax.
No related issues
=> :bug: (go/v4): Standardize 'AS' Keyword Capitalization in Dockerfile for Clarity

CONTRIBUTING.md
Clarify that PR contributions should have only 1 commit and address only 1 need by default. 
Closes: #3728
=> :book: Update CONTRIBUTING.md: Add info about 1 need/commit per PR

docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
Fixes #3715 
PR solves primary issue with synchronization of tools version between developers where older copies of repo can use older versions of binaries and it isn't updated by makefile.
PR unified way how tools are installed and adding better support for versioning of binary based on binary names.
It add new function into makefile and modified installation targets for tools.
It contains more specific version of tool setup-envtest, which was set to release-0.16 branch because this tools doesn't support proper versioning. It isn't ideally solution but still better as latest.
output:
```bash
ls bin 
controller-gen-v0.13.0     golangci-lint-v1.54.2      kustomize-v5.2.1           setup-envtest-release-0.16
make generate manifests undeploy test lint
.../example/bin/controller-gen-v0.13.0 …
```
=> :sparkles: (go/v4) : Ensure versioning of tools and binaries installed via Makefile

build/.goreleaser.yml
Issue: https://github.com/kubernetes-sigs/kubebuilder/issues/3740
this PR adds support for s390x through go release so that the required binaries are generated when these assets are generated via GitHub-actions
=> ✨ Start to build CLI binary for linux_s390x as target

build/thirdparty/darwin/Dockerfile, build/thirdparty/windows/Dockerfile
- Upgrade Golang version used to build the binaries to 1.21
- Upgrade the alpine version from 3.18 to 3.19 in for Windows targets.
=> 🌱 Bump golang 1.21 and alpine 3.19

Makefile, docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/component-config-tutorial/testdata/project/README.md, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/README.md, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go, test/e2e/v4/plugin_cluster_test.go, test/testdata/generate.sh, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup-with-deploy-image/README.md, testdata/project-v4-multigroup/Makefile, testdata/project-v4-multigroup/README.md, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-deploy-image/README.md, testdata/project-v4-with-deploy-image/config/manager/kustomization.yaml, testdata/project-v4-with-deploy-image/dist/install.yaml, testdata/project-v4-with-grafana/Makefile, testdata/project-v4-with-grafana/README.md, testdata/project-v4-with-grafana/config/manager/kustomization.yaml, testdata/project-v4-with-grafana/dist/install.yaml, testdata/project-v4/Makefile, testdata/project-v4/README.md, testdata/project-v4/config/manager/kustomization.yaml, testdata/project-v4/dist/install.yaml
- Add target to build the installer under dist/install.yaml
- Also, add e2e tests to ensure that installer will be working well as expected
- By last, add instruction into the README generate to make clear how to achieve this goal
Just generate the YAML with all that should be installed (same kustomize build of make install and make deploy) so that the project can be distributed as usually it is done by many solutions like Operator Prometheus for example, where users can run: kubectl apply -f dist/install.yaml and maintainers can easily project the raw of the file. 
- https://github.com/kubernetes-sigs/kubebuilder/discussions/3074
- https://github.com/kubernetes-sigs/kubebuilder/discussions/3081
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3185
IMPORTANT: For we are able …
=> ✨  (go/v4): Add method to allow users distribute the project

test/common.sh, test/e2e/setup.sh
Bump tools and dynamically set external plugin path to support running e2e test on Apple ARM machines.
1. Tools updates
- kind: `0.15.0` --> `0.20.0`
- memcached image: `1.4.36-alpine` --> `1.6.23-alpine`
- busybox image: `1.28` --> `1.36.1`
2. Use `uname -s` to detect the OS to determine the external plugin path.
Support running target `make test-e2e-local` available on Apple ARM machines.
=> 🌱 : bump e2e tools version to support running Apple ARM instance

docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go, docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-deploy-image/test/utils/utils.go, testdata/project-v4-with-grafana/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
Upgrade CertManager and Prometheus versions used in the e2e tests
=> :sparkles: (go/v4): Upgrade CertManager and Prometheus versions used in the e2e tests

docs/book/src/reference/raising-events.md
Fix typo in raising-events.md from rule.yaml to role.yaml
=> 📖 Fix typo in raising-events.md from rule.yaml to role.yaml

pkg/plugin/util/testdata/exampleFile.txt, pkg/plugin/util/util_test.go
Resolve https://github.com/kubernetes-sigs/kubebuilder/issues/3748
Drop the latest append `exampleCode` which is only for unit test, so as to avoid checkout that file each time.
=> 🌱 drop unnecessary file change for unit test

docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go, docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-deploy-image/test/utils/utils.go, testdata/project-v4-with-grafana/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
Reverts kubernetes-sigs/kubebuilder#3754
We have a test (project-v4-sample) which should be testing it.
However, the test passed, and we could check that the Prometheus Operator installer has an issue and cannot be applied directly. However, it seems that from k8s 1.29, we no longer see the error related to the CRD being too long. 
So the project-v4-sample is passing but it will not work in k8s versions which are lower the 1.29
=> :bug: Revert ":sparkles: (go/v4): Upgrade CertManager and Prometheus versions used in the e2e tests"

docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
**Description**:
current implementation of makefile target build-installer cannot work properly without crd. Root cause of problem is missing discard of content, if crd isn't used.
Result of problem is appending new content behind previous into dist/install.yaml and file content is growing and contains multiple versions.
=> :bug: (go/v4) Fix makefile target build-installer to discarding the previous content

docs/book/src/reference/admission-webhook.md
The [Admission webhooks][k8s-doc-admission-webhooks] is not working as a link at the beginning of the doc. Adding the missing [] for the link.
=>  📖 Fix #the reference link

docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go, hack/docs/internal/cronjob-tutorial/writing_tests_controller.go
In the "Writing tests" section of the cronjob tutorial, the following [code](https://github.com/kubernetes-sigs/kubebuilder/blob/0cb1258c00225720484f665dbf15d27190d75738/docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go#L118-L121)
```
if err != nil {
return false
}
return true
```
can be simplified to
```
return err == nil
```
=> 📖 Simplify if condition in cronjob tutorial

docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go, hack/docs/internal/cronjob-tutorial/controller_implementation.go
=> :book: Fix typo in cronjob-tutorial

docs/book/src/reference/watching-resources/testdata/external-indexed-field/controller.go
This aligns the examples with the changes in `controller-runtime`. I am adding context to handler funcs, because the signature of `MapFunc` changed in `controller-runtime` to allow context to be passed in all handler funcs[1]
[1] https://github.com/kubernetes-sigs/controller-runtime/commit/2464a9d7af4911c6bf6e0baaaf8dc0ab08c7452c
* Fixes #3583
* Tested in the controller I'm writing and watches work perfectly with these changes.
=> 📖 Add context to handler func

docs/book/src/quick-start.md
* Add brief explanation for newbies to understand
* So that new reader that will have a smoother understanding
* Clarifies what is being run and why it's not deployed the first time
=> 📖  Specify what is run and deployed

docs/book/src/reference/admission-webhook.md
The link to the Kubernetes docs for Admission webhooks was not present in the reference docs.
Adding for the sake of correctness.
=> 📖 Add the `Admission webhooks` link in `docs/book/src/reference/admisson-webhook.md`

README.md
Repair access address.
https://slack.k8s.io/#kubebuilder -> https://kubernetes.slack.com/messages/#kubebuilder
=> 📖 : (README) Fix slack channel access address

docs/book/src/component-config-tutorial/testdata/project/.gitignore, docs/book/src/component-config-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/.gitignore, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/.gitignore, docs/book/src/getting-started/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/gitignore.go, pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup-with-deploy-image/.gitignore, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup/.gitignore, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/.gitignore, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/.gitignore, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/.gitignore, testdata/project-v4/Makefile
Noticed that after generating project with kubebuilder, some files had an empty line in their first line. This PR fixes this.
Tried to find all files templates that started with an empty line in `pkg/plugins/golang/v4/scaffolds/internal/templates` folder. Removed it from them and ran `make generate`.
Confirm the changes do not break any use case.
=> :bug: fix: Remove empty line at beginning of generated files

.github/dependabot.yml
Add a condition to skip PR Verifier if the PR is created by dependabot
Current PRs created by dependabot fail the CI/CD workflows as the title of the PR does not match the community's criteria.
It seems dependabot does NOT provide an entry to configure the title, so I am thinking if we can just skip the PR verifier in such scenarios.
=> 🌱: Add prefix to bot PR title to respect community rule

docs/book/src/component-config-tutorial/testdata/project/README.md, docs/book/src/cronjob-tutorial/testdata/project/README.md, docs/book/src/getting-started/testdata/project/README.md, pkg/plugins/golang/v4/scaffolds/internal/templates/readme.go, testdata/project-v4-multigroup-with-deploy-image/README.md, testdata/project-v4-multigroup/README.md, testdata/project-v4-with-deploy-image/README.md, testdata/project-v4-with-grafana/README.md, testdata/project-v4/README.md
This should help users start out with a README that avoids trailing
whitespaces.
Fixes: https://github.com/kubernetes-sigs/kubebuilder/issues/3812
=> :bug: fix: remove trailing whitespace in readme gen

build-legacy/cloudbuild_kube-rbac-proxy.yaml, build/cloudbuild_kube-rbac-proxy.yaml
Just bump latest release: https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.16.0
=> 🌱  Bump kube-rbac-proxy 0.16

docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go, docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-deploy-image/test/utils/utils.go, testdata/project-v4-with-grafana/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
(go/v4) - Upgrade Prometheus version used in the tests from v0.68.0 to v0.72.0
=> :sparkles: (go/v4) - Upgrade Prometheus version used in the tests from v0.68.0 to v0.72.0

docs/book/src/component-config-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml, docs/book/src/getting-started/testdata/project/config/default/manager_auth_proxy_patch.yaml, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go, testdata/project-v4-multigroup-with-deploy-image/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-multigroup/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-with-deploy-image/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-with-deploy-image/dist/install.yaml, testdata/project-v4-with-grafana/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4-with-grafana/dist/install.yaml, testdata/project-v4/config/default/manager_auth_proxy_patch.yaml, testdata/project-v4/dist/install.yaml
Upgrade gcr.io/kubebuilder/kube-rbac-proxy image from v0.15.0 to v0.16.0
For more information check the release notes of the project: https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.16.0
=> :sparkles: Upgrade gcr.io/kubebuilder/kube-rbac-proxy image from v0.15.0 to v0.16.0

docs/book/src/component-config-tutorial/testdata/project/test/utils/utils.go, docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, test/e2e/utils/test_context.go, test/e2e/v4/e2e_suite_test.go, test/e2e/v4/plugin_cluster_test.go, testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-deploy-image/test/utils/utils.go, testdata/project-v4-with-grafana/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
Upgrade cert-manager version used from v1.5.3 to v1.14.4
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3760
=> ✨ Upgrade cert-manager version used from v1.5.3 to v1.14.4

docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml, docs/book/src/getting-started/testdata/project/config/crd/kustomization.yaml, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, test/testdata/generate.sh, testdata/project-v4-multigroup-with-deploy-image/config/crd/kustomization.yaml, testdata/project-v4-multigroup-with-deploy-image/config/manager/kustomization.yaml, testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml, testdata/project-v4-multigroup/config/crd/kustomization.yaml, testdata/project-v4-multigroup/config/manager/kustomization.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-deploy-image/config/crd/kustomization.yaml
This PR addresses a bug in the generation process of the dist/installer for the testdata sample with multi-group layouts. Previously, the process incorrectly generated webhook patches for all resources, leading to failures in installer creation. With this update, webhook patches are now correctly generated only for resources that have webhooks configured, resolving the issue and ensuring successful generation of the installer.
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3761
=> :bug: Fix the CRD kustomization path logic to ensure webhook patches are generated exclusively for resources that are configured with webhooks

test/e2e/deployimage/plugin_cluster_test.go, test/e2e/setup.sh, test/testdata/generate.sh, testdata/project-v4-with-deploy-image/PROJECT, testdata/project-v4-with-deploy-image/config/manager/manager.yaml, testdata/project-v4-with-deploy-image/dist/install.yaml
Upgrade images used in the samples and e2e tests for deployImage plugin
=> 🌱 Upgrade images used in the samples and e2e tests for deployImage plugin

hack/docs/internal/component-config-tutorial/generate_component_config.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go
Remove plugin flag from generate docs samples to ensure that it will be generated from the default plugin always. (Make easier we maintain the project)
=> 🌱 Remove plugin flag from generate docs samples

docs/book/src/component-config-tutorial/testdata/project/config/rbac/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/rbac/kustomization.yaml, docs/book/src/getting-started.md, docs/book/src/getting-started/testdata/project/config/rbac/kustomization.yaml, pkg/plugin/util/util.go, pkg/plugins/common/kustomize/v2/scaffolds/api.go, test/e2e/v4/plugin_cluster_test.go, testdata/project-v4-multigroup-with-deploy-image/config/rbac/kustomization.yaml, testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml, testdata/project-v4-multigroup/config/rbac/kustomization.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-deploy-image/config/rbac/kustomization.yaml, testdata/project-v4-with-deploy-image/dist/install.yaml, testdata/project-v4/config/rbac/kustomization.yaml, testdata/project-v4/dist/install.yaml
Fixes https://github.com/kubernetes-sigs/kubebuilder/issues/3782
Add the logic to insert generated roles into kustomization file when executing `kubebuilder create api`.
Cleanup
- Remove e2e steps for "applying the CRD Editor/Viewer Role".
- Remove outdated content in https://book.kubebuilder.io/getting-started#rbac-generate-under-configrbac.
- Generate docs and testdata; pass test-unit and test-e2e-local
=> :sparkles: (kustomize/v2): Add CRD viewer and editor roles in rbac/kustomization.yaml

build/cloudbuild_tools.yaml
Might be one of the last envtest releases here, but let's see how it goes
xref: https://github.com/kubernetes-sigs/controller-tools/pull/924
=> ✨ Bump envtest to 1.30

.golangci.yml, docs/book/src/component-config-tutorial/testdata/project/.golangci.yml, docs/book/src/cronjob-tutorial/testdata/project/.golangci.yml, docs/book/src/getting-started/testdata/project/.golangci.yml, docs/book/src/multiversion-tutorial/testdata/project/.golangci.yml, pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go, testdata/project-v4-multigroup-with-deploy-image/.golangci.yml, testdata/project-v4-multigroup/.golangci.yml, testdata/project-v4-with-deploy-image/.golangci.yml, testdata/project-v4-with-grafana/.golangci.yml, testdata/project-v4/.golangci.yml
As of 1.57 version, golangci-lint deprecated the `deadline` linter setting
(https://github.com/golangci/golangci-lint/releases/tag/v1.57.0). This PR changes `deadline` to `timeout` in the `.golangci.yml` configuration both for the project setup and for the `.golangci.yml` scaffolding.
=> ✨ : (go/v4): Replace `deadline` in favor of `timeout` in `golangci-lint` configuration

.github/workflows/test-sample-go.yml
We should not update the go mod
We do not need to install envtest
=> 🌱 ci: fix go sample e2e tests

build/thirdparty/darwin/Dockerfile, build/thirdparty/windows/Dockerfile
To fix: https://github.com/kubernetes-sigs/kubebuilder/pull/3864#issuecomment-2069064057
c/c @sbueringer
=> Upgrade go version to fix issues to build tools for k8s 1.30

roadmap/README.md, roadmap/roadmap_2024.md
This PR introduces the addition of detailed roadmaps to our project. These documents outline our strategic objectives, planned initiatives, and focus areas for the upcoming periods. The primary goal is to enhance visibility into the project's direction and foster a more collaborative environment for both current contributors and newcomers.
- **Project Roadmap 2024**: Outlines our major goals and initiatives for 2024, focusing on improving maintainability, user experience, and integrating new functionalities that meet our community's needs.
- **Enhance Visibility**: By clearly articulating our plans and priorities, we aim to provide all stakeholders with a transparent view of where the project is headed.
- **Encourage Collaboration**: The roadmaps are designed to invite contributions and …
=> :book: Add Roadmaps to bring visibility and allow better collaboration

designs/discontinue_usage_of_kube_rbac_proxy.md
Motivations
-  https://github.com/kubernetes-sigs/kubebuilder/issues/1885
-  https://github.com/kubernetes-sigs/kubebuilder/issues/3524
-  https://github.com/kubernetes-sigs/kubebuilder/issues/3482
-  https://github.com/kubernetes-sigs/kubebuilder/issues/3230
c/c @ibihim
=> 📖 : Proposal : Discontinue Kube RBAC Proxy in Default Kubebuilder Scaffolding

pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
If the domain is not informed then we cannot use it to generate the ID for the leader election
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3790
=> :bug: fix Invalid leader election ID generated when domain is empty

docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go, pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook.go, testdata/project-v4-multigroup/api/crew/v1/captain_webhook.go, testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook.go, testdata/project-v4-multigroup/api/v1/lakers_webhook.go, testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook.go, testdata/project-v4/api/v1/captain_webhook.go
Closes: - https://github.com/kubernetes-sigs/kubebuilder/issues/3811
=> :bug: Add comment to clarify that webhooks path in the marker values should not be changed

OWNERS_ALIASES
I would like to apply for the approver role :)
=> :seedling: move tony to approver

Makefile
Just start to run the tests for the Getting Start to ensure that all is fine for the sample code used in the tutorial.
=> 🌱 Began to test getting start sample in the CI

RELEASE.md
📖 Add note to clarify that kube-rbac-proxy images are no longer released
=> 📖 Add note to clarify that kube-rbac-proxy images are no longer released

docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
Fix command documentation.
When `make lint` command was added (https://github.com/kubernetes-sigs/kubebuilder/commit/46ea676fc75e7a8844bbf237cf8e1c4b66b24dd4#diff-e5d6d4f9d67174f1f3764674eb786688353c77cef8514e24d1323e55e5a4a7e8) I believe its documentation was copied from project Makefile (https://github.com/kubernetes-sigs/kubebuilder/commit/feb0c5463bb51d07dc9027a139a0c0a0cfc2253f#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52) which does run `yamllint`, but not command generated by kubebuilder. So, removed that part from command doc.
After applying changes, ran `make generate`. 
Confirm the documentation is correct now.
=> 🐛 makefile: remove invalid comment 

RELEASE.md
📖 Update RELEASE.md - Make clear the build of artifacts are deprecated
=> 📖 Update RELEASE.md - Make clear the build of artifacts are deprecated

docs/book/src/plugins/deploy-image-plugin-v1-alpha.md, docs/book/src/reference/envtest.md
📖 (plugin deploy-image and envtest): use ref of project-v4  instead of v3 in the examples
=> 📖 (plugin deploy-image and envtest): use ref of project-v4  instead of v3 in the examples

docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
fix: makefile: target docker-buildx should use the project name instead of fix value
=> 🐛 fix: makefile: target docker-buildx should use the project name instead of fix value

pkg/plugin/bundle.go, pkg/plugin/bundle_test.go, pkg/plugin/helpers.go, pkg/plugin/helpers_test.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go, pkg/plugins/golang/options.go
⚠️ Remove api deprecations: The methods NewBundle, GetShortName, IsLegacyLayout are no longer available
=> ⚠️ Remove api deprecations: The methods NewBundle, GetShortName, IsLegacyLayout are no longer available

roadmap/roadmap_2024.md
Just Update the Roadmap to bring clarity about the latest status
=> 📖 Update roadmap_2024.md - Latest status - 18 May

docs/book/src/migration/migration_guide_gov3_to_gov4.md, docs/book/src/migration/v3vsv4.md
📖 doc: small nits for the migration section
=> 📖 doc: small nits for the migration section

docs/book/theme/css/custom.css, docs/book/theme/header.hbs, docs/book/theme/index.hbs
Add header to clarify that book-v3 is legacy documentation
=> :book: Add header to clarify that book-v3 is legacy documentation

docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go, docs/book/src/getting-started/testdata/project/cmd/main.go, pkg/plugins/golang/v4/scaffolds/internal/templates/main.go, testdata/project-v4-multigroup-with-deploy-image/cmd/main.go, testdata/project-v4-multigroup/cmd/main.go, testdata/project-v4-with-deploy-image/cmd/main.go, testdata/project-v4-with-grafana/cmd/main.go, testdata/project-v4/cmd/main.go
ix typo issue in the flag description
=> :bug: fix typo issue in the flag description

test/e2e/deployimage/generate_test.go, test/e2e/deployimage/plugin_cluster_test.go
🌱 Cleanup e2e tests for deploy image
remove what is not used
encapsulate the code
=> 🌱 Cleanup e2e tests for deploy image

.golangci.yml, docs/book/src/cronjob-tutorial/testdata/project/.golangci.yml, docs/book/src/getting-started/testdata/project/.golangci.yml, pkg/cli/alpha.go, pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go, pkg/rescaffold/migrate.go, testdata/project-v4-multigroup-with-deploy-image/.golangci.yml, testdata/project-v4-multigroup/.golangci.yml, testdata/project-v4-with-deploy-image/.golangci.yml, testdata/project-v4-with-grafana/.golangci.yml, testdata/project-v4/.golangci.yml
Follow up PR as discussed here https://github.com/kubernetes-sigs/kubebuilder/pull/3904#issuecomment-2119929172
Added rule to check comment spaces in revive linter, in golangci-lint config files; fixed comments spaces; and then run `make generate`.
Check that all Go files now enforce comment spaces.
=> :sparkles: Add revive golangci linter with comment-spacings rule

test/e2e/utils/test_context.go, test/e2e/v4/plugin_cluster_test.go
Encapsulate logic to allow us grow the checks and tests
Remove duplications
=> 🌱 cleanup e2e tests for go/v4

CONTRIBUTING.md
Add detailed steps about how to run the e2e tests locally and debug them out.
=> :book: Update CONTRIBUTING.md - Add steps about how to debug e2e tests locally

pkg/rescaffold/migrate.go, test/e2e/alphagenerate/generate_test.go
Change the getAPIResourceFlags function to return `--namespaced=false` if resource.API.Namespaced and add corresponding test.
This is needed since currently `kubebuilder alpha migrate` always create namespaced APIs due to the default of namespaced being true.
Fixes #3969
=> :bug: fix generate command not respecting --namespaced=false of APIs

docs/book/src/reference/watching-resources/testdata/external-indexed-field/controller.go
I saw incorrect code in the documentation for
https://kubebuilder.io/reference/watching-resources/externally-managed
The provided code is not working
```
Watches(
&source.Kind{Type: &corev1.ConfigMap{}},
handler.EnqueueRequestsFromMapFunc(r.findObjectsForConfigMap),
builder.WithPredicates(predicate.ResourceVersionChangedPredicate{}),
).
```
i am getting an error
`source.Kind (value of type func[T client.Object](cache "sigs.k8s.io/controller-runtime/pkg/cache".Cache, object T, handler handler.TypedEventHandler[T], predicates ...predicate.TypedPredicate[T]) source.SyncingSource) is not a type`
Should be
```
Watches(
&corev1.ConfigMap{},
handler.EnqueueRequestsFromMapFunc(r.findObjectsForConfigMap),
builder.WithPredicates(predicate.ResourceVersionChangedPredicate{}),
).
```
this is [issue …
=> :book: bugfix: fix error in documentation Watching Externally Managed Resources

docs/book/src/migration/v2vsv3.md
This PR adds a page that got lost in clean-ups.
Fixes: #3981
=> 📖 Adding lost v2 vs v3 page.

.github/workflows/testdata.yml
See that how Golang works now we are facing changes in the files and testdata will fail every time that a new patch release be made se we need to add a fix version to the git hub action to avoid it.
=> 🌱 ci: fix testdata due golang module changes

pkg/machinery/marker.go, pkg/machinery/marker_test.go
This PR adds a code implementation which allow Kubebuilder lib consumes use custom names for the markers
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3990
=> :sparkles: (Only valid for those who consume Kubebuilder as a lib) - Allow usage of custom marker names

CONTRIBUTING.md
with more conventional choice of words and sentence structure.
These are all minor readability improvements.
=> :book: docs: clarify English prose in CONTRIBUTING.md

docs/book/src/quick-start.md
Permission denied to move the executable to /usr/local/bin. Need sudo permissions
=> 📖 Update quick-start.md

pkg/cli/cli.go, pkg/cli/cli_test.go, pkg/cli/options.go, pkg/cli/options_test.go
This PR introduces a new CLI option WithFilesystem to set the filesystem when using kubebuilder as library. Furthermore, it allows access to the underlying cobra command. 
**Motivations**
Both features are introduced to improve testability when using kubebilder as lib. Accessing the underlying command allows to pass call arguments to in tests. 
For more information see #4006
=> :sparkles: (Only relevant for users of Kubebuilder as a library) - Add new cli option and allow access to underlying cli command

docs/book/install-and-build.sh, docs/book/src/reference/artifacts.md, docs/book/src/reference/envtest.md, netlify.toml
This PR update the deps used to generate the data in the docs.
It should update the markers to address https://github.com/kubernetes-sigs/kubebuilder/issues/4009
Furthermore, for we are able to move forward here we need to remove the redirect for `https://go.kubebuilder.io/images` and `gcr.io/kubebuilder/thirdparty` which are deprecated and/or no longer used.
We are either adding a note in the in the Artefacts page to clarify that ENV TEST binaries are no longer produced by Kubebuilder and its build and promotion was moved to controller-gen. 
Close: https://github.com/kubernetes-sigs/kubebuilder/issues/4009
=> 📖 Upgrade controller-gen used to generated the docs and remove redirects for artefact images 

docs/book/src/migration/migration_guide_gov3_to_gov4.md
This PR will update the documentation to correct a typo that was found within the `migration_guide_gov3_to_gov4.md` doc.
Fixes #4014 
Please let me know if anything else needs to be correct. 😄
=> 📖 docs: correct typo in migration guide

docs/book/src/reference/metrics.md
Just address a nit in the docs to make clear that we are protecting the metrics endpoint from 4.1.0 by default via controller-runtime feature
=> 📖 clarify in note that metrics are protected by default via controller-runtime feature

docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_webhook_patch.yaml, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/webhook_manager_patch.go, testdata/project-v4-multigroup-with-deploy-image/config/default/manager_webhook_patch.yaml, testdata/project-v4-multigroup/config/default/manager_webhook_patch.yaml, testdata/project-v4-with-deploy-image/config/default/manager_webhook_patch.yaml, testdata/project-v4/config/default/manager_webhook_patch.yaml
Just add the missing labels for this kustomize file in order to ensure the project standards.
=> 🐛 (kustomize/v2,go/v4): add missing labels for config/default/manager_webhook_patch.yaml

Makefile
Cleanup ONLY
We no longer have go/v2 projects
=> 🌱 Update Makefile - Remove makefile target to test legacy project no longer supported

docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go, hack/docs/internal/cronjob-tutorial/writing_tests_controller.go
Change the example tests not to attempt to set Status on Create. The kubernetes api will ignore the status field on creation, leaving it blank.  A new user trying to follow the book might be surprised to find their tests failing because of an empty status.
Instead the example will update the Status immediately after creation. 
Per conversation in the [slack](https://kubernetes.slack.com/archives/CAR30FCJZ/p1720657748942639) 
Related to #1778. Updates the book documentation to match the issue resolution.
=> 📖 Update test examples not to set Status on create

pkg/model/resource/gvk.go, pkg/model/resource/gvk_test.go
Refactor the version validation to allow version values follow:
- Either literal string `__internal`
- OR DNS-1123
Resolve https://github.com/kubernetes-sigs/kubebuilder/issues/3739
=> 🐛  fix validation used to ensure Kind versions pattern

docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go, docs/book/src/getting-started/testdata/project/cmd/main.go, pkg/plugins/golang/v4/scaffolds/internal/templates/main.go, testdata/project-v4-multigroup-with-deploy-image/cmd/main.go, testdata/project-v4-multigroup/cmd/main.go, testdata/project-v4-with-deploy-image/cmd/main.go, testdata/project-v4-with-grafana/cmd/main.go, testdata/project-v4/cmd/main.go
This update streamlines the code and enhances maintainability by centralizing variable definitions.
=> :bug: cleanup/enhancement: keep all variables used defined on top of`main.go`

.github/workflows/release.yml
Follow up of: Update release.yml - Update goreleaser from 1.11.2 to v2.1.0 by @camilamacedo86 in https://github.com/kubernetes-sigs/kubebuilder/pull/4031
Note that the `--rm-dist` flag in GoReleaser was used to remove the dist directory before starting the release process. This ensured that any old build artifacts from previous runs were deleted, providing a clean environment for the new release.
Address the issue faced in the release of 4.1.1: https://github.com/kubernetes-sigs/kubebuilder/actions/runs/10054025442/job/27787845571
=> 🌱 fix error faced during release process by ensuring dist directory is cleaned before running GoReleaser

build/.goreleaser.yml
Follow up of: Update release.yml - Update goreleaser from 1.11.2 to v2.1.0 by @camilamacedo86 in https://github.com/kubernetes-sigs/kubebuilder/pull/4031
Address the warning: 
>   • only configurations files on version: 2 are supported, yours is version: 0, please update your configuration
See: https://github.com/kubernetes-sigs/kubebuilder/actions/runs/10054234782/job/27788445242
And update k8s version which was not the correct one
=> 🌱 Upgrade goreleaser

.github/workflows/release.yml, build/.goreleaser.yml
See the latest release: https://github.com/kubernetes-sigs/kubebuilder/actions/runs/10054397436/job/27788908893
=> 🌱 Update release branch with minor fixes/upgrades in GoReleaser to accomplish the latest release - 4.1.1.

docs/book/utils/markerdocs/html.go, docs/book/utils/markerdocs/main.go
This PR fixes the issue https://github.com/kubernetes-sigs/kubebuilder/issues/4044
Due to changes in the commit: https://github.com/kubernetes-sigs/kubebuilder/commit/bf42d50683595602edd28d56549ee33ef2df30cb, the build for the markerdocs application was failing.
For future reference, the error is being ignored in the build part of markerdocs app. 
https://github.com/kubernetes-sigs/kubebuilder/blob/f97e8734409a804e831d9863e625b18cbb08862d/docs/book/markerdocs.sh#L23C3-L24C1
I wasn't sure if the script was supposed to be fixed or not as the build failure is ignored.
The documentation for the CRD Generation screen in broken
=> 📖  Fix generation of markers based on controller-tools 

docs/book/src/SUMMARY.md, docs/book/src/reference/scopes.md
This PR add a required info to let users know what is API and Manager scope as how to manage them.
Closes; https://github.com/kubernetes-sigs/kubebuilder/issues/3623
=> 📖 Add crd-scope and operator-scope documentation

designs/template.md
This patch fixes a typo inside designs template.
"Implementeble" should be replaced by "Implementable".
Signed-off-by: gabriele-wolfox <gabriele.wolfox@gmail.com>
=> :book: Fix typo in designs template

pkg/plugin/util/util.go, test/e2e/utils/webhooks.go, test/e2e/v4/generate_test.go
This code implementation is valid only for the e2e tests and is not an Plugin Utils that can be used for those who consumes Kuebebuilder as a lib and should in this way be under tests/e2e/
=> ⚠️  (cleanup/fix): ImplementWebhooks method should only be used by the e2e tests and should be under its package

pkg/plugin/util/suite_test.go, pkg/plugin/util/testdata/exampleFile.txt, pkg/plugin/util/util_test.go
Have a suite test for the plugin utils and remove the need to have the testdata dir scaffolded
=> 🌱 (cleanup): cleanup tests for plugin/util functions

pkg/plugin/util/util_test.go
Just add tests to increase the coverage
=> 🌱 pkg/plugin/utils: add tests to cover funcs

docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml, hack/docs/internal/cronjob-tutorial/generate_cronjob.go
If the CRD are too big we will face ` Too long: must have at most 262144 bytes` when we run make install
More info: https://book.kubebuilder.io/faq#the-error-too-long-must-have-at-most-262144-bytes-is-faced-when-i-run-make-install-to-apply-the-crd-manifests-how-to-solve-it-why-this-error-is-faced
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4074
=> 📖  docs:samples:cronjob: change makefile to generate the CRD without description to allow apply CRDs

RELEASE.md, docs/book/src/reference/artifacts.md, docs/book/src/reference/envtest.md
This PR only update the Artifact docs in order to:
- Make clear the new location and that users should no longer use https://storage.googleapis.com/kubebuilder-tools
- Remove info from the deprecated location and keep it synced with the latest changes
More info: https://github.com/kubernetes-sigs/kubebuilder/discussions/4082
=> 📖 (cleanup and enhance) improve and make clear info about setup envtest and its binaries and that old location is deprecated

.github/workflows/test-devcontainer.yaml, docs/book/src/cronjob-tutorial/testdata/project/.devcontainer/devcontainer.json, docs/book/src/cronjob-tutorial/testdata/project/.devcontainer/post-install.sh, docs/book/src/getting-started/testdata/project/.devcontainer/devcontainer.json, docs/book/src/getting-started/testdata/project/.devcontainer/post-install.sh, pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go, test/check-license.sh, testdata/project-v4-multigroup-with-deploy-image/.devcontainer/devcontainer.json, testdata/project-v4-multigroup-with-deploy-image/.devcontainer/post-install.sh, testdata/project-v4-multigroup/.devcontainer/devcontainer.json, testdata/project-v4-multigroup/.devcontainer/post-install.sh, testdata/project-v4-with-deploy-image/.devcontainer/devcontainer.json, testdata/project-v4-with-deploy-image/.devcontainer/post-install.sh, testdata/project-v4-with-grafana/.devcontainer/devcontainer.json, testdata/project-v4-with-grafana/.devcontainer/post-install.sh, testdata/project-v4/.devcontainer/devcontainer.json, testdata/project-v4/.devcontainer/post-install.sh
[3432](https://github.com/kubernetes-sigs/kubebuilder/issues/3432)
This PR add the functionality of generating DevContainer configuration files along with rest of the Kubebuilder project during scaffolding.
DevContainer is an Open Source tool which allows users consolidate their development environment into single container image. This image then can be shared across any environment by anyone. DevContainers can then be launched using any IDE including VSCode. Github's CodeSpaces uses the same tech underline.
In the context of Kubebuilder, having a DevContainer with Kind, Go, and Kubebuilder will allow any user to readily test their Operator's changes without installing any of the tools explicitly, thereby saving the time.
=> ✨ (go/v4): Added DevContainer support for seamless development in environments like GitHub Workspaces without local setup.

docs/book/src/quick-start.md
Now that we have the Getting Started guide, which provides a solid overview, the most appropriate next step seems to be following this guide. Lastly, we are removing the note from the DeployImage section as it doesn't seem to fit well on this page.
=> :book: update the next step from quick start accordingly

docs/book/src/cronjob-tutorial/running-webhook.md, docs/book/src/cronjob-tutorial/running.md, docs/book/src/getting-started.md, docs/book/src/quick-start.md
This pull request includes several small but important improvements to the documentation, aimed at enhancing clarity and providing additional resources:
- Added a link to the CronJob Tutorial in the "Next Steps" section of the Getting Started guide.
- Fixed minor issues with documentation headings and improved consistency in the Quick Start guide.
- Clarified the need to push images in the Running guide with an added note.
- Recommended using Kind for testing in the Getting Started guide.
- Corrected a typo in the link to the Kind guide.
- Added a brief note in the "Next Steps" section about the Deploy Image plugin to offer further guidance.
=> :book: Minor Documentation Improvements: Add Links, Fix Typos, and Clarify Instructions

.github/workflows/verify.yml, hack/ci/pr_title_checker.sh
The kubebuilder-release-tools project is no longer really maintained. The image required for checks is deprecated due 
the infrastructure used to build and promote it be deprecated. Given the minimal nature of the check, it's unnecessary to maintain a GitHub Action for this purpose.
Also, it broke 1 day ago. Note that we need to pass permissions via GitHub Token, which is not very safe. This is another reason why we need to proceed with these changes.
**When it fails:**
**When the check pass:**
=> 🌱 (ci) - Fix the job to check the PR title and no longer use deprecated github action

docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller_test.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go, testdata/project-v4-with-deploy-image/internal/controller/busybox_controller_test.go, testdata/project-v4-with-deploy-image/internal/controller/memcached_controller_test.go
NIT: Just fix the name/term in the controller-test scaffolds which are done by the plugin.
=> :bug: (deploy-image/v1-alpha1): Fix typo issue by replacing typeNamespaceName with typeNamespacedName

docs/book/src/multiversion-tutorial/tutorial.md
We are in the k8s release 1.31 and we just support N-3 versions
We need doc future-gates but this note does not seems appropriate any more.
=> :book: remove warning note which was valid for old k8s versions

docs/book/src/getting-started/testdata/project/config/samples/cache_v1alpha1_memcached.yaml, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/config/samples/crd_sample.go, testdata/project-v4-with-deploy-image/config/samples/example.com_v1alpha1_busybox.yaml, testdata/project-v4-with-deploy-image/config/samples/example.com_v1alpha1_memcached.yaml
The config/sample generated when we are using the plugin was missing the labels
````yaml
labels:
app.kubernetes.io/name: {{ .ProjectName }}
app.kubernetes.io/managed-by: kustomize
```
=> :bug: (deploy-image/v1-alpha1): Fix sample by ensuring the right labels

docs/book/src/cronjob-tutorial/new-api.md, docs/book/src/cronjob-tutorial/webhook-implementation.md, docs/book/src/migration/legacy/migration_guide_v2tov3.md, docs/book/src/reference/generating-crd.md, docs/book/src/reference/webhook-overview.md
Those flgas were added to allow users still using the versions v1beta1 which is no longer supported and prvided since k8s 1.22 and were deprecated a long time ago and cannot be used with go/v4. Those are removed since is no longer possible to support those older version with the dependencies versions used currently. More info: https://github.com/kubernetes-sigs/kubebuilder/discussions/3622
=> :book: remove notes about crd-version and webhook-version flags which are no longer supported and provided 

docs/book/src/SUMMARY.md
Just fix the link it is broken
=> :book: fix link for reference doc to manager and crd scopes

docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go, pkg/plugins/golang/v4/scaffolds/internal/templates/main.go, testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/destroyer_webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v1beta1/frigate_webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook.go, testdata/project-v4-multigroup-with-deploy-image/cmd/main.go, testdata/project-v4-multigroup/api/crew/v1/captain_webhook.go, testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook.go, testdata/project-v4-multigroup/api/ship/v1beta1/frigate_webhook.go, testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook.go, testdata/project-v4-multigroup/api/v1/lakers_webhook.go, testdata/project-v4-multigroup/cmd/main.go, testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook.go, testdata/project-v4-with-deploy-image/cmd/main.go, testdata/project-v4/api/v1/admiral_webhook.go, testdata/project-v4/api/v1/captain_webhook.go, testdata/project-v4/api/v1/firstmate_webhook.go, testdata/project-v4/cmd/main.go
This PR fix the following issues:
```
$ make lint
testdata/project-v4/bin/golangci-lint run
cmd/main.go:154:37: string  has 3 occurrences, make it a constant (goconst)
if os.Getenv(ENABLE_WEBHOOKS) != false {
^
api/v1/firstmate_webhook.go:25:5: var  is unused (unused)
var firstmatelog = logf.Log.WithName(firstmate-resource)
```
=>  🐛  (go/v4): Fix linter issues in the scaffold 

docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go, testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go, testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
This PR fixes the following issues:
```
$ make lint
testdata/project-v4-with-deploy-image/bin/golangci-lint run
internal/controller/busybox_controller.go:338:6: comment-spacings: no space between comment delimiter and comment text (revive)
//Affinity: &corev1.Affinity{
^
internal/controller/busybox_controller.go:359:6: comment-spacings: no space between comment delimiter and comment text (revive)
//},
^
internal/controller/memcached_controller.go:338:6: comment-spacings: no space between comment delimiter and comment text (revive)
//Affinity: &corev1.Affinity{
^
internal/controller/busybox_controller.go:400:23: `labelsForBusybox` - `name` is unused (unparam)
func labelsForBusybox(name string) map[string]string {
^
internal/controller/memcached_controller.go:406:25: `labelsForMemcached` - …
```
=> 🐛 (deployimage/v1apha1): fix linter issues

docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/getting-started/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_suite_test.go, testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go, testdata/project-v4-multigroup/Makefile, testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-deploy-image/test/e2e/e2e_suite_test.go, testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go, testdata/project-v4-with-grafana/Makefile, testdata/project-v4-with-grafana/test/e2e/e2e_suite_test.go, testdata/project-v4-with-grafana/test/e2e/e2e_test.go, testdata/project-v4/Makefile, testdata/project-v4/test/e2e/e2e_suite_test.go, testdata/project-v4/test/e2e/e2e_test.go
- Ensure that kind is installed and running before run the tests. Otherwise it will fail since we need to load the Manager(Operator) image
- Add logic to skip the installation of CertManager and/or Prometheus via envvars.
- Ensure that the promethues and certmanager are installed in the suite test instead of beafore each test
- Ensure that the image is build and load in the suite instead instead for each test
- Add more comments to clarify the purpose of the tests
- Add TODO(user) to clarify that is expected action for the users to suplement and/or customize their e2e tests according to their needs
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4089
c/c  @DerekTBrown, @majewsky  @TAM360 @defo89
=> :sparkles: (go/v4) e2e tests: improve e2e tests and make test-e2e target

.github/workflows/lint-sample.yml
The lint sample should only run the lint checks for the samples
Either, make no sense we run for all of them. We can ensure all plugins by just running project-v4 and project-v4-with-deploy-image which has further code scafold. By last, see that the `make tests` are called in the prow already.
=> 🌱  ci- cleanup lint samples

.github/workflows/test-e2e-samples.yml, docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go, testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_suite_test.go, testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go, testdata/project-v4-with-deploy-image/test/e2e/e2e_suite_test.go, testdata/project-v4-with-grafana/test/e2e/e2e_suite_test.go, testdata/project-v4/test/e2e/e2e_suite_test.go
We are running make manifests and make generate in the github action when those should be called by the e2e tests since we can trigger those locally, for example, from IDE to troubleshooting
=> 🐛 (go/v4): fix test e2e by ensuring that make manifests and generate are executed as part of the tests

.github/workflows/test-e2e-samples.yml
For the DeployImage sample, we are only using validating webhooks. 
This commit updates the scaffold to reflect this by customizing 
the configuration accordingly.
Additionally, there is a known bug in the tool where it scaffolds 
uncommented data for MutatingWebhooks. As a workaround, this commit 
comments out the unnecessary MutatingWebhook configurations to avoid 
issues during the test execution.
=> 🌱 ci: fix GitHub action to test make test-e2e for deploy-image

docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup-with-deploy-image/Makefile, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-deploy-image/Makefile, testdata/project-v4-with-grafana/Makefile, testdata/project-v4/Makefile
Ensure consistency across targets by adding calls to manifests, generate, fmt, and vet before running tests.
=> 🐛 fix: ensure that make test-e2e call the same targets of make test

docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go, testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go, testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
Added detailed comments in the SetupManager scaffold within the controller to explain how the resource watching and reconciliation process works. These comments clarify how the controller watches for changes in Custom Resources and Deployments, ensuring that the cluster maintains the desired state.
=> :sparkles: (deploy-image/v1-alpha1): Add comments to clarify resource watching and reconciliation logic

docs/book/src/getting-started.md, docs/book/src/getting-started/testdata/project/PROJECT, docs/book/src/getting-started/testdata/project/api/v1alpha1/memcached_types.go, docs/book/src/getting-started/testdata/project/cmd/main.go, docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml, docs/book/src/getting-started/testdata/project/config/manager/manager.yaml, docs/book/src/getting-started/testdata/project/config/samples/cache_v1alpha1_memcached.yaml, docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go, docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller_test.go, hack/docs/internal/getting-started/generate_getting_started.go
- Refined the sample code implementation to keep it minimal, helping users better understand the core concepts.
- Properly implement automation to generate the sample
- Streamlined the guide by focusing on the main information and removing extraneous details.
- Ensured that the code and samples in the guide are consistent with the generated project.
- Simplified navigation by hiding the full code, making it easier for users to follow along.
- Replaced the use of the deploy image plugin with direct commands to provide more comprehensive and straightforward information.
=> 📖 Improve and Simplify the Getting Started Guide

docs/book/src/reference/webhook-for-core-types.md
Closes: https://github.com/kubernetes-sigs/kubebuilder/pull/3399
also, closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1241
=> 📖  update and supplement webhook documentation with example to work with core types

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_suite_test.go, testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go, testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go, testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-deploy-image/test/e2e/e2e_suite_test.go, testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go, testdata/project-v4-with-deploy-image/test/utils/utils.go, testdata/project-v4-with-grafana/test/e2e/e2e_suite_test.go, testdata/project-v4-with-grafana/test/e2e/e2e_test.go, testdata/project-v4-with-grafana/test/utils/utils.go, testdata/project-v4/test/e2e/e2e_suite_test.go, testdata/project-v4/test/e2e/e2e_test.go, testdata/project-v4/test/utils/utils.go
Provide further improvements for e2e tests test to help users be aware of how to tests using the metrics endpoint and validate if the metrics are properly expose. Furthermore, shows how to use it to validate the reconciliation.
Closes: https://github.com/kubernetes-sigs/kubebuilder/pull/4124
Partially closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4120
=> :sparkles: (go/v4) Add Metrics Validation and Helper Functions to E2E Tests

docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go, docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook_test.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/cronjob-tutorial/webhook_implementation.go, pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_test_template.go, testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook_test.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/destroyer_webhook_test.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v1beta1/frigate_webhook_test.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook_test.go, testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook_test.go, testdata/project-v4-multigroup/api/crew/v1/captain_webhook_test.go, testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook_test.go, testdata/project-v4-multigroup/api/ship/v1beta1/frigate_webhook_test.go, testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook_test.go, testdata/project-v4-multigroup/api/v1/lakers_webhook_test.go, testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook_test.go, testdata/project-v4/api/v1/admiral_webhook_test.go, testdata/project-v4/api/v1/captain_webhook_test.go, testdata/project-v4/api/v1/firstmate_webhook_test.go
In this PR we are improving the webhook tests by adding further info and examples for the users. Either we are implementing them further for the cronjob tutorial as an example and to help us to validate and spot issues on related areas when/if we need to change them
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3454
=> ✨ (go/v4): improve the webhook tests by adding examples. Also, improve cronjob tutorial to clarify its usage and validate the changes

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, pkg/plugins/golang/v4/scaffolds/webhook.go, testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go, testdata/project-v4-with-grafana/test/e2e/e2e_test.go, testdata/project-v4/test/e2e/e2e_test.go
A new scaffold marker is introduced to automatically adds end-to-end tests for webhooks in the test/e2e/test.go
The scaffolded tests include:
- Validation that cert-manager has successfully provisioned the secret, when/if an webhook is scaffold for the project.
- Verification that the CA bundle is injected into the mutating webhooks, if a mutating webhook is scaffolded.
- Verification that the CA bundle is injected into the validating webhooks, if a validating webhook is scaffolded.
PS.: See that a new maker `+kubebuilder:scaffold:e2e-webhooks-checks` is introduced to allow we add to the e2e tests the scaffolds only when users use kb create webhook accordinly. 
Partially closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4120
=> :sparkles: (go/v4) Add scaffold for e2e webhook checks

docs/book/src/getting-started.md, docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go, docs/book/src/plugins/creating-plugins.md, docs/book/src/plugins/deploy-image-plugin-v1-alpha.md, docs/book/src/reference/project-config.md, hack/docs/internal/getting-started/generate_getting_started.go, pkg/plugins/golang/deploy-image/v1alpha1/api.go, test/e2e/alphagenerate/generate_test.go, test/e2e/deployimage/generate_test.go, test/testdata/generate.sh, testdata/project-v4-with-deploy-image/PROJECT, testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
The memcached image fails to run when "-m=64" is passed to it.
We could either drop it, or replace it with "--memory-limit=64" which works.
When it runs, I get the error message 
``` sh
$ docker run --rm -it memcached:1.6.26-alpine3.19 memcached -m=64 -o modern -v
Cannot set item size limit higher than 1/2 of memory max.
```
=> 🌱 cleanup: Replace "-m=64" with "--memory-limit=64"

test/e2e/deployimage/generate_test.go, test/e2e/deployimage/plugin_cluster_test.go
Part of #4135
This commits cleans up "plugin_cluster_test.go" to be less verbose and use better use of Gomega's capabilities.
Notably, variables are used only when the output of some command is used later on in the test.  If we only assert things about the command output, it is generally in-lined.
Eventually functions are converted from `() error` to `(g Gomega)`, and Expects are converted to g.Expect inside the functions.  All offsets have been removed, since this isn't "helper" code, we want to know which line the test failed on.
Finally, the test for verifying available status has been fixed so that it checks the correct pod.
=> 🌱 cleanup plugin_cluster-test.go

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go, testdata/project-v4-with-grafana/test/e2e/e2e_test.go, testdata/project-v4/test/e2e/e2e_test.go
Some of the calls to Gomega's assertions are unneccessarily long; declaring variables, and checking both errors and values.  All of this can be done by Gomega itself.  This is part of #4135 
`Expect(func()).To(ContainSubstring("X"))` will 
* check that any err returned from the function is nil
* check that the first return value matches "X"
`Expect(func()).Error().To(HaveOccurred())` will 
* check that any err returned from the function is non-nil
* check that the first return value _is_ nil or zero.
=> ✨ (go/v4): cleanup: in e2e/test.go, make Gomega assertions more concise

docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go, hack/docs/internal/cronjob-tutorial/writing_tests_controller.go
Replaced some bespoke Eventually() signatures (e.g. func() bool and func() (int, error)) with the standard func(g Gomega), allowing gomega assertions to happen inside the Eventually().  I reworded the section just before the Eventually, to explain what it does, in the context of the new signature.
Generally you _expect_ something _to_ happen
and _eventually_, something _should_ happen.
This is a part of #4135.
=> 📖 cleanup: improves cronjob_controller_test.go gomega assertions

docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go, docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml, docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/destroyer_webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook.go, testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook.go, testdata/project-v4-multigroup-with-deploy-image/config/webhook/manifests.yaml, testdata/project-v4-multigroup-with-deploy-image/dist/install.yaml, testdata/project-v4-multigroup/api/crew/v1/captain_webhook.go, testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook.go, testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook.go, testdata/project-v4-multigroup/api/v1/lakers_webhook.go, testdata/project-v4-multigroup/config/webhook/manifests.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook.go, testdata/project-v4-with-deploy-image/config/webhook/manifests.yaml, testdata/project-v4-with-deploy-image/dist/install.yaml, testdata/project-v4/api/v1/admiral_webhook.go, testdata/project-v4/api/v1/captain_webhook.go, testdata/project-v4/config/webhook/manifests.yaml, testdata/project-v4/dist/install.yaml
Adjust webhook names for mutating and validating webhooks to avoid conflicts when creating multiple versions of the same API. 
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4144
=> 🐛 (go/v4) resolve duplicate webhook name issue in multi-version API

docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook_test.go, docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook_test.go, docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook_test.go, hack/docs/internal/cronjob-tutorial/webhook_implementation.go, pkg/plugins/golang/v4/scaffolds/internal/templates/api/webhook_test_template.go, testdata/project-v4-multigroup-with-deploy-image/api/crew/v1/captain_webhook_test.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v1/destroyer_webhook_test.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v1beta1/frigate_webhook_test.go, testdata/project-v4-multigroup-with-deploy-image/api/ship/v2alpha1/cruiser_webhook_test.go, testdata/project-v4-multigroup-with-deploy-image/api/v1/lakers_webhook_test.go, testdata/project-v4-multigroup/api/crew/v1/captain_webhook_test.go, testdata/project-v4-multigroup/api/ship/v1/destroyer_webhook_test.go, testdata/project-v4-multigroup/api/ship/v1beta1/frigate_webhook_test.go, testdata/project-v4-multigroup/api/ship/v2alpha1/cruiser_webhook_test.go, testdata/project-v4-multigroup/api/v1/lakers_webhook_test.go, testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_webhook_test.go, testdata/project-v4/api/v1/admiral_webhook_test.go, testdata/project-v4/api/v1/captain_webhook_test.go, testdata/project-v4/api/v1/firstmate_webhook_test.go
The webhook scaffold had some oddly indented regions, resulting in the generated source code having a mix of tabs and spaces, and was generally looking quite ugly.
The gomega asserions are too chatty; errors, and return values are checked after first being assigned as variables in scope.  This is not needed, and Gomega checks all of this for us:
* Expect(someFunc()).Error().To(HaveOccurred()) checks both the error, but also that the other return values are zero or nil.
* Expect(someFunc()).To(ContainSubstring("X")) checks both the return value _and_ verifies that the error is nil.
Fixes #4148.  Part of #4135.
- Fixes odd indentation, now it is in line with the other scaffolds
- Simplifies gomega assertions, to use fewer statements
- Updated the cronjob tutorial's tests too
=> 🐛 Enhances the webhook test template.

docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_webhook.go, docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml, docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go, docs/book/src/multiversion-tutorial/testdata/project/config/webhook/manifests.yaml, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/cronjob-tutorial/webhook_implementation.go
Apply the fix introduced in PR #4122. The default markers in the code have been replaced with the values defined in the hack/docs, but this change was missed in the tutorial samples.
=> 📖 fix marker for webhook server in the tutorial samples and position of explanations

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, testdata/project-v4-multigroup-with-plugins/test/e2e/e2e_test.go, testdata/project-v4-with-plugins/test/e2e/e2e_test.go, testdata/project-v4/test/e2e/e2e_test.go
Refactors all test cases that use g.Expect(utils.Run(cmd)) to improve both the readability of logs and the clarity of the code.
Changes:
- Replaced occurrences of g.Expect(utils.Run(cmd)) with:
```go
output, err := utils.Run(cmd)
g.Expect(err).NotTo(HaveOccurred())
g.Expect(string(output)).To(<condition>)
```
OR
```go
_, err := utils.Run(cmd)
g.Expect(err).NotTo(HaveOccurred())
```
**Motivation**
- **Human-readable logs:** Output is now converted to a string, providing more understandable logs by displaying actual kubectl command results instead of raw byte arrays.
- **Improved code clarity:** The previous `g.Expect(utils.Run(cmd))` usage did not make it clear that the function returns both output and error. By explicitly handling the output and err variables, the code is more transparent …
=> :bug: (go/v4): Refactor e2e-tests for clearer error handling and readable logs

docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go, docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go, docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go, pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/apps/deployment_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/crew/captain_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/example.com/busybox_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/example.com/memcached_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/fiz/bar_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/foo.policy/healthcheckpolicy_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/foo/bar_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/sea-creatures/kraken_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/sea-creatures/leviathan_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/ship/cruiser_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/ship/destroyer_controller.go, testdata/project-v4-multigroup-with-plugins/internal/controller/ship/frigate_controller.go, testdata/project-v4-with-plugins/internal/controller/busybox_controller.go, testdata/project-v4-with-plugins/internal/controller/memcached_controller.go, testdata/project-v4/internal/controller/admiral_controller.go, testdata/project-v4/internal/controller/captain_controller.go, testdata/project-v4/internal/controller/firstmate_controller.go
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4161
=> :bug: fix: ensure unique controller names to fix name conflicts in multigroup setup

docs/book/src/reference/raising-events.md
There is no need for `fmt.Sprintf` since `EventRecorder` already has `Eventf` method that accepts formatting string
=> 📖 Simplify event recording example

docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml, docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/test-e2e.yml, docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/test.yml, docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml, docs/book/src/getting-started/testdata/project/.github/workflows/test-e2e.yml, docs/book/src/getting-started/testdata/project/.github/workflows/test.yml, docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml, docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/test-e2e.yml, docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/test.yml, pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/internal/templates/github/lint.go, pkg/plugins/golang/v4/scaffolds/internal/templates/github/test-e2e.go, pkg/plugins/golang/v4/scaffolds/internal/templates/github/test.go, test/check-license.sh, testdata/project-v4-multigroup-with-plugins/.github/workflows/lint.yml, testdata/project-v4-multigroup-with-plugins/.github/workflows/test-e2e.yml, testdata/project-v4-multigroup-with-plugins/.github/workflows/test.yml, testdata/project-v4-with-plugins/.github/workflows/lint.yml, testdata/project-v4-with-plugins/.github/workflows/test-e2e.yml, testdata/project-v4-with-plugins/.github/workflows/test.yml, testdata/project-v4/.github/workflows/lint.yml, testdata/project-v4/.github/workflows/test-e2e.yml, testdata/project-v4/.github/workflows/test.yml
Within the changes of this PR new projects will become to be scaffold with GitHub actions which will allow users be aware of how to test their changes on the ci.
Either will make clear the purpose of the test-e2e and encorage common/best practices to ensure the quality of the properties
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4088
=> :sparkles: (go/v4) Add GitHub Actions

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-with-plugins/test/e2e/e2e_test.go, testdata/project-v4/test/e2e/e2e_test.go
BeforeAll func was missing the changes done in the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/4158
=> 🐛 (go/v4): Follow -up: Refactor e2e-tests for clearer error handling and readable logs

docs/book/src/getting-started.md
The documentation is actually trying to explain predicates.
Therefore, should not be linked in the Getting Started tutorial.
=> :book: remove from getting started the link for watching resources since this doc acctually document predicates

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-plugins/test/e2e/e2e_test.go, testdata/project-v4-with-plugins/test/utils/utils.go, testdata/project-v4/test/e2e/e2e_test.go, testdata/project-v4/test/utils/utils.go
- Gather logs, events, and pod descriptions when tests fail
- utils.Cmd returning string instead of []bytes for code simplification
The changes allow us to have the data to debug and identify the issues: https://github.com/kubernetes-sigs/kubebuilder/actions/runs/10878247989/job/30180826578?pr=4171
=> ✨ (go/v4): e2e tests: add data collection on failures and code simplification

README.md
…ngs are scheduled but most syncing happens offline via Slack
We haven't been holding the meetings due to a lack of topics on the agenda, and we've been syncing more frequently offline. This message is just to clarify how we're currently working.
=> :book: Update README.md - Clarify that monthly Kubebuilder sync meetings are scheduled but most syncing happens offline via Slack

pkg/model/resource/utils.go, pkg/model/resource/utils_test.go, test/e2e/utils/test_context.go
The APIPackagePathLegacy function was useful in older scaffolds to ensure backward compatibility. However, with the release of version 4.0.0, all deprecated features have been removed. As a result, this function should no longer be present
=> 🐛 cleanup: remove func APIPackagePathLegacy which is no longer used since release 4.0.0

docs/book/src/SUMMARY.md
It does not bring value for the docs. Therefore, we are removing it
=> 📖 (doc) remove from menu Appendix: The TODO Landing Page

docs/book/src/reference/platform.md
The usage of kube-rbac-proxy was discontinue and the image is no longer build or promoted by the project. Therefore, this section needs to be removed to avoid misleadings. More info: https://github.com/kubernetes-sigs/kubebuilder/discussions/3907
=> 📖 (doc): remove section in the platform documentation which says that kube-rbac-proxy is an image provided by default

pkg/plugin/util/util.go, pkg/plugins/common/kustomize/v2/scaffolds/api.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
The HasFragment method was mistakenly added, leading to code duplication. The existing HasFileContentWith method already handles the same functionality, so HasFragment has been removed to avoid redundancy.
=> ⚠️ 🐛fix: remove duplicate HasFragment method, replaced by HasFileContentWith

docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller_test.go, hack/docs/internal/getting-started/generate_getting_started.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go, testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller_test.go, testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller_test.go, testdata/project-v4-with-plugins/internal/controller/busybox_controller_test.go, testdata/project-v4-with-plugins/internal/controller/memcached_controller_test.go
Motivation: #4135 
* To(Not()) → NotTo()  (It seems that NotTo is used a lot elsewhere in the repository)
* Use default eventually timeouts, so we don't need to send them everywhere
* Eventually(func() error) → Eventually(func(g Gomega)) And then use g.Expect inside those Eventually() functions
* Use Gomega assertions for the condition check, which is more robust
=> ✨ (deploy-image/v1alpha): Improve tests scaffolded for the controllers

docs/book/src/migration/migration_guide_gov3_to_gov4.md
Clarify where to migrate the controllers to in the go/v3 to go/v4 migration guide.
=> 📖 docs: update migration_guide_gov3_to_gov4.md

docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, test/e2e/utils/test_context.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-plugins/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
Upgrade cert-manager  version used for the tests from v1.14.4 to v1.16.0
=> ✨ Upgrade cert-manager  version used on the tests from v1.14.4 to v1.16.0

docs/book/src/reference/using_an_external_resource.md
Fix layout and ensure that it has only documented info
=> 📖  small fixes for the doc Using External Resources

pkg/cli/alpha/command.go, pkg/cli/alpha/internal/generate.go
- Refactored the code implementation to improve error handling, encapsulate logic, and streamline execution flow.
- Moved the code implementation from `pkg` to the CLI since it pertains directly to a command.
- Additionally, moved the implementation to `internal` to prevent exposing the `Generate` code and avoid unintentional extensions on this alpha feature.
**Motivation**
Ensure better maintenance ability
Not allow unintentional extensions on this alpha feature.
=> ⚠️ cleanup/refactor: Alpha Generate command

docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, test/e2e/utils/test_context.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-plugins/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
Upgrade Prometheus Operator version used on the tests from v0.72.0 to 0.77.1
=> ✨ Upgrade Prometheus Operator version used on the tests from v0.72.0 to 0.77.1

roadmap/roadmap_2024.md
The current scaffold is using the new interfaces and no longer the methods which are not supported.
See that the changes were done in the following PRs:
- (go/v4): Replaced the deprecated webhook.Validator and webhook.Defaulter interfaces with CustomValidator and CustomDefaulter. Projects using the old interfaces must migrate to ensure compatibility with future versions. (https://github.com/kubernetes-sigs/kubebuilder/pull/4060)
- (go/v4): Webhooks are now decoupled from the API directory. Webhook files should be moved from api/<version> or api/<group>/<version> to internal/webhook/<version> or internal/webhook/<group>/<version>. This restructuring improves project organization. (https://github.com/kubernetes-sigs/kubebuilder/pull/4150)
=> 📖 Update roadmap_2024.md - Complete goal to align webhook scaffold with the latest changes in controller-runtime

docs/book/src/reference/using_an_external_resource.md, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, pkg/plugins/golang/v4/webhook.go, test/testdata/generate.sh, testdata/project-v4-multigroup/PROJECT, testdata/project-v4-multigroup/cmd/main.go, testdata/project-v4-multigroup/config/crd/patches/cainjection_in_certmanager_issuers.yaml, testdata/project-v4-multigroup/config/crd/patches/webhook_in_certmanager_issuers.yaml, testdata/project-v4-multigroup/config/webhook/manifests.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-multigroup/internal/webhook/certmanager/v1/issuer_webhook.go, testdata/project-v4-multigroup/internal/webhook/certmanager/v1/issuer_webhook_test.go, testdata/project-v4-multigroup/internal/webhook/certmanager/v1/webhook_suite_test.go, testdata/project-v4/PROJECT, testdata/project-v4/cmd/main.go, testdata/project-v4/config/crd/patches/cainjection_in_issuers.yaml, testdata/project-v4/config/crd/patches/webhook_in_issuers.yaml, testdata/project-v4/config/webhook/manifests.yaml, testdata/project-v4/dist/install.yaml, testdata/project-v4/internal/webhook/v1/issuer_webhook.go, testdata/project-v4/internal/webhook/v1/issuer_webhook_test.go
This PR addresses the creation of webhooks for external types. 
For further discussion, please refer to this issue: [#4201](https://github.com/kubernetes-sigs/kubebuilder/issues/4201).
Motivation: https://github.com/kubernetes-sigs/kubebuilder/pull/4176
=> ✨ Add support to scaffold controllers for External Types

.github/workflows/release.yml
We found an issue to publish the assets when we are trying to publish the release 4.3.0. Therefore, we are adding the content permission to verify if the issue can be solved within. More info: https://kubernetes.slack.com/archives/C01672LSZL0/p1729570852721079
=> 🌱 fix GoReleaser by adding permission to write content

test/testdata/generate.sh, testdata/project-v4-multigroup/PROJECT, testdata/project-v4-multigroup/config/manager/manager.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-plugins/PROJECT, testdata/project-v4-with-plugins/config/manager/manager.yaml, testdata/project-v4-with-plugins/dist/install.yaml
We generate a sample API in the testdata directory using the DeployImage plugin. However, the flag previously contained incorrect information regarding the image that should be used. This fix ensures the correct image is referenced.
=> 🌱 Fix incorrect image reference for DeployImage plugin in test data

.github/workflows/release.yml
🌱 Upgrade GoReleaser version from v2.1.0 to v2.3.2 used in the GitHub action
=> 🌱 Upgrade GoReleaser version from v2.1.0 to v2.3.2 used in the GitHub action

docs/book/install-and-build.sh
The documenation for the markers are generated automatic. The project currently scaffold solutions using controller-gen 0.16.4 therefore the documentation should either be generated using this version
=> :book: Upgrade controller-gen version used to generate documentation

pkg/plugins/golang/v4/scaffolds/api.go, pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go, pkg/plugins/golang/v4/scaffolds/webhook.go
Moves main.go boilerplate to the cmd/ directory to align the project structure with scaffolded templates, ensuring consistency and maintainability.
=> 🐛 fix internal layout: move main.go boilerplate to cmd/ directory

docs/book/install-and-build.sh, docs/book/theme/css/custom.css, docs/book/theme/index.hbs
📖 Fix CSS and Toggle Issues in Navigation and Sidebar
Description of the Change: This PR addresses two key issues related to the navigation and sidebar components:
Fixes a CSS styling issue affecting the appearance of the navigation bar.
Resolves a functionality issue with the sidebar toggle, ensuring that it operates as expected.
Related Issue: #4240 
Closes: https://github.com/kubernetes-sigs/kubebuilder/pull/4239
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4240
=> :book: Resolve navigation bar CSS issue and sidebar toggle functionality.

.github/dependabot.yml
- Remove configurations for deprecated branches no longer in use
- Change schedule to perform checks daily for up-to-date dependency management
- Ensure dependencies in sample projects are properly included in checks
Motivated by: https://github.com/kubernetes-sigs/kubebuilder/issues/3712
=> 🌱 Update Dependabot configuration

.github/dependabot.yml
The go.mod check for sample configuration helps us identify potential required bumps. However, note that go.mod is often updated by controller-runtime, so we can't manually change certain dependencies.
Additionally, we only need to check one sample project—there’s no need to duplicate efforts by opening the same PR across all samples.
Follow up of : https://github.com/kubernetes-sigs/kubebuilder/pull/4249
=> :seeding: Update dependabot.yml to just raise PRs against project-v4 sample

docs/book/src/SUMMARY.md, docs/book/src/quick-start.md, docs/book/src/versions_compatibility_supportability.md
The Quick Start now has a note that links its page. The info is too verbose and might be not helpful and it is scaring for those that are looking for a Quick Start. Furthermore add relevant info regards Project Customisation on this section.
=> 📖 move Versions Compatibility and Supportability info to a dedicated page

docs/book/src/reference/metrics.md
TLSOpts info was not accurate. Simplified the information to ensure accuracy in production setup notes and fixed grammar issues for readability and precision.
=> 📖 Correct misleading information in production note for metrics config

pkg/cli/alpha/command.go
Added comments to `NewScaffoldCommand` to clarify that the `kubebuilder alpha generate` command is designed for Kubebuilder’s internal use only.
The updated go documentation explains that importing this command into other projects is not supported, as it relies on Kubebuilder-specific configurations, key mappings, and plugins, which may not be applicable to other setups.
Projects that use Kubebuilder as a library and require similar functionality should implement a custom solution for compatibility with their specific configurations and plugins.
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4200
=> 🐛 clarify usage of alpha generate command as internal-only

.github/workflows/release.yml, build/.goreleaser.yml
- Integrated SBOM generation in GoReleaser using Syft to produce CycloneDX SBOMs.
- Updated GitHub Actions workflow to install Syft, enabling automated SBOM creation on release.
- This enhancement is part of ongoing efforts to align with the EU Cyber Resilience Act, ensuring transparency and security in our software supply chain.
Motivated by: https://github.com/kubernetes-sigs/kubebuilder/issues/3712
=> 🌱 Add SBOM generation for Cyber Resilience Act compliance

.github/workflows/codeql.yml
This workflow introduces CodeQL to automatically scan the project for security vulnerabilities, supporting efforts to maintain a secure codebase. It also helps us comply with standards like the Cybersecurity Certification Act (CCA) by ensuring continuous security monitoring.
Motivated by: https://github.com/kubernetes-sigs/kubebuilder/issues/3712
=> 🌱 Add GitHub workflow to scan project with CodeQL

pkg/plugins/golang/v4/webhook.go
Standardize resource generation options by adding the `--make=false` flag to `kubebuilder create webhook`, aligning it with the existing API creation process. This option is essential in scenarios such as project scaffolding, where running `make` commands immediately is deferred to allow modifications to generated files before execution.
=> 🐛 fix: ensure --make=false option is available for webhook creation for consistency

.github/workflows/codeql.yml
Follow up of : https://github.com/kubernetes-sigs/kubebuilder/pull/4252
We do not want to run for each Pull Request.
Execute it once per week is more than enough
=> 🌱 Update codeql.yml to run the workflow once per week only

docs/book/src/quick-start.md
- Updated the Quick Start guide to include details on how to work with the master branch.
- Linked to the contributing guide for building Kubebuilder locally.
=> 📖 fix(docs): update Quick Start guide with information on using the master branch

docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/manager/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml, docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml, docs/book/src/getting-started/testdata/project/config/manager/kustomization.yaml, docs/book/src/getting-started/testdata/project/dist/install.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/manager/kustomization.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/cronjob-tutorial/sample.go, hack/docs/internal/getting-started/generate_getting_started.go, hack/docs/internal/multiversion-tutorial/generate_multiversion.go, hack/docs/internal/multiversion-tutorial/kustomize.go
Introduces a bundle installer for sample projects, with config/default/kustomization.yaml settings uncommented to ensure complete bundle generation. This enhances review visibility by showing the final state of patches and Kustomize configurations directly in the generated bundle.
Motivation: Makes reviews more efficient by displaying final configurations directly in the bundle, with only relevant settings uncommented in config/default/kustomization.yaml for each sample.
=> 🌱 Add bundle installer for sample projects in docs

.github/workflows/test-e2e-samples.yml, docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/cronjob-tutorial/sample.go, hack/docs/internal/multiversion-tutorial/kustomize.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go, test/e2e/v4/generate_test.go, testdata/project-v4-multigroup/config/default/kustomization.yaml, testdata/project-v4-with-plugins/config/default/kustomization.yaml, testdata/project-v4/config/default/kustomization.yaml
- Relocated the cert-manager setup block (kind: Service, version: v1, name: webhook-service) to improve user experience since this one must be uncommented always and was hard to identify as it was organized previously.
- Change only affects new projects.
=> 🐛 (kustomize/v2,go/v4): Move cert-manager uncomment block to top of kustomization.yaml for better visibility in new projects

pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook.go, pkg/plugins/golang/v4/webhook.go, test/e2e/v4/generate_test.go, test/e2e/v4/plugin_cluster_test.go
Attempting to create multiple webhooks for the same resource with different configurations (e.g., `--defaulting` and `--programmatic-validation`) resulted in an error indicating that the webhook already exists.
This update allows multiple webhook types to be scaffolded for a single resource without conflict. Users can scaffold different webhooks for the same GKV afterwards without needing to do so all at once, as expected.
Either we are adding tests to cover the webhook undergo/v4 conversion type.
The tests are scaffolding the conversion webhook after the defaulting and validation were created already.
Therefore, we are validating the fix done in this PR. 
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4146
=> :bug: (go/v4) Fix issue with scaffolding multiple webhooks for the same resource

docs/book/src/getting-started.md
make generate does not generate the CRDs in config/crd/base the correct command to accomplish this is make manifests. See Makefile:
```
generate: controller-gen  ## Generate code (deepcopy)
$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
manifests: controller-gen  ## Generate manifests (CRDs, RBAC, etc.)
$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```
fixes: #4305
=> 📖 (doc): getting started: fix information about make command for generating manifests

pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook.go, pkg/plugins/golang/v4/webhook.go
We are reverting the changes done in the PR #4286. We are just keeping the e2e tests improvements.
We will not able to solve the issue https://github.com/kubernetes-sigs/kubebuilder/issues/4146 without add new markers.
We cannot skip the action to write an webhook since it will result in incomplete inplementation in the <kind>_webhook.go as in the <kind>_webhook_test.go
=> :bug: revert the changes done in the PR #4286

docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml, docs/book/src/getting-started/testdata/project/config/manager/manager.yaml, docs/book/src/getting-started/testdata/project/dist/install.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go, test/e2e/v4/generate_test.go, test/e2e/v4/plugin_cluster_test.go, testdata/project-v4-multigroup/config/manager/manager.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-plugins/config/manager/manager.yaml, testdata/project-v4-with-plugins/dist/install.yaml, testdata/project-v4/config/manager/manager.yaml, testdata/project-v4/dist/install.yaml
- Removed the comment about `seccompProfile` as `type: RuntimeDefault` is now set by default.
- Updated to reflect that Kubebuilder only tests and supports the latest three Kubernetes releases.
- Given that we’re currently using Kubernetes 1.31, there’s no longer a reason to keep this line commented, ensuring projects adhere to `restricted` Pod Security Standards by default.
- Either OCP 4.10 is in EOL already: https://endoflife.date/red-hat-openshift
=> :sparkles:  (go/v4): Enable `seccompProfile.type: RuntimeDefault` by default in scaffolded projects

docs/book/src/cronjob-tutorial/testdata/project/config/default/certmanager_metrics_manager_patch.yaml, docs/book/src/getting-started/testdata/project/config/default/certmanager_metrics_manager_patch.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/default/certmanager_metrics_manager_patch.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/certmanager_metrics_manager_patch.go, testdata/project-v4-multigroup/config/default/certmanager_metrics_manager_patch.yaml, testdata/project-v4-with-plugins/config/default/certmanager_metrics_manager_patch.yaml, testdata/project-v4/config/default/certmanager_metrics_manager_patch.yaml
This change ensures that only the necessary permissions are granted for accessing the metrics-server-cert secret. Note that setting defaultMode: 420 is not required.
=> ✨ Follow-up to PR #4243: Limit permissions to access the metrics-server-cert secret

README.md
Small fix of the README that contains an old url that were working in the [book-v3](https://book-v3.book.kubebuilder.io/plugins/creating-plugins.html) in the [Kubebuilder is also a library](https://github.com/kubernetes-sigs/kubebuilder/tree/master?tab=readme-ov-file#kubebuilder-is-also-a-library) section (how to create your own plugins).
The new url is the following: [https://book.kubebuilder.io/plugins/extending](https://book.kubebuilder.io/plugins/extending)
=> :book: Fix readme wrong url your-own-plugin

docs/CONTRIBUTING-ROLES.md
Small fix of the `docs/CONTRIBUTING-ROLES.md` that contains a typo `reasonble` instead of `reasonable`.
=> 📖 : Fix typo in contributing roles

Makefile
This PR is motivated by this issue: #4327.
It is a fix about the `make remove-spaces` command that was only working on OS X and not GNU based system. It is because the behavior of the `sed -i` command is different between these two systems (see [this stack exchange discussion](https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed/131940#131940)).
- On OS X: `sed -i ''`
- On GNU: `sed -i`
So I added a check by using `uname` to use the `sed -i` in the correct way depending if we are on GNU based system or on OS X based system.
=> 🌱 : Fix `make remove-spaces` for GNU system

Makefile
Reverts kubernetes-sigs/kubebuilder#4330
Broke the target (On Mac)
=> 🌱 : Revert Fix `make remove-spaces` for GNU system"

docs/book/src/plugins/extending/extending_cli_features_and_plugins.md
Relevant section: https://book.kubebuilder.io/plugins/extending/extending_cli_features_and_plugins#example
Fixed the broken URL and updated the code in the example to reflect the current API.
https://pkg.go.dev/sigs.k8s.io/kubebuilder/v4/pkg/plugin/util#InsertCode
=> 📖 small fixes to extending_cli_features_and_plugins.md

pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/helpers_tpl.go, testdata/project-v4-with-plugins/dist/chart/templates/_helpers.tpl
Looks like the value for "**_app.kubernetes.io/name:_**" is also not rendering properly. Can I add that fix in this PR as well? Or should I open a second one?
Edit: I created a new PR: https://github.com/kubernetes-sigs/kubebuilder/pull/4351
=> 🐛 fix: (helm/v1-alpha): Remove extra space before the labels section

pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/helpers_tpl.go, testdata/project-v4-with-plugins/dist/chart/templates/_helpers.tpl
The fix for the extra line after "**_labels:_**" is being fixed in this PR: https://github.com/kubernetes-sigs/kubebuilder/pull/4350
=> 🐛 fix: (helm/alpha-v1): Fix rendered value for app.kubernetes.io/name

testdata/project-v4-multigroup/go.mod, testdata/project-v4/go.mod
There was a release about 2 hours ago
https://github.com/cert-manager/cert-manager/releases/tag/v1.16.2
I guess this issue will eventually occur again if nothing is done to prevent it.
=> 🌱 fix: run make generate to fix ci

docs/book/src/reference/metrics.md
=> :book: follow up of update metrics documentation to bring more clarity #4358

README.md
The emoji did not rendered in a good way
=> 📖 Update README.md - Fix layout from notice

pkg/plugins/optional/helm/v1alpha/scaffolds/init.go, testdata/project-v4-with-plugins/dist/chart/templates/rbac/leader_election_role.yaml, testdata/project-v4-with-plugins/dist/chart/templates/rbac/leader_election_role_binding.yaml
I'm not sure this is the best approach but since there are already some hardcoded values in there I suppose it's not a terrible idea either.
The [Role](https://github.com/monteiro-renato/kubebuilder/blob/d0765c4eff32891f634183a2ab6487e8693b4c54/testdata/project-v4-with-plugins/config/rbac/leader_election_role.yaml) and [RoleBinding](https://github.com/monteiro-renato/kubebuilder/blob/d0765c4eff32891f634183a2ab6487e8693b4c54/testdata/project-v4-with-plugins/config/rbac/leader_election_role_binding.yaml) do not have a namespace associated with them when the project is `init`ed. I didn't actually try to deploy this but I believe this would actually fail to apply as is (without the namepace on the Role and RoleBinding - [src](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-a …
=> 🐛 fix: (helm/v1alpha1) add missing name prefix and namespace to leader-election-role and leader-election-rolebinding

Makefile
This PR is motivated by this issue: #4327.
It is a fix about the make remove-spaces command that was only working on OS X and not GNU based system. It is because the behavior of the sed -i command is different between these two systems (see [this stack exchange discussion](https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed/131940#131940)).
- On OS X: `sed -i ''`
- On GNU: `sed -i`
So I added a check by using `uname` to use the `sed -i` in the correct way depending if we are on GNU based system or on OS X based system.
This PR follows this one #4330 that was not working. So it got reverted here #4331. This PR should works correctly. I cannot test on a MAC since I only have a linux system.
This PR needs to be tested by someone that has a …
=> :seedling: Make `make remove-spaces` compatible with GNU and MAC OS X system

docs/book/src/getting-started.md
Fix a broken URL in [Getting Started](https://book.kubebuilder.io/getting-started#getting-started) related to the deploy plugin: 
[plugins/deploy-image-plugin-v1-alpha.html](https://book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html)   ->  
[plugins/available/deploy-image-plugin-v1-alpha](https://book.kubebuilder.io/plugins/available/deploy-image-plugin-v1-alpha)
=> 📖 Fix broken plugin URL in getting-started.md

pkg/plugins/optional/helm/v1alpha/edit.go
The force flag must have by default the value false. So that, we just overwritten the files when we it is informed
=> 🐛 (helm/v1alpha): fix default value of the force flag

docs/book/src/plugins/extending/extending_cli_features_and_plugins.md
You can see the 404 here: https://book.kubebuilder.io/plugins/extending/extending_cli_features_and_plugins#plugin-keys
(after clicking on the go.kubebuilder.io URL)
=> 📖 Fix: broken url in extending_cli_features_and_plugins.md

docs/book/src/plugins/extending/external-plugins.md
Relevant section > https://book.kubebuilder.io/plugins/extending/external-plugins#how-to-write-an-external-plugin
=> 📖 Fix: broken url in external-plugins.md

pkg/plugins/optional/helm/v1alpha/scaffolds/init.go, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/github/test_chart.go, testdata/project-v4-with-plugins/.github/workflows/test-chart.yml
Add action will help us and users validate the chart
See that it works: https://github.com/camilamacedo86/test-project/actions/runs/11971426907/job/33376226272
=> ✨ (helm/v1alpha1): add GitHub action to make easier validate the chart generate

roadmap/roadmap_2024.md
📖 Update roadmap_2024.md - Latest Status - Nov 2024
=> 📖 Update roadmap_2024.md - Latest Status - Nov 2024

.github/workflows/test-helm-samples.yml, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/github/test_chart.go, testdata/project-v4-with-plugins/.github/workflows/test-chart.yml
Fixes: https://github.com/kubernetes-sigs/kubebuilder/issues/4378
=> 🐛 fix: (helm/v1alpha1): install the prometheus-operator CRDs before installing a chart which configures a ServiceMonitor

pkg/plugins/optional/helm/v1alpha/scaffolds/init.go, testdata/project-v4-with-plugins/dist/chart/templates/rbac/service_account.yaml
The use case I have in mind is for example [Azure WI configuration](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html#service-account).
Sooner or later I think this way of massaging the yaml files is going to become burdensome.
=> ✨ feat: (helm/v1alpha1): Allow ServiceAccount annotations to be configurable

pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/manager/manager.go, testdata/project-v4-with-plugins/dist/chart/templates/manager/manager.yaml
The use case I have in mind is for example [Azure WI configuration](https://azure.github.io/azure-workload-identity/docs/topics/service-account-labels-and-annotations.html#pod).
=> ✨ feat: (helm/v1alpha1): Allow extra pod labels to be configured

.github/workflows/test-helm-samples.yml
Related to > https://github.com/kubernetes-sigs/kubebuilder/pull/4377
If you agree it's useful, I can add it to the  test_chart.go as well.
Note for example in the picture below that some resources are not being prefixed (The issue I mentioned here: https://github.com/kubernetes-sigs/kubebuilder/pull/4357)
=> ✨ (helm/v1alpha1): Add a step to render the chart in the GitHub Action

pkg/plugins/optional/helm/v1alpha/scaffolds/init.go, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/manager/manager.go, testdata/project-v4-with-plugins/dist/chart/templates/manager/manager.yaml, testdata/project-v4-with-plugins/dist/chart/templates/rbac/metrics_auth_role.yaml, testdata/project-v4-with-plugins/dist/chart/templates/rbac/metrics_auth_role_binding.yaml, testdata/project-v4-with-plugins/dist/chart/templates/rbac/role.yaml, testdata/project-v4-with-plugins/dist/chart/templates/rbac/role_binding.yaml
Hey 👋
I've added missing prefixes to k8s resources (except for cert-manager ones)
I've added 4 commits so it's easier to review.
I will delete the [helm-install.yaml](https://github.com/monteiro-renato/kubebuilder/blob/088436bd8f1b63c793a7f81f32301679f8998e8b/testdata/project-v4-with-plugins/dist/helm-install.yaml) file and squash the commits after the review.
=> 🐛 fix: (helm/v1alpha1): Add missing prefixes in various k8s resources

cmd/main.go, pkg/cli/alpha/internal/generate.go, pkg/plugins/common/kustomize/v2/init.go, pkg/plugins/golang/deploy-image/v1alpha1/api.go, pkg/plugins/optional/grafana/v1alpha/edit.go, pkg/plugins/optional/grafana/v1alpha/init.go, pkg/plugins/optional/helm/v1alpha/edit.go, pkg/plugins/optional/helm/v1alpha/init.go, pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
Fix https://github.com/kubernetes-sigs/kubebuilder/issues/4309
Ran these commands to find occurrences 
```sh
grep -Inr "base.go.kubebuilder.io" . --exclude=\*.{md,sh,toml}
grep -Inr "base/v4" . --exclude=\*.{md,sh,toml}
grep -Inr "deploy-image.go.kubebuilder.io" . --exclude=\*.{md,sh,toml}
grep -Inr "deploy-image/v1-alpha" . --exclude=\*.{md,sh,toml}
grep -Inr "grafana.kubebuilder.io" . --exclude=\*.{md,sh,toml}
grep -Inr "grafana/v1-alpha" . --exclude=\*.{md,sh,toml}
grep -Inr "helm.kubebuilder.io" . --exclude=\*.{md,sh,toml}
grep -Inr "helm/v1-alpha" . --exclude=\*.{md,sh,toml}
grep -Inr "kustomize.common.kubebuilder.io" . --exclude=\*.{md,sh,toml}
grep -Inr "kustomize/v2" . --exclude=\*.{md,sh,toml}
grep -Inr "sampleexternalplugin" . --exclude=\*.{md,sh,toml}
grep -Inr …
```
=> :seedling: fix: centralize plugin key declaration

pkg/plugins/optional/helm/v1alpha/scaffolds/init.go, testdata/project-v4-with-plugins/dist/chart/templates/rbac/leader_election_role_binding.yaml, testdata/project-v4-with-plugins/dist/chart/templates/rbac/metrics_auth_role_binding.yaml, testdata/project-v4-with-plugins/dist/chart/templates/rbac/role_binding.yaml, testdata/project-v4-with-plugins/dist/chart/templates/rbac/service_account.yaml
The ServiceAccount and RoleBinding currently generated in dist/chart/rbac do not reference the controllerManager.serviceAccountName defined in values.yaml.
=> 🐛 fix: (helm/v1alpha1): Use the ServiceAccount name defined in the values.yaml

docs/book/src/faq.md
Fix https://github.com/kubernetes-sigs/kubebuilder/issues/476
To review, check https://deploy-preview-4396--kubebuilder.netlify.app/faq#how-can-i-validate-and-parse-fields-in-crds-effectively
=> :book: doc: validating and parsing CRD fields

docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-with-plugins/test/e2e/e2e_test.go, testdata/project-v4/test/e2e/e2e_test.go
Fix https://github.com/kubernetes-sigs/kubebuilder/issues/4317
=> :sparkles: (go/v4): add support to inject conversion webhook for the marker +kubebuilder:scaffold:e2e-webhooks-checks 

docs/book/src/getting-started.md
Fixes #4414 
Changes made in this PR:
1. The following sentence in `getting-started.md`:
`To do it we are will use refer markers, such as ...`
has been fixed to:
`To achieve this, we will use markers such as ...`
=> 📖 [ISSUE-4414] Fix typo in getting-started.md

.github/workflows/test-e2e-samples.yml, docs/book/src/cronjob-tutorial/testdata/project/config/crd/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/getting-started/testdata/project/config/crd/kustomization.yaml, docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/crd/patches/cainjection_in_cronjobs.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/reference/markers/scaffold.md, hack/docs/internal/multiversion-tutorial/generate_multiversion.go, hack/docs/internal/multiversion-tutorial/kustomize.go, pkg/plugins/common/kustomize/v2/scaffolds/api.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization_conversion_updater.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, test/e2e/v4/generate_test.go, test/testdata/generate.sh, testdata/project-v4-multigroup/config/crd/kustomization.yaml, testdata/project-v4-multigroup/config/crd/patches/cainjection_in_example.com_wordpresses.yaml, testdata/project-v4-multigroup/config/default/kustomization.yaml, testdata/project-v4-with-plugins/config/crd/kustomization.yaml, testdata/project-v4-with-plugins/config/crd/patches/cainjection_in_wordpresses.yaml, testdata/project-v4-with-plugins/config/default/kustomization.yaml, testdata/project-v4/config/crd/kustomization.yaml, testdata/project-v4/config/crd/patches/cainjection_in_firstmates.yaml, testdata/project-v4/config/default/kustomization.yaml
The CA injection patch has **not** worked for `go/v4` and `kustomize/v2` (release `3.5.0`) due to the need to replace `vars` with `replacements`, as `vars` are no longer supported in the latest major versions of Kustomize. 
However, since webhook `--conversion` was an incomplete feature until the upcoming Kubebuilder future release `v4.4.0` (where [PR #4254](https://github.com/kubernetes-sigs/kubebuilder/pull/4254) is expected to be merged), users likely didn’t encounter this issue or addressed it manually by fixing the scaffold.
**Note:** This change only affects projects that require a **conversion webhook**. 
To better understand the issue and context please see: https://github.com/kubernetes-sigs/kubebuilder/issues/4285
Closes: …
=> 🐛 (kustomize/v2, go/v4):  Fix ca injection for conversion webhooks

Makefile
I believe this way is better? Specially now that the helm plugin is not yet available in any released version of kubebuilder?
For me, it also makes testing easier as I can make changes to the code and see it reflected in the generated chart without having to remember to `make install` beforehand.
=> 🌱Build the kubebuilder binary before and use it to regenerate the helm chart

.github/workflows/test-e2e-samples.yml, docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go, docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_webhook_patch.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml, docs/book/src/getting-started/testdata/project/cmd/main.go, docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml, docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go, docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_webhook_patch.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/webhook_manager_patch.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go, testdata/project-v4-multigroup/cmd/main.go, testdata/project-v4-multigroup/config/default/kustomization.yaml, testdata/project-v4-multigroup/config/default/manager_webhook_patch.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-plugins/cmd/main.go, testdata/project-v4-with-plugins/config/default/kustomization.yaml, testdata/project-v4-with-plugins/config/default/manager_webhook_patch.yaml, testdata/project-v4-with-plugins/dist/install.yaml, testdata/project-v4/cmd/main.go, testdata/project-v4/config/default/kustomization.yaml, testdata/project-v4/config/default/manager_webhook_patch.yaml, testdata/project-v4/dist/install.yaml
- Introduced CertWatcher for webhook server to dynamically reload certificates.
- Added CLI flags (--webhook-cert-path, --webhook-cert-name, --webhook-cert-key) to allow users to provide custom certificate paths.
- Updated manager to integrate CertWatcher into webhook TLS options.
- Ensured backward compatibility with default self-signed certificates if no custom certs are provided.
=> ✨ feat: add webhook CertWatcher and flags for custom certificate configuration

docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml, docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml, docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml, pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/internal/templates/github/lint.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup/.github/workflows/lint.yml, testdata/project-v4-with-plugins/.github/workflows/lint.yml, testdata/project-v4/.github/workflows/lint.yml
Noted while working on https://github.com/kubernetes-sigs/kubebuilder/pull/4425 that scaffold GitHub action and Makefile have different `golangci-lint` version
=> 🌱 : Ensure that golangci-lint CI version is passed for the templates

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/reference/metrics.md, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, test/e2e/deployimage/plugin_cluster_test.go, test/e2e/utils/test_context.go, test/e2e/v4/plugin_cluster_test.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-with-plugins/test/e2e/e2e_test.go, testdata/project-v4/test/e2e/e2e_test.go
Closes #4423 
Main changes:
- Updated the test scaffolds to enforce the restricted security policy:
- Labeled the manager namespace with `pod-security.kubernetes.io/enforce=restricted`.
- Changed the curl Pod creation command to adhere the `securityContext` Pod spec fields
- Updated the tests under test/e2e:
- Changed the utils func `LabelNamespacesToWarnAboutRestricted()`, `RemoveNamespaceLabelToWarnAboutRestricted()` to `LabelNamespacesToEnforceRestricted()`, `RemoveNamespaceLabelToEnforceRestricted()`.
- Made adjustments to ensure compatibility with the strict security policy enforced.
- Changed to use `curlimages/curl:latest` instead of pinning a version.
=> :sparkles: feat: enforce restricted Pod Security Context Compliance in testing

pkg/config/interface.go
=> :seedling: add better description to MarshalYAML and UnmarshalYAML methods

test/e2e/v4/plugin_cluster_test.go
Updates a couple of e2e tests to use Gomega style mentioned in https://github.com/kubernetes-sigs/kubebuilder/issues/4135 . 
I'm not sure if I 100% understood the issue so before I try to rewrite all of them I thought it would be better to create a smaller PR to get feedback earlier. 
relates #4424
=> 🌱improve Ginkgo/Gomega test style

.github/workflows/lint-sample.yml, docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go, docs/book/src/getting-started/testdata/project/cmd/main.go, docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go, pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go, testdata/project-v4-multigroup/cmd/main.go, testdata/project-v4-with-plugins/cmd/main.go, testdata/project-v4/cmd/main.go
This commit change the action in order to use a matrix to validate all samples under testdata
=> 🌱 (ci): Improve GitHub Action to linter samples under testdata

docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go, docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go, docs/book/src/getting-started/testdata/project/internal/controller/suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/internal/controller/suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v2/webhook_suite_test.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/cronjob-tutorial/writing_tests_env.go, pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go, pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go, testdata/project-v4-multigroup/internal/controller/apps/suite_test.go, testdata/project-v4-multigroup/internal/controller/cert-manager/suite_test.go, testdata/project-v4-multigroup/internal/controller/crew/suite_test.go, testdata/project-v4-multigroup/internal/controller/example.com/suite_test.go, testdata/project-v4-multigroup/internal/controller/fiz/suite_test.go, testdata/project-v4-multigroup/internal/controller/foo.policy/suite_test.go, testdata/project-v4-multigroup/internal/controller/foo/suite_test.go, testdata/project-v4-multigroup/internal/controller/sea-creatures/suite_test.go, testdata/project-v4-multigroup/internal/controller/ship/suite_test.go, testdata/project-v4-multigroup/internal/webhook/apps/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/cert-manager/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/core/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/crew/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/example.com/v1alpha1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/ship/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/ship/v2alpha1/webhook_suite_test.go, testdata/project-v4-with-plugins/internal/controller/suite_test.go, testdata/project-v4-with-plugins/internal/webhook/v1alpha1/webhook_suite_test.go, testdata/project-v4/internal/controller/suite_test.go, testdata/project-v4/internal/webhook/v1/webhook_suite_test.go
Make webhook and controller test suites more similar. This can facilitate changes to the code in the future
=> :sparkles: (go/v4): Standardize the webhook and controller test suites

.github/workflows/lint-sample.yml, .github/workflows/lint.yml, Makefile, docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml, docs/book/src/getting-started/testdata/project/Makefile, docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml, docs/book/src/multiversion-tutorial/testdata/project/Makefile, pkg/plugin/util/util.go, pkg/plugins/golang/go_version.go, pkg/plugins/golang/v4/scaffolds/init.go, testdata/project-v4-multigroup/.github/workflows/lint.yml, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-plugins/.github/workflows/lint.yml, testdata/project-v4-with-plugins/Makefile, testdata/project-v4/.github/workflows/lint.yml, testdata/project-v4/Makefile
Upgrade golangci-lint from v1.61.0 to  v1.62.2
=> ✨ Upgrade golangci-lint from v1.61.0 to  v1.62.2

roadmap/roadmap_2025.md
**Add "Kubebuilder Project Roadmap 2025" Document**
This PR introduces the **Kubebuilder Project Roadmap 2025** as a standalone document under the `roadmaps` directory. It outlines key priorities and goals for the Kubebuilder project in 2025, focusing on stability, usability, and alignment with best practices.
The roadmap serves as a transparent guide for contributors, maintainers, and users, offering a clear vision of the project's direction and priorities for 2025. It aims to enhance collaboration and keep the Kubebuilder community aligned with the evolving Kubernetes ecosystem.
- Improve webhook functionality, including CA injection, multiple webhook scaffolding, and end-to-end testing for conversion processes.
- Update tutorials to reflect the standards introduced by the DeployImage …
=> 📖 (doc): Add "Kubebuilder Project Roadmap 2025"

.github/workflows/codeql.yml
Fix https://github.com/kubernetes-sigs/kubebuilder/pull/4446#discussion_r1898664394
Make go version updates easier, as less files must be updated
=> :seedling: fix: use Go version from go.mod file in CI

docs/book/src/plugins/extending/testing-plugins.md, test/e2e/alphagenerate/generate_test.go, test/e2e/deployimage/generate_test.go, test/e2e/grafana/generate_test.go, test/e2e/v4/generate_test.go
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4424
=> 🌱 e2e tests improve assertions by simplify style of checks

.github/workflows/lint.yml, .golangci.yml, Makefile
Fix golangci-lint config schema errors: corrected invalid govet fieldalignment
This PR add the new target, which is also called in the CI to validate the Lint config for Kubebuilder itself and solve the issues found:
```
make lint-config
/Users/camilam/go/src/sigs.k8s.io/kubebuilder/bin/golangci-lint config verify
jsonschema: "linters-settings.revive.rules.3.arguments" does not validate with "/properties/linters-settings/properties/revive/properties/rules/items/properties/arguments/type": expected array, but got object
jsonschema: "linters-settings.govet" does not validate with "/properties/linters-settings/properties/govet/additionalProperties": additionalProperties 'enable=fieldalignment' not allowed
Failed executing command with error: the configuration contains invalid elements
make: …
```
=> 🌱 Add lint-config target to validate config and fix issues faced

.golangci.yml, pkg/cli/options_test.go, pkg/config/store/yaml/store.go, pkg/plugins/golang/deploy-image/v1alpha1/api.go, pkg/plugins/golang/v4/scaffolds/internal/templates/hack/boilerplate.go
Enable the check for Kubebuilder CLI and fix issues
=> 🌱 Enable lint check empty-block and fix issues

.golangci.yml, hack/docs/generate_samples.go, hack/docs/internal/getting-started/generate_getting_started.go, hack/docs/internal/multiversion-tutorial/generate_multiversion.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-metrics-traffic.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/allow-webhook-traffic.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/network-policy/kustomization.go, pkg/plugins/optional/helm/v1alpha/scaffolds/init.go, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/helpers_tpl.go, test/e2e/v4/generate_test.go, test/e2e/v4/plugin_cluster_test.go
Enable var-naming lint and fix issues for Kubebuilder CLI
=> 🌱 Enable var-naming lint and fix issues for Kubebuilder CLI

.golangci.yml, pkg/cli/alpha/internal/generate.go, pkg/plugins/common/kustomize/v2/init.go, pkg/plugins/golang/deploy-image/v1alpha1/api.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go, pkg/plugins/optional/helm/v1alpha/edit.go, pkg/plugins/optional/helm/v1alpha/init.go, test/e2e/utils/kubectl.go
Enable if-return linter check and fix issues for Kubebuilder CLI
=> 🌱 Enable if-return linter check and fix issues for Kubebuilder CLI

docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go, docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go, docs/book/src/getting-started/testdata/project/internal/controller/suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/internal/controller/suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v2/webhook_suite_test.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/cronjob-tutorial/writing_tests_env.go, pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go, pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go, testdata/project-v4-multigroup/internal/controller/apps/suite_test.go, testdata/project-v4-multigroup/internal/controller/cert-manager/suite_test.go, testdata/project-v4-multigroup/internal/controller/crew/suite_test.go, testdata/project-v4-multigroup/internal/controller/example.com/suite_test.go, testdata/project-v4-multigroup/internal/controller/fiz/suite_test.go, testdata/project-v4-multigroup/internal/controller/foo.policy/suite_test.go, testdata/project-v4-multigroup/internal/controller/foo/suite_test.go, testdata/project-v4-multigroup/internal/controller/sea-creatures/suite_test.go, testdata/project-v4-multigroup/internal/controller/ship/suite_test.go, testdata/project-v4-multigroup/internal/webhook/apps/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/cert-manager/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/core/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/crew/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/example.com/v1alpha1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/ship/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/ship/v2alpha1/webhook_suite_test.go, testdata/project-v4-with-plugins/internal/controller/suite_test.go, testdata/project-v4-with-plugins/internal/webhook/v1alpha1/webhook_suite_test.go, testdata/project-v4/internal/controller/suite_test.go, testdata/project-v4/internal/webhook/v1/webhook_suite_test.go
Add schemas prior to envtest start in `suite_test.go` files
This will help fix a bug with conversion webhooks with envtest
=> 🐛 (go/v4) ensure that schemas are added before start EnvTest-based suite tests for webhooks and controllers

.golangci.yml, pkg/plugins/golang/v4/scaffolds/edit.go
Fix linter error `nilness: impossible condition: nil != nil (govet)`
```
golangci-lint run
pkg/plugins/golang/v4/scaffolds/edit.go:60:9: nilness: impossible condition: nil != nil (govet)
if err != nil && s.multigroup != s.config.IsMultiGroup() {
^
make: *** [lint] Error 1
```
=> :seedling: Enable govet settings and fix issue found

.github/workflows/test-e2e-book.yml
Simplify E2E Book Samples GitHub Actions job by using matrix
=> :seedling:: simplify E2E Book Samples job

.github/workflows/test-devcontainer.yml, CONTRIBUTING.md, docs/book/book.toml, docs/book/src/quick-start.md, docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod, netlify.toml
Upgrade remaining Go versions from 1.22 to 1.23, after https://github.com/kubernetes-sigs/kubebuilder/pull/4446
Used `grep -Inr "1\.22" .` ouput to help me find occurrences
=> :seedling: fix: remaining Go upgrades

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go, testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go, testdata/project-v4-with-plugins/test/e2e/e2e_suite_test.go, testdata/project-v4/test/e2e/e2e_suite_test.go
`make manifests` and `make generate` are already called prior to running E2E tests
https://github.com/kubernetes-sigs/kubebuilder/blob/18df53806e97f5ed41161edeb7607bf0f04b1d07/testdata/project-v4/Makefile#L70
=> 🌱 : fix: remove unnecessary make manifests and make generate in E2E scaffold code

pkg/plugins/golang/v4/init.go
The minimal golang version provided in init operation for validation should be 1.23.0, as embedded go.mod contains this one.
Otherwise, project init will fails on downloading with following log
```shell
[xyz@fedora kbtest]$ kubebuilder init --repo kb --domain bootsman.tech
INFO Writing kustomize manifests for you to edit... 
INFO Writing scaffold for you to edit...          
INFO Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.19.4 
go: errors parsing go.mod:
go.mod:5: unknown directive: godebug
Error: failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v4": exit status 1
FATA failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v4": exit status 1 
[xyz@fedora kbtest]$ go version
go version go1.22.10 linux/amd64 …
```
=> 🐛 Update golang version to 1.23.0 in init validation logic

pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/prometheus/monitor.go, testdata/project-v4-with-plugins/dist/chart/templates/prometheus/monitor.yaml
Closes: https://github.com/kubernetes-sigs/kubebuilder/pull/4490
=> 🐛 (helm/alpha-v1): fix yaml lint in the ServiceMonitor file

pkg/cli/alpha/internal/generate.go
Allow re-generate projects which were previously scaffolded with an external API; a webhook was created for those. 
The issue is encountered when using the command before this Pull Request to re-generate the scaffold under test data, for example.
=> 🐛 fix: kubebuilder alpha generate command to allow re-create projects with webhooks for external-apis

docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-plugins/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
The `cert-manager` project has been transferred to the `cert-manager` organization from the jetstack.
Fix the `certmanagerURLTmpl` value to follow them.
=> ✨ (go/v4): Follow cert-manager org name changes

pkg/cli/alpha/command.go, pkg/cli/alpha/internal/generate.go, test/e2e/alphagenerate/generate_test.go
If not informed of an input directory and an output directory, then the tool should re-generate the project in the current directory.
=> 🌱 fix: alpha generate command. If the output-dir path is not informed than it should be the current directory

docs/book/src/cronjob-tutorial/testdata/project/.devcontainer/devcontainer.json, docs/book/src/cronjob-tutorial/testdata/project/Dockerfile, docs/book/src/getting-started/testdata/project/.devcontainer/devcontainer.json, docs/book/src/getting-started/testdata/project/Dockerfile, docs/book/src/migration/legacy/manually_migration_guide_v2_v3.md, docs/book/src/multiversion-tutorial/testdata/project/.devcontainer/devcontainer.json, docs/book/src/multiversion-tutorial/testdata/project/Dockerfile, docs/book/src/reference/submodule-layouts.md, pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go, pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go, testdata/project-v4-multigroup/.devcontainer/devcontainer.json, testdata/project-v4-multigroup/Dockerfile, testdata/project-v4-with-plugins/.devcontainer/devcontainer.json, testdata/project-v4-with-plugins/Dockerfile, testdata/project-v4/.devcontainer/devcontainer.json, testdata/project-v4/Dockerfile
Fixes build failure with non-docker builders like buildah in docs and scaffolding. Initially reported in my operator that closely aligns to scaffolding, so I figured I'd upstream the fix.
Docker's builder uses `docker.io` by default if no prefix is provided, but buildah doesn't, and I don't think it's part of the spec.
=> 🐛 Use explicit docker.io prefix for Docker Hub images

Makefile, build/.goreleaser.yml, cmd/cmd.go, cmd/version.go, main.go, test/common.sh
Closes https://github.com/kubernetes-sigs/kubebuilder/issues/4079
This PR makes `kubebuilder` go installable.
Changes:
- Renamed `main` package originally from `cmd/` to `cmd`
- Renamed `main` function previously inside `cmd/cmg.go` to `Run` - following Go Cobra's pattern
- Created new main file at the root of the project
- Renamed package on `doc.go` to `main`
- Fixed building `make build` target
- Fixed GoReleaser config
=> :bug: Make kubebuilder go install-able

docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/webhook_suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v2/webhook_suite_test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go, testdata/project-v4-multigroup/internal/webhook/apps/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/cert-manager/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/core/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/crew/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/example.com/v1alpha1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/ship/v1/webhook_suite_test.go, testdata/project-v4-multigroup/internal/webhook/ship/v2alpha1/webhook_suite_test.go, testdata/project-v4-with-plugins/internal/webhook/v1alpha1/webhook_suite_test.go, testdata/project-v4/internal/webhook/v1/webhook_suite_test.go
Enable conversion webhooks for webhook `suite_test.go` `envtest` by using `k8s.io/client-go/kubernetes/scheme` instead of creating new scheme (this also already done in  controller `suite_test.go`)
- Updated the webhook suite test to follow the structure and conventions of the controller's suite test. 
- Switched to using `k8s.io/client-go/kubernetes/scheme` instead of `k8s.io/apimachinery/pkg/runtime`. 
- This ensures consistency across test suites and improves maintainability.
=> :bug: (go/v4): Align webhook suite test with controller's suite test

pkg/plugins/golang/v4/init.go
=> 🐛 fix: disallow files containing unwanted files when initializing a project

docs/book/src/reference/artifacts.md, docs/book/src/reference/envtest.md
doc: update the Artifacts with the latest changes on the EnvTest Makefile target configurations
=> 📖 doc: update the Artifacts with the latest changes on the EnvTest Makefile target configurations

RELEASE.md, docs/book/src/migration/manually_migration_guide_gov3_to_gov4.md, docs/book/src/reference/metrics.md, docs/book/src/reference/platform.md, docs/book/src/reference/pprof-tutorial.md, docs/book/src/reference/submodule-layouts.md, docs/kubebuilder_annotation.md
This change introduces some fixes to a number of small typos that appear in the Kubebuilder documentation and some other markdown files within the repo.
=> 📖 fix: correct minor typos in documentation

docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/getting-started/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml, docs/book/src/getting-started/testdata/project/dist/install.yaml, docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, docs/book/src/multiversion-tutorial/testdata/project/Makefile, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go, hack/docs/internal/cronjob-tutorial/e2e_implementation.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/getting-started/generate_getting_started.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, testdata/project-v4-multigroup/Makefile, testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-with-plugins/Makefile, testdata/project-v4-with-plugins/test/e2e/e2e_suite_test.go, testdata/project-v4-with-plugins/test/e2e/e2e_test.go, testdata/project-v4/Makefile, testdata/project-v4/test/e2e/e2e_suite_test.go, testdata/project-v4/test/e2e/e2e_test.go
=> :bug: (go/v4): e2e test: Removed Prometheus dependency

Makefile
=> 🌱 : Add YAML Linting to CI Workflow for Scaffolded Charts

docs/book/src/reference/good-practices.md
This advice is simplyfing things and making an "It depends" situation look like there was a clear good and a clear bad way that is the same in all situations. Pretty much none of the issues stated will get better if each controller gets its own CR:
* Race conditions: Conflict errors can always happen and all controllers need to be able to deal with them. If a full reconciliation is too expensive, they can use something like `retry.OnConflict`
* Concurrency issues with different interpretations of state: This example sounds like just buggy software. Copying the state to a new CR doesn't eliminate this problem
* Maintenance and support difficulties: This is definitely not going to get any better by adding more CRDs into the mix, if anything, it will get more complicated
* Status tracking …
=> :book: Remove simplistic advice about multiple controllers reconciling same CR

Makefile
We must revert this change as it is not working well for the Helm Charts.
We are already using Helm Lint to validate Helm YAML files.
However, we will need to see if we can find another one to prevent scenarios like https://github.com/kubernetes-sigs/kubebuilder/pull/4490. Maybe, why it is not falling in the Helm Lint.
=> Revert "Merge pull request #4512 from sarthaksarthak9/lint"

docs/book/src/reference/watching-resources/predicates-with-watch.md, docs/book/src/reference/watching-resources/secondary-resources-not-owned.md
When following the docs for watching a non-owned resource (like `corev1.Pod{}`) the function `handler.EnqueueRequestsFromMapFunc` now requires a `context.Context` argument that is not supplied in the docs.
This PR updates the documentation to match the function signature.
Reference: https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/handler/enqueue_mapped.go#L36
=> 📖 Update documentation for non-owned resources

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go, pkg/plugins/golang/v4/scaffolds/api.go, pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/webhook.go
=> ✨ handle missing boilerplate file gracefully during scaffolding

docs/book/src/cronjob-tutorial/testdata/finalizer_example.go, pkg/config/version.go, pkg/plugin/version.go
This PR fixes grammar: `lets` (meaning "let us") --> `let's`.
=> :book: Fix grammar in lets -> let's.

docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml, docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml, docs/book/src/getting-started/testdata/project/config/prometheus/monitor_tls_patch.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml, hack/docs/internal/cronjob-tutorial/sample.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor_tls_patch.go, test/e2e/v4/generate_test.go, testdata/project-v4-multigroup/config/default/kustomization.yaml, testdata/project-v4-multigroup/config/prometheus/monitor_tls_patch.yaml, testdata/project-v4-with-plugins/config/default/kustomization.yaml, testdata/project-v4-with-plugins/config/prometheus/monitor_tls_patch.yaml, testdata/project-v4/config/default/kustomization.yaml, testdata/project-v4/config/prometheus/monitor_tls_patch.yaml
Fixes #4533 
- Fixed `config/prometheus/monitor_tls_patch.yaml` fiel
- Added `serverName` field in `monitor_tls_patch.yaml` for metric server cert validation
=> :bug: (kustomize/v2): fix ServiceMonitor with TLS kustomize scaffolding

test/common.sh
Upgrade from v0.19 to v0.20 which is the version used in the scaffold.
=> 🌱 Update controller-runtime version used in the common.sh tests

.github/workflows/lint-sample.yml, docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go, docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller_test.go, docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook.go, docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook_test.go, docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go, docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go, docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller_test.go, docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook.go, docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook_test.go, hack/docs/internal/cronjob-tutorial/controller_implementation.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/cronjob-tutorial/webhook_implementation.go, hack/docs/internal/cronjob-tutorial/writing_tests_controller.go, hack/docs/internal/getting-started/generate_getting_started.go, hack/docs/internal/multiversion-tutorial/generate_multiversion.go
✨ Summary
This PR enhances code quality and maintainability by addressing various linter issues and improving the CronJob controller Reconcile function code structure to reduce the cyclomatic complexity.
- Adds linting to documentation samples to ensure consistency and prevent future issues.
- Fixes lint issues across multiple tutorials and utilities, improving code readability and compliance.
- Refactors the CronJob controller’s Reconcile function for the samples to reduce cyclomatic complexity and enhance maintainability.
- Consolidates sample linting into a single workflow for better efficiency and organization.
The goal of this PR is to enhance the overall linting coverage of sample code, ensuring that all included examples meet best practices. By addressing lint issues and …
=> 🌱 : Improve samples linting & fix samples lint issues

docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml, docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml, docs/book/src/getting-started/testdata/project/config/prometheus/monitor_tls_patch.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml, hack/docs/internal/cronjob-tutorial/sample.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor_tls_patch.go, test/e2e/v4/generate_test.go, testdata/project-v4-multigroup/config/default/kustomization.yaml, testdata/project-v4-multigroup/config/prometheus/monitor_tls_patch.yaml, testdata/project-v4-with-plugins/config/default/kustomization.yaml, testdata/project-v4-with-plugins/config/prometheus/monitor_tls_patch.yaml, testdata/project-v4/config/default/kustomization.yaml, testdata/project-v4/config/prometheus/monitor_tls_patch.yaml
Reverts kubernetes-sigs/kubebuilder#4536
Those changes broke the project: Example: https://github.com/kubernetes-sigs/kubebuilder/actions/runs/13250335077/job/36986568474?pr=4555
It is strange but seems that the tests were not executed and the PR merged without them
=> 🌱 Revert (kustomize/v2): fix ServiceMonitor with TLS kustomize scaffolding

pkg/cli/alpha/internal/generate.go
Ran to an issue when running `kubebuilder alpha generate`, and since my project was not on the GOPATH, there was no implicit call to `go mod init`.
>  If your project is initialized within GOPATH, the implicitly called go mod init will interpolate the module path for you. Otherwise --repo=<module path> must be set.
This change updates `alpha generate` command so that `--repo` is always included when running kubebuilder init to fix issue when not on GOPATH. The value for `repo` is retrieved from the PROJECT file as other kubebuilder init options.
=> 🐛 Fix kubebuild alpha generate when not in GOPATH

testdata/project-v4-multigroup/go.mod, testdata/project-v4/go.mod
=> 🌱 fix testdata generation

test/e2e/alphagenerate/generate_v4_multigroup_test.go, test/e2e/alphagenerate/generate_v4_test.go, test/e2e/alphagenerate/generate_v4_with_plugins_test.go
- Added e2e tests for alpha generate command for scaffolded data under testdata 
- made some minor changes in underlying testContext to enable ~~creation of TestContext for scaffolded data and~~
destruction of the regenerated directory
- ~~added a makefile entry for running all these commands~~
- ~~added a github workflow to run these tests on specific changes~~
- submitting PR as a solution to this issue #4508
=> 🌱  Added e2e tests for alpha generate command for scaffolded data 

Makefile, build/.goreleaser.yml, cmd/cmd.go, cmd/version.go, main.go, test/common.sh
Closes #4575
- Resolved an issue preventing Kubebuilder from being installed using go install, ensuring a smoother installation process.
- Change goreleaser to ensure that the version will still inject in the binary
=> 🐛 Fix Kubebuilder Installation with go install

pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
Previously, the scaffolding process would create empty directories in the Helm chart even when the corresponding source directory was missing or contained no YAML files. This commit updates the logic to check for the existence of the source directory and its contents before attempting to copy files.
Changes:
- Skip processing if the source directory does not exist.
- Skip creating destination directories if no YAML files are found.
- Ensure only relevant directories and files are included in the chart.
**Motivation**
If a user removes, for example, the network-policy directory from a project scaffolded with an old version, we do not create an empty directory.
=> 🐛 (helm/v1-alpha): Skip empty directories in chart generation

.github/workflows/release.yml, build/.goreleaser.yml
The current used GoReleaser is v2.3.2 from Sept/2024.
This PR upgrades it t othe latest release v2.7.0 and also adds a fix for a small deprecation on `goreleaser.yml`.
Docs: https://goreleaser.com/deprecations/
Before:
After:
=> :seedling: Upgrade Goreleaser + fix deprecation on release.yml

docs/book/src/reference/watching-resources.md
This PR adds a hyperlink to [Watching Secondary Resources That Are Not Owned](https://book.kubebuilder.io/reference/watching-resources/secondary-resources-not-owned.html?highlight=BackupBusyboxReconciler#configuration-example).
I think that is useful to better understand the text.
=> 📖 Add link to Watching Secondary Resources Owned by the Controller

docs/book/src/migration/multi-group.md
This PR addresses the following issue
https://github.com/kubernetes-sigs/kubebuilder/issues/4530
Update the Single group to Multi group migration doc, that mentions what needs to be done about already existing webhooks while migrating to multigroup. 
- 📖 (:book:): documentation
=> 📖 Update Single Group to Multi-Group Documentation to Add Webhooks Details 📖

docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/Makefile, docs/book/src/multiversion-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-plugins/Makefile, testdata/project-v4/Makefile
This PR removes the hardcoded Kind version and related logic from the Makefile templates. Instead, it introduces a variable for the Kind binary in end-to-end (e2e) tests, allowing users to specify a Kind installation located outside of $PATH.
Currently, the Makefile templates assume a fixed Kind version and location, which limits flexibility. This change ensures that Kind can be used from custom locations, improving compatibility in different environments.
Let me know if you want to tweak anything! 🚀
=> 🐛 Make the Kind integration in the Makefile configurable like the other variables.

.github/workflows/test-alpha-generate.yml, pkg/cli/alpha/internal/generate.go, pkg/cli/cli.go, pkg/cli/cmd_helpers.go
Fixes: #4433 
- Fixed issue where 'kubebuilder alpha generate' failed if PROJECT contained go.kubebuilder.io/v3.  
- Automatically updates outdated plugin references (v3 → v4) to support scaffolding.  
- Added a warning to notify users before modifying the PROJECT file. 
<br>
<br>
=> 🐛 Allow 'kubebuilder alpha generate' rescaffolds work with no longer supported/available plugins ( go/v3 and go/v2 )

docs/book/src/cronjob-tutorial/writing-tests.md
The advanced examples section links to the "Azure Databricks Operator" that was archived more than 3 years ago. Instead, I'm adding a note mentioning the tests from `DeployPlugin`.
=> 📖 Remove outdated test examples

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go, pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go, testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller_test.go, testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller_test.go, testdata/project-v4-with-plugins/internal/controller/busybox_controller_test.go, testdata/project-v4-with-plugins/internal/controller/memcached_controller_test.go
Correct indentation for imported packages in the e2e test suite to maintain consistent code formatting.
=> 🐛  (go/v4): fix indentation of imports in test files

pkg/cli/alpha/internal/generate.go
The loop variable `plugin` was shadowing the imported `plugin` package from sigs.k8s.io/kubebuilder. Renamed it to `plg` to improve clarity and prevent potential confusion or unintended behavior.
=> 🌱 fix: avoid variable shadowing by renaming loop variable 'plugin'

docs/book/utils/litgo/literate.go
correct variable name to avoid shadowing and potential errors in file reading process. Updated `path` to `fullPath` for clarity and accuracy.
=> 🌱 fix: resolve shadowed variable issue in literate.go

pkg/cli/alpha.go
The local variable `alpha` was shadowing the imported `alpha` package, causing ambiguity and potential readability issues. Renamed to `cmd` and `cmds` to improve clarity and avoid name collision.
=> 🌱 (chore): avoid variable shadowing by renaming local 'alpha' variable

pkg/cli/alpha/internal/generate.go
The local variable `config` was shadowing the imported `config` package, which could lead to confusion or unexpected behavior. Renamed to `projectConfig` for clarity and to prevent name collision.
=> 🌱 (chore): rename local 'config' variable to avoid collision with imported package

test/e2e/alphagenerate/generate_test.go
The local variable 'resource' in the e2e test was shadowing the imported 'resource' package, which could cause confusion or conflicts. Renamed to 'resourceData' to clarify intent and eliminate the naming collision.
=> 🌱 (chore): rename local 'resource' variable to avoid shadowing import

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go, hack/docs/internal/cronjob-tutorial/e2e_implementation.go
correct "it's" to "its" in comments to ensure grammatical accuracy in e2e test files and cronjob tutorial implementation.
=> 🌱 fix(docs): correct typo in comments across multiple files

pkg/model/resource/gvk.go
The local variable `errors` was shadowing the standard library `errors` package, which can lead to confusion and potential issues when calling package functions. Renamed the variable to `errs` to clarify intent and resolve the name collision.
=> 🌱 (chore): avoid variable shadowing by renaming local 'errors' variable

docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go, testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go, testdata/project-v4-with-plugins/test/e2e/e2e_suite_test.go, testdata/project-v4/test/e2e/e2e_suite_test.go
Removed duplicated word "the" in the description of `TestE2E` functions across various scaffolded and tutorial test files.
=> 🐛 (go/v4): fix typo in e2e test suite comments

pkg/machinery/scaffold_test.go
Reformatted the inline struct definition in `scaffold_test.go` to a multi-line layout.
=> 🌱 (chore): improve readability of test case for alternative delimiters

hack/docs/internal/getting-started/generate_getting_started.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization_conversion_updater.go
Refactored standalone `const` declarations into grouped blocks in `kustomization_conversion_updater.go` and `generate_getting_started.go` to improve readability and align with Go style conventions.
=> 🌱 (chore): group const declarations into blocks for clarity

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go, pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
Renamed the `config` parameter to `cfg` in Helm and DeployImage plugin scaffolds to avoid
shadowing the imported package. Also replaced short variable declarations with assignments
for `err` and introduced `errPatch` for clearer separation of error contexts.
Additionally, updated a call to `util.InsertCode` in the DeployImage scaffolder to ensure
a proper newline is injected before `env:`, improving the correctness and formatting
of the generated manifest.
=> 🌱 (chore): avoid shadowing of 'config', 'err', and patch error in helm and deploy-image scaffolds

hack/docs/internal/cronjob-tutorial/controller_implementation.go, hack/docs/internal/cronjob-tutorial/e2e_implementation.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, hack/docs/internal/cronjob-tutorial/webhook_implementation.go, hack/docs/internal/getting-started/generate_getting_started.go, hack/docs/internal/multiversion-tutorial/generate_multiversion.go, pkg/cli/cli_test.go, pkg/cli/completion_test.go, pkg/plugin/bundle.go, pkg/plugins/common/kustomize/v2/create.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization_conversion_updater.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_admin_role.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_editor_role.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/rbac/crd_viewer_role.go, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/samples/kustomization.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, pkg/plugins/external/helpers.go, pkg/plugins/golang/v4/api.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/init.go, test/e2e/alphagenerate/generate_test.go, test/e2e/alphagenerate/generate_v4_multigroup_test.go, test/e2e/alphagenerate/generate_v4_test.go, test/e2e/alphagenerate/generate_v4_with_plugins_test.go, test/e2e/grafana/generate_test.go, test/e2e/utils/test_context.go, test/e2e/v4/generate_test.go
Cleaned up redundant blank lines and unnecessary trailing newlines across various files, including test suites, scaffolds, plugin templates, and documentation scripts. This improves code consistency and reduces visual noise, particularly in generated and test-related files.
=> 🌱 (chore): remove unnecessary trailing newlines and redundant blank lines

pkg/plugins/golang/v4/scaffolds/internal/templates/controllers/controller_suitetest.go, pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, pkg/plugins/golang/v4/scaffolds/internal/templates/webhooks/webhook_suitetest.go
Converted single-variable `var` to blocks `var(...)` declarations
in `controller_suitetest.go`, `devcontainer.go`, `webhook_suitetest.go`, and `test.go`.
=> 🌱 (chore): simplify variable declarations by adding var blocks

pkg/cli/root.go, pkg/config/registry.go, pkg/plugins/golang/go_version.go, pkg/plugins/golang/options.go, pkg/plugins/optional/grafana/v1alpha/plugin.go, test/e2e/grafana/generate_test.go
Converted single-variable `var (...)` blocks to direct `var` declarations in various packages such as `golang/options.go`, `cli/root.go`, `config/registry.go`, and test files. This makes the code more concise and aligns with idiomatic Go style.
=> 🌱 (chore): simplify variable declarations by removing unnecessary var blocks

pkg/plugins/golang/v4/scaffolds/webhook.go, pkg/plugins/optional/helm/v1alpha/scaffolds/init.go, test/e2e/v4/plugin_cluster_test.go
Added trailing commas in multi-line function declarations in `webhook.go`, `plugin_cluster_test.go`, and helm init scaffolder to align with Go formatting conventions and avoid formatting diffs from `gofmt`.
=> 🌱 (chore): fix formatting for multi-line function signatures

pkg/cli/options.go, pkg/config/store/yaml/store.go, pkg/plugins/external/helpers.go
Replaced short variable declarations with assignments in `pkg/cli/options.go`, `pkg/config/store/yaml/store.go`, and `pkg/plugins/external/helpers.go` to avoid shadowing the `err` variable.
=> 🌱 (chore): avoid shadowing of 'err' in CLI options, YAML store, and external plugin helpers

pkg/model/resource/resource_test.go, pkg/plugins/external/external_test.go, test/e2e/deployimage/plugin_cluster_test.go, test/e2e/v4/plugin_cluster_test.go
Replaced short variable declarations with assignments in `test/e2e` and `pkg/plugins/external` to avoid shadowing the `err` variable and other previously declared variables. This includes explicit declarations for variables like `output`, `status`, and `fileInfo` to ensure consistent error handling and improved readability in test logic.
=> 🌱 (chore): avoid shadowing of 'err' and related variables in E2E and external plugin tests

pkg/internal/validation/dns.go
Renamed the parameter `fmt` to `pattern` in `pkg/internal/validation/dns.go` to avoid shadowing
the standard library `fmt` package. This improves code clarity and prevents potential issues
when using formatting functions like `fmt.Sprintf` within the same scope.
=> 🌱 (chore): avoid shadowing of 'fmt' in regexError helper

pkg/plugins/common/kustomize/v2/scaffolds/api.go, pkg/plugins/common/kustomize/v2/scaffolds/init.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
Renamed variables and function parameters in `pkg/plugins/common/kustomize/v2` scaffolds to avoid shadowing imported packages and previously declared variables. Specifically, `config` → `cfg`, `resource` → `res`, and inner `err` → `errCheck`. This improves code readability and avoids confusion or bugs caused by variable shadowing.
=> 🌱 (chore): avoid shadowing of 'config', 'resource', and 'err' in kustomize/v2 scaffolds

pkg/config/v3/config.go, pkg/config/v3/config_test.go
Renamed local variables in `pkg/config/v3/config.go` and `config_test.go` to avoid shadowing the `pluginConfig` package identifier and improve clarity. Updated `pluginConfig` → `pluginCfg` consistently across both implementation and unit tests. This helps prevent confusion and potential misuses, especially when debugging or working with similarly named types or packages.
=> 🌱 (chore): avoid shadowing of 'pluginConfig' in config v3 implementation and tests

pkg/config/version.go, pkg/plugin/version.go
Renamed inner error variables in version parsing logic in `pkg/plugin/version.go` and `pkg/config/version.go` from `err` to `errParse` to avoid shadowing the outer `err` variable. This improves clarity in control flow and prevents potential confusion in error handling.
=> 🌱 (chore): avoid shadowing of 'err' in version parsing for plugin and config packages

pkg/cli/options.go, pkg/cli/options_test.go
Renamed local `fs` variables and parameters to `filesystem` to prevent shadowing of the `io/fs` package and improve code clarity. Also corrected the typo in the function name `isPluginExectuable`, now properly named `isPluginExecutable`.
This also updates corresponding test cases to follow the same naming convention.
=> 🌱 (chore): avoid 'fs' shadowing and rename 'isPluginExectuable' to 'isPluginExecutable'

hack/docs/internal/cronjob-tutorial/generate_cronjob.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
Refactored `var` declarations to use short form where appropriate:
- Replaced `var templatesBuilder =` with `:=` in the Grafana scaffolder.
- Replaced `var fs =` with `:=` in the cronjob tutorial generator. This improves code clarity and aligns with idiomatic Go style.
=> 🌱 (chore): clean up var declarations in grafana scaffolder and cronjob doc generator

docs/book/src/getting-started/testdata/project/dist/chart/templates/certmanager/certificate.yaml, docs/book/src/getting-started/testdata/project/dist/chart/templates/manager/manager.yaml, pkg/plugins/optional/helm/v1alpha/scaffolds/init.go, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/cert-manager/certificate.go, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/manager/manager.go
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4582
=> 🐛 (helm/v1-alpha): not scaffold webhooks conditionals manifests for projects without webhooks

pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
Split the error handling for config reading and file closing in `pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go` to avoid shadowing the `err` variable. This improves error visibility and follows best practices for clarity in error handling and variable reuse.
=> 🐛 (grafana/v1alpha) avoid shadowing of 'err' in grafana plugin code generating

pkg/machinery/scaffold.go
Renamed the parameter `resource` to `res` in the `WithResource` function to avoid shadowing the imported package. Also replaced `:=` with `=` when assigning to `err` to prevent redeclaration and shadowing of the existing error variable.
=> 🌱 (chore): avoid shadowing of 'resource' and 'err' in machinery scaffold

pkg/plugin/util/util.go, pkg/plugin/util/util_test.go
Replaced short variable declarations with assignments in `pkg/plugin/util/util.go` and `util_test.go` to avoid shadowing the existing `err` variable. This ensures proper error propagation, improves code readability, and aligns with Go best practices for error handling and scope control.
=> 🌱 (chore): avoid shadowing of 'err' in plugin util and test utilities

.golangci.yml
Enabled the `gofumpt` linter in `.golangci.yml` to enforce stricter formatting rules and ensure consistency with gofumpt standards across the codebase.
=> 🌱 (chore): add gofumpt to golangci-lint configuration

pkg/plugins/common/kustomize/v2/scaffolds/init.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
Replaces import alias `network_policy` with `networkpolicy` to follow Go naming conventions.
=> 🌱 (chore): unify import alias for network-policy

docs/book/src/getting-started.md
Fix incorrect location of the samples folder.
Currently the documentation suggests that the location for the samples is config/crd/samples, but from what I can see when I create my getting-started project it's under config/samples.
=>  📖 Fix path for samples in the Getting Started tutorial

pkg/config/v3/config.go
- Use %w consistently in fmt.Errorf for proper error wrapping
=> 🌱 (chore): normalize error messages and wrap errors using %w

pkg/model/resource/gvk.go, pkg/plugins/external/helpers.go, pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
- Replaced legacy `%v` error wrapping with `%w` in `fmt.Errorf(...)` calls
- Applied `%q` for path-related variables to improve clarity
- Affected areas include `helm/v1alpha`, `external/helpers`, and `model/resource`
=> 🌱 (chore): wrap file and I/O errors with '%w' in 'pkg'

pkg/cli/options.go, pkg/plugins/golang/options.go, pkg/plugins/optional/grafana/v1alpha/commons.go
- Removed stray empty lines in `grafana`, `golang`, and CLI plugin logic
- Keeps code formatting consistent and clean
=> 🌱 (chore): remove unnecessary blank lines across plugin configuration and options

designs/crd_version_conversion.md
- Updated `fmt.Errorf` to use `%w` for proper error wrapping in code snippets
- Improves consistency and error traceability in example code
=> 📖 Improve error format in the design docs for API Versioning in Kubebuilder

pkg/plugins/golang/v4/scaffolds/api.go, pkg/plugins/golang/v4/scaffolds/edit.go, pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/webhook.go, pkg/plugins/golang/v4/webhook.go
Renamed variables and function parameters in `pkg/plugins/golang/v4` to avoid shadowing imported packages: `config` → `cfg`, and `resource` → `res`. This includes updates to the webhook, scaffolds (api, edit, init, webhook), and internal validation logic. These changes improve code readability and prevent potential issues when using package-level identifiers within the same scope.
=> 🌱 (chore): avoid shadowing of 'config' and 'resource' in golang/v4 plugins

pkg/plugins/common/kustomize/v2/init.go, pkg/plugins/common/kustomize/v2/scaffolds/api.go, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go
Replaced uses of `%v` with `%w` in `fmt.Errorf` to support proper error wrapping. Standardized formatting style, e.g. quoting strings with `%q` where appropriate.
=> 🌱 (chore): wrap errors with '%w' and normalize formatting in 'kustomize/v2'

test/e2e/utils/test_context.go
- Updated error formatting to use `%w` in `fmt.Errorf` for proper error chaining
- Affects command execution error reporting in test context
=> 🌱 (chore): wrap error with %w in test_context.go for improved diagnostics

docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go, docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go, docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go, hack/docs/internal/cronjob-tutorial/controller_implementation.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-plugins/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
- Use `%w` in `fmt.Errorf` for proper error wrapping
- Quote string with `%q` for clarity
- Applied consistently across all testdata and tutorial utility files
=> 🐛 (go/v4): wrap test command execution errors with %w in test utils

pkg/cli/alpha/internal/generate.go
Renamed variables and function parameters in `pkg/cli/alpha/internal/generate.go` to avoid shadowing imported packages: `config` → `cfg`, `store` → `s`, `resource` → `res` and `resource` → `resourceData`. This improves code readability and prevents potential issues when calling package-level functions.
=> 🌱 (chore): avoid shadowing of 'config', 'store', and 'resource' in cli/alpha/generate

.golangci.yml
Now that all variable shadowing issues have been resolved in previous commits, the `shadow` linter in govet is enabled and `import-shadowing` rule from revive is activated, to ensure consistent detection of future shadowing problems.
=> 🌱 (chore): enable shadow checks via import-shadowing linter

pkg/cli/cli_test.go
This change moves mutable shared test data such as `projectVersion` and plugin key lists into `BeforeEach` blocks to ensure test isolation within Ginkgo. 
Previously, these variables were declared and modified in the outer scope of the `Describe` blocks, which could lead to pollution across tests due to shared state.
This improves test reliability and maintainability by making each test's state self-contained.
No behavior change.
=> 🌱  (chore): refactor unit tests to isolate mutable test data in CLI spec to improve maintainability 

.golangci.yml
- Added `asciicheck` to detect non-ASCII characters in identifiers and strings. Helps prevent hidden bugs and improves readability across systems.
- Added `bidichk` to catch Unicode bidirectional control characters. Protects against visual code obfuscation and potential security vulnerabilities.
These linters help enforce safer and more maintainable Go code, especially in kubebuilders collaborative environment with many contributors.
=> 🌱 (chore): enable 'asciicheck' and 'bidichk' for improved code safety and clarity

docs/book/src/cronjob-tutorial/testdata/project/.golangci.yml, docs/book/src/getting-started/testdata/project/.golangci.yml, docs/book/src/multiversion-tutorial/testdata/project/.golangci.yml, pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go, testdata/project-v4-multigroup/.golangci.yml, testdata/project-v4-with-plugins/.golangci.yml, testdata/project-v4/.golangci.yml
This PR adds the `import-shadowing` linter to all `.golangci.yml` configuration files across test projects and templates.  
The `import-shadowing` linter detects cases where a package import shadows an existing variable, which can lead to subtle bugs.
Adding this linter helps maintain cleaner and more maintainable code by avoiding accidental name collisions.  
This change aligns the lint configuration across the codebase and ensures new code follows the same checks.
- Added `import-shadowing` to:
- `testdata/project-v4*/.golangci.yml`
- test projects in `docs/book/src/**/testdata`
- generated linter config in `pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go`
No functional code changes were made—this is purely a tooling/linting update.
=> ✨ (go/v4): enable 'import-shadowing' linter

pkg/cli/options_test.go, pkg/cli/resource_test.go
This refactors the `options_test.go` spec to define mutable test variables like `projectVersion`, plugin mocks, and env paths inside `BeforeEach` blocks. This avoids potential side effects and improves Ginkgo test isolation.
Previously, some of these variables were declared in outer scopes and could accidentally retain or leak state between examples.
This change improves test clarity and maintainability without impacting behavior.
=> 🌱  (chore): refactor unit tests to isolate mutable state with BeforeEach for pkg/cli

pkg/config/store/errors_test.go, pkg/config/store/yaml/store_test.go
This change refactors `store_test.go` and `errors_test.go` to move test-specific variable initialization into `BeforeEach` blocks.
This avoids any risk of test state leakage between specs and aligns with best practices for Ginkgo-based tests. Ensures cleaner, more isolated, and maintainable test definitions.
=> 🌱  (chore): refactor unit tests to isolate mutable state with BeforeEach for pkg/config/store

pkg/config/errors_test.go, pkg/config/registry_test.go, pkg/config/v3/config_test.go, pkg/config/version_test.go
This change refactors multiple Ginkgo test suites to move shared variables into `BeforeEach` blocks, including:
- `pkg/config/errors_test.go`
- `pkg/config/version_test.go`
- `pkg/config/v3/config_test.go`
- `pkg/config/registry_test.go`
By initializing test data in `BeforeEach`, we ensure test isolation and avoid accidental state pollution between specs. This also aligns with best practices and improves test readability and maintainability.
=> 🌱  (chore): refactor unit tests to isolate mutable state with BeforeEach in pkg/config

pkg/machinery/errors_test.go, pkg/machinery/injector_test.go, pkg/machinery/mixins_test.go, pkg/machinery/scaffold_test.go
This refactors multiple test files to move mutable test variables into `BeforeEach` blocks. This prevents unintended state sharing across tests and improves isolation and readability.
- `pkg/machinery/errors_test.go`
- `pkg/machinery/injector_test.go`
- `pkg/machinery/mixins_test.go`
- `pkg/machinery/scaffold_test.go`
This aligns with Ginkgo best practices and avoids potential side effects from shared variables in nested contexts or table-driven specs.
=> 🌱  (chore): refactor unit tests to isolate mutable state with BeforeEach in pkg/machinery tests

pkg/model/stage/stage_test.go
This PR refactors the `stage_test.go` file to:
- Replace alias-based import (`g.`) with standard Ginkgo imports for clarity and consistency
- Move shared variables into `BeforeEach` to isolate test state
- Improve naming consistency and indentation
This keeps the test style aligned with the rest of the project and prevents potential side effects or shared mutable state across test cases.
=> 🌱 (chore): refactor stage unit tests with Ginkgo conventions and simplify logic in stage_test.go

pkg/model/resource/api_test.go, pkg/model/resource/gvk_test.go, pkg/model/resource/resource_test.go, pkg/model/resource/webhooks_test.go
This PR updates resource-related unit tests to:
- Move mutable/shared test variables (e.g., `gvk`, `res`, `webhooks`, etc.) into `BeforeEach` blocks
- Use closures in `DescribeTable` entries to avoid cross-contamination between test cases
- Align with best practices for writing safe, isolated Ginkgo tests
This change improves test clarity and avoids issues from shared mutable state, especially useful as the test suite grows and evolves.
=> 🌱  (chore): refactor unit tests to isolate mutable state with BeforeEach in resource-related tests

pkg/plugins/external/external_test.go, pkg/plugins/golang/go_version_test.go, pkg/plugins/golang/options_test.go
This PR ensures test isolation by moving mutable shared variables and initialization logic into `BeforeEach` blocks across multiple test suites, including:
- `pkg/plugins/golang/go_version_test.go`
- `pkg/plugins/golang/options_test.go`
- `pkg/plugins/external/external_test.go`
This approach prevents side effects between test cases and aligns with best practices for Ginkgo-style testing. The changes:
- Avoid spec pollution
- Enable safer use of `DescribeTable`
- Improve maintainability and clarity
=> 🌱 (chore): refactor shared setup logic in plugins into BeforeEach to isolate test state

.golangci.yml
Adds `whitespace` to the list of active linters in `.golangci.yml` to enforce consistent formatting and improve code cleanliness.
=> 🌱 (chore): enable 'whitespace' linter in golangci-lint config

pkg/plugin/bundle_test.go, pkg/plugin/errors_test.go, pkg/plugin/filter_test.go, pkg/plugin/helpers_test.go, pkg/plugin/util/util_test.go, pkg/plugin/version_test.go
This PR ensures better test isolation and avoids spec pollution by refactoring test files to initialize shared variables inside `BeforeEach` blocks.
Refactored files include:
- `pkg/plugin/filter_test.go`
- `pkg/plugin/bundle_test.go`
- `pkg/plugin/errors_test.go`
- `pkg/plugin/version_test.go`
- `pkg/plugin/util/util_test.go`
- `pkg/plugin/helpers_test.go`
This aligns with Ginkgo best practices for clean and deterministic tests.
=> 🌱 (chore): refactor shared setup logic in plugin into BeforeEach to isolate test state

pkg/config/v3/config_test.go
Fix plugin config test by resetting struct to avoid value reuse
Avoids test contamination caused by shared PluginConfig variable by explicitly resetting it before decoding in each test case. Also resolves shadowing linter errors reported by golangci-lint.
=> 🌱 fix (ci): fix lint issue: shadow: declaration of pluginCfg shadows declaration

docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go, docs/book/src/getting-started/testdata/project/cmd/main.go, docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go, docs/book/src/reference/raising-events.md, hack/docs/internal/multiversion-tutorial/generate_multiversion.go, pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go, testdata/project-v4-multigroup/cmd/main.go, testdata/project-v4-with-plugins/cmd/main.go, testdata/project-v4/cmd/main.go
Errors in the snippet added to `cmd/main.go` when the controller and webhook are generated(like `kubebuilder create api`) was referring to something out of scope, so this has been corrected to a limited scoped error.
```go
if err = (&controller.FrigateReconciler{
Client: mgr.GetClient(),
Scheme: mgr.GetScheme(),
}).SetupWithManager(mgr); err != nil {
setupLog.Error(err, "unable to create controller", "controller", "Frigate")
os.Exit(1)
}
// +kubebuilder:scaffold:builder
if metricsCertWatcher != nil {
setupLog.Info("Adding metrics certificate watcher to manager")
if err := mgr.Add(metricsCertWatcher); err != nil {
setupLog.Error(err, "unable to add metrics certificate watcher to manager")
os.Exit(1)
}
}
if webhookCertWatcher != nil {
setupLog.Info("Adding webhook certificate watcher to …
```
=> 🐛 (go/v4) Update main.go scaffold to follow Go best practices by reducing the scope of err using short variable declarations (:=)

hack/docs/internal/cronjob-tutorial/generate_cronjob.go
Replace hardcoded controller-runtime version in `hack/docs/internal/cronjob-tutorial/generate_cronjob.go` with a reference to the `ControllerRuntimeVersion` constant from the scaffolding package.
This prevents the docs generation from breaking when the controller-runtime version is updated in the scaffolding logic, ensuring that `make generate-docs` remains stable across version bumps.
- Import the scaffolds/init package to access the ControllerRuntimeVersion constant
- Replace the hardcoded version string with a dynamic reference using fmt.Sprintf
This change adheres to the DRY principle by having a single source of truth for the controller-runtime version, preventing future breakages when dependencies are updated.
Fixes the issue where make generate-docs fails when controller-runtime is …
=> 🌱 Use dynamic controller-runtime version in doc generator to make easier update the version

.golangci.yml
This PR adds the following configuration to `.golangci.yml`:
```yaml
linters-settings:
ginkgolinter:
forbid-spec-pollution: true
```
Enabling forbid-spec-pollution ensures all shared test state is scoped within BeforeEach or similar blocks, helping prevent flaky tests and improving test isolation in Ginkgo test suites.
=> 🌱 (chore): enable ginkgolinter forbid-spec-pollution to enforce isolated test specs

.golangci.yml
:seedling: enable ginkgolinter forbid-focus-container
This PR adds the following configuration to `.golangci.yml`:
```yaml
linters-settings:
ginkgolinter:
forbid-focus-container: true
```
Enabling forbid-focus-container protects the code in the repository against accident committing of debug code. A contributeor may use ginkgo's focus container (e.g. `FIt`, `FContext` etc. or by adding the `Focus` decorator), in order to locally debug a specific test. Merging a ginkgo's focus container will prevent running of all the other tests in CI.
Inspired by #4710
=> 🌱 (chore): enable ginkgolinter forbid-focus-container

pkg/config/store/yaml/store_test.go, pkg/config/v3/config_test.go, pkg/machinery/scaffold_test.go
This update improves Gomega assertions by replacing `errors.As()` with `MatchError()` where the test intends to match specific error types rather than extract them.
This change simplifies the assertions and improves readability, aligning with idiomatic Gomega style.
=> 🌱 (chore): replace errors.As() with MatchError() in error assertions

.golangci.yml
The current file is wrong with duplicated key: the `linters-settings.ginkgolinter` key, appears twice, as result of merging two PRs: #4710 and #4714.
This is breaking golangci-lint.
This PR fixes this issue by merging the duplicated keys into one.
=> 🌱 Fix golangci-lint wrong configurations

pkg/cli/completion_test.go, pkg/cli/version_test.go
Replaced redundant multi-line `var` blocks with single-line declarations in `version_test.go` and `completion_test.go`. This reduces visual noise and aligns with idiomatic Go style for concise test setup.
=> 🌱 (chore): simplify test variable declarations for CLI tests

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
- Ensured proper error wrapping using `fmt.Errorf(..., %w, ...)` throughout `scaffolds/api.go`
- Used `%q` for filenames and paths for better formatting
=> 🌱 (chore): replace '%v' with '%w' in deploy-image v1alpha1 plugin errors

pkg/plugins/golang/go_version.go, pkg/plugins/golang/repository.go, pkg/plugins/golang/v4/init.go, pkg/plugins/golang/v4/scaffolds/api.go
Replaced usage of `%v` with `%w` in `fmt.Errorf` calls to enable proper error chaining across:
- `pkg/plugins/golang/repository.go`
- `go_version.go`
- `v4/scaffolds/api.go`
Also improved formatting by quoting dynamic values with `%q` and removed redundant error wrapping logic.
=> 🌱 (chore): wrap errors using '%w' and improve formatting in golang plugin

pkg/cli/cli.go, pkg/cli/options.go, pkg/cli/options_test.go
This change updates several pkg/cli files to ensure consistent use of error wrapping via `fmt.Errorf` with `%w`. This improves debugging and traceability by providing more context when errors occur, especially in scenarios involving file I/O and scaffolding.
=> 🌱 (chore): improve error wrapping for external plugin discovery and config loading

pkg/plugin/util/exec.go, pkg/plugin/util/util.go, pkg/plugin/version.go
This change updates several pkg/plugin files to ensure consistent use of error wrapping via `fmt.Errorf` with `%w`. This improves debugging and traceability by providing more context when errors occur, especially in scenarios involving file I/O and scaffolding.
=> 🌱 (chore): wrap plugin and util error returns for better context

docs/book/utils/plugin/plugin.go
This change adds error handling for the `os.WriteFile` function when writing the `litout.json` file. Previously, the error was not checked, which could lead to silent failures.
Ensuring that errors are properly handled and reported improves the robustness and reliability of the code. This change helps to catch and report any issues that may occur when writing the `litout.json` file.
=> 🌱 (chore): check and return error from os.WriteFile when writing litout.json

pkg/plugins/golang/deploy-image/v1alpha1/api.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
This change wraps errors in the deploy-image plugin with contextual messages to provide more informative error outputs. This helps in debugging and understanding the source of errors more easily.
=> 🌱 (chore): wrap deploy-image plugin errors with contextual messages

pkg/plugins/golang/repository.go, pkg/plugins/golang/v4/api.go, pkg/plugins/golang/v4/edit.go, pkg/plugins/golang/v4/init.go, pkg/plugins/golang/v4/webhook.go
This PR improves error diagnostics for the Golang plugin commands (`init`, `edit`, `create api`, `create webhook`, etc.) by consistently wrapping returned errors with contextual messages.
Improved developer experience: easier to trace and understand failure origins.
=> 🌱 (chore): add detailed error wrapping across Golang plugin commands

pkg/plugins/optional/helm/v1alpha/commons.go, pkg/plugins/optional/helm/v1alpha/edit.go, pkg/plugins/optional/helm/v1alpha/init.go, pkg/plugins/optional/helm/v1alpha/scaffolds/init.go
This change updates several Helm plugin files to ensure consistent use of error wrapping via `fmt.Errorf` with `%w`. This improves debugging and traceability by providing more context when errors occur, especially in scenarios involving file I/O and scaffolding.
No functional changes are introduced—this is purely an internal consistency and developer experience improvement.
=> 🌱 (chore): consistently wrap and enrich error messages across helm plugin

test/e2e/utils/kubectl.go, test/e2e/utils/test_context.go, test/e2e/utils/webhooks.go, test/e2e/v4/plugin_cluster_test.go
This change updates several test/e2e/utils files to ensure consistent use of error wrapping via `fmt.Errorf` with `%w`. This improves debugging and traceability by providing more context when errors occur, especially in scenarios involving file I/O and scaffolding.
=> 🌱 (chore): improve error context and wrapping in utility and test helpers

pkg/plugins/common/kustomize/v2/api.go, pkg/plugins/common/kustomize/v2/create.go, pkg/plugins/common/kustomize/v2/init.go, pkg/plugins/common/kustomize/v2/scaffolds/init.go, pkg/plugins/common/kustomize/v2/webhook.go
This change updates several kustomize/v2 files to ensure consistent use of error wrapping via `fmt.Errorf` with `%w`. This improves debugging and traceability by providing more context when errors occur, especially in scenarios involving file I/O and scaffolding.
=> 🌱 (chore): improve error context in common kustomize plugin scaffolds

pkg/plugins/golang/v4/scaffolds/edit.go, pkg/plugins/golang/v4/scaffolds/init.go, pkg/plugins/golang/v4/scaffolds/webhook.go
This change updates several v4/scaffolds files to ensure consistent use of error wrapping via `fmt.Errorf` with `%w`. This improves debugging and traceability by providing more context when errors occur, especially in scenarios involving file I/O and scaffolding.
=> 🌱 (chore): add error context to golang scaffolder execution steps

pkg/config/store/yaml/store.go, pkg/config/v3/config.go, pkg/config/version.go
This change updates several pkg/config files to ensure consistent use of error wrapping via `fmt.Errorf` with `%w`. This improves debugging and traceability by providing more context when errors occur, especially in scenarios involving file I/O and scaffolding.
=> 🌱 (chore): wrap config parsing and validation errors with contextual messages

docs/book/utils/litgo/literate.go, docs/book/utils/plugin/utils.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/init.go
This change removes unnecessary `string()` and `[]byte` conversions in various files. These conversions were redundant and could lead to performance overhead.
=> 🌱 (chore): remove unnecessary string() and []byte conversions

pkg/plugins/golang/repository.go
Refactored error handling in `repository.go`:
- Replaced type assertion with `errors.As` for `*exec.ExitError`
- Ensured command stderr is preserved in the wrapped `fmt.Errorf` output
- Set up for better error introspection and debugging
=> 🌱  (chore): use 'errors.As' and wrap exec errors in repository.go

docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/flags.go, docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/cmd/metadata.go, docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/init.go, docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/webhook.go
This improves the robustness of the external plugin examples in the docs by adding proper error handling when parsing flags with `pflag`.
If parsing fails, the plugin sets `pluginResponse.Error = true` and includes a clear error message in `ErrorMsgs`, preventing silent failures and making debugging easier for plugin authors following the tutorial.
=> 📖 : Improve sample external plugin by adding error handling for flag parsing failures.

pkg/plugins/external/external_test.go, pkg/plugins/external/helpers.go
This change wraps error returns in the plugins external helpers functions with contextual messages to provide more informative error outputs. This helps in debugging and understanding the source of errors more easily.
=> ✨ (API) add contextual error wrapping for external plugin helpers

docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-plugins/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
`utils.go` file under `pkg/plugins/golang/v4/scaffolds/internal/templates/test/` was updated to improve error context in utility functions like `GetProjectDir` and `UncommentCode`.
All returned errors are now consistently wrapped using `fmt.Errorf` with `%w` to preserve the original error while adding context. This aids debugging, especially in test scaffolds that may fail silently otherwise.
These changes continue the effort toward more robust and informative error handling throughout the codebase.
=> 🌱 (chore): consistently wrap and enrich error messages across test utils

cmd/cmd.go, cmd/version.go, docs/book/src/cronjob-tutorial/testdata/project/PROJECT, docs/book/src/getting-started/testdata/project/PROJECT, docs/book/src/multiversion-tutorial/testdata/project/PROJECT, docs/book/src/reference/project-config.md, pkg/cli/cli.go, pkg/cli/cmd_helpers.go, pkg/cli/options.go, pkg/config/interface.go, pkg/config/v3/config.go, testdata/project-v4-multigroup/PROJECT, testdata/project-v4-with-plugins/PROJECT, testdata/project-v4/PROJECT
This PR adds a new field to the PROJECT file: `cliVersion.`
Additionally, it updates the documentation in the [Project Configuration Reference](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/reference/project-config.md) to include the new `cliVersion` field.
It also updates the PROJECT file scaffolded in the docs and in testdata.
Closes: #4398  
Test Steps:
1. Build a snapshot release using GoReleaser:
```bash
~/kubebuilder$ goreleaser release --snapshot --skip=publish -f ./build/.goreleaser.yml
```
2. Create a new test project directory:
```bash
mkdir -p ~/projects/test-project-file && cd ~/projects/test-project-file
```
3. Initialize the test project using the Kubebuilder snapshot:
```bash
~/kubebuilder/dist/kubebuilder_linux_amd64_v1/kubebuilder init --domain …
```
=> ✨ (API, CLI, go/v4) Add cliVersion field to the PROJECT file configuration to store the CLI binary version used to scaffold projects.

Makefile
This commit changes how the Makefile handles updating Kubernetes version in `cmd/version.go` when running `make generate`.
Rely on ldflags to set `kubernetesVendorVersion`, similarly to the other variables in `cmd/version.go.`
Use a single variable to define `K8S_VERSION` for both ldflags and the `goreleaser` configuration.
This makes our version handling more consistent and avoids unnecessary diffs in version control when only generating docs or other build artifacts.
Closes: #4611
=> 🌱 Add kubernetesVendorVersion for binary builds with LD_FLAGS

docs/book/src/versions_compatibility_supportability.md
Fix link pointing to the wrong page
=> 📖 Update versions_compatibility_supportability.md to fix link in the warning note

docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/test-e2e.yml, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/.github/workflows/test-e2e.yml, docs/book/src/getting-started/testdata/project/Makefile, docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/test-e2e.yml, docs/book/src/multiversion-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/github/test-e2e.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup/.github/workflows/test-e2e.yml, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-plugins/.github/workflows/test-e2e.yml, testdata/project-v4-with-plugins/Makefile, testdata/project-v4/.github/workflows/test-e2e.yml, testdata/project-v4/Makefile
change default Kind cluster names to be project-specific for e2e tests
Previously, the default Kind cluster name was "kind", which could lead to conflicts when running multiple e2e tests concurrently across different projects. This change updates the Kind cluster name to be project-specific, reducing potential conflicts and improving the isolation of e2e test environments.
=> ✨ (go/v4): Add new makefile target to create a cluster name to run the e2e tests

Makefile
This change updates the trailing spaces removal in the Makefile. Previously, the script used the `uname` check to determine whether to use GNU or BSD sed syntax, which did not work well on macOS when GNU sed is installed.
Now the script uses a check on `sed --version` for "GNU" to decide which sed syntax to apply. This ensures that, regardless of the OS, if GNU sed is available in the PATH, the GNU sed branch is used.
=> 🌱 (fix/enhance): correct GNU sed detection method for remove-spaces makefile target

pkg/plugins/optional/grafana/v1alpha/commons.go, pkg/plugins/optional/grafana/v1alpha/edit.go, pkg/plugins/optional/grafana/v1alpha/init.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go, pkg/plugins/optional/grafana/v1alpha/scaffolds/init.go
This change wraps error returns in the grafana functions with contextual messages to provide more informative error outputs. This helps in debugging and understanding the source of errors more easily.
=> 🌱 (chore): wrap and contextualize errors across Grafana plugin

.golangci.yml
🌱 Enable `wrapcheck` linter
This change improves code quality by enforcing two new linting rule:
- `wrapcheck` ensures wrapped errors are properly handled and not silently ignored.
The motivation is to promote modern Go practices and ensure consistent error wrapping and checking across the codebase.
=> 🌱 (chore): Enable wrapcheck linter

docs/book/src/cronjob-tutorial/testdata/project/dist/chart/templates/metrics/metrics-service.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/chart/templates/prometheus/monitor.yaml, docs/book/src/getting-started/testdata/project/dist/chart/templates/metrics/metrics-service.yaml, docs/book/src/getting-started/testdata/project/dist/chart/templates/prometheus/monitor.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/metrics/metrics-service.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/prometheus/monitor.yaml, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/metrics/metrics_service.go, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/prometheus/monitor.go, testdata/project-v4-with-plugins/dist/chart/templates/metrics/metrics-service.yaml, testdata/project-v4-with-plugins/dist/chart/templates/prometheus/monitor.yaml
The Helm plugin scaffolding was missing the control-plane: controller-manager label on the metrics service, which prevented the ServiceMonitor from finding the service and collecting metrics when deployed via Helm chart.
fixes: #4591
=> 🐛 (helm/alpha-v1): Add control-plane labels to metrics service and ServiceMonitor templates

docs/book/src/cronjob-tutorial/testdata/project/go.mod, docs/book/src/getting-started/testdata/project/go.mod, docs/book/src/multiversion-tutorial/testdata/project/go.mod, docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod, go.mod, pkg/plugins/golang/v4/scaffolds/internal/templates/gomod.go, testdata/project-v4-multigroup/go.mod, testdata/project-v4-with-plugins/go.mod, testdata/project-v4/go.mod
=> 🐛 Remove redundant/noisy godebug default= lines from go.mod. 

CONTRIBUTING.md, test/e2e/kind-config.yaml, test/e2e/setup.sh, test/e2e/v4/plugin_cluster_test.go
> The recent changes in https://github.com/kubernetes-sigs/kind/pull/3612 have made it possible to test Kubernetes NetworkPolicy resources without requiring a custom CNI like Calico.
This PR fixes issue https://github.com/kubernetes-sigs/kubebuilder/issues/4790
The kind cluster doesn't need calico to test network policies anymore. 
After making changes to setup and cluster config - I got rid of test cases checking for Calico pods so e2e runs successfully - Adding a screenshot for reference
=> 🌱 Removing calico - using default CNI from Kind

docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/crd/batch.tutorial.kubebuilder.io_cronjobs.yaml, pkg/plugins/optional/helm/v1alpha/scaffolds/init.go, testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_wordpresses.yaml
fixes: #4807 
The Helm plugin scaffolding did not adjust the service name for conversion webhooks in the CRDs. This prevented the conversion webhook from being reached.
=> 🐛 (helm/v1-alpha): Append project name to webhook service name

docs/book/src/cronjob-tutorial/testdata/project/.devcontainer/devcontainer.json, docs/book/src/cronjob-tutorial/testdata/project/Dockerfile, docs/book/src/getting-started/testdata/project/.devcontainer/devcontainer.json, docs/book/src/getting-started/testdata/project/Dockerfile, docs/book/src/multiversion-tutorial/testdata/project/.devcontainer/devcontainer.json, docs/book/src/multiversion-tutorial/testdata/project/Dockerfile, pkg/plugins/golang/v4/scaffolds/internal/templates/devcontainer.go, pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go, testdata/project-v4-multigroup/.devcontainer/devcontainer.json, testdata/project-v4-multigroup/Dockerfile, testdata/project-v4-with-plugins/.devcontainer/devcontainer.json, testdata/project-v4-with-plugins/Dockerfile, testdata/project-v4/.devcontainer/devcontainer.json, testdata/project-v4/Dockerfile
✅ Why?
Docker already defaults to Docker Hub (docker.io) when no registry is specified.
So both forms are functionally the same, but:
---
2. Keeps the scaffold clean and idiomatic
- Most open source projects use the short form (golang:1.24).
- It's easier to read and better for beginners.
- This follows standard Go and Docker community practices.
- Adding docker.io just adds noise to the file.
---
3. Avoids lock-in or assumptions
- Hardcoding docker.io can break things in environments with custom or mirrored registries.
- It may confuse users who want to use private registries or CI configs.
- By writing golang:1.24, we let the Docker config decide where to pull from — which is more flexible and future-proof.
---
TL;DR
golang:1.24 already pulls from Docker Hub.
Adding docker.io is not …
=> 🐛 (go/v4) fix: revert accidental addition of explicit docker.io registry in Dockerfile

cmd/cmd.go, cmd/version.go
Avoid exporting an unnecessary helper.
This change keeps the API surface minimal and avoids exposing internal details unless truly needed.
Note: the function was newly introduced and hasn't been included in any release yet, so we can safely change its visibility without breaking anything.
=> 🐛 refactor: inline getKubebuilderVersion into cli.WithCliVersion setup

docs/book/src/reference/watching-resources/predicates-with-watch.md, docs/book/src/reference/watching-resources/secondary-resources-not-owned.md
I've followed the Kubebuilder book to add the Watches() method with predicates.
I'm using a project scaffolded with Kubebuilder v4.
I found that the examples didn't compile due to:
related bug: https://github.com/kubernetes-sigs/kubebuilder/issues/3698
The last remaining place that uses source.Kind{} is migration guide from v0 to v1 (which does the opposite operation - it introduces the source.Kind)
https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/migration_guide.md?plain=1#L107-L108
=> 📖 fix examples how to specify watched CR in Watches()

pkg/cli/alpha/internal/generate.go
The command should ensure that all manifest and default commands are properly executed as a post-scaffold action.
=> 🐛 fix(cli): ensure 'alpha generate' runs 'make manifests generate fmt vet lint-fix' after scaffolding

test/e2e/utils/test_context.go
We should not try to remove the ns when we uninstall the release.
The function should only do what its name suggests, which is to uninstall the Helm release.
Furthermore, if we manage the namespace, it needs to be for all cases, not just when we install the solution with Helm.
=> 🌱 (e2e test context): not try remove ns when we uninstall release

test/e2e/v4/plugin_cluster_test.go
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4853
PS: We let controller-runtime maintainers be aware of the scenario at https://github.com/kubernetes-sigs/controller-runtime/issues/3238
=> 🌱 (ci) fix: e2e tests by adding sleep before metrics access to handle K8s 1.33 cert delay

docs/book/src/getting-started/testdata/project/api/v1alpha1/memcached_types.go, hack/docs/internal/getting-started/generate_getting_started.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go, testdata/project-v4-multigroup/api/example.com/v1alpha1/busybox_types.go, testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_types.go, testdata/project-v4-with-plugins/api/v1alpha1/busybox_types.go, testdata/project-v4-with-plugins/api/v1alpha1/memcached_types.go
Simplify the Conditions field in status scaffolding by removing patchStrategy, patchMergeKey, and protobuf tags.
Applied to:
- deploy-image/alpha-v1 plugin template
- Getting Started Memcached example
These fields are unnecessary by default and can introduce unexpected
strategic merge behavior. Omitting them simplifies CRD scaffolding
and avoids compatibility risks for most use cases.
Follows Kubernetes API conventions:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
**Motivation**
- https://github.com/kubernetes-sigs/kubebuilder/issues/4809
- https://github.com/kubernetes-sigs/kubebuilder/pull/4888#discussion_r2171476294
=> 🐛 (deploy-image/v1alpha1): drop patchStrategy/protobuf tags from Conditions

go.mod, go.sum, pkg/config/store/yaml/store_test.go
Description: updated sigs.k8s.io/yaml version form 1.4.0 to 1.5.0 and changed formatting in 2 failing tests
Fixes https://github.com/kubernetes-sigs/kubebuilder/issues/4886
=> 🌱 updated sigs.k8s.io/yaml version form 1.4.0 to 1.5.0 and changed formatting in 2 tests

docs/book/src/getting-started/testdata/project/api/v1alpha1/memcached_types.go, docs/book/src/getting-started/testdata/project/config/crd/bases/cache.example.com_memcacheds.yaml, docs/book/src/getting-started/testdata/project/dist/chart/templates/crd/cache.example.com_memcacheds.yaml, docs/book/src/getting-started/testdata/project/dist/install.yaml, hack/docs/internal/getting-started/generate_getting_started.go, pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go, testdata/project-v4-multigroup/api/example.com/v1alpha1/busybox_types.go, testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_types.go, testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml, testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-plugins/api/v1alpha1/busybox_types.go, testdata/project-v4-with-plugins/api/v1alpha1/memcached_types.go, testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_busyboxes.yaml, testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_memcacheds.yaml, testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_busyboxes.yaml, testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_memcacheds.yaml, testdata/project-v4-with-plugins/dist/install.yaml
Updated comments for the Conditions field to use more descriptive.
Perform the change for deploy-image and Getting Started sample
- Applied CRD OpenAPI validation markers:
- `+listType=map` ensures conditions are represented as a map.
- `+listMapKey=type` enforces uniqueness of condition types.
- Improved in-code comments for maintainability and user clarity.
- Fixed minor typos and updated phrasing for accuracy.
**Motivation**
- https://github.com/kubernetes-sigs/kubebuilder/issues/4809
=> ✨ (deploy-image/v1alpha1) : Improve clarity and human readability of conditions field documentation in CRDs.

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/api/types.go, testdata/project-v4-multigroup/api/example.com/v1alpha1/busybox_types.go, testdata/project-v4-multigroup/api/example.com/v1alpha1/memcached_types.go, testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_busyboxes.yaml, testdata/project-v4-multigroup/config/crd/bases/example.com.testproject.org_memcacheds.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-plugins/api/v1alpha1/busybox_types.go, testdata/project-v4-with-plugins/api/v1alpha1/memcached_types.go, testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_busyboxes.yaml, testdata/project-v4-with-plugins/config/crd/bases/example.com.testproject.org_memcacheds.yaml, testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_busyboxes.yaml, testdata/project-v4-with-plugins/dist/chart/templates/crd/example.com.testproject.org_memcacheds.yaml, testdata/project-v4-with-plugins/dist/install.yaml
This removes the default max validation for the size field in the deploy-image plugin.
Since the plugin allows deploying any image, setting a default maximum doesn’t seem appropriate and could be misleading.
We believe it’s better to leave this responsibility to the user.
This change aligns with flexibility and avoids setting unnecessary constraints by default.
=> 🐛 (deploy-image/v1-alpha1): Remove default max size validation

docs/book/src/faq.md
Reverts kubernetes-sigs/kubebuilder#4884
=> 📖: Revert   guide for building a bundle with kubebuilder-based projects for management by OLM and/or publication on OperatorHub.io

docs/book/src/cronjob-tutorial/writing-tests.md, docs/book/src/plugins/available/deploy-image-plugin-v1-alpha.md, docs/book/src/plugins/available/go-v4-plugin.md
This pr is about fixing some of the broken links on https://book.kubebuilder.io/
fixes #4906
=> 📖 (doc): fixed the broken links

pkg/cli/alpha/internal/update/prepare.go
Found this while I was working on writing the Unit Test cases for alpha cli commands.
The alpha update command --to-version verifies if the 'v' prefix is added by user, if not prepends 'v' to the specified version. But here, the check is done on --from-version instead of --to-version which might cause 'v' to be prefixed even if user specifies it in the command line for --to-version field
=> 🐛 (CLI) fix alpha update command to version pre-require check

.github/workflows/lint-sample.yml, .github/workflows/lint.yml, .golangci.yml, Makefile, docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml, docs/book/src/getting-started/testdata/project/Makefile, docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml, docs/book/src/multiversion-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/init.go, testdata/project-v4-multigroup/.github/workflows/lint.yml, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-plugins/.github/workflows/lint.yml, testdata/project-v4-with-plugins/Makefile, testdata/project-v4/.github/workflows/lint.yml, testdata/project-v4/Makefile
- For Kubebuilder CLI and scaffolds
=> ✨ Upgrade Golang-CI from v2.1.6 to v2.2.2

docs/book/src/reference/commands/alpha_update.md, pkg/cli/alpha/internal/update/update.go, pkg/cli/alpha/update.go
This PR adds the `--force` flag to the `alpha update` command, as well as e2e tests for the flag. 
The `--force` flag makes it possible to run the `alpha update` command in CI workflows.
If the `--force` flag is not passed to the command, the update operation will abort if there are conflicts, informing the user that manual resolution is necessary:
```
vitor@pc:~/go/src/github.com/vitorfloriano/multiversion$ kubebuilder alpha update --from-version v4.5.0 --to-version v4.
6.0 --from-branch main
INFO Checking if is a git repository
INFO Checking if branch has uncommitted changes
INFO Binary version v4.5.0 is available
INFO Binary version v4.6.0 is available
INFO Checking out base branch: main
INFO Using branch names:
INFO   Ancestor: tmp-ancestor-16-07-25-23-25
INFO   Original: …
```
=> ✨ (alpha update command): add --force flag

docs/book/src/reference/commands/alpha_update.md
This PR removes a suggestion marker in the `alpha update` docs.
The marker was mistakenly left in the document when accepting a suggestion on #4936 .
=> 📖 (docs/alpha update): remove suggestion marker

docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go, docs/book/src/getting-started/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go, docs/book/src/multiversion-tutorial/testdata/project/Makefile, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_suite_test.go, docs/book/src/multiversion-tutorial/testdata/project/test/e2e/e2e_test.go, hack/docs/internal/cronjob-tutorial/e2e_implementation.go, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/suite.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go, test/check-license.sh, testdata/project-v4-multigroup/Makefile, testdata/project-v4-multigroup/test/e2e/e2e_suite_test.go, testdata/project-v4-multigroup/test/e2e/e2e_test.go, testdata/project-v4-with-plugins/Makefile, testdata/project-v4-with-plugins/test/e2e/e2e_suite_test.go, testdata/project-v4-with-plugins/test/e2e/e2e_test.go, testdata/project-v4/Makefile, testdata/project-v4/test/e2e/e2e_suite_test.go, testdata/project-v4/test/e2e/e2e_test.go
Some users unintentionally ran E2E tests against production environments by using `go test ./...`. This can lead to dangerous side effects like uninstalling Cert Manager or modifying shared clusters.
- Added `//go:build e2e` tags to all E2E test files.
- Updated the `Makefile` to run E2E tests with `-tags=e2e`.
You must explicitly pass the tag:
```bash
make test-e2e
go test -tags=e2e ./test/e2e/...
```
E2E tests are no longer included in default `go test ./...` runs, reducing risk of accidental execution.
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4116
c/c @applejag
=> ✨ (go/v4) add e2e build tag to prevent accidental execution of end-to-end tests

.github/workflows/lint.yml, docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml, docs/book/src/getting-started/testdata/project/Makefile, docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml, docs/book/src/multiversion-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/init.go, testdata/project-v4-multigroup/.github/workflows/lint.yml, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-plugins/.github/workflows/lint.yml, testdata/project-v4-with-plugins/Makefile, testdata/project-v4/.github/workflows/lint.yml, testdata/project-v4/Makefile
This PR updates golangci-lint to v2.3.0 to resolve issues with the var-naming rule in revive.
context - https://github.com/kubernetes-sigs/kubebuilder/pull/4954#issuecomment-3102383102
=> ✨ Upgrade Golang-CI from v2.2.2 to v2.3.0

.github/workflows/release-version-ci.yml
=> 🌱 (ci) - Add test for release mock

pkg/plugins/golang/go_version_test.go, pkg/plugins/golang/options_test.go, pkg/plugins/golang/repository_test.go
Issue: https://github.com/kubernetes-sigs/kubebuilder/issues/4925
Continuation from my previous UT PRs :-)
- Improves the coverage by adding UTs for plugins/golang package.
- This should cover all the UTs for plugins pkg
=> 🌱 (CLI): Add unit tests and improve coverage for plugins/golang pkg

docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go, hack/docs/internal/cronjob-tutorial/e2e_implementation.go, hack/docs/internal/cronjob-tutorial/generate_cronjob.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-plugins/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
We removed the Prometheus helpers from the E2E test utils:
- `installPrometheus`
- `uninstallPrometheus`
- `isPrometheusInstalled`
We don’t use Prometheus in E2E tests anymore. The tests work fine without it because:
- We don’t actually rely on Prometheus during tests
- We can check reconciliation metrics using `controller-runtime` (which gives us basic metrics by default)
This cleanup makes the code simpler and easier to maintain.
PS: we kept the example in the docs to show how to do.
=> 🐛 remove: Prometheus install/check helpers from e2e utils

docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go, docs/book/src/getting-started/testdata/project/test/utils/utils.go, docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go, pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go, testdata/project-v4-multigroup/test/utils/utils.go, testdata/project-v4-with-plugins/test/utils/utils.go, testdata/project-v4/test/utils/utils.go
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4712
> **NOTE:** The E2E tests are designed to run in isolated environments intended specifically for them,  
> such as the GitHub Actions workflows scaffolded by default.
c/c @wallrj @erikgb @mahmoudhossam
=> 🐛 (go/v4)(fix): (e2e) delete CertManager leftover leases in kube-system (not cleaned by default)

.github/workflows/lint-sample.yml, Makefile
Fixes: https://github.com/kubernetes-sigs/kubebuilder/issues/4972
This fix updates the version in the Makefile and lint yaml to v2.3.0.
=> ✨ Version bump for golangci-lint to 2.3.0 ( follow up #4957 )

docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/chart/templates/manager/manager.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/chart/values.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml, docs/book/src/getting-started/testdata/project/config/manager/manager.yaml, docs/book/src/getting-started/testdata/project/dist/chart/templates/manager/manager.yaml, docs/book/src/getting-started/testdata/project/dist/chart/values.yaml, docs/book/src/getting-started/testdata/project/dist/install.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/manager/manager.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/chart/values.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml, go.mod, go.sum, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/manager/manager.go, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/values.go, testdata/project-v4-multigroup/config/manager/manager.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-plugins/config/manager/manager.yaml, testdata/project-v4-with-plugins/dist/chart/templates/manager/manager.yaml, testdata/project-v4-with-plugins/dist/chart/values.yaml, testdata/project-v4-with-plugins/dist/install.yaml, testdata/project-v4/config/manager/manager.yaml, testdata/project-v4/dist/install.yaml
Adding image pull policy tag to the helm template
Fixing issue: #4859
=> ✨  (go/v4;helm/alpha-v1;kustomize/v2): Adding default image policy for the manager

Makefile
- Introduced `LOCALBIN` to define local binary installation directory (`./bin`).
- Added a reusable `go-install-tool` Make function to install Go tools with version pinning.
- Refactored `golangci-lint` and `go-apidiff` targets to use `go-install-tool`.
- Defined tool binary paths (`GO_APIDIFF`, `GOLANGCI_LINT`) and their corresponding version variables.
=> 🌱 Add versioned tool installation via `go-install-tool` helper in Kubebuilder Makefile such as we provide for end users

roadmap/README.md
This PR adds a link to the 2025 roadmap in the documentation.
At first glance of it didn’t appear there was a roadmap for the year, adding the reference for clarify and visibility.
=> 📖 (docs) include 2025 roadmap

docs/book/src/cronjob-tutorial/testdata/project/config/manager/manager.yaml, docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml, docs/book/src/getting-started/testdata/project/config/manager/manager.yaml, docs/book/src/getting-started/testdata/project/dist/install.yaml, docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml, docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml, pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/config.go, testdata/project-v4-multigroup/config/manager/manager.yaml, testdata/project-v4-multigroup/dist/install.yaml, testdata/project-v4-with-plugins/config/manager/manager.yaml, testdata/project-v4-with-plugins/dist/install.yaml, testdata/project-v4/config/manager/manager.yaml, testdata/project-v4/dist/install.yaml
Why are we reverting the scaffold changes?
- Scaffold Stability: Changes to the default scaffold can't be done lightly. They can create a lot of extra work and cause issues for end-users when they upgrade to a new version. We want to avoid causing upgrade burden.
- Complexity: Adding a large number of defaults to the scaffold would make it overly complex and difficult to maintain over time.
- A Better Approach: We need to address the Helm chart plugin's design in a more comprehensive way, as outlined in the Kubebuilder issues:
- https://github.com/kubernetes-sigs/kubebuilder/issues/4833
- https://github.com/kubernetes-sigs/kubebuilder/milestone/39
- https://github.com/kubernetes-sigs/kubebuilder/issues/4912
Thank you to the original author for their contribution. This change is being made …
=> 🐛 (revert) only changes done in the default scaffold in the pr: 4932 ( kept helm chart changes )

cmd/cmd.go, docs/book/src/SUMMARY.md, docs/book/src/plugins/available/autoupdate-v1-alpha.md, docs/book/src/plugins/to-add-optional-features.md, docs/book/src/reference/commands/alpha_update.md, pkg/cli/alpha/internal/generate.go, pkg/cli/alpha/internal/update/update.go, pkg/plugins/optional/autoupdate/v1alpha/edit.go, pkg/plugins/optional/autoupdate/v1alpha/init.go, pkg/plugins/optional/autoupdate/v1alpha/plugin.go, pkg/plugins/optional/autoupdate/v1alpha/scaffolds/init.go, pkg/plugins/optional/autoupdate/v1alpha/scaffolds/internal/github/auto_update.go, test/e2e/alphagenerate/generate_test.go, test/testdata/generate.sh, testdata/project-v4-with-plugins/.github/workflows/auto_update.yml, testdata/project-v4-with-plugins/PROJECT
Adds an optional plugin that scaffolds a GitHub Actions workflow to keep projects aligned with the latest Kubebuilder scaffold. The workflow runs `kubebuilder alpha update` (3-way merge), pushes an update branch, and opens a GitHub Issue with a compare link so maintainers can open a PR and review safely.
=> ✨ Add plugin for Alpha Update Command

docs/book/src/reference/commands/alpha_update.md, pkg/cli/alpha/update.go
Switch default Git config to use `merge.conflictStyle=merge`, so conflicts render as:
```diff
<<<<<<< HEAD
foo
=======
bar
>>>>>>> branch
```
Note after we added the configs this configuration was lost.
=> 🐛 (alpha update): ensure that by default is used merge.conflictStyle=merge to facilitate the review

cmd/cmd.go, pkg/cli/alpha/generate.go, pkg/cli/alpha/internal/generate.go, pkg/cli/alpha/internal/update.go, pkg/cli/alpha/update.go, pkg/plugin/util/exec.go
(fix): Fix inconsistent logging format 
Follow up: https://github.com/kubernetes-sigs/kubebuilder/pull/4968
Testing alpha update and generate revealed logs were not in the right format.
Changes:
- Initialize consistent logging handler in alpha commands to fix level=info msg= format
- Replace log.Fatalf with slog.Error + os.Exit(1) for proper error handling
- Standardize log imports to use log "log/slog" across all files
- Remove redundant command info from RunCmd logging output
- Ensure all kubebuilder processes use the same colored INFO/WARN format
Before: level=warning msg="Using current working directory..."
After:  WARN Using current working directory...
=> 🌱  (fix): Fix inconsistent logging format  ( Follow up: #4968 )

cmd/cmd.go, pkg/cli/alpha/generate.go, pkg/cli/alpha/internal/generate.go, pkg/cli/alpha/internal/update/helpers/git_commands.go, pkg/cli/alpha/internal/update/update.go, pkg/cli/alpha/update.go
This PR centralises the initialisation of the logs in the CLI and address the fix for alpha update and generate commands
Old kubebuilder binaries executed during update were outputting
level=info msg= format. Now captures and reformats to INFO/WARN/ERROR
style for a consistent user experience.
=> 🐛 (fix) reformat subprocess output for consistent logging during alpha commands (Follow up: #4968)

docs/book/src/quick-start.md
=> 📖 (docs): Add missing information to quick start and supplement links

docs/book/src/cronjob-tutorial/testdata/project/Dockerfile, docs/book/src/getting-started/testdata/project/Dockerfile, docs/book/src/multiversion-tutorial/testdata/project/Dockerfile, pkg/plugins/golang/v4/scaffolds/internal/templates/dockerfile.go, testdata/project-v4-multigroup/Dockerfile, testdata/project-v4-with-plugins/Dockerfile, testdata/project-v4/Dockerfile
Fix a couple typos in the Dockerfile comments.
Noticed this while building a new CRD (very smooth flow by the way, really appreciate the effort in this area!)
=> 🐛 (go/v4) fix simple typos in Dockerfile comments

README.md, docs/windows.md
This pull request updates the project's documentation to clarify the status of Windows support and provide guidance for Windows users.
Documentation updates regarding Windows support:
* Updated the `README.md` to direct Windows users to a new `docs/windows.md` file for instructions, and clarified that contributions towards native Windows support are not planned.
* Added a new `docs/windows.md` file explaining that native Windows support is not being pursued, and providing instructions for using Kubebuilder on Windows via **WSL2** and **Docker Desktop**, with links to relevant official documentation.
Closes #2940
=> 📖 add note about Windows support

.github/workflows/test-helm-book.yml, .github/workflows/test-helm-samples.yml, docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/test-chart.yml, docs/book/src/getting-started/testdata/project/.github/workflows/test-chart.yml, docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/test-chart.yml, pkg/plugins/common/kustomize/v2/scaffolds/webhook.go, pkg/plugins/optional/helm/v1alpha/edit.go, pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/github/test_chart.go, testdata/project-v4-with-plugins/.github/workflows/test-chart.yml
The Helm chart flag installCRDs has been replaced with the community-standard crds.enabled. Update your GitHub action `test-chart.yml`to ensure CRDs are installed during chart deployment.
=> ⚠️ (helm/v1-alpha): Migrate from installCRDs=true to crds.enabled=true in GitHub action `test-chart.yml`

.github/workflows/test-e2e-samples.yml, docs/book/src/cronjob-tutorial/testdata/project/Makefile, docs/book/src/getting-started/testdata/project/Makefile, docs/book/src/multiversion-tutorial/testdata/project/Makefile, pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go, testdata/project-v4-multigroup/Makefile, testdata/project-v4-with-plugins/Makefile, testdata/project-v4/Makefile
This PR fixes an issue where `make install` fails on freshly initialized Kubebuilder projects that have no APIs created yet. The
scaffolded Makefile now gracefully handles missing CRD directories.
When users run `kubebuilder init` without creating any APIs, the `config/crd` directory doesn't exist. This causes `make install` to  fail with: Error: must build at directory: not a valid directory: evalsymlink failure on 'config/crd' : lstat .../config/crd: no such file or directory
This breaks the basic e2e tests and GitHub Actions workflows for projects in their initial state.
1. **Updated Makefile template** (`pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go`):
- Modified `install` target to check if CRDs exist before attempting to install
- Modified `uninstall` target with …
=> 🐛 (go/v4) Handle empty CRD directories in Makefile install/uninstall targets

.golangci.yml, cmd/cmd.go, docs/book/src/plugins/extending/extending_cli_features_and_plugins.md, pkg/cli/alpha/internal/generate.go, pkg/cli/cli_test.go, pkg/plugins/optional/helm/v1alpha/scaffolds/edit.go, test/e2e/alphagenerate/generate_test.go, test/e2e/alphagenerate/generate_v4_multigroup_test.go, test/e2e/alphagenerate/generate_v4_with_plugins_test.go
As we have some inconsistency on few aliased imports (typo, different alias naming) which also leads to using wrong packages in one/two code path
=> 🌱 chore: enforce internal package import aliases

docs/book/src/quick-start.md
If you follow the guide from top to `kubectl apply -k config/samples/`, then the command will fail here.
I added a note, so that the first-time-user
experience is a bit more convenient.
=> 📖 Quickstart: Add note about editing the resource
