kubernetes-sigs/kubebuilder

docs/tools_user_guide.md

Updated docs to show the new way to build and install the CRD and controller manager.

"kubebuilder create config" not "installer containers"

---

cmd/kubebuilder/create/util/util.go

Disallow pluralized Kinds when creating resources

---

cmd/kubebuilder/initproject/init.go

Check that go version is 1.10+ in kubebuilder init

---

pkg/inject/args/args.go

Needed for writing some unit tests.

Update InjectArgs kubernetes Clientset to Interface.

---

test.sh

NOTE: This is a quick way to run current tests locally. Next step is to add it to travis.

added script to perform a quick test

---

test.sh

Adds a very basic test for `kubebuilder create config --crds` that verifies the content of a single CRD.

Add basic test for kubebuilder create config --crds

---

README.md

...it wasn't immediately obvious that this was just for CRDs to me as a new person

Add link to CRD docs to README

---

cmd/kubebuilder/create/resource/run.go
cmd/kubebuilder/create/util/util.go
test.sh

Allow plural resource names

---

docs/book/beyond_basics/controllers_for_core_resources.md

Update GitBook docs with warning about core-type scaffold tests failing

---

cmd/internal/codegen/parse/crd.go
cmd/internal/codegen/parse/util.go
cmd/kubebuilder-gen/internal/resourcegen/versioned_generator.go
pkg/gen/apis/doc.go
test.sh
test/resource/expected/crd-expected.yaml

Add more support for CRD validation

---

docs/book/book.json

Do not merge this PR. 
I am running to weird npm related errors, so want to try out this change in someone's environment.

WIP: added Google Analytics to gitbook

---

cmd/kubebuilder/initproject/vendor.go

Create dep manifest file if it doesn't exist

---

README.md
docs/book/README.md

Also add message about sharing the book.
Fixes #174
Fixes #173

Add links to slack, googlegroup resources to GitBook and README.md

---

pkg/controller/controller.go
pkg/controller/controller_test.go

pkg/controller: re-add to the queue failed reconcile keys

---

test/e2e/config.go
test/e2e/e2e.go
test/e2e/e2e_test.go
test/e2e/framework/ginkgowrapper/wrapper.go
test/e2e/framework/test_context.go
test/e2e/framework/util.go
test/internal/e2e/kubebuildertest.go

Fix: https://github.com/kubernetes-sigs/kubebuilder/issues/166
the PR
- add e2e framework
- add test case to cover main workflow
TODO: 
-  (in separate PRs) add more tests to cover edge-cases
/assign @droot @pwittrock

Add e2e test for kubebuilder

---

cmd/internal/codegen/parse/crd.go
test.sh
test/data/resource/expected/crd-expected.yaml

fix crd validation spec for byte arrays

---

build/thirdparty/brodocs/Dockerfile
build/thirdparty/brodocs/runbrodocs.sh
cmd/kubebuilder/docs/docs.go

Run brodocs container as the current user.

---

cmd/kubebuilder/initproject/init.go

removed an extra 'dep ensure' step in init project

---

cmd/internal/codegen/parse/crd.go
cmd/internal/codegen/types.go
cmd/kubebuilder-gen/internal/resourcegen/versioned_generator.go
cmd/kubebuilder/create/resource/resource.go
cmd/kubebuilder/create/resource/run.go

Add categories to the CRD installed by the controller

---

cmd/Gopkg.lock
cmd/kubebuilder/v1/api.go
cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/controller/controllertest.go
testv1.sh

- add --namespaced flag
- enable test for core type controller

fix core type controller

---

build/gitbook/config/deployment_new.yaml
build/gitbook/config/service_new.yaml
docs/book/README.md
docs/book/SUMMARY.md
docs/book/basics/project_creation_and_structure.md
docs/book/basics/simple_controller.md
docs/book/basics/simple_controller_manager.md
docs/book/basics/simple_resource.md
docs/book/basics/what_is_a_controller.md
docs/book/basics/what_is_a_resource.md
docs/book/basics/what_is_the_controller_manager.md
docs/book/beyond_basics/boilerplate.md
docs/book/beyond_basics/controller_watches.md
docs/book/beyond_basics/controllers_for_core_resources.md
docs/book/beyond_basics/creating_events.md
docs/book/beyond_basics/generating_documentation.md
docs/book/beyond_basics/running_tests.md
docs/book/beyond_basics/upgrading_kubebuilder.md
docs/book/getting_started/hello_world.md
docs/book/getting_started/installation_and_setup.md
docs/book/getting_started/what_is_kubebuilder.md
docs/book/getting_started/why_kubernetes.md
docs/book/node_modules/gitbook-plugin-theme-api/README.md
docs/book/quick_start.md

Staged here:
http://docs.kubebuilder.io/

GitBook updates for 1.0

---

common.sh
testv1.sh

Speed up tests by caching deps

---

cmd/Gopkg.lock
cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/controller/controllertest.go
cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/project/makefile.go

Pick up changes for https://github.com/kubernetes-sigs/kubebuilder/pull/310

update controller-tools vendor

---

cmd/kubebuilder/v1/api.go
common.sh
test/e2e/common.go
test/e2e/e2e_test.go
test/e2e/e2e_v0.go
test/e2e/e2e_v1.go
test/internal/e2e/kubebuildertest.go

add e2e test for v1 kubebuilder

---

cmd/kubebuilder/initproject/init.go
cmd/kubebuilder/initproject/project.go
cmd/kubebuilder/main.go
cmd/kubebuilder/util/util.go
cmd/kubebuilder/v1/commands.go
cmd/kubebuilder/v1/docs.go
testv0.sh
testv1.sh

- change `kubebuilder init` default to v1 `init`
- add `docs` command in v1 commands
- change version in `PROJECT` file from 2 to 1

Set default to v1 commands

---

cmd/kubebuilder/initproject/vendor.go

fixed gopkg.toml lookup code in vendor update

---

docs/book/SUMMARY.md
test/e2e/e2e_v0.go
test/e2e/e2e_v1.go

This PR fixes typo for "Controller".

Fix typo for "Controller"

---

docs/README.md
docs/book/getting_started/installation_and_setup.md
docs/book/quick_start.md

gitbook: fixed installation instructions

---

cmd/kubebuilder/v1/api.go

Validate create api flags

---

docs/book/getting_started/installation_and_setup.md

Update newest stable version to "1.0.1".

Update stable version in book

---

cmd/Gopkg.lock
cmd/vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/testData/pkg/apis/fun/v1alpha1/toy_types.go
cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/crd.go
cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/util.go
cmd/vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/types.go
cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/project/gitignore.go
cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/project/kustomize.go
cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/resource/typestest.go
cmd/vendor/sigs.k8s.io/controller-tools/pkg/scaffold/scaffold.go

fixes https://github.com/kubernetes-sigs/kubebuilder/issues/385

pick up latest controller-tools

---

docs/book/SUMMARY.md
docs/book/basics/simple_resource.md
docs/book/beyond_basics/annotations.md

Add subresource annotation documents in gitbook

---

pkg/scaffold/controller/controller.go

This is already taken care of by `AddToManagerFuncs`.

Remove unneeded user action comment.

---

docs/book/basics/simple_resource.md
docs/book/public/basics/simple_resource.html

Remove the duplicated word "defaults"

Remove the duplicated word "defaults"

---

cmd/api.go
docs/book/basics/simple_resource.md
docs/book/public/basics/simple_resource.html
test/e2e/common.go
test/e2e/e2e_test.go

Fix typos: runing->running, genrating->generating

Fix typos: runing->running, genrating->generating

---

docs/book/beyond_basics/controller_watches.md

Adding unstructured example for book

---

pkg/scaffold/controller/controller.go
pkg/scaffold/controller/controllersuitetest.go
test/project/pkg/controller/firstmate/firstmate_controller.go
test/project/pkg/controller/firstmate/firstmate_controller_suite_test.go
test/project/pkg/controller/frigate/frigate_controller_suite_test.go
test/project/pkg/controller/healthcheckpolicy/healthcheckpolicy_controller_suite_test.go
test/project/pkg/controller/kraken/kraken_controller_suite_test.go
test/project/pkg/controller/namespace/namespace_controller_suite_test.go

Fix: kubernetes-sigs/kubebuilder#380
Thanks for the review.

use controller-runtime logging in controller

---

docs/book/basics/simple_controller.md

Controller example in gitbook does not work due to wrong Reconcile
function. This patch updates the function.
Fixes #473

Fix controller example in gitbook

---

.travis.yml
scripts/install.sh
scripts/install_test.sh

Add a script to test installation script

---

pkg/scaffold/webhook/admissionhandler.go
test/project/pkg/webhook/default_server/firstmate/mutating/firstmate_create_update_handler.go
test/project/pkg/webhook/default_server/firstmate/mutating/firstmate_delete_handler.go
test/project/pkg/webhook/default_server/frigate/validating/frigate_update_handler.go
test/project/pkg/webhook/default_server/kraken/validating/kraken_create_handler.go
test/project/pkg/webhook/default_server/namespace/mutating/namespace_update_handler.go

[doc] add comments about how to use the client in webhook handler

---

docs/book/package-lock.json

This PR solve a issue with lodash.
See https://app.netlify.com/sites/kubebuilder/deploys/5c2e608168545047b71695b7 as an example.

fix package lock

---

docs/README.md
docs/book/README.md

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
Before: 
After:

Update book README, fix a typo and formatting

---

README.md
docs/migration_guide.md
docs/using_an_external_type.md
pkg/scaffold/project/gopkg.go
scripts/install.sh

Signed-off-by: Alex Yang <yangyang1@zte.com.cn>

Fix some typos

---

cmd/docs.go

Signed-off-by: runzexia <runzexia@yunify.com>

Improve the commands descriptions

---

docs/book/beyond_basics/creating_events.md

Add more details to creating events section of the book:
* Required RBAC permissions
* Creating an events recorder 
* Concrete example of creating events

:book: update create events section

---

docs/book/_redirects

add https redirect

---

pkg/scaffold/controller/controller.go
pkg/scaffold/controller/controllertest.go
test/project/pkg/controller/firstmate/firstmate_controller.go
test/project/pkg/controller/firstmate/firstmate_controller_test.go

Also changed one test of reconcile on delete

Skip update op when instance is created

---

docs/book/getting_started/why_kubernetes.md

Kubenernetes typo fixed to Kubernetes.

Typo fixed - Kubenernetes

---

build/build_kubebuilder.sh
cmd/main.go
common.sh
pkg/scaffold/project/project.go
test.sh

GOPATH is a multi-value environment variable

---

docs/kubebuilder_annotation.md

- Syntax of annotation
- Symbols allowed in annotation

Kubebuilder Annotation Document

---

pkg/scaffold/controller/controllertest.go
pkg/scaffold/resource/typestest.go
test/project/pkg/apis/creatures/v2alpha1/kraken_types_test.go
test/project/pkg/apis/crew/v1/firstmate_types_test.go
test/project/pkg/apis/policy/v1beta1/healthcheckpolicy_types_test.go
test/project/pkg/apis/ship/v1beta1/frigate_types_test.go
test/project/pkg/controller/firstmate/firstmate_controller_test.go
test/project/pkg/controller/frigate/frigate_controller_test.go
test/project/pkg/controller/healthcheckpolicy/healthcheckpolicy_controller_test.go
test/project/pkg/controller/kraken/kraken_controller_test.go
test/project/pkg/controller/namespace/namespace_controller_test.go

resolves #598
Co-authored-by: Sam Gunaratne <sgunaratne@pivotal.io>

Use idiomatic gomega syntax in generated tests

---

cmd/init_project.go

Fix typo in init_project

---

pkg/scaffold/controller/controller.go
test/project/pkg/controller/firstmate/firstmate_controller.go

Follow up: https://github.com/kubernetes-sigs/kubebuilder/pull/463/files#r259120676
/assign @mengqiy

Template controller name when logging

---

README.md
designs/README.md
designs/template.md

This adds a design folder and template that we can use for documenting
major design decisions.

:running: add a design folder and template

---

pkg/scaffold/manager/config.go
test/project/config/manager/manager.yaml

:bug: Workaround an issue so that controller-manager can rollback from a broken state

---

docs/book/quick_start.md

Signed-off-by: Oren Shomron <shomron@gmail.com>

Fix typo in quickstart guide

---

cmd/main.go

Just a minor change around double quotes.

Updating double quotes in help text

---

README.md

Signed-off-by: Alex Yang <yangyang1@zte.com.cn>

:doc: Fix link of designs directory

---

docs/book/basics/simple_resource.md

:doc: Typo

---

pkg/scaffold/project/project.go
pkg/scaffold/v1/manager/apis.go

Fixes #300. ~~Add windows binaries for kubebuilder~~. Depends on https://github.com/kubernetes-sigs/controller-tools/pull/179.

🐛 fix windows releases

---

docs/book/_redirects

Nicer shortlinks for downloads (eg. go.kubebuilder.io/dl/1.0.8/linux).

:running: More shortlinks

---

netlify.toml

This adds a netlify config for the v1 book branch.

Add v1 Netlify Config

---

docs/book/src/quick-start.md

:running: updated install instructions to use 2.0.0-alpha.0

---

docs/book/src/quick-start.md

quick start update to install 2.0.0-alpha.1

:book: quick start update to install 2.0.0-alpha.1

---

designs/simplified-scaffolding.md
docs/book/src/cronjob-tutorial/testdata/project/api/v1/groupversion_info.go
pkg/scaffold/v2/group.go
testdata/project-v2/api/v1/groupversion_info.go

s/schemeBuilder/SchemeBuilder/g

scaffold/v2/group: fix comment capitalization for golint

---

docs/book/src/quick-start.md

:book: Update controller file path

---

pkg/scaffold/v2/controller_suitetest.go

:bugfix: fixed path-to-crd-dir in controller test suite

---

docs/using_an_external_type.md

I came across the guide [Using an External Type](https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/using_an_external_type.md) doc when adding an external type to a project. While it was helpful, the naming conventions were confusing, it is not clear what should be added vs appended to existing files, and the order of steps could be improved. This was particularly true when testing with external types, and this was also raised in https://github.com/kubernetes-sigs/kubebuilder/issues/369. 
To address this, I have made the following changes:
- Improved the naming conventions (i.e. `my` vs `their`) to make it easier to tell what is internal vs external
- Show how external schema and CRDs are added
- Move `dep ensure` before referencing `vendor` in tests
In …

Doc Clarification: Using an External Type

---

docs/book/src/quick-start.md

update quickstart to use 2.0.0-alpha.3 release

:book: update quickstart to use 2.0.0-alpha.3 release

---

pkg/scaffold/v2/typestest.go
testdata/project-v2/api/v1/captain_types_test.go
testdata/project-v2/api/v1/firstmate_types_test.go

Fixes a minor typo in the templates.

fix: additonal->additional

---

docs/book/src/SUMMARY.md
docs/book/src/cronjob-tutorial/testdata/finalizer_example.go
docs/book/src/reference/reference.md
docs/book/src/reference/using-finalizers.md

This PR adds reference documentation for using finalizers.
fixes https://github.com/kubernetes-sigs/kubebuilder/issues/379

:book: docs for using finalizers

---

generated_golden.sh
pkg/scaffold/v2/controller_suitetest.go
pkg/scaffold/v2/main.go
testdata/project-v2/controllers/suite_test.go
testdata/project-v2/main.go

Follow up from #780, this fixes a few more issues.
I haven't managed to get the tests working yet, so I expect these will fail while I figure that out.

fix golangci-lint reported issues

---

docs/book/src/quick-start.md

Fix typo in quick-start.md

---

docs/book/src/cronjob-tutorial.md
docs/book/src/quick-start.md

Found some typos while reading the book

:book: fix typos

---

docs/book/src/cronjob-tutorial.md

s/It does the by/It does this by/

cronjob-tutorial.md - fix typo

---

pkg/scaffold/project/gopkg.go

Signed-off-by: Haiyan Meng <haiyanmeng@google.com>

:book: Comment fix

---

cmd/webhook_v2.go
generated_golden.sh
testdata/project-v2/api/v1/captain_webhook.go
testdata/project-v2/api/v1/firstmate_webhook.go
testdata/project-v2/config/webhook/manifests.yaml

Fix a bug caused by copy-pasting.
And modify the tests a bit to cover it.

:bug: fix a bug in create webhook command

---

cmd/main.go

:book: fix root help text

---

designs/README.md
designs/simplified-scaffolding.md
designs/template.md

A few minor spelling corrections in the design docs. Thank you to the maintainers for your hard work on this project!

typos: minor spelling corrections in design docs

---

designs/simplified-scaffolding.md

A few small updates to code examples in `designs/simplified-scaffolding.md`. Observed when implementing updated folder structure. Thanks!

scaffold: update code examples to be valid

---

docs/book/src/cronjob-tutorial/epilogue.md
docs/book/src/cronjob-tutorial/gvks.md
docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_types.go
docs/book/src/multiversion-tutorial/webhooks.md
docs/book/src/reference/markers.md
docs/book/src/reference/markers/object.md
docs/book/utils/litgo/literate.go
docs/book/utils/plugin/input.go
docs/book/utils/plugin/utils.go

This PR fixes some typos I found when reading the book.
Thx for the great docs!

fixed some typos in the book

---

docs/book/src/quick-start.md

updated instructions to install 2.0.0-rc.0 release

:book: updated instructions to install 2.0.0-rc.0 release

---

pkg/scaffold/v1/manager/manager_test.go
pkg/scaffold/v1/resource/resource_test.go
pkg/scaffold/v1/webhook/webhook_test.go

Otherwise it's really hard to understand the ginkgo output

ginkgo: Print the name of the golden file we are matching

---

docs/book/src/cronjob-tutorial/api-design.md

This PR is to address the typo in #921

Add int64 to numbers section in api-design doc

---

docs/book/src/SUMMARY.md
docs/book/src/reference/writing-tests.md

Sorry this is so minimal, but I think a pointer to an existing set of tests will be helpful. It took me some time to find this example test myself, so hopefully this can save someone else some time.

:book: Add some very rudimentary testing tips

---

docs/book/src/migration/guide.md

Fix link of v1-project

---

scripts/install_and_setup.sh

v3.1.0 matches the version we suggest in quick-start.md

:running: use kustomize v3.1.0 for testing

---

DESIGN.md

A few typos jumped at me when looking around the DESIGN.md file.

DESIGN: Fix a few typos

---

docs/book/src/quick-start.md

updated quick-start to use 2.0.1 release

:book: updated quick-start to use 2.0.1 release

---

scripts/demo/README.md
scripts/demo/run.sh
scripts/demo/util.sh

Add demo script to run quick demo of Kubebuilder. This is
also useful for recording demo videos using asciinema.

:running: added demo script

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/support-question.md
.github/PULL_REQUEST_TEMPLATE.md

**Description of the change:**
Improve PR Templates
**Motivation for the change:**
https://github.com/kubernetes-sigs/kubebuilder/issues/1028

:running: improve issue and PR templates

---

pkg/scaffold/v1/resource/doc.go
pkg/scaffold/v1/resource/group.go
pkg/scaffold/v1/resource/register.go
pkg/scaffold/v1/resource/resource.go
pkg/scaffold/v1/resource/types.go
pkg/scaffold/v1/resource/version_suitetest.go
pkg/scaffold/v2/controller.go
pkg/scaffold/v2/controller_suitetest.go
pkg/scaffold/v2/group.go
pkg/scaffold/v2/main.go

fix: Error in the scaffold files when the group name has "-"
**Motivation**
https://github.com/kubernetes-sigs/kubebuilder/issues/1007
**Steps to Test**
Follow the Quick Start with this PR and use the group name as webaap-test. Then, all should work well.

fix: Error in the scaffold files when the group name has "-"

---

CONTRIBUTING.md

Fix the steps as adding the prerequisites. 
**Motivation**
Issues faced trying to contribute with. 
https://github.com/kubernetes-sigs/kubebuilder/issues/1070

fix contribution steps

---

pkg/scaffold/v1/resource/resource.go
pkg/scaffold/v1/resource/resource_test.go

Replace group name regex validation for k8s framework validation
**Motivation**
https://github.com/kubernetes-sigs/kubebuilder/issues/1040
https://github.com/kubernetes-sigs/kubebuilder/issues/1037

Replace group name regex validation for k8s framework validation

---

docs/book/src/cronjob-tutorial/running.md
docs/book/src/quick-start.md

- Add prerequisites
- Small changes in order to make easier the understatement for new users. 
**Motivation**
IMHO: These small changes are very helpful to make it easier for new users and avoid mistake and/or them face issues because they were missing the prerequisites for example. Which motivate me to do this PR was my experience as a new user trying to follow up these steps.  
* https://github.com/kubernetes-sigs/kubebuilder/issues/984
* https://github.com/kubernetes-sigs/kubebuilder/issues/1034
* https://github.com/kubernetes-sigs/kubebuilder/issues/1033
* https://github.com/kubernetes-sigs/kubebuilder/issues/1031

doc(quick) : improvements in order to improve the experience of new users

---

docs/book/src/quick-start.md
pkg/scaffold/v2/webhook/webhook.go

- Improve the steps to create a new project
- add section next steps to make clear that demo project will be checked by following the tutorial. 
- add links to golang docs for new users which are not skilled in Go. 
**Motivation**
Closes: #1031 and #1033

doc(quick-start) : improvements

---

pkg/scaffold/v1/resource/resource_test.go
pkg/scaffold/v2/webhook/webhook.go

- Add a new unit test
- Fix issue where webhooks were to checking/validating the input data. 
**Motivation**
https://github.com/kubernetes-sigs/kubebuilder/issues/1069

Fix double import

---

pkg/scaffold/v2/controller.go
pkg/scaffold/v2/main.go
testdata/project-v2/controllers/admiral_controller.go
testdata/project-v2/controllers/captain_controller.go
testdata/project-v2/controllers/firstmate_controller.go
testdata/project-v2/controllers/namespace_controller.go
testdata/project-v2/main.go

Pass schema to CRD cntrolller. 
**Motivation**
https://github.com/kubernetes-sigs/kubebuilder/issues/986
**Local Test**

add schema for CRD controllers

---

docs/book/src/quick-start.md

Updated bash command in doc so that it can be easily copy and paste
from website/book

Updated docs

---

.travis.yml
Makefile
test/e2e/utils/kubectl.go
test/e2e/utils/test_context.go
test/e2e/utils/util.go
test/e2e/v1/e2e_suite.go
test/e2e/v1/e2e_test.go
test/e2e/v2/e2e_suite.go
test/e2e/v2/e2e_test.go
test_e2e_v2.sh

- Restructuring e2e tests by version to solve the timeout issue. See #1097. Also, it will be helpful to identify issues and increase the manutence ability of it. 
**Motivation**
Closes: #1097

Fix CI which is broken 

---

docs/book/src/quick-start.md

Small PR, just to fix the links.

fix quick start links

---

docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go

Deprecated use removal from the book

---

pkg/scaffold/v2/controller.go
pkg/scaffold/v2/controller_suitetest.go
pkg/scaffold/v2/group.go
pkg/scaffold/v2/main.go

:sparkles: Cleanup scaffolding 

---

cmd/version/version.go

> Unused parameter inspection
> Reports unused function parameters.
- [Blank identifier](https://golang.org/doc/effective_go.html#blank)
- [Blank Identifier for unused variables](https://golang.org/doc/effective_go.html#blank_unused)
Closes: #1179
/kind cleanup

Unused parameters replacement by blank identifier

---

docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
plugins/addon/controller.go

Add Schema Reconciler attr in the tutorial, design doc and plugins scaffold impl
**Motivation**
Checked that this places still missing the value/updated.

Add Schema Reconciler attr in the tutorial and plugins scaffold impl

---

docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
docs/book/utils/litgo/literate.go
docs/book/utils/markerdocs/doctypes.go
docs/book/utils/markerdocs/html.go
docs/book/utils/markerdocs/main.go
docs/book/utils/plugin/input.go
docs/book/utils/plugin/plugin.go
pkg/scaffold/project/project.go
pkg/scaffold/scaffold.go
pkg/scaffold/scaffoldtest/scaffoldtest.go
pkg/scaffold/v2/mgrrolebinding.go
pkg/scaffold/v2/prometheus/kustomize.go

This formats the book-related code (including utilities and example code).

Format book-related coe

---

CONTRIBUTING.md

- Improvements
- Add test info
**Motivation**
Closes:  #1194

:book: (CONTRIBUTING.md) : improvements and add tests info

---

cmd/init_project.go
cmd/util/validations.go
pkg/scaffold/project/kustomize.go
pkg/scaffold/v2/kustomize.go

- add validation for the name of the project in the init
**Motivation**
Closes: #891

Add init name check

---

OWNERS

add camilamacedo86 as reviewer

add camilamacedo86 as reviewer

---

cmd/api.go
pkg/scaffold/resource/resource.go

-  Fix the scenarios when the group, version, and or kind can be empty. 
**Motivation**
Closes: #1153 
**Solution**

add required flags validation for create api command

---

docs/book/src/cronjob-tutorial/testdata/project/main.go

Update the book to remove outdated add of builtin scheme.
Fixes #1118

Update scheme handling in the book

---

docs/book/src/quick-start.md

:book: use v2.2.0 in quick start

---

pkg/scaffold/v1/webhook/admissionwebhooks.go

Verify that AdmissionWebhooks implements File

---

docs/book/src/reference/generating-crd.md

Fix minor typo

---

docs/book/src/cronjob-tutorial/testdata/emptymain.go

Provide required info about project scope definitions using namespace as an option in the manager. 
**Motivation**
https://github.com/operator-framework/operator-sdk/issues/2008
**To verify**
https://deploy-preview-1229--kubebuilder.netlify.com/cronjob-tutorial/empty-main.html

doc: improve manager info

---

OWNERS
OWNERS_ALIASES

:running: add joelanford as reviewer

---

CONTRIBUTING.md

add note in contributing.md about where to find the netlify preview

doc: add info to check changes in the docs

---

build/cloudbuild_tools.yaml
build/thirdparty/darwin/Dockerfile
build/thirdparty/linux/Dockerfile

Motivation: https://github.com/kubernetes-sigs/kubebuilder/pull/1273#issuecomment-569425462

:sparkles: build k8s tools for 1.16.4

---

docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
docs/book/src/cronjob-tutorial/testdata/project/main.go
docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go

Motivation: https://github.com/kubernetes-sigs/kubebuilder/pull/1162#issuecomment-562365769

docs: update content since now its has the schema

---

OWNERS_ALIASES

OWNERS: add estroz to reviewers

---

docs/book/src/quick-start.md

Signed-off-by: Luyao Zhong <luyao930620@gmail.com>
Fixes #1258

fix invalid validation marker in example in quick-start.md

---

docs/book/src/quick-start.md
testdata/project-v2/Makefile

It isn't obvious that the download is 60+Mb and may take some time on slow internet. Progress bars FTW.
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    69  100    69    0     0    315      0 --:--:-- --:--:-- --:--:--   315
100   125  100   125    0     0    480      0 --:--:-- --:--:-- --:--:--   480
100   628    0   628    0     0    853      0 --:--:-- --:--:-- --:--:--  613k
100 60.6M  100 60.6M    0     0   563k      0  0:01:50  0:01:50 --:--:--  955k
```

helpfully show progress of kubebuilder download

---

scripts/verify.sh

- enable gocycle lint check
(it checks the complexity of the code - func > 20 lines )

:running: enable gocycle lint check

---

pkg/scaffold/project/project_test.go
scripts/verify.sh

Enable lint goconst check
Fix issues (clean code)

:running: enable lint goconst

---

cmd/init_project.go
pkg/scaffold/resource/resource.go
pkg/scaffold/scaffold.go
scripts/verify.sh

- enable maligned lint check
- perform code fixes

enable maligned lint check

---

scripts/verify.sh
test/e2e/utils/test_context.go

enable gosec lint check

---

docs/book/src/cronjob-tutorial/running-webhook.md

:book: update command in running webhook section

---

docs/book/src/migration/multi-group.md

Fix wrong paths in multi-group migratig doc

---

common.sh

Signed-off-by: Bharath Thiruveedula <bharath_ves@hotmail.com>
Closes #1308

Bump up the version of kind to 0.7.0

---

docs/book/src/SUMMARY.md
docs/book/src/reference/webhook-for-core-types.md

:book: admission webhook for core types

---

designs/simplified-scaffolding.md
docs/book/src/cronjob-tutorial/testdata/emptymain.go
docs/book/src/cronjob-tutorial/testdata/project/main.go
docs/book/src/multiversion-tutorial/testdata/project/main.go
pkg/scaffold/internal/templates/v2/main.go
testdata/project-v2-multigroup/main.go
testdata/project-v2/main.go

This is the port of https://github.com/kubernetes-sigs/kubebuilder/pull/1116.
Resolves https://github.com/kubernetes-sigs/kubebuilder/issues/1105.

Use zap helpers

---

OWNERS_ALIASES

add camilamacedo86 as approver

---

docs/book/src/cronjob-tutorial/testdata/finalizer_example.go

Fixes some pointer and return errors in the finalizers example.

Fix code errors in finalizer example

---

.travis.yml

upgrade golangci version used to v1.23.3

upgrade golangci version used to v1.23.3

---

pkg/model/file/interfaces.go
pkg/model/file/marker.go

As requested in https://github.com/kubernetes-sigs/kubebuilder/pull/1375#pullrequestreview-362318348
NITs:
- https://github.com/kubernetes-sigs/kubebuilder/pull/1375#discussion_r382265396
- https://github.com/kubernetes-sigs/kubebuilder/pull/1375#discussion_r382274049

NITs raised in 1375

---

cmd/api.go
pkg/model/config/config.go

As discussed in https://github.com/kubernetes-sigs/kubebuilder/pull/1355#discussion_r385074333

Delegate config checks to the config model

---

testdata/project-v2-addon/config/default/manager_auth_proxy_patch.yaml

- Update testdata to fix the build ci in master branch
**Motivation**
See: https://travis-ci.org/kubernetes-sigs/kubebuilder/builds/659287381

fix: master branch broken ci - update testdata

---

docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go

Resolves #1422. 
Please proof read this change, review it and compile it to html to verify it compiles correctly (I haven't checked this).
Feel free to make changes as you deem fit.

Added explanatory note about the index

---

docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go

Added note to cronjob book docs explaining the childjob index

---

pkg/cli/cli.go

Clones #1447 because travis is not updating status.

cli: check if project is v1 when validating default plugins

---

docs/book/src/introduction.md

Add contribution link to the book

---

pkg/scaffold/internal/templates/makefile.go
testdata/project-v2-addon/Makefile
testdata/project-v2-multigroup/Makefile
testdata/project-v2/Makefile
testdata/project-v3-addon/Makefile
testdata/project-v3-multigroup/Makefile
testdata/project-v3/Makefile

Missed in #1430
/cc @camilamacedo86 @mengqiy

makefile: use $(KUSTOMIZE) variable instead of binary name directly

---

docs/book/src/reference/webhook-for-core-types.md

This PR is going to fix these two trivial problems.
Signed-off-by: imjoey <majunjiev@gmail.com>

docs: Fix a literal typo and incorrect list

---

docs/book/theme/css/custom.css
docs/book/theme/header.hbs
docs/book/theme/index.hbs

Inclusive is better than exclusive: this is a core principal of
Kubernetes.
When people are systematically murdered, dehumanized, marginalized, threatened,
and made to feel unwelcome, it's our job to make it clear that such
things will not fly in our community, and must not be allowed to fly in
society.
Without inclusivity, there is no community, and without community, there
is no Kubernetes, there is no KubeBuilder.
---
Banner verbiage and general design taken from the main Kubernetes website
(https://github.com/kubernetes/website/pull/21505).

Black Lives Matter

---

OWNERS_ALIASES

Would like to be able to approve PRs such as this one: #1518

Add pwittrock to approvers

---

OWNERS_ALIASES

Contributions:
* [Authored issues](https://github.com/kubernetes-sigs/kubebuilder/issues/created_by/estroz)
* [Authored and merged PRs](https://github.com/kubernetes-sigs/kubebuilder/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Aestroz+is%3Aclosed)
* [Reviewed PRs](https://github.com/kubernetes-sigs/kubebuilder/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+reviewed-by%3A%40me)
/cc @DirectXMan12 @droot @mengqiy @camilamacedo86

OWNERS_ALIASES: add estroz to approvers

---

pkg/plugin/v3/scaffolds/internal/templates/makefile.go
testdata/project-v3-addon/Makefile
testdata/project-v3-multigroup/Makefile
testdata/project-v3/Makefile

More info:  https://hermanschaaf.com/running-the-go-race-detector-with-cover/

feat: improve go test for the scaffolded projects due checking race conditionals (v3 only)

---

docs/book/src/multiversion-tutorial/deployment.md
docs/book/src/reference/webhook-overview.md

i fix crd-version-pref url！thanks!

fix crd-version-pref url

---

test/e2e/v2/e2e_suite.go
test/e2e/v3/e2e_suite.go

cleanup: Remove the word sanity from our codebase

---

docs/book/src/cronjob-tutorial/running-webhook.md
docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_webhook.go

A few small typo fixes from the book.

docs/book: fix small typos

---

build/cloudbuild_tools.yaml
build/thirdparty/darwin/Dockerfile
build/thirdparty/linux/Dockerfile

When this PR merges, it should trigger the cloud build pipeline.

:running: build KB tools for k8s 1.17

---

docs/book/src/reference/makefile-helpers.md

doc: makefile helpers nit fix

---

build/cloudbuild_tools.yaml
build/thirdparty/darwin/Dockerfile
build/thirdparty/linux/Dockerfile

Signed-off-by: Vince Prignano <vincepri@vmware.com>
/assign @mengqiy @DirectXMan12

Publish Kubernetes 1.19 tools

---

docs/book/src/cronjob-tutorial/empty-main.md

fix title: lost "needs"

---

docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go

📖 : JobConditionType is "Complete" or "Failed", so I update succeeded to Complete in this file.
-> k8s.io/api@v0.17.2/batch/v1/types.go:165

📖 update succeeded to Complete

---

.golangci.yml
pkg/cli/cli_suite_test.go
pkg/model/resource/resource.go
pkg/plugin/interfaces.go
pkg/plugin/internal/util/repository.go
pkg/plugin/v2/plugin.go
pkg/plugin/v2/scaffolds/api.go
pkg/plugin/v2/scaffolds/doc.go
pkg/plugin/v2/scaffolds/internal/templates/main.go
pkg/plugin/v3/api.go
pkg/plugin/v3/plugin.go
pkg/plugin/v3/scaffolds/doc.go
pkg/plugin/v3/scaffolds/init.go
pkg/plugin/v3/scaffolds/internal/templates/dockerignorefile.go
pkg/plugin/v3/scaffolds/internal/templates/main.go
test/e2e/utils/util.go

All exported funcs should be doc so the lint will ensure that.

:seedling: add lint check to ensure that all exported funcs are properly documented

---

build/cloudbuild_tools.yaml
build/thirdparty/darwin/Dockerfile
build/thirdparty/linux/Dockerfile

/assign @alvaroaleman @DirectXMan12 @mengqiy

Build kubebuilder-tools v1.19.2

---

docs/book/src/reference/makefile-helpers.md

Added documentation discussed in #1693

:book: - Update makefile-helpers.md

---

generate_testdata.sh

Remove unnecessary resetting of GOPATH while scaffolding test project.
**Motivation**
Cleanup

:seedling: Remove resetting of GOPATH while scaffolding test project

---

README.md

- add meetings info in the README
**Motivation**
We will start to do the Bug Triage for Kubebuilder

:book: add meetings info in the README

---

pkg/cli/cli_suite_test.go
pkg/cli/cli_test.go

**Describe**
- move the specific mock data used ONLY in the cli_test from the suite to this file
- add a new test to cover CLI with Extra commands
**Motivation**
- Maintainability
- basic coverage for CLI with extra commands scenario.

:seedling: improve cli tests 

---

VERSIONING.md

Push @estroz's old suggestion in the VERSIONING.md file done in : https://github.com/kubernetes-sigs/kubebuilder/pull/1539
The@author of these changes is @estroz 
Closes: #1519

:book: versioning update after the latest plugins definitions

---

cmd/main.go
pkg/cli/cli_test.go

Added tests for the following `cli.Option`s for `cli.New`:
- `WithCommandName`
- `WithDefaultProjectVersion`

🌱 Add tests for cli's options that were not tested

---

docs/book/src/quick-start.md
testdata/project-v2-addon/go.mod

Cheerry-pick 8acdc2872d1704cd9d0ff48a1b55fdc0f7a51d1c

:book: add note about officially versions supported

---

pkg/model/config/config_test.go

Add unit tests for the config
**Motivation**
Increase the coverage (coverage/coveralls — Coverage increased (+1.2%) to 73.719%)

:seedling: add unit tests for the config

---

.gitignore
generate_testdata.sh

- .gitignore: combine bin and testbin ignore statements
- generate_testdata.sh: remove unnecessary conditions, have scaffold_test_project accept flags from arg 2 onwards

:seedling: .gitignore,generate_testdata.sh: cleanup

---

CONTRIBUTING.md
docs/book/src/cronjob-tutorial/writing-tests.md

📖 Fix typos

---

docs/book/src/cronjob-tutorial/testdata/project/main.go

The code in the master branch disables env ENABLE_WEBHOOKS, so I made this bugfix.
Signed-off-by: sayaoailun <guojianwei007@126.com>

📖: allow running cronjob tutorial w/o webhoooks

---

docs/book/src/cronjob-tutorial/gvks.md

Address the answer to common questions raised by giving a better explanation over APIs with examples.

:book: add info to tutorial about apis with examples

---

build/cloudbuild_tools.yaml
build/thirdparty/darwin/Dockerfile
build/thirdparty/linux/Dockerfile

Updates kubebuilder tools to version ~`1.20.1`~ `1.20.2`

Build kubebuilder-tools v1.20.2

---

pkg/plugins/golang/v2/scaffolds/internal/templates/api/types.go
pkg/plugins/golang/v2/scaffolds/internal/templates/controllers/controller.go
pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller.go
plugins/addon/controller.go
plugins/addon/type.go
testdata/project-v2-addon/controllers/admiral_controller.go
testdata/project-v2-addon/controllers/captain_controller.go
testdata/project-v2-addon/controllers/firstmate_controller.go
testdata/project-v3-addon/controllers/admiral_controller.go
testdata/project-v3-addon/controllers/captain_controller.go
testdata/project-v3-addon/controllers/firstmate_controller.go

Verify that the scaffolded files are already properly formatted before running `go fmt`.

🌱 Go fmt templates

---

plugins/addon/controller.go
plugins/addon/type.go
testdata/project-v2-addon/api/v1/admiral_types.go
testdata/project-v2-addon/controllers/admiral_controller.go
testdata/project-v2-addon/controllers/captain_controller.go
testdata/project-v2-addon/controllers/firstmate_controller.go
testdata/project-v3-addon/api/v1/admiral_types.go
testdata/project-v3-addon/controllers/admiral_controller.go
testdata/project-v3-addon/controllers/captain_controller.go
testdata/project-v3-addon/controllers/firstmate_controller.go

Bump addon `*_types.go` and `controller.go` templates with changes that were done to the equivalent templates of the go plugin.

🌱 Bump addon *_types.go and controller.go templates

---

pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go

ignore maligned lint issue for WebhookSuite struct

:seedling: ignore maligned lint issue for WebhookSuite struct

---

pkg/plugins/golang/v3/init.go

GitHub allows to create projects with `LICENSE` and `README.md` files aside from the already accepted `.gitignore` file but plugin `go/v3` didn't allow this files to exist at init.
Fixes: #2004

✨ Accept auto-generated files from GitHub into the allowed set of files

---

docs/book/src/quick-start.md
docs/book/src/reference/artifacts.md
netlify.toml

- netlify.toml: update redirects for v3.0.0
- docs/book/src: update https://go.kubebuilder.io links to match new redirects and download instructions

:book: update redirects for v3.0.0

---

RELEASE.md

- adding info about the release process
- updating the data accordingly with V3 and the latest discussions
**Motivation**
Make clear some points that were not for me after follow up it.

:book: adding info about the release process

---

docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go

This PR improves the testing section of the documentation.
The idea is to recommend to use a strongly consistent client ```client.New``` instead of the manager's client in the case of tests.
**Motivation**
* Closes: #2018
* It is highly inspired by this discussion https://github.com/kubernetes-sigs/controller-runtime/issues/343.

📖 Use client.New instead of manager client in tests

---

pkg/cli/cli.go
pkg/cli/init.go

Fix issues in: https://github.com/kubernetes-sigs/kubebuilder/actions/runs/665901004
Required for: #2101

🌱 Fix linting issues

---

docs/book/src/reference/generating-crd.md

📖 change scale example attribute

---

pkg/plugins/golang/v3/scaffolds/init.go

fix lint issue on master for the release
**Motivation**
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2130
It is a blocker for the rc.

:seedling: fix lint issue on master for the release

---

docs/book/src/cronjob-tutorial/testdata/finalizer_example.go

controller-runtime provider finalizer [tools,](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L340) it's better use them.

 📖 use controller-runtime modify finalizer

---

build/build.sh

Follow up from #2158 to clean up some testing code.

:sparkles: build/build.sh: fix image repo

---

README.md

@camilamacedo86 how about this to fix #2193 ?

Replace broken Travis CI badge in README with GitHub Lint & Unit Test actions

---

docs/book/src/quick-start.md

Hello 👋🏻 
A very tiny fix to fix the blog post link in the quick-start section on documentation
Have a good day 🚀

📖 fix blog post link in quick-start on documentation

---

docs/book/src/component-config-tutorial/api-changes.md
docs/book/src/component-config-tutorial/tutorial.md

fix broken links
https://github.com/kubernetes-sigs/kubebuilder/blob/b6ecf5ef413852d8ca2a7b0281c54e316dbb5b29/docs/book/src/component-config-tutorial/api-changes.md#L5-L7

📖 fix component config tutorial

---

OWNERS_ALIASES

As per
https://groups.google.com/g/kubebuilder/c/-5hOFa_adr4/m/Sp_Zb755AwAJ

:seedling: Move directxman12 to approvers-emeritus

---

build/cloudbuild_tools.yaml
build/thirdparty/darwin/Dockerfile
build/thirdparty/linux/Dockerfile

Signed-off-by: Vince Prignano <vincepri@vmware.com>

🌱 Build kubebuilder-tools for Kubernetes v1.21.2

---

docs/book/theme/css/markers.css
docs/book/utils/markerdocs/main.go

Fixes #2242
See https://github.com/kubernetes-sigs/kubebuilder/issues/2242#issuecomment-870854192
cc @camilamacedo86

📖 Make markers more easily copyable

---

pkg/plugins/common/kustomize/v1/init.go

Clean up extra spaces, although these errors are not important, they affect the code specification.

🌱 Clean up extra spaces

---

README.md

* a description of the change : Fix typos > principals -> principles
* the motivation for the change ->  The typo stands out in an otherwise great document,

:book: Update Typo in README.md

---

docs/book/src/cronjob-tutorial/gvks.md

:book: Fixed small typo

---

OWNERS_ALIASES

As discussed between current admins and approvers @pwittrock @mengqiy @droot @camilamacedo86.

:seedling:  chore(owners): add estroz to OWNERS_ALIASES admins, move mengqiy and droot to emiritus-approvers

---

build/cloudbuild_tools.yaml
build/thirdparty/darwin/Dockerfile
build/thirdparty/linux/Dockerfile

Signed-off-by: Joe Lanford <joe.lanford@gmail.com>

🌱 Build kubebuilder-tools for Kubernetes 1.22.0

---

pkg/cli/cmd_helpers.go
pkg/machinery/scaffold.go
pkg/model/resource/resource.go
pkg/plugins/common/kustomize/v1/init.go
pkg/plugins/golang/v3/init.go
test/e2e/utils/kubectl.go
test/e2e/utils/test_context.go
test/e2e/v2/plugin_cluster_test.go
test/e2e/v3/generate_test.go
test/e2e/v3/plugin_cluster_test.go

Fix lint issues that began to raise on master.
Close: https://github.com/kubernetes-sigs/kubebuilder/issues/2307
Close: https://github.com/kubernetes-sigs/kubebuilder/issues/2301
Close: https://github.com/kubernetes-sigs/kubebuilder/issues/2294

:seedling: fix lint issues on master

---

netlify.toml

Cherry-pick of #2321 
/cc @joelanford 

:book: fix(netlify): fix broken redirect resource

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

This PR fixes a typo in the `bug_report.yaml` and `feature_request.yaml` issue templates.

🌱 Fixes a typo in bug report and feature request templates :ghost:

---

docs/book/src/SUMMARY.md
docs/book/src/reference/reference.md
docs/book/src/reference/watching-resources.md
docs/book/src/reference/watching-resources/externally-managed.md
docs/book/src/reference/watching-resources/operator-managed.md
docs/book/src/reference/watching-resources/testdata/external-indexed-field/api.go
docs/book/src/reference/watching-resources/testdata/external-indexed-field/controller.go
docs/book/src/reference/watching-resources/testdata/owned-resource/api.go
docs/book/src/reference/watching-resources/testdata/owned-resource/controller.go

Currently there is no information in the Kubebuilder book on how to really use the Watches() functionality.
This PR adds a page that explains how to watch and reconcile an object based on changes to an object that it references in its CRD.
This feature is used extensively in the [Solr Operator](https://github.com/apache/lucene-solr-operator), so the ideas behind the test code have been tested.
Very open to suggestions/changes. This is my first PR for Kubebuilder, and I'm sure there are things I have missed.

📖Add page in book for how to watch objects referenced in the CRD.

---

OWNERS_ALIASES

:seedling: add camilamacedo86 as admin

---

docs/book/src/cronjob-tutorial/running-webhook.md
docs/book/src/cronjob-tutorial/running.md
docs/book/src/quick-start.md

Fixes [#2439](https://github.com/kubernetes-sigs/kubebuilder/issues/2439)
Add flag to kind command to make it clearer.
Add note for docker push/pull commands. 
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>

📖 Modify commands & add notes to cronjob-tutorial 

---

docs/book/src/cronjob-tutorial/testdata/project/controllers/suite_test.go

Update suite_test.go client creation instructions for reading consistency.
Fix extra spaces.

:book: Update suite_test.go client creation details

---

build/cloudbuild_kube-rbac-proxy.yaml

**description**
🌱 bump kube-rbac-proxy version version v0.10.0
**motivation**
Generate images for v0.10.0 release

🌱 bump kube-rbac-proxy version version v0.10.0

---

pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
pkg/plugins/golang/v2/scaffolds/internal/templates/config/kdefault/manager_auth_proxy_patch.go
testdata/project-v2-addon/config/default/manager_auth_proxy_patch.yaml
testdata/project-v2-multigroup/config/default/manager_auth_proxy_patch.yaml
testdata/project-v2/config/default/manager_auth_proxy_patch.yaml
testdata/project-v3-addon/config/default/manager_auth_proxy_patch.yaml
testdata/project-v3-config/config/default/manager_auth_proxy_patch.yaml
testdata/project-v3-multigroup/config/default/manager_auth_proxy_patch.yaml
testdata/project-v3-v1beta1/config/default/manager_auth_proxy_patch.yaml
testdata/project-v3/config/default/manager_auth_proxy_patch.yaml

Upgrade kube-rbac-proxy from v0.8.0 to v0.11.0
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2519

:sparkles: (kustomize/v1) : Upgrade kube-rbac-proxy from v0.8.0 to v0.11.0

---

docs/book/src/quick-start.md

Update and fix the 404 link
Signed-off-by: Le Yao <le.yao@intel.com>

📖 Update the link of kustomize

---

docs/book/src/plugins/plugins.md

Uodated the plugins page on Kubebuilder book to add latest plugin design phase 2 docs.

:book: added link to plugin design phase 2 docs

---

docs/book/src/plugins/available-plugins.md
docs/book/src/plugins/declarative-v1.md
docs/book/src/plugins/go-v2-plugin.md
docs/book/src/plugins/go-v3-plugin.md
docs/book/src/plugins/kustomize-v1.md

The work to provide the docs was split.
This PR just try to shape/improve what was added

:book: improve plugin available doc (nits)

---

.github/workflows/lint.yml
Makefile

upgrade golanglint to fix issues
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2616

:seedling: upgrade golanglint to fix issues

---

VERSIONING.md

:book: fix minor misspelling issue

---

build/cloudbuild_tools.yaml

Bump KUBERNETES_VERSION from 1.23.3 to 1.23.5
**Motivation**
Generate the artefacts with the version bumped on Kubebuilder

Bump KUBERNETES_VERSION from 1.23.3 to 1.23.5

---

docs/book/src/SUMMARY.md

fix kustomize plugin doc by adding link

:book: fix kustomize plugin doc by adding link 

---

pkg/plugins/golang/v3/scaffolds/internal/templates/api/webhook_suitetest.go

**description**
Fix dead code which was not checked before the PR be merged : https://github.com/kubernetes-sigs/kubebuilder/pull/2619/files
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2658

:seedling: fix deadcode

---

build/cloudbuild_snapshot.yaml

Fix the following issue (faced in the snapshot released done from master):

🌱  fix snapshot releases built from master

---

OWNERS_ALIASES

move estroz and adirio for emeritus (no longer directly involved)

:seedling: move estroz and adirio for emeritus (no longer directly involved)

---

test/common.sh

Add k8s 1.24 and envtest 1.24.1 to the tests.
Support for k8s 1.24

:seedling: add envtest 1.24.1 for k8s 1.24 tests

---

test/testdata/test.sh

adding v3 with kustomize v2-alpha option to the be covered with the tests
**Motivation**
Increase the test coverage with the new options

:seedling: adding v3 with kustomize v2-alpha option to the be covered with the tests

---

docs/book/src/cronjob-tutorial/gvks.md

Signed-off-by: Dharmit Shah <shahdharmit@gmail.com>
* a description of the change - A couple of minor fixes to the book
* the motivation for the change - To be accurate
* what issue it fixes, if any, in GitHub syntax (e.g. Fixes #XYZ) - N/A

📖 Address typos in cronjob tutorial

---

docs/book/src/plugins/kustomize-v2-alpha.md

##Description
:book: update info about new kustomize plugin alpha
##Motivation
Provide info about how to convert vars to replacements

:book: update info about new kustomize plugin alpha

---

OWNERS_ALIASES

* a description of the change
Adding `rashmigottipati` to the reviewer's list
* the motivation for the change
Get myself permission to be a KB reviewer
Membership request was approved last year: https://github.com/kubernetes/org/issues/2951

🌱 Add rashmigottipati as a reviewer in the repo

---

pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/controller_manager_config.go
pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/manager/controller_manager_config.go
testdata/project-v3-addon/config/manager/controller_manager_config.yaml
testdata/project-v3-config/config/manager/controller_manager_config.yaml
testdata/project-v3-multigroup/config/manager/controller_manager_config.yaml
testdata/project-v3-with-kustomize-v2/config/manager/controller_manager_config.yaml
testdata/project-v3/config/manager/controller_manager_config.yaml

kustomize/v1 - fix spaces for comments 
v2-alpha - ensure additions ( we did not added the same feature to the kustomize-v2-alpha and this PR fixes it
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/2716

:bug: (kustomize/v1 and v2-alpha): fix spaces for comments and ensure additions

---

RELEASE.md

update the release doc with missing steps and workarounds
ensure that we have all info indeed the possible workarounds doc for those need to do the releases

📖  update the release doc with missing steps and workarounds

---

docs/book/src/component-config-tutorial/testdata/project/Makefile
docs/book/src/cronjob-tutorial/testdata/project/Makefile
docs/book/src/migration/manually_migration_guide_v2_v3.md
docs/book/src/multiversion-tutorial/testdata/project/Makefile
pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go
pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
testdata/project-v2/Makefile
testdata/project-v3-addon/Makefile
testdata/project-v3-config/Makefile
testdata/project-v3-multigroup/Makefile
testdata/project-v3-with-kustomize-v2/Makefile
testdata/project-v3/Makefile

fix kustomize make file target which fails when called twice
**Motivation**
See: https://github.com/operator-framework/operator-sdk/issues/5875

:bug: fix kustomize make file target which fails when called twice

---

docs/book/src/plugins/deploy-image-plugin-v1-alpha.md

Documentation for deploy-image plugin

📖 Documentation for deploy-image plugin

---

README.md

📖 Add to the README darwin/arm64

📖 Add to the README darwin/arm64

---

build/cloudbuild_tools.yaml

Generate Kubebuilder-Tools for k8s 1.24.2

:sparkles: Generate Kubebuilder-Tools for k8s 1.24.2

---

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller_suitetest.go
test/e2e/deployimage/plugin_cluster_test.go
testdata/project-v3-addon/controllers/suite_test.go
testdata/project-v3-config/controllers/suite_test.go
testdata/project-v3-multigroup/controllers/apps/suite_test.go
testdata/project-v3-multigroup/controllers/crew/suite_test.go
testdata/project-v3-multigroup/controllers/fiz/suite_test.go
testdata/project-v3-multigroup/controllers/foo.policy/suite_test.go
testdata/project-v3-multigroup/controllers/foo/suite_test.go
testdata/project-v3-multigroup/controllers/sea-creatures/suite_test.go
testdata/project-v3-multigroup/controllers/ship/suite_test.go
testdata/project-v3-multigroup/controllers/suite_test.go
testdata/project-v3-with-deploy-image/controllers/busybox_controller.go
testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go
testdata/project-v3-with-deploy-image/controllers/memcached_controller.go
testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go
testdata/project-v3-with-deploy-image/controllers/suite_test.go
testdata/project-v3-with-kustomize-v2/controllers/suite_test.go
testdata/project-v3/controllers/suite_test.go

Add integration tests for the controller scaffolded by the `deploy-image/v1-alpha` plugin.

✨deploy-image/v1-alpha: add tests for controller using ENV TEST

---

OWNERS_ALIASES

add @everettraven (me!) as a reviewer in the `OWNERS_ALIASES` file
@camilamacedo86 has mentioned to me that I am ready to be added as a reviewer. This would also allow me to help with properly reviewing and approving PRs :smiley:

:seedling: add everettraven as a reviewer

---

pkg/plugins/golang/deploy-image/v1alpha1/api.go
pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
test/testdata/generate.sh
testdata/project-v3-with-deploy-image/PROJECT
testdata/project-v3-with-deploy-image/api/v1alpha1/busybox_types.go
testdata/project-v3-with-deploy-image/api/v1alpha1/memcached_types.go
testdata/project-v3-with-deploy-image/config/crd/bases/example.com.testproject.org_busyboxes.yaml
testdata/project-v3-with-deploy-image/config/crd/bases/example.com.testproject.org_memcacheds.yaml
testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go
testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go
testdata/project-v4-with-deploy-image/PROJECT
testdata/project-v4-with-deploy-image/api/v1alpha1/busybox_types.go
testdata/project-v4-with-deploy-image/api/v1alpha1/memcached_types.go
testdata/project-v4-with-deploy-image/config/crd/bases/example.com.testproject.org_busyboxes.yaml
testdata/project-v4-with-deploy-image/config/crd/bases/example.com.testproject.org_memcacheds.yaml
testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go
testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go

:bug: (deploy-image/v1-alpha) : remove the namespaced option
This option cannot be supported by the plugin

:bug: (deploy-image/v1-alpha) : remove the namespaced option

---

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go
pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
testdata/project-v3-with-deploy-image/controllers/busybox_controller.go
testdata/project-v3-with-deploy-image/controllers/memcached_controller.go
testdata/project-v4-with-deploy-image/controllers/busybox_controller.go
testdata/project-v4-with-deploy-image/controllers/memcached_controller.go

:sparkles: (deploy-image/v1-alpha) : improve variable name used
Make clear for users that is the CR

:sparkles: (deploy-image/v1-alpha) : improve variable name used

---

test/e2e/kind-config.yaml

We do not need to create 3 nodes to do the tests so that this PR changes the config for the default one
**Motivation**
We are not doing any tests which require many nodes
So the idea is to keep it lightly as possible

🌱 change the Kind for just one node (default config)

---

build/cloudbuild.yaml

Pass the secret.GITHUB_TOKEN to gcloud to do the releases 
See if we can fix the issue and no longer need the secret

:seedling: try to fix release issue

---

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go

small code implementation imprevements for better maintainability

🌱 : (deploy-image/v1-alpha):  improve code implementation for better maintainability

---

docs/book/src/cronjob-tutorial/testdata/project/controllers/cronjob_controller.go
docs/book/src/multiversion-tutorial/testdata/project/controllers/cronjob_controller.go

Small nit fix in the kubebuilder book.
https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html

📖 : fix typo in tutorial ( replace date with data )

---

README.md

Update the README 
- clarifies project usage and supportability
- Improve readme by adding the links

:book: Update the README

---

README.md

:book: update the README to address the suggestions made in the PR 2823
(c/c @jmrodri )

:book: update the README to address the suggestions made in the PR 2823

---

docs/book/src/plugins/deploy-image-plugin-v1-alpha.md

update the doc to reflect latest changes and add some small improvements

:book: (deployimage/v1-alpha) update the doc to reflect latest changes and add some small improvements

---

README.md

Remove info from readme that is not valid to the latest release

:seedling: fix readme

---

docs/book/src/multiversion-tutorial/deployment.md

:book: Fix typo in Multi-Version API tutorial

---

pkg/plugins/optional/grafana/v1alpha/scaffolds/internal/templates/runtime.go
testdata/project-v3-addon-and-grafana/grafana/controller-runtime-metrics.json
testdata/project-v4-addon-and-grafana/grafana/controller-runtime-metrics.json

Correct syntax of Grafana dashboards titles and descriptions.
Apply nits in https://github.com/kubernetes-sigs/kubebuilder/pull/2834 .
Fix https://github.com/kubernetes-sigs/kubebuilder/issues/2846 .

:seedling: grafana/v1-alpha: correct title and description syntax

---

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
testdata/project-v3-with-deploy-image/controllers/busybox_controller_test.go
testdata/project-v3-with-deploy-image/controllers/memcached_controller_test.go
testdata/project-v4-with-deploy-image/controllers/busybox_controller_test.go
testdata/project-v4-with-deploy-image/controllers/memcached_controller_test.go

This PR adds a check in the controller tests (scaffolded by the `deploy-image/v1-alpha` plugin) for the status conditions added to the custom resource.

✨deploy-image/v1-alpha: add check for status conditions added to the custom resource

---

OWNERS_ALIASES

I would like to be added as a reviewer to this project.
Contributions / Involvements: 
PRs involved: https://github.com/kubernetes-sigs/kubebuilder/pulls?q=is%3Apr+varshaprasad96+is%3Aclosed
Issues involved: https://github.com/kubernetes-sigs/kubebuilder/issues?q=is%3Aissue+varshaprasad96+is%3Aclosed

✨  Add varshaprasad96 to reviewers

---

docs/book/src/component-config-tutorial/testdata/project/Makefile
docs/book/src/cronjob-tutorial/testdata/project/Makefile
docs/book/src/migration/manually_migration_guide_v2_v3.md
docs/book/src/multiversion-tutorial/testdata/project/Makefile
pkg/cli/alpha/config-gen/cmd.go
pkg/cli/alpha/config-gen/examples/kustomize/README.md
pkg/plugins/golang/v2/scaffolds/internal/templates/makefile.go
pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
testdata/project-v2/Makefile
testdata/project-v3-addon-and-grafana/Makefile
testdata/project-v3-config/Makefile
testdata/project-v3-multigroup/Makefile
testdata/project-v3-with-deploy-image/Makefile
testdata/project-v3/Makefile
testdata/project-v4-addon-and-grafana/Makefile
testdata/project-v4-config/Makefile
testdata/project-v4-multigroup/Makefile
testdata/project-v4-with-deploy-image/Makefile
testdata/project-v4/Makefile

(makefile): make kustomize does not show curl error output #2873

 🐛 (makefile): make kustomize does not show curl error output

---

OWNERS_ALIASES

Add jmrodri & varsha to approvers list.
PS>: Both completed the criteria are active maintainers

:seedling: Add jmrodri & varsha to approvers

---

README.md
docs/book/src/plugins/deploy-image-plugin-v1-alpha.md
docs/book/src/plugins/grafana-v1-alpha.md
docs/book/src/quick-start.md

- Add info in the README and Quick start to let users know about the plugin so that will help them skill and speed up
- Supplement reference links on the plugins page.

:book: supplement info about the new plugins

---

OWNERS_ALIASES

:sparkles: Add @jmrodri and @varshaprasad96 to KB admins list.

:sparkles: Add members to kb-admins

---

OWNERS_ALIASES

Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>

:sparkles: Add members to OWNERS

---

docs/book/src/SUMMARY.md

fix the link for platform support
It is broken

:book: fix link for platform support

---

docs/book/src/migration/manually_migration_guide_v2_v3.md
docs/book/src/plugins/declarative-v1.md
docs/book/src/plugins/kustomize-v2-alpha.md
docs/book/src/reference/platform.md

I scanned the links in Kubebuilder and found a few broken links/incorrectly formatted links. This pr fixes them. There seem to be a few more but I will investigate what they should be before making a pr for them.

:book: fix broken links

---

pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go

remove unused value in the bollerplate
Clean up

🌱 (deploy-image): remove unused value in the bollerplate

---

test/e2e/utils/test_context.go
test/e2e/v3/plugin_cluster_test.go
test/e2e/v4/plugin_cluster_test.go

🌱 (cleanup/e2e tests): cert-manager and prometheus installs into e2e tests
Maintainability

🌱 (cleanup/e2e tests): cert-manager and prometheus installs into e2e tests

---

OWNERS_ALIASES

Adding jmrodri and varsha to admins
Signed-off-by: jesus m. rodriguez <jesusr@redhat.com>

🌱 Make jmrodri and varsha admins

---

docs/book/src/SUMMARY.md
docs/book/src/component-config-tutorial/api-changes.md
docs/book/src/cronjob-tutorial/basic-project.md
docs/book/src/cronjob-tutorial/cert-manager.md
docs/book/src/cronjob-tutorial/cronjob-tutorial.md
docs/book/src/cronjob-tutorial/running-webhook.md
docs/book/src/cronjob-tutorial/testdata/emptymain.go
docs/book/src/multiversion-tutorial/tutorial.md
docs/book/src/plugins/available-plugins.md
docs/book/src/plugins/creating-plugins.md
docs/book/src/plugins/extending-cli.md
docs/book/src/plugins/go-v2-plugin.md
docs/book/src/plugins/to-add-optional-features.md
docs/book/src/plugins/to-be-extended.md
docs/book/src/plugins/to-scaffold-project.md
docs/book/src/reference/completion.md
docs/book/src/reference/controller-gen.md
docs/book/src/reference/kind.md
docs/book/src/reference/markers.md
docs/book/src/reference/metrics.md
docs/book/src/reference/watching-resources/testdata/owned-resource/controller.go

This fixes various rendering issues:
* Wrong or uninterpreted formatting
* Some missing links
* Incorrect markup
* Missing documentation pages
This doesn't fix all the links but at least the initial ones.
Example of fixes (current rendering containing issues):
https://book.kubebuilder.io/cronjob-tutorial/basic-project.html
https://book.kubebuilder.io/component-config-tutorial/api-changes.html
https://book.kubebuilder.io/cronjob-tutorial/cert-manager.html

📖 Improve rendering of the documentation

---

docs/book/src/component-config-tutorial/testdata/project/Makefile
docs/book/src/cronjob-tutorial/testdata/project/Makefile
docs/book/src/multiversion-tutorial/testdata/project/Makefile
pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
testdata/project-v3-addon-and-grafana/Makefile
testdata/project-v3-config/Makefile
testdata/project-v3-multigroup/Makefile
testdata/project-v3-with-deploy-image/Makefile
testdata/project-v3/Makefile
testdata/project-v4-addon-and-grafana/Makefile
testdata/project-v4-config/Makefile
testdata/project-v4-multigroup/Makefile
testdata/project-v4-with-deploy-image/Makefile
testdata/project-v4/Makefile

__Description__
Fixed a minor typo in the Makefile template.
__Motivation__
This is a minor issue, but many users will see the Makefile.
Sorry to bother you to check!

🐛 fix a minor typo in Makefile

---

pkg/plugins/common/kustomize/v2-alpha/scaffolds/api.go
pkg/plugins/common/kustomize/v2-alpha/scaffolds/internal/templates/config/samples/kustomization.go

Fix lint issue master branch
Bot dep bump causes the issue

🌱 fix lint issue

---

docs/book/src/cronjob-tutorial/testdata/emptycontroller.go

Add details rbac doc in tutorial.
Fixes #3105

:book: add details rbac doc in tutorial

---

docs/book/src/reference/envtest.md

📖 Update envtest.md

---

build/thirdparty/windows/Dockerfile

update alpine image from 3.16 to 3.17 for windows
Sort out tech debts and re-trigger the jobs

🌱 : update alpine image from 3.16 to 3.17 for windows

---

designs/template.md

Update the template with more specific and required information and examples based on the template used by Operator Framework and Openshift but with only which would be more relevant to this project so that we can provide a better guidance to community

:book: update the template for proposals

---

designs/code-generate-image-plugin.md
designs/crd_version_conversion.md
designs/extensible-cli-and-scaffolding-plugins-phase-1-5.md
designs/extensible-cli-and-scaffolding-plugins-phase-1.md
designs/extensible-cli-and-scaffolding-plugins-phase-2.md
designs/integrating-kubebuilder-and-osdk.md
designs/simplified-scaffolding.md

Update the status of the proposals in the repo so that the community can know what is or has not been implemented so far.

:book: update the status of the proposals in the repo

---

README.md

Just added the latest release as a badge in the *README.md* (documentation best practices).

📖 Add latest release badge to readme 

---

OWNERS_ALIASES

I would like to request for becoming reviewer to get more engaged in the community.

👻 : add tony as reviewer

---

docs/book/src/component-config-tutorial/api-changes.md

:book: Fix typo in api-changes.md

---

pkg/config/store/yaml/store_test.go

Just fix a small nit lint issue
fix red badge master

🌱 fix nit lint issue

---

docs/book/src/quick-start.md
docs/book/src/reference/completion.md

Add _fish_ and _powershell_ of autocompletion command

📖 doc: add fish and powershell of autocompletion command

---

pkg/plugin/util/exec_test.go

added tests for exec.go
Fixes #3211

🌱 added test for exec.go

---

build/cloudbuild_tools.yaml

Build kubebuilder-tools for k8s 1.27.1

:sparkles: Build kubebuilder-tools for k8s 1.27.1

---

docs/book/src/component-config-tutorial/testdata/project/.dockerignore
docs/book/src/component-config-tutorial/testdata/project/.gitignore
pkg/plugins/golang/v4/scaffolds/internal/templates/dockerignore.go
pkg/plugins/golang/v4/scaffolds/internal/templates/gitignore.go
testdata/project-v4-config/.dockerignore
testdata/project-v4-config/.gitignore
testdata/project-v4-declarative-v1/.dockerignore
testdata/project-v4-declarative-v1/.gitignore
testdata/project-v4-multigroup/.dockerignore
testdata/project-v4-multigroup/.gitignore
testdata/project-v4-with-deploy-image/.dockerignore
testdata/project-v4-with-deploy-image/.gitignore
testdata/project-v4-with-grafana/.dockerignore
testdata/project-v4-with-grafana/.gitignore
testdata/project-v4/.dockerignore
testdata/project-v4/.gitignore

Remove  remove bintest dir from gitignore and dockerfile since this directory is not scaffolded

:bug: (go/v4) fix scaffold remove bintest dir from gitignore and dockerfile since this directory is not scaffolded

---

docs/book/src/component-config-tutorial/testdata/project/Makefile
pkg/plugins/common/kustomize/v2/plugin.go
testdata/project-v4-config/Makefile
testdata/project-v4-declarative-v1/Makefile
testdata/project-v4-multigroup/Makefile
testdata/project-v4-with-deploy-image/Makefile
testdata/project-v4-with-grafana/Makefile
testdata/project-v4/Makefile

(kustomize/v2,go/v4): Upgrade kustomize version from 5.0.0 to 5.0.1

:sparkles: (kustomize/v2,go/v4): Upgrade kustomize version from 5.0.0 to 5.0.1

---

docs/book/src/cronjob-tutorial/testdata/project/.dockerignore
docs/book/src/cronjob-tutorial/testdata/project/.gitignore
docs/book/src/cronjob-tutorial/testdata/project/Dockerfile
docs/book/src/cronjob-tutorial/testdata/project/Makefile
docs/book/src/cronjob-tutorial/testdata/project/config/crd/bases/batch.tutorial.kubebuilder.io_cronjobs.yaml
docs/book/src/cronjob-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
docs/book/src/cronjob-tutorial/testdata/project/config/rbac/role.yaml
docs/book/src/cronjob-tutorial/testdata/project/config/webhook/manifests.yaml
docs/book/src/cronjob-tutorial/testdata/project/go.mod
docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go

After we get merged https://github.com/kubernetes-sigs/kubebuilder/pull/3231 we need to re-run make generate to ensure that we have the samples update within the latest changes merged on master.

:book: update doc samples within the latest changes

---

.github/dependabot.yml
docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/go.mod

1. Update go version for the external plugin sample.
2. Automate the update with dependabot
Keep the sample dependencies always align with the latest version.

🌱 Update go version for external plugin sample

---

README.md

📖 : Update README.md - Community Meetings

---

build/thirdparty/darwin/Dockerfile
build/thirdparty/linux/Dockerfile
build/thirdparty/windows/Dockerfile

🌱 Bump etcd to v3.5.9

---

hack/docs/generate.sh

🌱 make generate error:  target directory is not empty

---

.github/workflows/lint.yml
Makefile
cmd/main.go

Update golangci-lint version
Fix lint issue

:seedling: fix lint ci issue and update golangci-lint version

---

docs/book/src/component-config-tutorial/testdata/project/Makefile
docs/book/src/cronjob-tutorial/testdata/project/Makefile
pkg/plugins/common/kustomize/v2/plugin.go
testdata/project-v4-multigroup/Makefile
testdata/project-v4-with-deploy-image/Makefile
testdata/project-v4-with-grafana/Makefile
testdata/project-v4/Makefile

upgrade kustomize version from 5.0.1 to 5.1.1

:sparkles: (kustomize/v2, go/v4) upgrade kustomize version from 5.0.1 to 5.1.1

---

.golangci.yml

remove gosec lint due false claims

🌱 : remove gosec lint due false claims

---

RELEASE.md

📖 add tip for release notes

---

docs/book/src/reference/good-practices.md

📖 fix link best practices

---

cmd/main.go
hack/docs/generate_samples.go

🐛  fix: disable log timestamp

---

docs/book/src/component-config-tutorial/testdata/project/go.mod
docs/book/src/component-config-tutorial/testdata/project/go.sum
docs/book/src/cronjob-tutorial/testdata/project/go.mod
docs/book/src/cronjob-tutorial/testdata/project/go.sum
docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
pkg/plugins/golang/v4/scaffolds/init.go
testdata/project-v4-multigroup/go.mod
testdata/project-v4-multigroup/internal/controller/apps/deployment_controller.go
testdata/project-v4-multigroup/internal/controller/crew/captain_controller.go
testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
testdata/project-v4-multigroup/internal/controller/fiz/bar_controller.go
testdata/project-v4-multigroup/internal/controller/foo.policy/healthcheckpolicy_controller.go
testdata/project-v4-multigroup/internal/controller/foo/bar_controller.go
testdata/project-v4-multigroup/internal/controller/lakers_controller.go
testdata/project-v4-multigroup/internal/controller/sea-creatures/kraken_controller.go
testdata/project-v4-multigroup/internal/controller/sea-creatures/leviathan_controller.go
testdata/project-v4-multigroup/internal/controller/ship/cruiser_controller.go
testdata/project-v4-multigroup/internal/controller/ship/destroyer_controller.go
testdata/project-v4-multigroup/internal/controller/ship/frigate_controller.go
testdata/project-v4-with-deploy-image/go.mod
testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go
testdata/project-v4-with-deploy-image/internal/controller/memcached_controller.go
testdata/project-v4-with-grafana/go.mod
testdata/project-v4/go.mod
testdata/project-v4/internal/controller/admiral_controller.go
testdata/project-v4/internal/controller/captain_controller.go
testdata/project-v4/internal/controller/firstmate_controller.go
testdata/project-v4/internal/controller/laker_controller.go

Fixes #3621
Bump controller-runtime 0.16.2 #3621

✨ update controller-runtime to 0.16.2

---

docs/book/src/getting-started.md

Fixes #3678 
Getting Started fix code examples indentation

:book: Getting Started fix code examples indentation

---

OWNERS_ALIASES

Just update the onwer alias with the same content from master branch

📖 doc:update the owner alias

---

build/cloudbuild_tools.yaml

Bump k8s 1.29.1 to generate tools for 1.29.1

Bump k8s 1.29.1

---

test/e2e/ci.sh

Increase the verbose for e2e tests.

🌱 : increase verbose for e2e tests

---

docs/book/src/multiversion-tutorial/deployment.md

📖 Typo multi-version tutorial deployment.md

---

docs/book/src/component-config-tutorial/testdata/project/test/e2e/e2e_test.go
docs/book/src/cronjob-tutorial/testdata/project/test/e2e/e2e_test.go
docs/book/src/getting-started/testdata/project/test/e2e/e2e_test.go
pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go
testdata/project-v4-multigroup-with-deploy-image/test/e2e/e2e_test.go
testdata/project-v4-multigroup/test/e2e/e2e_test.go
testdata/project-v4-with-deploy-image/test/e2e/e2e_test.go
testdata/project-v4-with-grafana/test/e2e/e2e_test.go
testdata/project-v4/test/e2e/e2e_test.go

Fix scaffolding e2e template missing err check. #3785

fix: 🐛 scaffolding e2e template err check

---

docs/book/src/cronjob-tutorial/testdata/emptycontroller.go
docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
pkg/plugins/golang/v4/scaffolds/internal/templates/main.go
testdata/project-v3/main.go
testdata/project-v4-multigroup-with-deploy-image/cmd/main.go
testdata/project-v4-multigroup/cmd/main.go
testdata/project-v4-with-deploy-image/cmd/main.go
testdata/project-v4-with-grafana/cmd/main.go
testdata/project-v4/cmd/main.go

:book: Fix typo issue in the docs

---

docs/book/src/migration/v3vsv4.md
docs/book/src/reference/submodule-layouts.md

add the missing `basic-project-doc` page link

📖 Add missing basic-project-doc link

---

build/cloudbuild_tools.yaml
build/thirdparty/darwin/Dockerfile
build/thirdparty/linux/Dockerfile
build/thirdparty/windows/Dockerfile

✨  Upgrade ETCD and Bump K8S to v1.29.3

---

Makefile

Small fix for do not finish with error

🌱 Fix makefile target make generate

---

.github/workflows/test-sample-go.yml
test/common.sh

Update common kind and envtest for e2e tests

🌱 Update common kind and envtest for e2e tests

---

docs/book/src/reference/raising-events.md

📖 fix typo in raising-events.md

---

docs/book/src/faq.md

:book: Add note to link Controller-Runtime FAQ page
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/3873

:book: Add note to link Controller-Runtime FAQ page

---

docs/book/src/multiversion-tutorial/testdata/project/.gitignore
docs/book/src/multiversion-tutorial/testdata/project/Makefile
docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_types.go
docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook.go
docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_webhook_test.go
docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
docs/book/src/multiversion-tutorial/testdata/project/config/certmanager/certificate.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/crd/kustomization.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/default/manager_auth_proxy_patch.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/default/webhookcainjection_patch.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/manager/manager.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_client_clusterrole.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_role.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_role_binding.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/auth_proxy_service.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/cronjob_editor_role.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/cronjob_viewer_role.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/kustomization.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/leader_election_role.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/leader_election_role_binding.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/rbac/role_binding.yaml
docs/book/src/multiversion-tutorial/testdata/project/go.mod
docs/book/src/multiversion-tutorial/testdata/project/go.sum
docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller_test.go
docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go

:book: Update Multi-Version Tutorial

---

docs/book/src/faq.md

:book: Fix link for controller-runtime FAQ

:book: Fix link for controller-runtime FAQ

---

docs/book/src/faq.md

Fix link for controller-runtime FAQ

📖 Fix link for controller-runtime FAQ

---

docs/book/src/plugins/extending-cli.md

extending-cli: remove ref of deprecated plugins

📖 extending-cli: remove ref of deprecated plugins

---

CONTRIBUTING.md

Update CONTRIBUTING.md - Clarify book-v3 docs publish status and blocker faced

📖 Update CONTRIBUTING.md - Clarify book-v3 docs publish status and blocker faced

---

docs/book/theme/header.hbs

:book: book-v2 : Ensure standard for legacy doc headers

:book: book-v2 : Ensure standard for legacy doc headers

---

CONTRIBUTING.md
docs/book/src/introduction.md
docs/book/theme/index.hbs

We are doing small changes to add v3 docs as legacy and prepare master branch for the next 4x release

📖 Prepare docs for 4x release

---

docs/book/theme/index.hbs

:book: Update index.hbs - Just to keep a standard for the version dropdown menu

:book: Update index.hbs - Just to keep a standard for the version dropdown menu

---

.github/workflows/test-sample-go.yml

cleanup:  run-test-e2e-for-project-v4-sample workflow by remove unnecessary steps

🌱 cleanup:  run-test-e2e-for-project-v4-sample workflow by remove unnecessary steps

---

docs/README.md
docs/book/theme/index.hbs

Fix 2 links in project documentation.

📖 : fix: documentation links

---

docs/book/src/introduction.md

:book: fix: book v3 link

---

docs/book/src/reference/using_an_external_type.md

📖 Update using_an_external_type.md

---

roadmap/roadmap_2024.md

📖 Update roadmap_2024.md - with the latest changes and by order the tasks adding what was done at the bottom of the page so that we bring a better visibility for what we still needing to accomplish.

📖 Update roadmap_2024.md - with the latest changes and by order the tasks adding what was done at the bottom of the page

---

.github/workflows/release.yml

Update release.yml - Update goreleaser from 1.11.2 to v2.1.0 to solve techdebts

🌱 Update release.yml - Update goreleaser from 1.11.2 to v2.1.0

---

docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
docs/book/src/getting-started/testdata/project/test/utils/utils.go
docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
docs/book/src/reference/envtest.md
pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
testdata/project-v4-multigroup-with-deploy-image/test/utils/utils.go
testdata/project-v4-multigroup/test/utils/utils.go
testdata/project-v4-with-deploy-image/test/utils/utils.go
testdata/project-v4-with-grafana/test/utils/utils.go
testdata/project-v4/test/utils/utils.go

🐛 Fix golang documentation of the method LoadImageToKindClusterWithName  scaffold in the e2e tests

---

docs/book/utils/markerdocs/html.go
docs/book/utils/markerdocs/main.go

📖 fix(markerdocs): reverting changes that broker markerdocs app build

---

docs/book/install-and-build.sh

Upgrade controller-gen used to generate the docs from 0.15.0 to 0.16.1

📖 : Upgrade controller-gen used to generate the docs from 0.15.0 to 0.16.1

---

README.md
docs/book/src/quick-start.md

Refine information about compatibility and supportability of dependencies

:book: Update docs support

---

docs/book/src/SUMMARY.md
docs/book/src/cronjob-tutorial/running-webhook.md
docs/book/src/quick-start.md
docs/book/src/reference/kind.md

Just to refine and improve the info.
Let people be aware of the kind option in the quick start

:book: provide better info about usage of kind

---

hack/ci/pr_title_checker.sh

Follow up of: https://github.com/kubernetes-sigs/kubebuilder/pull/4095

🌱 ci: Normalize text-based emoji codes to actual emojis in PR title checker

---

.github/workflows/apidiff.yml
.github/workflows/lint.yml
.github/workflows/spaces.yml
.github/workflows/test-devcontainer.yaml
.github/workflows/testdata.yml
.github/workflows/unit-tests.yml

Small nit to avoid we spend time and costs running unnecessary tests

🌱 ci: no longer call github actions for changes which are only made in the docs files (*/*.md)

---

pkg/machinery/marker_test.go

To ensure that current code implementation is well tested and changes will not break it

🌱 add better coverage to pkg/machinery/marker

---

docs/book/src/SUMMARY.md
docs/book/src/reference/markers/scaffold.md
docs/book/src/reference/reference.md

See the Preview: https://deploy-preview-4173--kubebuilder.netlify.app/reference/markers/scaffold
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1487

📖 : add documentation about kubebuilder:scaffold  marker

---

docs/book/src/reference/markers/crd-validation.md

Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/1513

📖 add note to clarify markers in the doc

---

.gitignore

🌱 add to be ignored .DS_Store

---

test/e2e/v4/plugin_cluster_test.go

Enhance e2e test coverage by including scenarios that verify webhook functionality when the installation is performed via the installer.

🌱 e2e tests: increase coverage by validating webhooks with installer-based installation

---

roadmap/roadmap_2024.md

Add latest status of helm plugin since it's initial version is implemented

📖 doc: update roadmap for 2024

---

designs/code-generate-image-plugin.md

Small PR - fixes the `generate.sh` by removing the extra "a" in "testadata".

📖: update testdata reference

---

docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller.go
hack/docs/internal/getting-started/generate_getting_started.go

details of commit here: #4323 
messed up branch squashing and rebasing and figured a new PR would be faster.

📖 Docs: removed typeDegradedMemcached and comment

---

README.md

📖 Readme: Make more clear notice

📖 Readme: Make more clear notice abour kube-rbac-proxy

---

README.md

:book: nit - remove spaces

---

designs/discontinue_usage_of_kube_rbac_proxy.md

📖 Update discontinue_usage_of_kube_rbac_proxy.md - Typos/grammar fixes and use the right link for the new location of the images

---

docs/book/src/getting-started.md

📖 Update getting-started.md

---

test/e2e/deployimage/plugin_cluster_test.go

Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4450

🌱 e2e - ensure that error from command is checked

---

.github/workflows/lint-sample.yml
docs/book/src/cronjob-tutorial/testdata/project/Makefile
docs/book/src/getting-started/testdata/project/Makefile
docs/book/src/multiversion-tutorial/testdata/project/Makefile
pkg/plugins/golang/v4/scaffolds/internal/templates/makefile.go
testdata/project-v4-multigroup/Makefile
testdata/project-v4-with-plugins/Makefile
testdata/project-v4/Makefile

Co-Author: Mateus Oliveira <msouzaol@redhat.com>
Closes; https://github.com/kubernetes-sigs/kubebuilder/pull/4425
Cloeses: https://github.com/kubernetes-sigs/kubebuilder/issues/4416

✨ (go/v4): Add new makefile target to check and validate the linter config

---

docs/book/src/SUMMARY.md

The doc was added but not listed in the summary

📖 Add helm-plugin to the summary of available plugins

---

.github/workflows/lint-sample.yml
.github/workflows/lint.yml
Makefile
docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml
docs/book/src/cronjob-tutorial/testdata/project/Makefile
docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml
docs/book/src/getting-started/testdata/project/Makefile
docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml
docs/book/src/multiversion-tutorial/testdata/project/Makefile
pkg/plugins/golang/v4/scaffolds/init.go
testdata/project-v4-multigroup/.github/workflows/lint.yml
testdata/project-v4-multigroup/Makefile
testdata/project-v4-with-plugins/.github/workflows/lint.yml
testdata/project-v4-with-plugins/Makefile
testdata/project-v4/.github/workflows/lint.yml
testdata/project-v4/Makefile

✨ Upgrade GolangCI Lint from v1.62.2 to v1.63.4

✨ Upgrade GolangCI Lint from v1.62.2 to v1.63.4

---

build/.goreleaser.yml

🌱 : Fix Kubernetes version in the goreleaser by upgrading it from 1.31.0 to 1.32.0

---

test/common.sh

🌱 test: add to commmon.sh the latest k8s release 1.32

---

roadmap/roadmap_2025.md

📖 Update Roadmap 2025 with latest status

---

.github/workflows/test-e2e-samples.yml
docs/book/src/cronjob-tutorial/testdata/project/config/default/kustomization.yaml
docs/book/src/cronjob-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml
docs/book/src/cronjob-tutorial/testdata/project/dist/chart/templates/prometheus/monitor.yaml
docs/book/src/cronjob-tutorial/testdata/project/dist/install.yaml
docs/book/src/getting-started/testdata/project/config/default/kustomization.yaml
docs/book/src/getting-started/testdata/project/config/prometheus/monitor_tls_patch.yaml
docs/book/src/getting-started/testdata/project/dist/chart/templates/prometheus/monitor.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/default/kustomization.yaml
docs/book/src/multiversion-tutorial/testdata/project/config/prometheus/monitor_tls_patch.yaml
docs/book/src/multiversion-tutorial/testdata/project/dist/chart/templates/prometheus/monitor.yaml
docs/book/src/multiversion-tutorial/testdata/project/dist/install.yaml
hack/docs/internal/cronjob-tutorial/sample.go
pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/kdefault/kustomization.go
pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/prometheus/monitor_tls_patch.go
pkg/plugins/optional/helm/v1alpha/scaffolds/internal/templates/chart-templates/prometheus/monitor.go
test/e2e/v4/generate_test.go
testdata/project-v4-multigroup/config/default/kustomization.yaml
testdata/project-v4-multigroup/config/prometheus/monitor_tls_patch.yaml
testdata/project-v4-with-plugins/config/default/kustomization.yaml
testdata/project-v4-with-plugins/config/prometheus/monitor_tls_patch.yaml
testdata/project-v4-with-plugins/dist/chart/templates/prometheus/monitor.yaml
testdata/project-v4/config/default/kustomization.yaml
testdata/project-v4/config/prometheus/monitor_tls_patch.yaml

Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4533

🐛 (go/v4,ksutomize/v2,helm/v1-alpha): Fix prometheus integration with TLS check

---

Makefile

✨ Add Makefile target to sync Kubernetes version

---

.github/workflows/verify.yml

🌱 fix PR title check

---

README.md

Update the README.md file with some minor changes

📖 Update README.md with minor changes

---

docs/book/src/quick-start.md

:book: docs: fix incorrect json tag in API example.

---

cmd/version.go

Ensure that the cmd/version is properly updated.

🌱 Fix: ensure tha cmd/verdion.go is properly updated to return this value for go modules

---

docs/book/src/cronjob-tutorial/testdata/project/Makefile
docs/book/src/getting-started/testdata/project/Makefile
docs/book/src/multiversion-tutorial/testdata/project/Makefile
pkg/plugins/common/kustomize/v2/plugin.go
testdata/project-v4-multigroup/Makefile
testdata/project-v4-with-plugins/Makefile
testdata/project-v4/Makefile

✨ (go/v4): Upgrade kustomize version from v5.5.0 to v5.6.0

✨ (go/v4): Upgrade kustomize version from v5.5.0 to v5.6.0

---

docs/book/src/migration/migration_guide_gov3_to_gov4.md
docs/book/src/migration/v3-plugins.md
docs/book/src/migration/v3vsv4.md

Added index for better viewing of the steps and removed the redundant lines and whitespaces

📖 Updated migration pages 

---

docs/book/src/getting-started/testdata/project/internal/controller/memcached_controller_test.go
hack/docs/internal/getting-started/generate_getting_started.go
pkg/plugins/external/helpers.go
pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller-test.go
pkg/plugins/optional/grafana/v1alpha/scaffolds/edit.go
testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller_test.go
testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller_test.go
testdata/project-v4-with-plugins/internal/controller/busybox_controller_test.go
testdata/project-v4-with-plugins/internal/controller/memcached_controller_test.go

replace empty slice literals with idiomatic var decls for []metav1.Condition, []templates.CustomMetricItem and []external.Flag

🌱 (chore): replace empty slice literals with idiomatic var decls

---

pkg/cli/alpha/internal/generate.go

This change ensures all errors within the `pkg/cli/alpha/internal/generate` command path are consistently wrapped with context, using `%w` and providing informative error messages. This improves traceability and makes debugging easier when a failure occurs during project regeneration.
Also ensures no error is silently discarded or reported generically, aligning with best practices for error transparency.

🌱 (chore): improve error wrapping for generate command execution

---

pkg/machinery/scaffold.go
pkg/plugin/util/exec.go
pkg/plugin/util/util.go
pkg/plugin/version.go

This change wraps error returns in the plugin and utility functions with contextual messages to provide more informative error outputs. This helps in debugging and understanding the source of errors more easily.

🌱 (chore): wrap plugin and util error returns for better context

---

pkg/plugins/golang/v4/scaffolds/internal/templates/hack/boilerplate.go

use pointer receiver for Validate and rename shadowed var

🌱 (chore): use pointer receiver for Validate and rename shadowed var

---

docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1/scaffolds/api.go

handle flag parsing errors in simple external plugin tutorial API scaffolder

📖  handle flag parsing errors in simple external plugin tutorial API scaffolder

---

docs/book/src/cronjob-tutorial/testdata/project/.golangci.yml
docs/book/src/cronjob-tutorial/testdata/project/internal/controller/cronjob_controller.go
docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook.go
docs/book/src/cronjob-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook_test.go
docs/book/src/cronjob-tutorial/testdata/project/test/utils/utils.go
docs/book/src/getting-started/testdata/project/.golangci.yml
docs/book/src/getting-started/testdata/project/test/utils/utils.go
docs/book/src/multiversion-tutorial/testdata/project/.golangci.yml
docs/book/src/multiversion-tutorial/testdata/project/internal/controller/cronjob_controller.go
docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook.go
docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v1/cronjob_webhook_test.go
docs/book/src/multiversion-tutorial/testdata/project/internal/webhook/v2/cronjob_webhook.go
docs/book/src/multiversion-tutorial/testdata/project/test/utils/utils.go
hack/docs/internal/cronjob-tutorial/controller_implementation.go
hack/docs/internal/cronjob-tutorial/webhook_implementation.go
hack/docs/internal/multiversion-tutorial/generate_multiversion.go
hack/docs/internal/multiversion-tutorial/webhook_v2_implementaton.go
pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/internal/templates/controllers/controller.go
pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go
pkg/plugins/golang/v4/scaffolds/internal/templates/test/utils/utils.go
testdata/project-v4-multigroup/.golangci.yml
testdata/project-v4-multigroup/internal/controller/example.com/busybox_controller.go
testdata/project-v4-multigroup/internal/controller/example.com/memcached_controller.go
testdata/project-v4-multigroup/test/utils/utils.go
testdata/project-v4-with-plugins/.golangci.yml
testdata/project-v4-with-plugins/internal/controller/busybox_controller.go
testdata/project-v4-with-plugins/internal/controller/memcached_controller.go
testdata/project-v4-with-plugins/test/utils/utils.go
testdata/project-v4/.golangci.yml
testdata/project-v4/test/utils/utils.go

Co-Author: dongjiang <dongjiang1989@126.com>

🐛 (Follow up of : #4752 - Upgrade GolangCI) - fix: address staticcheck linter issues (ST1005, QF1008) in scaffolds and tutorials

---

docs/book/src/cronjob-tutorial/testdata/project/.golangci.yml
docs/book/src/cronjob-tutorial/testdata/project/cmd/main.go
docs/book/src/getting-started/testdata/project/.golangci.yml
docs/book/src/multiversion-tutorial/testdata/project/.golangci.yml
docs/book/src/multiversion-tutorial/testdata/project/cmd/main.go
pkg/plugins/golang/v4/scaffolds/internal/templates/cmd/main.go
pkg/plugins/golang/v4/scaffolds/internal/templates/golangci.go
testdata/project-v4-multigroup/.golangci.yml
testdata/project-v4-with-plugins/.golangci.yml
testdata/project-v4-with-plugins/cmd/main.go
testdata/project-v4/.golangci.yml
testdata/project-v4/cmd/main.go

Close https://github.com/kubernetes-sigs/kubebuilder/issues/4778

🐛Fix: Incorrect Webhook Import Aliasing in cmd/main.go Scaffold 

---

testdata/project-v4-multigroup/go.mod
testdata/project-v4/go.mod

🌱 (testdata): Upgrade version used in the samples under testdata

---

docs/book/install-and-build.sh

Upgrade the docs to be generated from the latest released version of controller-tools.

📖 (docs): Upgrade controller-tools from v0.17.4 to v0.18.0

---

pkg/cli/alpha/internal/generate.go

Follow up #4843 ( not released yet - I realised that I committed a mistake that could break automations using it )

🐛 (cli)(fix): postscaffold for alpha generate should return warning (follow-up: 4843)

---

test/e2e/v4/plugin_cluster_test.go

🌱 (ci): Temporarily comment out tests failing on Kubernetes 1.33 to unblock CI and allow for a calmer investigation and fix

---

testdata/project-v4-multigroup/go.mod
testdata/project-v4/go.mod

✨ Upgrade usage of cert-manager from v1.17.2 to v1.18.0

---

docs/book/src/migration/multi-group.md

A blank line right before the code block is required to make it rendered successfully. Thank you.
Link: https://kubebuilder.io/migration/multi-group.html

📖 docs: fix code block rendering

---

docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_types.go
pkg/plugins/golang/v4/scaffolds/webhook.go
testdata/project-v4-multigroup/api/example.com/v1/wordpress_types.go
testdata/project-v4-with-plugins/api/v1/wordpress_types.go
testdata/project-v4/api/v1/firstmate_types.go

Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4836

🐛 (go/v4)(fix): remove unused marker +kubebuilder:conversion:hub for conversion webhooks

---

docs/book/src/cronjob-tutorial/testdata/project/api/v1/cronjob_types.go
docs/book/src/multiversion-tutorial/testdata/project/api/v1/cronjob_types.go
docs/book/src/multiversion-tutorial/testdata/project/api/v2/cronjob_types.go
hack/docs/internal/cronjob-tutorial/api_design.go
hack/docs/internal/multiversion-tutorial/cronjob_v2.go

Motivated by: https://github.com/kubernetes-sigs/kubebuilder/issues/4809
Note: A partial change is required. Here we are just fixing the description of the specs so that we reduce the number of changes to be discussed and we can properly debate and find out what markers we should use for each spec

📖 Update Cronjob Tutorials API spec descriptions to better adopt  k8s API convetions

---

.github/workflows/lint-sample.yml
.github/workflows/test-devcontainer.yml

🌱 (ci): only call lint sample and test-devcontainer checks when has changes in the specific directories checked

---

pkg/plugin/util/stdin.go
pkg/plugin/util/stdin_test.go
pkg/plugin/util/util_test.go

Issue: https://github.com/kubernetes-sigs/kubebuilder/issues/4925
- Improve the coverage by adding UTs for plugin package (covers util).
- Also make readstdin function to follow camelcase convention.

🌱 (CLI): Add unit tests for plugin utils

---

pkg/machinery/scaffold.go
pkg/plugins/golang/v4/scaffolds/internal/templates/test/e2e/test.go

It allows backwards compatibility as custom code 
Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4509
It will not fail now:
```
$ kubebuilder create webhook --group ship --version v1beta1 --kind Frigate3 --defaulting --programmatic-validation
INFO Writing kustomize manifests for you to edit... 
INFO Writing scaffold for you to edit...          
INFO internal/webhook/v1beta1/frigate3_webhook.go 
WARN Skipping missing test file: test/e2e/e2e_test.go 
WARN The code fragments will not be inserted.     
INFO internal/webhook/v1beta1/frigate3_webhook_test.go 
INFO internal/webhook/v1beta1/webhook_suite_test.go 
INFO Update dependencies:
$ go mod tidy           
INFO Running make:
$ make generate                
/Users/camilam/go/src/sigs.k8s.io/test-pr/bin/controller-gen …
```

🐛 (go/v4): gracefully skip webhook test injection if file or markers are missing

---

test/e2e/alphaupdate/update_test.go

- Add a test where the user changes the version in the Makefile to trigger a conflict
- Check that both the user version and the new version appear in the conflict block
- Make sure the update keeps user code and updates go modules correctly
- Add clearer step messages using By() to make the test flow easier to follow
- Improve check to verify if has markers conflicts

🌱 (e2e) Make alpha update tests easier to understand and more complete

---

.gitignore
pkg/cli/alpha/internal/common/common_test.go
pkg/cli/alpha/internal/common/suite_test.go
test/e2e/utils/test_context.go

Closes: https://github.com/kubernetes-sigs/kubebuilder/issues/4971

🌱 refactor TestContext to allow use in unit tests with directory setup

---

docs/book/src/reference/commands/alpha_update.md
pkg/cli/alpha/internal/update/update.go
pkg/cli/alpha/internal/update/update_test.go
pkg/cli/alpha/update.go
pkg/cli/alpha/update_test.go
test/e2e/alphaupdate/update_test.go

(nore released yet so we can change besides is alpha)

✨ (alpha update): Rename alpha update flag preserve-path to restore-path

---

roadmap/roadmap_2025.md

Updated status of Comprehensive E2E Testing and provided additional details on the proposal for keeping users updated.

📖 Update roadmap for 2025 with new statuses and details

---

docs/book/src/cronjob-tutorial/testdata/project/.github/workflows/lint.yml
docs/book/src/cronjob-tutorial/testdata/project/Makefile
docs/book/src/getting-started/testdata/project/.github/workflows/lint.yml
docs/book/src/getting-started/testdata/project/Makefile
docs/book/src/multiversion-tutorial/testdata/project/.github/workflows/lint.yml
docs/book/src/multiversion-tutorial/testdata/project/Makefile
pkg/plugins/golang/v4/scaffolds/init.go
testdata/project-v4-multigroup/.github/workflows/lint.yml
testdata/project-v4-multigroup/Makefile
testdata/project-v4-with-plugins/.github/workflows/lint.yml
testdata/project-v4-with-plugins/Makefile
testdata/project-v4/.github/workflows/lint.yml
testdata/project-v4/Makefile

✨ Upgrade golang CI from v2.3.0 to v2.4.0

---

README.md

Removed the unit tests badge from the README.

📖 Remove unit tests badge from README
